MM-42278 Playwright base setup
mattermost/mattermost-webapp pull request #10023
Opened 2022-03-17 18:14 UTC by saturninoabril

#### Summary
Submitted on top of https://github.com/mattermost/mattermost-webapp/pull/10020 for ease of review. See https://github.com/mattermost/mattermost-webapp/commit/23a58235f0a20e7d8f5315510a7569e289059483 for specific changes in this PR.

This PR introduced Playwright initially for visual testing, then eventually for v2 of end-to-end tests. Once it reached stability and maturity based on our use case, completed other important items like reporting, integration, pipeline, etc. and accepted for dev/community to write tests, it will be used to automate tests of new features while Cypress will go on maintenance mode.

Files and folders are to be found at `/e2e/playwright/`.

Visual testing is known to be problematic for elements that render dynamic information like date/time, name of teams/channels/users, etc. To deal with it, it will be hidden as needed using [page.addStyleTag([options])](https://playwright.dev/docs/api/class-page#page-add-style-tag) (thanks to @hmhealey for the [info](https://github.com/mattermost/mattermost-webapp/pull/9930#issuecomment-1059528475)).

I've extended `Client4` and made some changes to its properties and relocated couple of helper functions to make it compatible as node client. `Client4` was more of a browser client, though. Well noted on @hmhealey's comment [here](https://github.com/mattermost/mattermost-webapp/pull/9930#issuecomment-1059528475) and I'll update once `@mattermost/client` is released but for now, I'm proposing to change here for Playwright's setup to move forward.

For local development and in-house visual test run, screenshots were created using the official [Playwright docker container](https://playwright.dev/docs/docker) which uses Linux/Ubuntu (focal) distribution. Using such container makes the screenshot consistent even with developers using different local environment and will match with the same container we'll use in the pipeline. Screenshots generated my MacOS (darwin) or Windows are included in `.gitignore`.

To test screenshots in wide-range of different environments (OS, browser and mobile clients) and easy enough for QA to handle during release testing, I've added the ability to run both using [applitools](https://applitools.com/) and [percy](https://percy.io/). Nothing official yet but both provided so we'll get enough time to evaluate which tool is best for us.

To follow in separate PR:
- Support for remote storage of golden screenshots via S3 so that webapp repo will not be bloated with screenshot images
- Support for Cloud server
- Support with Calls product
- Reporting - to community, dashboard and Zephyr
- Gitlab pipeline
- Docs on best practices, semi-opinionated patterns and styles

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42278

#### Release Note
```release-note
NONE
```

2022-03-18 04:56 UTC, saturninoabril commented
/e2e-test

2022-03-18 04:57 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-03-18 04:57 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/172241

2022-03-18 05:00 UTC, saturninoabril commented
/e2e-test

2022-03-18 05:01 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-03-18 05:01 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/172242

2022-03-18 19:58 UTC, Phrynobatrachus commented on e2e/playwright/README.md
> +
I also had to `npx playwright install`.

2022-03-21 07:46 UTC, saturninoabril commented on e2e/playwright/README.md
> +
Thanks Cass! Added with:
```
# Install browser binaries as prompted if Playwright is just installed or updated
# See https://playwright.dev/docs/browsers
npx playwright install
```

2022-03-21 15:08 UTC, hmhealey requested changes

2022-03-21 15:09 UTC, hmhealey commented
I tried running those login tests myself. They worked in Docker, but not locally. I'm not sure if that failure was just caused by my local server not being set up with the correct credentials though

2022-03-21 15:12 UTC, Phrynobatrachus approved these changes
Impressive! Both integrations work and everything looks solid to me.

2022-03-21 21:10 UTC, devinbinnie approved these changes
LGTM! Awesome stuff @saturninoabril 🚀

2022-03-21 23:55 UTC, josephbaylon approved these changes
LGTM. I was able to have a successful run using
```
npm run test -- login --project=chrome
```

I did install `npx playwright install` but I couldn't get the `npm run test -- login` to have a successful run. Wondering if it's missing an installation step. But the one with chrome above worked for me, so I'll approve the PR.

2022-03-22 00:02 UTC, saturninoabril commented
@hmhealey @josephbaylon Thanks for testing! Would you mind sharing the error logs?

2022-03-22 00:04 UTC, josephbaylon commented
@saturninoabril haha, I guess 3rd time's a charm. I just tried it again and it seems to be cooperating now
![Screen Shot 2022-03-21 at 5 03 45 PM](https://user-images.githubusercontent.com/487991/159382309-30fc1196-b7ab-46ed-a305-c8bd2c53756e.png)

2022-03-22 01:15 UTC, saturninoabril commented
/e2e-test

2022-03-22 01:15 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-03-22 01:15 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/173683

2022-03-22 01:24 UTC, saturninoabril commented on packages/mattermost-redux/src/utils/helpers_client.ts
> +export const isMinimumServerVersion = (currentVersion: string, minMajorVersion = 0, minMinorVersion = 0, minDotVersion = 0): boolean => {
I see. Done, please take a look again. Thanks!

2022-03-22 01:34 UTC, saturninoabril commented
@hmhealey If it worked in docker, then one culprit might be due to missing snapshot/s in OS other than `linux` which is expected.
Maybe you're seeing similar error like below?
```
Error: [redacted_path]-darwin.png is missing in snapshots, writing actual.
```
If it's the case, then it should pass after the first run.
Btw, if you're experiencing a different issue, then I'll wait for the logs and see if it's something we can fix in this PR.

2022-03-22 06:37 UTC, saturninoabril commented
Hello @amyblais, if all are good with reviews, I recommend to include this in March 30th Cloud release so it will eventually become part of v6.6. Thanks!

2022-03-23 15:57 UTC, saturninoabril commented
Thanks! You may check `e2e/playwright/test-results` folder and see the failed screenshot. Another way is to run in headed mode by adding `--headed`, as in `npm run test -- login --project=chrome --headed`. I've set it headless by default though, at `e2e/playwright/playwright.config.ts`.

2022-03-23 18:25 UTC, hmhealey commented
Okay, perhaps the issue was with my local server not running. I tried again with `--headed` and I got the error about the files missing. After I ran it a second time with `--headed`, it passed.

Are we expecting that we're only going to check in the linux images for now, or is that why we're running the tests in Docker? I'd be on board with just running them in Docker since I've noticed doing dev stuff inside a container does seem to simplify a lot of things

2022-03-23 21:50 UTC, saturninoabril commented
@hmhealey Glad it's finally resolved on you.
Yes, we're expecting to check in linux images only and it's the primary reason of using Docker so that images will be consistent among developers/contributors local setup and in CI pipeline. But yes, aside from that, the container has all it needs and easier to get up and running. On the other hand, running directly on host makes it easier to see what's going on and to interact/inspect with the browser during debugging in headed mode, although those can be done as well directly via IDE or by looking at the saved screenshots/recording.
Note that linux images will typically be used in our CI pipeline but during prerelease/release testing, we'll use a third-party image diff service (percy or applitools) so that it will be easier for non-tech QA to analyze the difference between actual and expected.

2022-03-25 13:40 UTC, hmhealey approved these changes

2022-03-25 14:45 UTC, saturninoabril commented
/update-branch

2022-03-25 15:18 UTC, pfltdv commented
/check-cla

2022-03-26 09:49 UTC, metanerd commented
/check-cla

2022-03-28 09:50 UTC, saturninoabril commented
@pfltdv This is going to be part of Cloud March 30th and eventually for v6.6. Is there a workaround to get this merge? Thanks!

2022-03-28 09:53 UTC, saturninoabril commented
/update-branch

2022-03-28 09:57 UTC, pfltdv commented
@saturninoabril I will investigate what we can do manually. And for `untagged-build` having successful build on CircleCI should mark that green. (Currently there is a build running) https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp?branch=pull%2F10023&filter=all

2022-03-28 10:04 UTC, saturninoabril commented
Thanks @pfltdv! I thought there's still an outstanding issue. Looks like all good now. Again, thanks!

2022-03-28 10:04 UTC, merged

2022-03-28 10:04 UTC, mattermod commented
Cherry pick is scheduled.

2022-03-28 10:04 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
   d0ba91dca..1cf5db4c7  MM-38902   -> upstream/MM-38902
 * [new branch]          MM-41997   -> upstream/MM-41997
 * [new branch]          MM-42353-task-list-icon-covers-sysadmin-console-bottom-options -> upstream/MM-42353-task-list-icon-covers-sysadmin-console-bottom-options
 * [new branch]          MM-42592-visual-elements-partially-visible -> upstream/MM-42592-visual-elements-partially-visible
   95d5ff70f..894545dc9  MM-42604-actions-menu-misaligned-menu-items-redo -> upstream/MM-42604-actions-menu-misaligned-menu-items-redo
   d0b9d6a3c..520a2dd5e  MM-42655_permission-selectors -> upstream/MM-42655_permission-selectors
   8d522ecc2..2a20f517b  MM-42713   -> upstream/MM-42713
 * [new branch]          MM-42778-js-errors-hover -> upstream/MM-42778-js-errors-hover
   e7c8a3d84..8dbec491e  cloud      -> upstream/cloud
 * [new branch]          cursor2    -> upstream/cursor2
   e155dad1b..e123c229c  master     -> upstream/master
Fetching origin
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
!!! 'upstream/release-cloud' not found. The second argument should be something like upstream/release-0.21.
    (In particular, it needs to be a valid, existing remote branch that I can 'git checkout'.)

+++ Returning you to the master branch and cleaning up.

```

2022-03-28 10:06 UTC, saturninoabril commented
/cherry-pick cloud

2022-03-28 10:06 UTC, mattermod commented
Cherry pick is scheduled.

2022-03-28 10:06 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-webapp-#10023-upstream-cloud-1648461980
Switched to a new branch 'automated-cherry-pick-of-mattermost-webapp-#10023-upstream-cloud-1648461980'
Branch 'automated-cherry-pick-of-mattermost-webapp-#10023-upstream-cloud-1648461980' set up to track remote branch 'cloud' from 'upstream'.

+++ About to attempt cherry pick of PR #10023 with merge commit e123c229c07a5846e8af36db45883b5d07b5db72.

error: could not apply e123c229c... MM-42278 Playwright base setup (#10023)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU packages/mattermost-redux/src/client/client4.ts
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2022-03-28 11:34 UTC, saturninoabril commented
@amyblais Done manual cherry-pick into cloud branch.