MM-42030: Migrate Threads RHS tour tip to tippy based tour tip
mattermost/mattermost-webapp pull request #10099
Opened 2022-03-30 15:05 UTC by codedsun

#### Summary

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/19802

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note
NONE
```

2022-03-30 15:06 UTC, mattermod commented
Hello @codedsun,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-03-31 13:16 UTC, AshishDhama commented
@codedsun Could you please fix the broken test.

2022-04-04 05:23 UTC, saturninoabril commented on components/crt_tour/crt_threads_pane_tutorial_tip/crt_threads_pane_tutorial_tip.tsx
> +            nextBtn={nextBtn()}
@codedsun Looks like this should be,
```suggestion
            nextBtn={nextBtn}
```

2022-04-16 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-04-19 07:05 UTC, AshishDhama commented
@codedsun Were you able to add the patch?

2022-05-11 10:25 UTC, AshishDhama commented
/update-branch

2022-05-11 10:35 UTC, AshishDhama commented
@jfrerich @jgilliam17 This pr is ready for review

2022-05-12 15:01 UTC, jfrerich approved these changes
LGTM

2022-05-16 18:11 UTC, AshishDhama approved these changes
LGTM!

2022-05-24 05:04 UTC, AshishDhama commented
@jgilliam17 Gentle reminder on this one.

2022-05-24 17:14 UTC, jgilliam17 commented
/update-branch

2022-05-24 19:17 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/198144

2022-05-24 23:07 UTC, saturninoabril commented
/update-branch

2022-05-25 00:12 UTC, saturninoabril commented
/e2e-test

2022-05-25 00:12 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/198266

2022-05-25 02:30 UTC, jgilliam17 commented
Thanks @codedsun and also @saturninoabril for fixing the pipeline and running the e2es.
There are few failures related to this PR. @codedsun Please see the report [here](https://mattermost-cypress-report.s3.amazonaws.com/198266-017b1b1-onprem-ent-webapp-pr-10099-mattermost/mm-ee-test017b1b1/mochawesome.html) and let us know if you need help addressing these

2022-06-05 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-06-13 17:10 UTC, jgilliam17 requested changes
@codedsun Let me know if you have any questions about addressing E2E failures
See comment here: https://github.com/mattermost/mattermost-webapp/pull/10099#issuecomment-1136650269

2022-09-09 04:22 UTC, AshishDhama commented
closing in favour of https://github.com/mattermost/mattermost-webapp/pull/11107

2022-09-09 04:22 UTC, closed without merging