MM-41323: Secure Marketplace URL
mattermost/mattermost-webapp pull request #10113
Opened 2022-03-31 18:22 UTC by agnivade

Disable marketplace URL text box when
plugin uploads are disabled.

https://mattermost.atlassian.net/browse/MM-41323

2022-03-31 18:22 UTC, agnivade commented
/release-note-none

2022-04-01 10:02 UTC, saturninoabril requested changes
Thanks @agnivade! LGTM, except for few comment in test. Please fix the build then I'll run the test in Gitlab with mmctl.

2022-04-01 10:02 UTC, saturninoabril commented on e2e/cypress/tests/integration/system_console/plugin_marketplace_url_spec.js
> +        cy.apiAdminLogin();
Can be removed as well.

2022-04-04 06:52 UTC, srkgupta approved these changes
Thanks @agnivade. Changes LGTM

2022-04-05 23:52 UTC, saturninoabril commented
/update-branch

2022-04-06 09:58 UTC, saturninoabril approved these changes
Thanks @agnivade! Tested and passed. Looks good to me. For test infra, I'll submit an update to share volume of socket path/file to Cypress container, so that `--local` will work.

2022-04-06 09:59 UTC, merged