[MM-42869] Fix dot menu dark mode hover
mattermost/mattermost-webapp pull request #10111
Opened 2022-03-31 15:11 UTC by jfrerich

#### Summary
This PR fixes an issue caused buy borrowing styling from `status-dropdown-menu-global-header`.  Fixed by creating a new class specifically for the dot menu component.

For the CSS, I borrowed from the `status-dropdown-menu-global-header` but on only what was needed to format the RHS decorator.
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42869

#### Related Pull Requests

#### Screenshots
|  before  |  after  |
|----|----| 
| <img width="256" alt="image" src="https://user-images.githubusercontent.com/7575921/161089701-4770f160-2053-4cc7-b948-b87b04e65033.png"> | <img width="292" alt="image" src="https://user-images.githubusercontent.com/7575921/161089932-8b8ed810-fb02-4bc9-83d2-b91af7166317.png"> |
| <img width="507" alt="image" src="https://user-images.githubusercontent.com/7575921/161139262-5e3f8895-c99d-4391-9d98-529a59dec556.png"> | <img width="339" alt="image" src="https://user-images.githubusercontent.com/7575921/161139431-368eb3f2-691b-462a-b7e1-d3cb2d61fea9.png"> |
  
#### Release Note

```release-note

```

2022-03-31 20:29 UTC, jwilander approved these changes
LGTM but I'll let Michel comment on the CSS

2022-03-31 22:17 UTC, amyblais commented
/release-note-none

2022-04-01 08:55 UTC, michelengelen requested changes
as a side-note, since you did not build this component: the naming is a bit inconsistent. We name the files here `dot_menu.tsx`, which follows the convention of separating pascal case namings with underscores (`DotMenu` -> `dot_menu.tsx`), but the naming in the CSS classes do not.

I am 4/5 that this is out of scope of this PR, but wanted to raise awareness anyways. I hope you don't mind.

2022-04-01 08:55 UTC, michelengelen commented on components/dot_menu/dot_menu.scss
> +            display: grid;
NICE ... finally someone that uses `grid`! :D

2022-04-01 08:55 UTC, michelengelen commented on components/dot_menu/dot_menu.scss
> +.dotmenu-dropdown-menu {
I would prefer to name this `dropdown-menu__dotmenu` for a simple reason: We already have the class `dropdown-menu` and this i just a variation of that.

2022-04-01 08:55 UTC, michelengelen commented on components/dot_menu/dot_menu.scss
> +        left: inherit;
I don't think we need this here. This might even be prone to bugs when some parent element has a value for `left` defined

2022-04-01 08:55 UTC, michelengelen commented on components/dot_menu/dot_menu.tsx
> +                className={'dotmenu-dropdown-menu'}
according to the comment in `dot_menu.scss`:

```suggestion
                className={'dropdown-menu__dotmenu'}
```

2022-04-01 13:20 UTC, michelengelen approved these changes
LGTM

2022-04-01 13:20 UTC, jfrerich commented
> as a side-note, since you did not build this component: the naming is a bit inconsistent. We name the files here `dot_menu.tsx`, which follows the convention of separating pascal case namings with underscores (`DotMenu` -> `dot_menu.tsx`), but the naming in the CSS classes do not.
> 
> I am 4/5 that this is out of scope of this PR, but wanted to raise awareness anyways. I hope you don't mind.

Can you give an example of a CSS class that would be renamed in your example.  Perhaps there is an eslint rule that could be created to ensure class names are pascal case?  Perhaps this could be a HW campaign?

2022-04-01 13:23 UTC, matthewbirtch commented
Looks good to me @jfrerich. I noticed another issue about the theme color used for menu items with the `dangeours` hover state, but I'll create a separate ticket for that (only in the `Quartz` theme) - screenshot below

<img width="324" alt="image" src="https://user-images.githubusercontent.com/2040554/161271775-50fcf99e-d0eb-491e-935a-2e01cc83c3fb.png">

2022-04-01 13:23 UTC, michelengelen commented
> > as a side-note, since you did not build this component: the naming is a bit inconsistent. We name the files here `dot_menu.tsx`, which follows the convention of separating pascal case namings with underscores (`DotMenu` -> `dot_menu.tsx`), but the naming in the CSS classes do not.
> > I am 4/5 that this is out of scope of this PR, but wanted to raise awareness anyways. I hope you don't mind.
> 
> Can you give an example of a CSS class that would be renamed in your example. Perhaps there is an eslint rule that could be created to ensure class names are pascal case? Perhaps this could be a HW campaign?

the CSS class for the `DotMenu` component would be such a case, since `DotMenu` would result in a CSS class `dot-menu`

2022-04-01 13:26 UTC, jfrerich commented
Thanks @matthewbirtch, can you mark approved if you don't have any issues outside of your new finding (dangerous hover state)

2022-04-01 13:27 UTC, matthewbirtch approved these changes

2022-04-04 17:21 UTC, amyblais commented
@DHaussermann @saturninoabril This one would be nice to get merged soon :)

2022-04-06 01:17 UTC, saturninoabril commented
/update-branch

2022-04-06 01:30 UTC, saturninoabril commented
/update-branch

2022-04-06 02:00 UTC, saturninoabril commented
/e2e-test

2022-04-06 02:01 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/179634

2022-04-06 02:28 UTC, saturninoabril approved these changes
Thanks @jfrerich! Tested and passed.

2022-04-06 02:29 UTC, merged

2022-04-06 02:29 UTC, mattermod commented
Cherry pick is scheduled.

2022-04-06 12:07 UTC, amyblais commented
/cherry-pick cloud

2022-04-06 12:07 UTC, mattermod commented
Cherry pick is scheduled.