[MM-44159] Members RHS: fix search + allow to load more users
mattermost/mattermost-webapp pull request #10330
Opened 2022-05-18 18:57 UTC by JulienTant

#### Summary
This PR fixes the search two issues:

- Be able to load more than 100 users at a time.
- Searching was not working on not loaded users.

```diff
- IMPORTANT NOTICE:
```

This is a 'poor-man' solution as it does not take into consideration the performance issue a user would face if they decide to load thousands of users in the list. It is difficult to use a virtualized list to solve the issue because the scrollable zone is composed of two lists:

![image](https://user-images.githubusercontent.com/785518/169121938-8535f09f-f26a-450d-bd9a-ba510d80e911.png)

As a solution we could:
- Add simple pagination instead of infinite scrolling on the members list.
- Making only the "Members" area scrollable, but we could end up with weird-looking pages if the channel admin section is pretty height.

In both scenarios, it will also require being able to load 'Channel admin' and 'Members' separately instead of all together followed by a sorting process.

If there's a better solution I'm happy to hear it.

I decided to submit this PR anyway to propose a 'quick solution' to the problem, if we would rather not offer this solution I'm fine closing this PR and delaying it until we have a better solution - and more time on my side to work on it.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44159

#### Related Pull Requests
- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

https://user-images.githubusercontent.com/785518/169131868-d933c44d-53ba-4cc9-9847-ff710a4ad908.mp4

#### Release Note
```release-note
NONE
```

2022-05-18 19:13 UTC, matthewbirtch commented
Is there a way to load up a lot of test users on this server so we can see it in action @JulienTant ?

2022-05-18 19:13 UTC, JulienTant commented
> Is there a way to load up a lot of test users on this server so we can see it in action @JulienTant ?

Yep I loaded 1000 users!

2022-05-18 19:21 UTC, matthewbirtch approved these changes
Seems pretty great to me! Not noticing any performance issues

2022-05-18 19:22 UTC, JulienTant commented
> Seems pretty great to me! Not noticing any performance issues

It's going to be computer-dependent and the more you load the worst it's getting.

2022-05-19 14:21 UTC, hmhealey requested changes

2022-05-19 14:21 UTC, hmhealey commented on components/channel_members_rhs/channel_members_rhs.tsx
> +    const searchDebounced = debounce(
This is going to get redefined every time this re-renders, so you'll lose the state tracking the debouncing. I'm not sure exactly how to make this work in a hook, but maybe something like wrapping it in a `useMemo` would work to fix that?

2022-05-19 14:21 UTC, hmhealey commented on components/channel_members_rhs/channel_members_rhs.tsx
> +                actions.loadMyChannelMemberAndRole(channel.id);
Do these need to be reloaded when we're searching? I would think we only need the search results at this point

2022-05-19 14:21 UTC, hmhealey commented on components/channel_members_rhs/channel_members_rhs.tsx
> +        await actions.loadMyChannelMemberAndRole(channel.id);
Similarly, why do we need to reload the current user's channel member each time?

2022-05-19 14:36 UTC, julmondragon requested changes
Noticed some behaviors:

1. After reaching the end of the list, the scroll continues firing requests for more data not available:

https://user-images.githubusercontent.com/79058848/169321797-9ef2026a-7f50-412b-a579-1f0c3ae789d8.mp4

2. After reaching the end of the list, going back to channel info and then back again to the members list, the full list is already loaded, but the scroll fires requests to load data since the beginning (page 1):

https://user-images.githubusercontent.com/79058848/169321902-6ab79311-18b7-46e0-88ae-30c84ad22b9d.mp4

3. After having loaded a big amount of users the actions start to lag a little bit.

2022-05-19 14:36 UTC, julmondragon commented on i18n/en.json
> +  "channel_members_rhs.list.loading": "Loading",
nit: Could add the ellipsis char `…` or use the `LoadingScreen` component.

2022-05-19 15:59 UTC, JulienTant commented
Staling this PR for now; I don't have enough bandwidth

2022-06-10 21:35 UTC, closed without merging