WIP: [MM-44429] Top threads widget
mattermost/mattermost-webapp pull request #10356
Opened 2022-05-20 20:02 UTC by BenCookie95

#### Summary
Top threads widget insight

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44429

#### Related Pull Requests

#### Screenshots

#### Release Note

```release-note
NONE
```

2022-05-27 16:44 UTC, mkraft commented on i18n/en.json
> +  "insights.topThreads.totalMessages": "Participants",
Do these blanks need values?

2022-05-30 20:31 UTC, BenCookie95 commented on i18n/en.json
> +  "insights.topThreads.totalMessages": "Participants",
Fixed

2022-05-30 20:31 UTC, BenCookie95 commented on components/activity_and_insights/insights/top_threads/top_threads.tsx
> +    const skeletonLoader = useCallback(() => {
You are correct!

2022-05-30 20:31 UTC, BenCookie95 commented on components/activity_and_insights/insights/top_threads/top_threads.tsx
> +    }), []);
Removed this, wasn't needed

2022-06-06 06:47 UTC, plant99 requested changes

2022-06-06 06:47 UTC, plant99 commented on components/activity_and_insights/insights/top_threads/top_threads.tsx
> +                                            url={imageURLForUser(thread.user_id)}
This would be `thread.user_information.id`

2022-06-06 06:47 UTC, plant99 commented on components/activity_and_insights/insights/top_threads/top_threads.tsx
> +                                            <span>{thread.reply_count}</span>
https://github.com/mattermost/mattermost-server/pull/20195#issuecomment-1144737818 Other things LGTM, only fixes related to the removal of  these fields remain.

2022-06-07 18:23 UTC, mkraft approved these changes

2022-06-07 18:26 UTC, plant99 approved these changes

2022-06-10 13:13 UTC, matthewbirtch approved these changes
Approving based on our review yesterday. I can take a much closer look once merged, but didn't see anything glaring

2022-06-16 21:22 UTC, furqanmlk reviewed
Hi @matthewbirtch,  Everything is Working fine except the thread window is hiding the insight menu.
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/6909890/174167755-99727712-eb5a-4b23-be8d-fcf658b0b3b9.png">

2022-06-16 23:01 UTC, matthewbirtch commented
> Hi @matthewbirtch, Everything is Working fine except the thread window is hiding the insight menu.

Yes, @furqanmlk this is something @BenCookie95 was going to look at in a separate PR to ensure the RHS only overlaps the view when absolutely necessary

2022-06-17 17:22 UTC, merged