Fix E2Es for RHS (Advanced Text Editor)
mattermost/mattermost-webapp pull request #10586
Opened 2022-06-13 16:35 UTC by AshishDhama

#### Summary
Fix E2Es for RHS (Advanced Text Editor)

#### Ticket Link
 Fixes https://mattermost.atlassian.net/browse/MM-44990

#### Related Pull Requests
NONE 

#### Screenshots
NONE

#### Release Note
```release-note
Fix: E2Es for RHS (Advanced Text Editor)
```

2022-06-13 16:45 UTC, AshishDhama commented
/e2e-test

2022-06-13 17:06 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-06-14 04:32 UTC, AshishDhama commented
@jgilliam17 Yeah there was some issue have fixed that now.

2022-06-14 04:52 UTC, AshishDhama commented
/e2e-test

2022-06-14 04:52 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/207044

2022-06-14 08:35 UTC, AshishDhama commented
/e2e-test

2022-06-14 08:35 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/207128

2022-06-14 09:48 UTC, AshishDhama commented
/e2e-test

2022-06-14 09:48 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/207176

2022-06-14 10:17 UTC, michelengelen requested changes
looking good overall .. just some suggestions.

What really needs to be adjusted are the descriptions for the test-steps.

2022-06-14 11:00 UTC, AshishDhama commented on e2e/cypress/tests/support/ui/sidebar_right.js
> +    return cy.get('.sidebar--right').findByTestId('SendMessageButton');
Yeah will add this in future PR

2022-06-14 11:45 UTC, AshishDhama commented
/update-branch

2022-06-14 12:43 UTC, AshishDhama commented
/e2e-test

2022-06-14 12:43 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/207279

2022-06-14 13:29 UTC, michelengelen requested changes
still a few things that need to change, but it is looking great for the most part!

2022-06-14 13:29 UTC, michelengelen commented on e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
> +        cy.get('#advancedTextEditorCell').within(() => {
yep, after going through the changes: we use that a lot ... so could you please create a getter function for that?

2022-06-14 20:11 UTC, furqanmlk reviewed
Thank @AshishDhama  Following test cases files are failing in your spec files.
<img width="909" alt="image" src="https://user-images.githubusercontent.com/6909890/173677865-1a9e378c-e50a-4ddd-99c4-51b70f215306.png">

<img width="908" alt="image" src="https://user-images.githubusercontent.com/6909890/173677933-5714623f-a369-4d8a-9b28-1bea0680e2f9.png">

2022-06-16 13:29 UTC, AshishDhama commented on e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
> +        cy.get('#advancedTextEditorCell').within(() => {
Yeah will add this in next separate PR

2022-06-16 14:58 UTC, AshishDhama commented
/update-branch

2022-06-21 10:50 UTC, AshishDhama commented
/update-branch

2022-06-21 12:01 UTC, AshishDhama commented
/e2e-test

2022-06-21 12:01 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/210283

2022-06-21 13:06 UTC, jgilliam17 approved these changes
Thanks @AshishDhama 
Here is the latest [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/210283-24ae0ed-onprem-ent-webapp-pr-10586-mattermost/mm-ee-test24ae0ed/mochawesome.html), all listed test cases are passing, except `/poll` so I will remove it from the description and we can address in a different PR.

2022-06-21 18:12 UTC, furqanmlk approved these changes
Thanks @AshishDhama LGTM

2022-06-21 20:02 UTC, AshishDhama commented
@michelengelen Please review it as soon as possible if there aren’t any blocking changes would like to merge it, I need changes done on this pr to fix other breaking e2e don’t want to make this a giant with 100 file changes. Please add your suggestions if any will add those in follow up PR.

2022-06-28 07:54 UTC, michelengelen reviewed
@AshishDhama there are still some things that haven't been adressed yet. Other than that this looks good to merge for me

2022-06-28 08:06 UTC, michelengelen commented
> @AshishDhama there are still some things that haven't been adressed yet. Other than that this looks good to merge for me

I don't know why, but when I was looking now the files had the changes I was expecting... For some reason it did not update it when I had a look some minutes ago. So everything is fine... I'll approve and merge!

Sorry for the false alarm! 🙇🏼

2022-06-28 08:06 UTC, michelengelen approved these changes

2022-06-28 08:06 UTC, merged