[MM-45616] add insights as last channel viewed
mattermost/mattermost-webapp pull request #10637
Opened 2022-06-23 17:37 UTC by Willyfrog

#### Summary
Make insights available as last channel viewed

it is missing the tests, but I'll try to get them tomorrow, in the meantime you can review.

#### Screenshots

<img width="750" alt="Screenshot 2022-06-23 at 19 36 22" src="https://user-images.githubusercontent.com/1515906/175360435-2d9650c7-7803-4585-8830-0fd7af851cb6.png">

#### Release Note

```release-note
NONE
```

2022-06-23 19:28 UTC, mkraft approved these changes
Code LGTM.

2022-06-23 19:31 UTC, mkraft commented
@jfrerich I hope you don't mind I swapped you into this review instead of Ben because he's on PTO until next week.

2022-06-24 08:00 UTC, Willyfrog commented
> @Willyfrog Just so that I'm sure I understand the purpose... this will make you return to insights if it was the last thing you were looking at prior to changing teams, right?

Exactly

2022-06-24 12:18 UTC, Willyfrog commented
@saturninoabril I added the check for the feature flag in cypress test, is that ok? I've been trying to figure it out and seems like this is the expected approach

2022-06-24 12:18 UTC, mattermod commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2022-06-24 14:30 UTC, Willyfrog commented
Thanks for confirming, I was not really sure as the test fails if the featureflag is not set

2022-06-24 20:25 UTC, jfrerich approved these changes
LGTM!  Nice work @Willyfrog

2022-06-28 15:11 UTC, jgilliam17 commented
@Willyfrog Can you please resolve conflicts and update so we can trigger e2es? Thanks 🙂

2022-07-05 18:03 UTC, jgilliam17 requested changes
@Willyfrog 
I added test IDs and few suggestions to update descriptions
I'll trigger the e2es after we add these - thanks

2022-07-05 18:03 UTC, jgilliam17 commented on e2e/cypress/tests/integration/insights/last_viewed_spec.js
> +        // Verify url is set up for threads view when thread view is the penultimate view
```suggestion
        // * Verify url is set up for insights view when insights view is the penultimate view
```

2022-07-08 10:03 UTC, Willyfrog commented
@jgilliam17 added your suggestions (thanks!) and solved the conflict

2022-07-08 17:35 UTC, jgilliam17 approved these changes
Thanks @Willyfrog 
Tested, looks good to merge
Verified insights are available as last channel viewed.
E2E report - no PR related failures. New e2es added here are passing.
<img width="1180" alt="Screen Shot 2022-07-08 at 11 40 53 AM" src="https://user-images.githubusercontent.com/52937121/178042194-23900a81-3254-4721-b10e-12713a93d58f.png">

2022-07-08 17:43 UTC, jgilliam17 commented
Added Jira ticket for release testing https://mattermost.atlassian.net/browse/MM-45616

2022-07-08 17:44 UTC, merged