add typescript support to e2e tests
mattermost/mattermost-webapp pull request #10657
Opened 2022-06-27 18:15 UTC by neallred

#### Summary
Add Typescript support to e2e tests

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45386

#### Related Pull Requests
N/A

#### Release Note
```release-note
NONE
```

2022-06-27 18:15 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-06-27 18:17 UTC, neallred commented on e2e/cypress/tests/support/api/setup.ts
> +import {UserProfile} from '@mattermost/types/users';
One pain point of reviewing is that ofen, for the support files, it isn't recognized that the old `.js` & `d.ts` files are a rename to `.ts`, so it makes the diffs larger than they really are.

2022-06-27 18:18 UTC, neallred commented on e2e/cypress/tests/integration/account_settings/profile/profile_picture_spec.ts
> +import "cypress-file-upload";
This is a temporary add until `tests/support/index.ts` is converted to Typescript: it already has this import, which exends cypress with `attachFiles`. Until then, the easiest way is to redeclare the import.

2022-06-27 18:46 UTC, JulienTant requested changes
LGTM,  just found this little quark but I'll turn my review green upon fix!

2022-06-27 18:48 UTC, JulienTant approved these changes

2022-06-27 21:15 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/212575

2022-06-28 02:30 UTC, saturninoabril commented
@mickmister I've added you to further check on how this will play with E2E tests of https://github.com/mattermost/mattermost-plugin-apps which imports this repo as its dependency with custom commands/helpers.

2022-07-08 05:59 UTC, saturninoabril approved these changes
Thanks @neallred! Looks good to me.

2022-07-11 12:53 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/216953

2022-07-11 14:13 UTC, merged