Fixed type of post parameter of createPost method.
mattermost/mattermost-webapp pull request #10698
Opened 2022-07-04 16:20 UTC by DamirAhm

Initially createPost method received parameter post of type Post that doesn't make sense since post isn't created yet. I added a new type PostToCreate which is a type of body for Create Post method from mattermost api reference, and changed type of post parameter to it. It won't break existing typings since PostToCreate type is subtype of Post.

#### Release Note

```
NONE
```

2022-07-05 13:48 UTC, neallred requested changes
Thanks for this, @DamirAhm ! Could you add a few more missing fields?

```
create_at
update_at
pending_post_id
reply_count
```

I see those being assigned in some of the code that uses this function.

It also looks like there are some [type checking errors](https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/56014/workflows/caebfb65-cbac-46f1-aa82-98fe4389820d/jobs/386715) that will need resolving. It's likely that resolving them will result in having to change a handful of other files that currently assert that the object they are passing a Post.

2022-07-18 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-07-18 14:14 UTC, neallred commented
@DamirAhm, any questions on the PR feedback?

2022-12-16 15:26 UTC, hmhealey commented
Removing my review request on this to clear out some notifications. Let me know when this is ready for my review again

2022-12-18 06:58 UTC, M-ZubairAhmed commented
@DamirAhm feel free to reopen, closing this one out to clear.

2022-12-18 06:58 UTC, closed without merging