[MM-45423]: re-added save option to post-dotmenu
mattermost/mattermost-webapp pull request #10701
Opened 2022-07-05 08:35 UTC by michelengelen

#### Summary
re-added the save/unsave option to the post dotmenu

#### Ticket Link
[MM-45423](https://mattermost.atlassian.net/browse/MM-45423)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

2022-07-05 14:21 UTC, matthewbirtch approved these changes
LGTM

2022-07-08 19:11 UTC, jgilliam17 commented
Apologies, requesting changes after posting approval 🤦🏽‍♀️ - We have a test for Copy menu option that you can use as a guideline `e2e/cypress/tests/integration/messaging/copy_post_text_spec.js`, can you please add something similar for Save? Thanks 🙂

2022-07-11 21:26 UTC, hmhealey approved these changes

2022-07-27 18:41 UTC, jfrerich approved these changes
LGTM!

2022-07-28 10:33 UTC, michelengelen commented
@jgilliam17 I have added tests for saving and unsaving a post.

I also did change add a new verification function, moved it to the post.js file and used it in saving spec and the post-pre-header spec (where i got most of the code from.

cc @saturninoabril

2022-07-28 12:50 UTC, jgilliam17 commented
Thanks @michelengelen for the test. 
Can you please fix failed checks, so we can trigger e2es

2022-07-28 13:55 UTC, jgilliam17 requested changes
Adding few test id suggestions

2022-07-28 13:55 UTC, jgilliam17 commented on e2e/cypress/tests/integration/messaging/save_post_spec.js
> +    it('MM-Txxxx Save menu item should save post', () => {
```suggestion
    it('MM-T4948_1 Save menu item should save post', () => {
```

2022-07-28 13:55 UTC, jgilliam17 commented on e2e/cypress/tests/integration/messaging/save_post_spec.js
> +    it('MM-Txxxx Save hotkey should save post', () => {
```suggestion
    it('MM-T4948_2 Save hotkey should save post', () => {
```

2022-07-28 13:55 UTC, jgilliam17 commented on e2e/cypress/tests/integration/messaging/save_post_spec.js
> +            cy.uiClickPostDropdownMenu(postId, 'Remove from Saved');
Can we add a line here to verify post was unsaved?

2022-07-28 13:55 UTC, jgilliam17 commented on e2e/cypress/tests/integration/messaging/save_post_spec.js
> +            cy.get('body').type('s');
same here, can we check if it was unsaved successfully

2022-07-28 16:45 UTC, michelengelen commented
/e2e-test

2022-07-28 16:45 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/223711

2022-07-28 17:55 UTC, jgilliam17 reviewed
Can we please add this tag too? 
Sorry I missed this, I just realized while looking at the report and could't find the new tests there.

2022-07-28 17:55 UTC, jgilliam17 commented on e2e/cypress/tests/integration/messaging/save_post_spec.js
> +
```suggestion

// Stage: @prod
```

2022-07-29 05:16 UTC, michelengelen commented
/e2e-test

2022-07-29 05:16 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/223871

2022-08-12 17:09 UTC, jgilliam17 commented
@michelengelen apologies for delay, I'm catching up after time off 
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/223871-3147883-onprem-ent-webapp-pr-10701-mattermost/mm-ee-test3147883/mochawesome.html)shows new tests are failing (MM-T4948)

2022-08-15 12:55 UTC, michelengelen commented
/e2e-test

2022-08-15 12:55 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/229646

2022-08-15 15:39 UTC, jgilliam17 commented
Checking why cypress run [failed](https://automation-dashboard.vercel.app/cycles/3c1242be-ca8a-4ae3-9029-ca3bdcf58ebf) to run

2022-08-15 15:50 UTC, jgilliam17 commented
/e2e-test

2022-08-15 15:50 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/229714

2022-08-15 19:56 UTC, jgilliam17 commented
Thanks @michelengelen - [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/229714-84be26d-onprem-ent-webapp-pr-10701-mm-ee-test:84be26d/mochawesome.html) looks good.
<img width="1175" alt="Screen Shot 2022-08-15 at 3 45 09 PM" src="https://user-images.githubusercontent.com/52937121/184706322-6db8eacc-4d6d-4b14-aa40-b8343e1ea8f7.png">

2022-08-15 19:56 UTC, jgilliam17 approved these changes

2022-08-15 19:56 UTC, merged