Fixing button text
mattermost/mattermost-webapp pull request #10731
Opened 2022-07-07 16:59 UTC by ctlaltdieliet

#### Summary
The text at start_trial.modal_btn.start isn't the same as mentioned in start_trial.modal.disclaimer
A translator noticed this
#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/20605
#### Release Note
```release-note
NONE
```

2022-07-07 16:59 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-07-08 13:53 UTC, AGMETEOR approved these changes

2022-07-15 23:00 UTC, jgilliam17 commented
/update-branch

2022-07-15 23:13 UTC, jgilliam17 commented
/e2e-test

2022-07-15 23:13 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/219259

2022-07-15 23:25 UTC, jgilliam17 requested changes
Thanks @ctlaltdieliet 
one word placement issue
<img width="602" alt="Screen Shot 2022-07-15 at 7 19 37 PM" src="https://user-images.githubusercontent.com/52937121/179323825-c3fc0588-e549-453f-ab16-a6f2de951cad.png">

2022-07-15 23:25 UTC, jgilliam17 commented on i18n/en.json
> +  "start_trial.modal.disclaimer": "By clicking “Start 30-day free trial”, I agree to the <linkEvaluation>Mattermost Software Evaluation Agreement</linkEvaluation>, <linkPrivacy>privacy policy</linkPr
```suggestion
  "start_trial.modal.disclaimer": "By clicking “Start free 30-day trial”, I agree to the <linkEvaluation>Mattermost Software Evaluation Agreement</linkEvaluation>, <linkPrivacy>privacy policy</linkPrivacy> and receiving product emails.",
```
I think `free` should be placed before `30-day` . Maybe @cwarnermm can confirm - thanks 🙂

2022-07-18 16:33 UTC, jgilliam17 approved these changes
Thanks @ctlaltdieliet 
Tested, looks good to merge.
Verified updated button text.
[E2E report ](https://automation-dashboard.vercel.app/cycles/45f68b75-c0f3-4904-a8ed-838915768f8c)- no PR related failures.

2022-07-18 16:35 UTC, jgilliam17 commented
@devinbinnie Do you mind quickly checking and approving the last workflow so we can merge? Thanks 🙂

2022-07-18 16:55 UTC, merged