[MM-45736] - Pricing Modal for Grandfathered Starter shows Free Starter Limits
mattermost/mattermost-webapp pull request #10815
Opened 2022-07-21 10:02 UTC by AGMETEOR

#### Summary
This PR ensures that StarterDisclaimerCTA does not show for legacy starter product.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45736

#### Release Note

```release-note
NONE
```

2022-07-21 10:10 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-07-21 10:16 UTC, AGMETEOR commented
> Cws@10102020

I have updated this spinwick to legacy cloud starter

2022-07-21 10:18 UTC, AGMETEOR commented
@johndavidlugtu adding you so that you can have a look at the legacy starter feature list in the console

2022-07-21 14:10 UTC, johndavidlugtu commented
@AGMETEOR thanks for tagging! The legacy Cloud Starter features in the System Console actually doesn't need to be updated. In the Jira ticket I mentioned that the proposed bullet points for the legacy Cloud Starter in the pricing modal was from the feature list from the System Console.

2022-07-21 15:02 UTC, marianunez requested changes
Condition to hide the limit disclaimer LGTM. However, we still need to change the pricing modal text for when they have no limits - see details in the ticket

2022-07-21 15:02 UTC, marianunez commented on components/admin_console/billing/plan_details/feature_list.tsx
> -        }),
Is this removal intended? This still applies to all Starter plans and the System Console card wouldn't require any changes

2022-07-21 15:04 UTC, neallred commented
Ditto what Maria said. Looks like that code lives in `components/pricing_modal/content.tsx`. We could check it by checking for a starter sku with no limits.

2022-07-21 16:15 UTC, AGMETEOR commented
> @AGMETEOR thanks for tagging! The legacy Cloud Starter features in the System Console actually doesn't need to be updated. In the Jira ticket I mentioned that the proposed bullet points for the legacy Cloud Starter in the pricing modal was from the feature list from the System Console.

Updated
<img width="1442" alt="Screenshot 2022-07-21 at 19 15 00" src="https://user-images.githubusercontent.com/28563179/180263196-ceed71be-ce29-40e9-b46c-a0d8e615e5e5.png">

2022-07-21 16:46 UTC, marianunez approved these changes
LGTM, thanks @AGMETEOR!

2022-07-21 16:47 UTC, marianunez commented
> > @AGMETEOR thanks for tagging! The legacy Cloud Starter features in the System Console actually doesn't need to be updated. In the Jira ticket I mentioned that the proposed bullet points for the legacy Cloud Starter in the pricing modal was from the feature list from the System Console.
> 
> Updated <img alt="Screenshot 2022-07-21 at 19 20 05" width="1442" src="https://user-images.githubusercontent.com/28563179/180264159-9c1ae6c3-3fe6-496a-87ea-dd3571ede018.png">

@AGMETEOR From the image, it seems legacy lost the `Current Plan` tag?

2022-07-21 16:48 UTC, AGMETEOR commented
> > > @AGMETEOR thanks for tagging! The legacy Cloud Starter features in the System Console actually doesn't need to be updated. In the Jira ticket I mentioned that the proposed bullet points for the legacy Cloud Starter in the pricing modal was from the feature list from the System Console.
> > 
> > 
> > Updated <img alt="Screenshot 2022-07-21 at 19 20 05" width="1442" src="https://user-images.githubusercontent.com/28563179/180264159-9c1ae6c3-3fe6-496a-87ea-dd3571ede018.png">
> 
> @AGMETEOR From the image, it seems legacy lost the `Current Plan` tag?

No this image is from local environment where my set up is not proper (i don't have products pulled in). I just wanted to use this image to show the copy. For a true image use the spinwick

2022-07-21 17:26 UTC, neallred approved these changes
LGTM, thanks @AGMETEOR !

2022-07-21 17:48 UTC, johndavidlugtu approved these changes
Good stuff @AGMETEOR !

2022-07-25 13:28 UTC, marianunez commented
@stevemudie can we prioritize this PR for today? Would like to get this fix in for the upcoming cloud release

2022-07-25 17:02 UTC, stevemudie commented
/e2e-test

2022-07-25 17:02 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/222341

2022-07-25 17:03 UTC, stevemudie commented
Looks good @AGMETEOR Just waiting on the E2E to run then I'll approve it.

2022-07-25 17:43 UTC, merged

2022-07-25 18:11 UTC, marianunez commented
/cherry-pick cloud

2022-07-25 18:11 UTC, mattermod commented
Cherry pick is scheduled.

2022-07-25 18:11 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
   313fe51f5..cb8f67ae2  MM-36439   -> upstream/MM-36439
 * [new branch]          MM-42719-z -> upstream/MM-42719-z
   e64a7f70e..ed1207e56  MM-43609   -> upstream/MM-43609
   54f18b7a7..833fcd83e  MM-43612   -> upstream/MM-43612
   81eff362d..eecd78c19  MM-44889-add-disclaimer-where-trial-starts-directly -> upstream/MM-44889-add-disclaimer-where-trial-starts-directly
   d72ab0f01..8bfff46b4  MM-45679-three-days-left-automatic-modal -> upstream/MM-45679-three-days-left-automatic-modal
   eac727dc0..ce8b3d8ab  POC/user-groups_compass-design -> upstream/POC/user-groups_compass-design
 * [new branch]          chore/master/update-notice-txt-2022-07-25 -> upstream/chore/master/update-notice-txt-2022-07-25
   f09269769..6ff57e87a  cloud      -> upstream/cloud
   707a67f05..8ab2f78ab  master     -> upstream/master
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-webapp-#10815-upstream-cloud-1658772698
Switched to a new branch 'automated-cherry-pick-of-mattermost-webapp-#10815-upstream-cloud-1658772698'
Branch 'automated-cherry-pick-of-mattermost-webapp-#10815-upstream-cloud-1658772698' set up to track remote branch 'cloud' from 'upstream'.

+++ About to attempt cherry pick of PR #10815 with merge commit 8ab2f78abbaaa5b2b51a78b547450101d2e2c52f.

error: could not apply 8ab2f78ab... [MM-45736] - Pricing Modal for Grandfathered Starter shows Free Starter Limits CTA (#10815)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2022-07-25 18:13 UTC, AGMETEOR commented
> /cherry-pick cloud

Let me do it manually

2022-07-25 18:13 UTC, mattermod commented
Cherry pick is scheduled.

2022-07-25 18:13 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.112.4' to the list of known hosts (/app/.ssh/known_hosts).
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
!!! 'upstream/cloud

Let' not found. The second argument should be something like upstream/release-0.21.
    (In particular, it needs to be a valid, existing remote branch that I can 'git checkout'.)

+++ Returning you to the master branch and cleaning up.

```

2022-07-25 18:14 UTC, marianunez commented
> > /cherry-pick cloud
> 
> Let me do it manually

Thanks @AGMETEOR

2022-07-25 18:14 UTC, mattermod commented
Cherry pick is scheduled.

2022-07-25 18:14 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
!!! 'upstream/cloud
>' not found. The second argument should be something like upstream/release-0.21.
    (In particular, it needs to be a valid, existing remote branch that I can 'git checkout'.)

+++ Returning you to the master branch and cleaning up.

```

2022-07-25 18:55 UTC, AGMETEOR commented
> > > /cherry-pick cloud
> > 
> > 
> > Let me do it manually
> 
> Thanks @AGMETEOR

https://github.com/mattermost/mattermost-webapp/pull/10831

2022-07-25 18:55 UTC, mattermod commented
Cherry pick is scheduled.

2022-07-25 18:55 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
   1b1ad36c2..e9c990a3b  MM-45387_use-websocket -> upstream/MM-45387_use-websocket
 * [new branch]          cherry-pick-MM-45736   -> upstream/cherry-pick-MM-45736
 * [new branch]          cleanup-rollup-error   -> upstream/cleanup-rollup-error
Fetching origin
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
!!! 'upstream/cloud
>' not found. The second argument should be something like upstream/release-0.21.
    (In particular, it needs to be a valid, existing remote branch that I can 'git checkout'.)

+++ Returning you to the master branch and cleaning up.

```

2022-07-25 18:55 UTC, mattermod commented
Cherry pick is scheduled.

2022-07-25 18:55 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-webapp-#10815-upstream-*-1658775357
fatal: 'upstream/*' is not a commit and a branch 'automated-cherry-pick-of-mattermost-webapp-#10815-upstream-*-1658775357' cannot be created from it

+++ Returning you to the master branch and cleaning up.

```