[MM-42526] When a profile picture fails to load,  fall back to the user's default picture
mattermost/mattermost-webapp pull request #10810
Opened 2022-07-20 13:47 UTC by kyeongsoosoo

#### Summary

If user's profile picture fails to load, replace src with default profile src(I used the regex).
`Client4.getUsersRoute() + '/' + userId + '/image?_=' + lastPictureUpdate` 
-> 
`Client4.getUsersRoute() + '/' + userId + '/image/default'` 

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/19815

#### Screenshots

#### Release Note

```release-note
add fallback src to an avatar
```

2022-07-20 13:47 UTC, mattermod commented
Hello @kyeongsoosoo,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-07-21 10:48 UTC, michelengelen requested changes

2022-07-21 15:42 UTC, kyeongsoosoo commented on components/widgets/users/avatar/avatar.tsx
> +const isURLForUser = (url: string | undefined): url is string => Boolean(url && url.startsWith(Client4.getUsersRoute()));
@michelengelen Thanks for the tip! I made a mistake😅

2022-07-21 18:28 UTC, michelengelen approved these changes
LGTM... thanks!

2022-07-26 12:50 UTC, BenCookie95 approved these changes
LGTM, nice work!

2022-07-26 16:48 UTC, michelengelen commented
/e2e-test

2022-07-26 16:48 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/222825

2022-07-27 15:54 UTC, furqanmlk reviewed
Hi @kyeongsoosoo can you please provide me broken image.

2022-07-27 20:46 UTC, hmhealey commented
This error case could be caused by a few different things (like the image being deleted on the server or a network issue), but the best way to repro this would probably be to block the request using the browser's dev tools. You can do that by:
1. Right clicking on the user's profile picture and copy the image link. It'll look like `https://mattermost-webapp-pr-10810.test.mattermost.cloud/api/v4/users/u8hqnuam9intmydrg7kbepy6we/image?_=1658954268819` which is the current url for user-1's profile picture on that test server.
2. Go to the Network tab of the browser's dev tools and find how to show blocked requests. On Firefox, it's the 🚫 icon to the right of the filter box.
3. Enter the URL from step 1 to block
4. Refresh the page

Or you can take my word that it works based on these screenshots:
|Normal (request allowed)|Error (request blocked)|
|-|-|
|![Screen Shot 2022-07-27 at 4 41 23 PM](https://user-images.githubusercontent.com/3277310/181368773-15332ed3-e298-41f6-94b5-b9cd5b594b5f.png)|![Screen Shot 2022-07-27 at 4 41 31 PM](https://user-images.githubusercontent.com/3277310/181368920-baa5f95c-dd27-4f21-ad10-cd5aceaf52f5.png)|

2022-08-03 03:00 UTC, kyeongsoosoo commented
> This error case could be caused by a few different things (like the image being deleted on the server or a network issue), but the best way to repro this would probably be to block the request using the browser's dev tools. You can do that by:
> 
@furqanmlk  I tested it in a similar way!

2022-08-03 18:13 UTC, furqanmlk approved these changes
Thanks @kyeongsoosoo  working fine


**With Profile Picture**
<img width="378" alt="image" src="https://user-images.githubusercontent.com/6909890/182679060-a25369ca-ef46-499d-8051-95798dff92c7.png">

**Without Profile Picture**
<img width="379" alt="image" src="https://user-images.githubusercontent.com/6909890/182678934-d1743f4e-3f0a-4014-ae98-9b0d71071c47.png">

2022-08-04 20:55 UTC, hmhealey commented
Great. Thanks again for the PR!

2022-08-04 20:55 UTC, merged