[MM-44860] Screen reader announcing link copied on coping the link in invite modal
mattermost/mattermost-webapp pull request #11081
Opened 2022-09-07 10:57 UTC by babinderrathi

#### Summary
Screen reader announcing link copied on coping the link in invite modal

#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/MM-44860

#### Related Pull Requests
None

#### Screenshots

|  before  |
|----|
https://user-images.githubusercontent.com/102028591/188860492-8e308cf1-e6e7-42bb-a06c-65cfa5809290.mp4

|  after |
|----|
https://user-images.githubusercontent.com/102028591/188861546-eed97466-0b40-440d-85b7-fd27cec8ac99.mp4

#### Release Note
```release-note
* Screen reader announcing link copied on copieng the link in invite modal
```

2022-09-07 10:57 UTC, mattermod commented
Hello @babinderrathi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-09-07 19:34 UTC, hmhealey requested changes
Thanks for the PR, @babinderrathi! There's one small thing I'd like changed, but this looks good to me.

One other thing I did notice is that I would've expected the button to need an aria-live so that changes in the label are read out, but I'm not too familiar with screen readers, so perhaps that isn't needed as long as the button is stays in focus after interacting with it

2022-09-07 19:34 UTC, hmhealey commented on components/invitation_modal/invite_view.tsx
> +            aria-label={localizeMessage(
Instead of `localizeMessage` could you instead use `formatMessage` for these?

2022-09-09 10:13 UTC, nevyangelova approved these changes
Thanks @babinderrathi and also for adding the translations, LGTM!

2022-09-09 16:40 UTC, hmhealey approved these changes
Thanks for changing that!

2022-09-12 17:25 UTC, mkraft approved these changes

2022-09-13 18:55 UTC, hmhealey commented
/e2e-tests

2022-09-13 18:55 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/240584

2022-09-24 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-09-29 02:04 UTC, AshishDhama commented
@jgilliam17 this is ready for QA Review

2022-09-29 19:20 UTC, jgilliam17 commented
/update-branch

2022-09-29 19:35 UTC, jgilliam17 commented
Thanks @babinderrathi 
macOS VoiceOver is announcing "Link Copied", but Windows Jaws reader is still not announcing when the link is copied. Instead it announces "space" which is the key pressed to activate/copy the link.

2022-10-10 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-10-11 15:53 UTC, hmhealey commented
Hi @babinderrathi. Are you able to look into that issue with JAWS? It's generally the screen reader that we test with since we have some big deployments using it.

If you need help fixing it or reproducing the issue yourself, let us know and we can help out.

2023-01-11 21:34 UTC, mkraft approved these changes

2023-01-13 10:02 UTC, nevyangelova approved these changes
LGTM!

2023-01-13 10:54 UTC, nevyangelova commented
/update-branch

2023-01-24 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-01-24 04:50 UTC, AshishDhama commented
@jgilliam17 could you please check if this working as expected now.

2023-01-28 02:22 UTC, jgilliam17 commented
@AshishDhama JAWS reader is announcing the whole Invite link e.g. https://mattermost-webapp-pr-11081.test.mattermost.cloud/signup_user_complete/?id=p561t9zowb8j5ca3kc8goufsme&sbr=fa
Instead of only announcing "Link Copied" or similar

2023-02-01 05:38 UTC, AshishDhama commented
@babinderrathi could you please fix this?

2023-02-17 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-02-24 17:40 UTC, lindy65 commented
/update branch

2023-02-24 17:44 UTC, lindy65 commented
Hey @AshishDhama - are we still having issues setting up spinwicks?

2023-02-24 17:46 UTC, AshishDhama commented
@lindy65 Yeah, for fork pr, there are some issues

2023-02-24 18:51 UTC, lindy65 commented
Thanks @AshishDhama - I will test this as soon as the spinwick issues are resolved.

2023-03-09 06:14 UTC, AshishDhama commented
@lindy65 You can test this pr now.

2023-03-13 10:50 UTC, lindy65 approved these changes
Thanks @babinderrathi - this is fixed, Jaws announces that the link is copied

cc @AshishDhama

2023-03-23 11:01 UTC, M-ZubairAhmed commented
Hey there!, Thank you for your PR.
Webapp is now part of mattermost monorepo now at https://github.com/mattermost/mattermost-server/tree/master/webapp Would you be interested in opening the PR over there?

2023-03-23 20:23 UTC, hmhealey commented
The web app now lives in the `webapp/channels` over in https://github.com/mattermost/mattermost-server. We decided to move it to be a monorepo to make both development and our CI pipelines easier, but it's unfortunately disruptive right now. We've updated [our setup docs](https://developers.mattermost.com/contribute/developer-setup/) and added [some steps for migrating to working with the monorepo](https://developers.mattermost.com/contribute/monorepo-migration-notes/).

Copying the changes over there hopefully shouldn't be too hard. There's a few changes to file paths (such as the code living in a dedicated `src` subdirectory), but most things should look the same as they do now. 

Let us know if you could use any help with this. Hopefully the process is smooth.

2023-04-03 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-04-03 09:33 UTC, AshishDhama commented
Closing in favour of https://github.com/mattermost/mattermost-server/pull/22785

2023-04-03 09:33 UTC, closed without merging