Mm 46596 successfull login announce
mattermost/mattermost-webapp pull request #11083
Opened 2022-09-07 12:09 UTC by AbhinavVihan

#### Summary
Screen Reader Announces Login Successfull

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46596

#### Related Pull Requests
None

#### Screenshots

#### Release Note

```release-note
   Screen Reader Announces Login Successfull

```

2022-09-07 12:09 UTC, mattermod commented
Hello @AbhinavVihan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-09-07 12:09 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-09-08 05:22 UTC, AshishDhama commented on components/login/login.tsx
> +        srSpeak('Login Successfull', 'assertive');
@AbhinavVihan use FormatMessage to localise message.

2022-09-08 05:25 UTC, AshishDhama commented
@nevyangelova I think you have an idea of accessibility, if you could confirm, it is the right approach for this?

2022-09-09 10:21 UTC, nevyangelova requested changes
Thanks @AbhinavVihan I would like to suggest a different approach. You do not need to add a function for this, as HTML5 elements support their own accessibility props. In this case you can check which elements are being read out loud when login is successful and remove them from the login group, as well as adding missing aria-labels. You can read about it here https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label
https://developer.mozilla.org/en-US/docs/Web/Accessibility

2022-09-14 11:16 UTC, nevyangelova approved these changes
Thanks, looks great!

2022-09-14 11:26 UTC, AshishDhama approved these changes

2022-09-14 11:27 UTC, AshishDhama commented
@AbhinavVihan Could you please update the failing snapshot

2022-09-14 11:54 UTC, AbhinavVihan commented
on it

2022-09-15 04:47 UTC, AshishDhama approved these changes

2022-09-26 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-09-29 19:44 UTC, jgilliam17 commented
Thanks @AbhinavVihan 
The announcement at login is "Mattermost message input complementary region" since that is where the focus is placed at login. No "login successful" announcement after user presses Enter to log in.
Tested using Jaws reader on Windows.

2022-09-30 04:09 UTC, AbhinavVihan commented
@jgilliam17, Would you take a look please

2022-09-30 15:00 UTC, jgilliam17 commented
/e2e-test

2022-09-30 15:00 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/245872

2022-09-30 20:31 UTC, jgilliam17 commented
Thank you for the quick fix @AbhinavVihan 
When testing manually, reader is announcing "login successful".
[E2E report](https://automation-dashboard.vercel.app/cycles/c1e929d9-070a-4e47-83c1-54213b2517a0) show that 2 tests are failing in tests/integration/accessibility/accessibility_nav_diff_regions_spec.js
Can you please take a look?

2022-10-01 03:22 UTC, AbhinavVihan commented
Hi @jgilliam17, I don't think there was some failing issue in the tests, I've rechecked it.
![Screenshot from 2022-10-01 08-50-19](https://user-images.githubusercontent.com/89139362/193384584-b30bfb1a-28b6-463e-94a0-d82e8ee00ba1.png)

2022-10-03 11:50 UTC, jgilliam17 approved these changes
Thanks for verifying the tests @AbhinavVihan. 
Looks good to merge.
@AshishDhama can you please approve the last workflow and merge - thanks 🙂

2022-10-04 13:46 UTC, merged

2022-10-24 16:51 UTC, amyblais commented
/cherry-pick release-7.1

2022-10-24 16:51 UTC, mattermod commented
Cherry pick is scheduled.

2022-10-24 16:51 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
Fetching origin
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-webapp-#11083-upstream-release-7.1-1666630311
Switched to a new branch 'automated-cherry-pick-of-mattermost-webapp-#11083-upstream-release-7.1-1666630311'
Branch 'automated-cherry-pick-of-mattermost-webapp-#11083-upstream-release-7.1-1666630311' set up to track remote branch 'release-7.1' from 'upstream'.

+++ About to attempt cherry pick of PR #11083 with merge commit 25f6eaf48110d3cbfd3d13ce63416a206c51ef72.

error: could not apply 25f6eaf48... [MM-46596] Screen Reader Announces Login Successful (#11083)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU components/advanced_text_editor/advanced_text_editor.tsx
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2022-10-24 16:54 UTC, amyblais commented
@nevyangelova @AshishDhama Can you help manually cherry-pick this to the ``release-7.1`` branch? I was requested to backport this to the v7.1 ESR.