[Mm 44864] Too long time stamp announcement
mattermost/mattermost-webapp pull request #11139
Opened 2022-09-15 04:02 UTC by AbhinavVihan

#### Summary
Time stamp announcement shortened (when focused on post time)

#### Ticket Link
fixes https://mattermost.atlassian.net/browse/MM-44864

#### Related Pull Requests
None

#### Screenshots

#### Release Note
NA
```release-note
Time stamp announcement shortened (when focused on post time)

```

2022-09-15 04:02 UTC, mattermod commented
Hello @AbhinavVihan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-09-15 04:02 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-09-20 16:37 UTC, nevyangelova requested changes
Thanks @AbhinavVihan can you please update the failing snapshots?

2022-09-21 05:13 UTC, AbhinavVihan commented
Done

2022-09-28 08:21 UTC, AbhinavVihan commented
Hi @nevyangelova, Can you plaease take a look now.

2022-09-28 10:23 UTC, nevyangelova approved these changes

2022-09-28 10:24 UTC, nevyangelova approved these changes

2022-10-09 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-10-11 19:13 UTC, AshishDhama commented
@jgilliam17 Gentle reminder on this one.

2022-10-11 19:14 UTC, AshishDhama commented
@BenCookie95 Take a look.

2022-10-11 19:37 UTC, BenCookie95 requested changes
The ticket's title is a little misleading, I think the issue is that the timestamp announcement doesn't follow the users time display settings?

The announcement should match what appears in the tooltip when you hover over a posts timestamp I think. @jgilliam17 can you confirm?

2022-10-11 21:46 UTC, jgilliam17 commented
@BenCookie95 yes, I agree - as written in the ticket expected section, the announcement should follow user set time format i.e. 12h or 24h clock, and read out what is displayed for post time stamp

2022-10-12 03:50 UTC, AbhinavVihan commented
@BenCookie95, So then length of announced timestamp should remain the same? **Reader announces the date and time using 24 hour clock, including adding GMT information**
or it should be shortened and announced in ***format selected by the user in settings for clock display***

2022-10-12 13:28 UTC, BenCookie95 commented
> @BenCookie95, So then length of announced timestamp should remain the same? **Reader announces the date and time using 24 hour clock, including adding GMT information** or it should be shortened and announced in _**format selected by the user in settings for clock display**_

I think the length should remain the same but if the timestamp has a time in there, the time should follow the setting from their clock display settings

2022-10-12 16:20 UTC, calebroseland commented
@AbhinavVihan (and others) I'm sorry that I let this review slip. Albeit much late, here is some background and a few thoughts.

Ideally, I think that the announcement should match the contents of the tooltip, as the spoken announcement is an alternative presentation of the tooltip, which is a more precise timestamp—`time` and `date`.

<img width="167" alt="CleanShot 2022-10-12 at 09 01 24@2x" src="https://user-images.githubusercontent.com/11724372/195369997-4d4d4371-5462-4a75-8b6f-9edd340695e9.png">

IMO, shorting the `aria-label` it to just `time` negates the purpose of the more precise timestamp. It feels odd just having the time announced twice.

When Timestamp was first written, the `formatLabel` method was a bit of a shortcut and not polished. Additionally, the `datetime` attribute on `<time>` gives the screenreader what it needs (machine-readable ISO-time) to read out according to the screenreader's time locale options. 

## Possible Solution

To get the announcement to say what is in the tooltip, I think we should drop the default `area-label` from Timestamp/SemanticTime (SemanticTime would still be semantic because of the `datetime` attribute.) With that `aria-label` gone, it would let the tooltip's `labelled-by` attribute to point to the tooltip when focusing on the permalink. For the screenshot above, it would then announce: "Link, 5:15PM. September 15 at 5:15PM" 

I would suggest:
- in `timestamp`:
```diff
--- a/components/timestamp/timestamp.tsx
+++ b/components/timestamp/timestamp.tsx
@@ -429,7 +429,7 @@ class Timestamp extends PureComponent<Props, State> {
             formatted = (
                 <SemanticTime
                     value={value}
-                    aria-label={label ?? Timestamp.formatLabel(value, timeZone)}
+                    aria-label={label}
                     className={className}
                 >
                     {formatted}
```
- in `semantic_time`:
```diff
--- a/components/timestamp/semantic_time.tsx
+++ b/components/timestamp/semantic_time.tsx
@@ -1,6 +1,7 @@
 // Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
 // See LICENSE.txt for license information.
 
+import {DateTime} from 'luxon';
 import React, {FC, ReactNode, memo, TimeHTMLAttributes} from 'react';
 
 export type Props = {
@@ -11,14 +12,12 @@ export type Props = {
 const SemanticTime: FC<Props> = ({
     value,
     children,
-    'aria-label': label = value.toLocaleString(),
     ...props
 }: Props) => {
     return (
         <time
             {...props}
-            aria-label={label}
-            dateTime={value.toISOString()}
+            dateTime={DateTime.fromJSDate(value).toLocal().toISO({includeOffset: false})}
         >
             {children}
         </time>
```

- in `post_time`:
```diff
--- a/components/post_view/post_time/post_time.tsx
+++ b/components/post_view/post_time/post_time.tsx
@@ -101,6 +101,7 @@ export default class PostTime extends React.PureComponent<Props> {
                         <Timestamp
                             value={eventTime}
                             ranges={POST_TOOLTIP_RANGES}
+                            useSemanticOutput={false}
                         />
                     </Tooltip>
                 }
```


Again, I'm sorry for the long delay. Happy to continue to discuss.

2022-10-14 04:44 UTC, AbhinavVihan commented
@calebroseland, Thankyou for all the information, truly.

2022-10-14 15:30 UTC, BenCookie95 requested changes
Thanks for looking into this again @AbhinavVihan but still a few issues. The announcer is now using the aria-describedby attribute from the link but it's still only reading the time and not any date information. We need to add `aria-labelledby={eventTime.toString()}` to the Link component in the post_time file and that will fix it!

Thanks for the detailed response @calebroseland!

2022-10-14 16:34 UTC, calebroseland commented on components/post_view/post_time/post_time.tsx
> +                useSemanticOutput={false}
Yes, this should go onto the timestamp in the tooltip, not the one here.

2022-11-18 14:27 UTC, BenCookie95 approved these changes

2022-11-25 18:30 UTC, calebroseland approved these changes

2022-12-05 18:08 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2022-12-05 18:12 UTC, jgilliam17 commented
/e2e-test

2022-12-05 18:12 UTC, mattermod commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/271135) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/271135)

2022-12-07 05:39 UTC, AbhinavVihan commented
@jgilliam17, rebased with master

2022-12-07 06:25 UTC, M-ZubairAhmed commented
/e2e-test

2022-12-07 06:25 UTC, mattermod commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/272167) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/272167)

2022-12-07 14:54 UTC, jgilliam17 commented
Thanks for running e2es @M-ZubairAhmed 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/272167-3bd3d58-onprem-ent-webapp-pr-11139-mm-ee-test:3bd3d58/mochawesome.html) looks good, no PR related failures.

2022-12-07 14:55 UTC, jgilliam17 approved these changes

2022-12-07 14:55 UTC, merged