Search date provider
mattermost/mattermost-webapp pull request #11188
Opened 2022-09-23 13:43 UTC by BediNimret

#### Summary

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note

```

2022-09-23 13:43 UTC, mattermod commented
Hello @BediNimret,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-09-23 13:43 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-09-26 08:18 UTC, AshishDhama commented
@BediNimret there are couple of lint issue you could fix those

2022-09-27 13:14 UTC, M-ZubairAhmed requested changes
Can you recheck the types, it seems its failing CI

2022-09-27 13:14 UTC, M-ZubairAhmed commented on components/suggestion/search_date_provider.tsx
> +import {TypeOf} from 'yup';
why do we need this?

2022-09-27 13:14 UTC, M-ZubairAhmed commented on components/suggestion/search_date_provider.tsx
> +            const dates: Array<{lable: string;date: string}> = Object.assign([], [{label: 'Selected Date', date: datePrefix}]);
typo in label

2022-09-30 04:53 UTC, closed without merging

2022-09-30 10:28 UTC, BediNimret commented
This PR has been closed by mistake. The new PR for this migration is https://github.com/mattermost/mattermost-webapp/pull/11222. 
Sorry for inconvenience caused.