People - Add search to people list
mattermost/mattermost-webapp pull request #11192
Opened 2022-09-23 15:31 UTC by julmondragon

#### Summary
Adding search to people list

#### Screenshots

#### Release Note
```release-note
NONE
```

2022-09-23 15:35 UTC, BenCookie95 requested changes

2022-09-23 15:35 UTC, BenCookie95 commented on components/people/directory/directory.tsx
> +            allow_inactive: true,
I think we can set this to false

2022-09-23 15:58 UTC, Pinjasaur approved these changes
LGTM other than a small CI error and other feedback. I hackily fixed the styling that the `<Highlight>` component broke. Good enough for now. 🎉

2022-09-23 17:23 UTC, julmondragon commented on components/people/directory/directory.tsx
> +            allow_inactive: true,
Done

2022-09-25 13:10 UTC, BenCookie95 approved these changes

2022-09-25 13:29 UTC, merged