MM-47098: Migrate components/channel_notifications_modal/channel_notifications_modal.test.jsx to typescript
mattermost/mattermost-webapp pull request #11209
Opened 2022-09-28 05:23 UTC by AbhinavVihan

#### Summary
Migrate components/channel_notifications_modal/channel_notifications_modal.test.jsx to typescript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21071
Fixes https://mattermost.atlassian.net/browse/MM-47098

#### Related Pull Requests
None

#### Screenshots
None

#### Release Note

```release-note
Migrate components/channel_notifications_modal/channel_notifications_modal.test.jsx to typescript
```

2022-09-28 05:23 UTC, mattermod commented
Hello @AbhinavVihan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-09-28 05:23 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-09-29 21:43 UTC, M-ZubairAhmed requested changes

2022-09-29 21:43 UTC, M-ZubairAhmed commented on packages/types/src/channels.ts
> +    push_threads: 'default' | 'all' | 'mention' | 'none';
these belong in UserNotifyProps and not in here. cc @koox00

2022-09-29 22:07 UTC, M-ZubairAhmed commented
i am sorry there was a mistake on our side , this was a duplicate ticket opened on us. Apologies for your re-work 😞 
feel free to close this one out

2022-09-29 22:08 UTC, closed without merging

2022-09-30 11:10 UTC, AbhinavVihan commented
No worries