MM-47087 : Migrate "components/integrations/integrations.jsx"
mattermost/mattermost-webapp pull request #11205
Opened 2022-09-27 17:01 UTC by babinderrathi

#### Summary
Migration of integrations.jsx to integrations.tsx

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/21082

  Fixes https://mattermost.atlassian.net/browse/MM-47087

#### Related Pull Requests
None 

#### Screenshots
None

#### Release Note

```release-note

Migration of integrations.jsx to integrations.tsx successful.

```

2022-09-27 17:01 UTC, mattermod commented
Hello @babinderrathi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-09-27 17:01 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-09-28 10:36 UTC, AshishDhama submitted a review, later dismissed

2022-09-29 05:42 UTC, M-ZubairAhmed requested changes

2022-09-29 05:42 UTC, M-ZubairAhmed commented on components/integrations/index.js
> +import Integrations from './integrations';
this needs to be converted to "ts"

2022-09-29 05:45 UTC, M-ZubairAhmed requested changes

2022-09-29 05:45 UTC, M-ZubairAhmed commented on components/integrations/integrations.tsx
> +    };
this needs to be `Team` type

2022-09-30 12:51 UTC, nevyangelova requested changes
Thanks @babinderrathi would it be possible to convert the index.js file as well?

Also I can see a few places in the component functions that could be typed as well. Do you mind double checking?

2022-10-01 14:23 UTC, M-ZubairAhmed commented
/release-note-none

2022-10-03 11:59 UTC, nevyangelova approved these changes

2022-10-05 14:13 UTC, M-ZubairAhmed requested changes

2022-10-05 14:13 UTC, M-ZubairAhmed commented on components/integrations/integrations.tsx
> +    };
@babinderrathi please take a look at this one

2022-10-05 18:53 UTC, M-ZubairAhmed approved these changes
💯 It looks good to me. Thank you 🎉

2022-10-05 19:03 UTC, merged