Migrate "components/markdown_image.jsx" to Typescript
mattermost/mattermost-webapp pull request #11203
Opened 2022-09-27 16:07 UTC by babinderrathi

#### Summary
Migration of markdown_image fie from jsx to tsx

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/21062

  Fixes  https://mattermost.atlassian.net/browse/MM-47108

#### Related Pull Requests
None

#### Screenshots
None

#### Release Note
```release-note

markdown_image.jsx file is succesfully migrated to markdown_image.tsx .

```

2022-09-27 16:07 UTC, mattermod commented
Hello @babinderrathi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-09-27 16:07 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-09-29 06:05 UTC, M-ZubairAhmed requested changes

2022-09-29 06:05 UTC, M-ZubairAhmed commented on components/markdown_image/markdown_image.tsx
> +        }: any = this.props;
lets me more specific than any

2022-10-05 13:58 UTC, M-ZubairAhmed requested changes

2022-10-05 13:58 UTC, M-ZubairAhmed commented on components/markdown_image/markdown_image.tsx
> -    handleImageLoaded = ({height, width}) => {
lets remove "any" here

2022-10-05 13:58 UTC, M-ZubairAhmed commented on components/markdown_image/markdown_image.tsx
> +    componentDidUpdate(prevProps: any) {
lets remove "any" here

2022-10-11 10:59 UTC, M-ZubairAhmed requested changes

2022-10-11 10:59 UTC, M-ZubairAhmed commented on components/markdown_image/markdown_image.tsx
> +    postId: string;
nit
postId: Post['id'}

2022-10-11 10:59 UTC, M-ZubairAhmed commented on components/markdown_image/markdown_image.tsx
> +    postType: string;
nit
From Post type

2022-10-11 10:59 UTC, M-ZubairAhmed commented on components/markdown_image/markdown_image.tsx
> +    onImageLoaded: ({}) => void;
i am not sure if we need `{}` in the parameters

2022-10-11 10:59 UTC, M-ZubairAhmed commented on components/markdown_image/markdown_image.tsx
> +                                }}
from where did these came from, these should not be passed here, since they are dispatched inside of markdownimageexapand itself

2022-10-11 10:59 UTC, M-ZubairAhmed commented on components/markdown_image_expand/markdown_image_expand.tsx
> +    }, [isExpanded, onToggle]);
lets revert this.

2022-10-11 12:36 UTC, m1lt0n requested changes
Left one additional comment on top of the ones the other reviewers left and are still pending.

2022-10-11 12:36 UTC, m1lt0n commented on components/markdown_image/markdown_image.tsx
> +    showModal = (e: any, link: string) => {
Let's remove the any type of the event in the signature.

2022-10-22 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-10-24 09:24 UTC, M-ZubairAhmed commented
@babinderrathi hey gentle ping on this one :)

2022-11-04 07:53 UTC, M-ZubairAhmed commented
@babinderrathi feel free to use the re-request review once you are done

2023-01-20 01:04 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-03-02 21:18 UTC, lieut-data commented
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

2023-03-02 21:18 UTC, closed without merging