MM-47068: Migrate components/suggestion/provider.jsx to typescript
mattermost/mattermost-webapp pull request #11272
Opened 2022-10-04 15:47 UTC by AbhinavVihan

#### Summary
Migrate components/suggestion/provider.jsx to typescript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21131
JIRA: https://mattermost.atlassian.net/browse/MM-47068

#### Related Pull Requests
None

#### Screenshots
None

#### Release Note

```release-note
Migrate components/suggestion/provider.jsx to typescript
```

2022-10-04 15:47 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-06 09:20 UTC, michelengelen requested changes
only a small change to be done ... otherwise LGTM

2022-10-06 09:20 UTC, michelengelen commented on components/suggestion/provider.tsx
> +import {ProviderResults} from 'components/forward_post_modal/forward_post_channel_select';
it would be better to define the `ProviderResult` type here and import it in the `forward_post_modal.tsx` instead

2022-10-06 09:20 UTC, michelengelen commented on components/forward_post_modal/forward_post_channel_select.tsx
> +export type ProviderResults = {
please move this to the provider file and import here ... also this should probably be renamed to `ProviderResult`

2022-10-06 11:51 UTC, AbhinavVihan commented
@michelengelen, Requested changes are done.
Would you please take a look.

2022-10-06 12:33 UTC, michelengelen commented on components/suggestion/provider.tsx
> +    // eslint-disable-next-line
we are already disabling the linting in the next line ... so this is not necessary

2022-10-07 08:38 UTC, m1lt0n approved these changes

2022-10-07 08:54 UTC, m1lt0n commented
/e2e-test

2022-10-07 08:54 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/248183

2022-10-08 05:07 UTC, AbhinavVihan commented
@michelengelen, the requested changes are done.

2022-10-08 05:55 UTC, michelengelen commented on components/suggestion/provider.tsx
> +    forceDispatch: boolean;
@AbhinavVihan sry, I wasn't clear on this. We should keep the block, but only add a single blank line so that it is separated from the constructor

2022-10-08 05:58 UTC, michelengelen requested changes
I am sorry @AbhinavVihan ...

2022-10-08 05:58 UTC, michelengelen commented on components/suggestion/provider.tsx
> +    // eslint-disable-next-line
Could you please only disable the rule that is being violated and not all of eslint?

2022-10-09 05:32 UTC, michelengelen approved these changes

2022-10-14 03:50 UTC, jgilliam17 approved these changes
Thanks @AbhinavVihan 
Tested, looks good to merge.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/248183-addb292-onprem-ent-webapp-pr-11272-mm-ee-test:addb292/mochawesome.html) - no PR related failures.

2022-10-14 03:50 UTC, merged