MM-47109 : Migrate components/list_modal.jsx to Typescript
mattermost/mattermost-webapp pull request #11319
Opened 2022-10-10 03:31 UTC by AbhinavVihan

#### Summary
Migrate components/list_modal.jsx to Typescript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21061
JIRA: https://mattermost.atlassian.net/browse/MM-47109

#### Related Pull Requests
None

#### Screenshots
None

#### Release Note

```release-note
Migrate components/list_modal.jsx to Typescript
```

2022-10-10 03:31 UTC, mattermod commented
Hello @AbhinavVihan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-10 03:31 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-11 11:04 UTC, M-ZubairAhmed commented
/release-note-none

2022-10-11 11:04 UTC, M-ZubairAhmed commented
@AbhinavVihan can you please CI for us to initiate the review

2022-10-11 11:16 UTC, AbhinavVihan commented
@M-ZubairAhmed, Its ready for review. Thanks

2022-10-11 12:31 UTC, m1lt0n requested changes
Looks good, left a couple of comments about optional props.

2022-10-11 12:31 UTC, m1lt0n commented on components/list_modal.tsx
> +    titleText: string;
Based on the comments, also `titleText`, `show` and `searchPlaceholderText` are optional. Below they are marked as required.

2022-10-13 06:12 UTC, m1lt0n approved these changes

2022-10-13 15:43 UTC, sinansonmez requested changes
Thanks for the contribution. I just have one minor comment related to deleted comments

2022-10-13 15:43 UTC, sinansonmez commented on components/list_modal.tsx
> -        /**
As I was informed previously, these comments are picked up by some tool for documentation. For this reason, I would keep the comments

2022-10-14 08:05 UTC, sinansonmez approved these changes
LGTM thanks

2022-10-14 08:06 UTC, sinansonmez commented on components/list_modal.tsx
> -        /**
Thanks for adding back the comments

2022-10-25 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-10-25 13:03 UTC, jgilliam17 commented
/update-branch

2022-10-25 13:03 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2022-10-25 13:04 UTC, jgilliam17 commented
/e2e-test

2022-10-25 13:04 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/254639

2022-10-25 17:37 UTC, jgilliam17 commented
@m1lt0n can you please approve the last workflow and merge? Thanks 🙂

2022-10-26 08:58 UTC, merged

2022-11-16 19:56 UTC, jordanafung commented
@AbhinavVihan - Thank you for participating in Hacktoberfest!
Please fill out [this form](https://docs.google.com/forms/d/1s0xarmIVqXcut1Z7waaKqrWbuwCpGg4s9lA-bChO89Y/) if you'd like to get your Hacktoberfest Stickers!

2023-01-05 18:48 UTC, jordanafung commented
Hi @AbhinavVihan 
You were selected as one of our Top Contributors for Hacktoberfest!
Please fill out [this form](https://docs.google.com/forms/d/11pLB3pF1CmOslYqHr7c7bxFWU6QAEAJuiaKgHD1vJtg) to select your swag as thanks!
Thank you for all you do and for making Mattermost even better!