MM-47242 - improve tasklist items texts
mattermost/mattermost-webapp pull request #11335
Opened 2022-10-12 12:33 UTC by pvev

#### Summary
Improve the tasklists texts. POC

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note

```

2022-10-13 07:40 UTC, pvev commented
@marianunez @dontoisme @annelieseklein (please, ignore the repeated icons, I will update this along with the width size decisition)

With width of 500px:
<img width="1618" alt="Captura de Pantalla 2022-10-13 a las 9 37 24" src="https://user-images.githubusercontent.com/10082627/195532949-bc0c2bec-537b-4f08-ae1e-bf18087e35c4.png">


With current width:
<img width="1443" alt="Captura de Pantalla 2022-10-13 a las 9 37 46" src="https://user-images.githubusercontent.com/10082627/195532899-618234e9-54c9-4f51-8920-91d1d8dce80d.png">

2022-10-14 21:33 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-18 20:51 UTC, annelieseklein commented
@pvev 
please keep at current width - the text for 1st, 2nd and 3rd points will be: "Learn about messaging", "plan a sprint with kanban-style boards", "Resolve incidents faster with playbooks" ; keep the other points all the same text as current

2022-10-18 20:52 UTC, annelieseklein approved these changes

2022-10-19 11:14 UTC, pvev commented
> @pvev please keep at current width - the text for 1st, 2nd and 3rd points will be: "Learn about messaging", "plan a sprint with kanban-style boards", "Resolve incidents faster with playbooks" ; keep the other points all the same text as current

ok, thanks for the feedback @annelieseklein, what about the icons?
@dontoisme ^^

2022-10-19 16:03 UTC, annelieseklein commented
@pvev keep the icons for all items please, thank you! :)

2022-10-20 23:40 UTC, marianunez requested changes

2022-10-20 23:40 UTC, marianunez commented on components/onboarding_tasks/onboarding_tasks_manager.tsx
> +            defaultMessage='👋 Enhance your Mattermost experience. Invite your team to check out our developer platform'
@pvev heads up that we only want to change the first top three items, everything from this one down should only add the emoji and no text change cc / @annelieseklein

2022-10-21 16:46 UTC, marianunez requested changes
@pvev changes LGTM but I still the text changes in the last items in the list as I mentioned here: https://github.com/mattermost/mattermost-webapp/pull/11335/files#r1001220301

2022-10-24 19:01 UTC, marianunez approved these changes
Thanks @pvev!

2022-10-24 19:09 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/254345

2022-10-24 19:42 UTC, marianunez commented
@amyblais heads up we would like to cherry pick this change to `cloud`. It's a same text change for no major risks

2022-10-24 19:42 UTC, mattermod commented
A pipeline with the same environment variables is already running. 
 Please cancel it first with /e2e-cancel, or specify different environment variables.

2022-10-24 19:51 UTC, JulienTant approved these changes
LGTM ~ bit: I wonder if we should have "plain" emojis in translation files

2022-10-24 19:51 UTC, julmondragon approved these changes
LGTM!
nit: Would be good to update the description in ticket to reflect the final emoji/wordings implemented in this PR.

2022-10-24 20:19 UTC, merged