MM-47298 migrate e2e test to typescript
mattermost/mattermost-webapp pull request #11353
Opened 2022-10-13 18:44 UTC by Yordaniss

#### Summary
Migrated e2e test from JavaScript to Typescript with type declaration.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/21310

JIRA: https://mattermost.atlassian.net/browse/MM-47298

#### Screenshots

![Bildschirmfoto 2022-10-13 um 20 42 33](https://user-images.githubusercontent.com/68282006/195680030-aabc98d1-712d-4392-8f30-e47cf7ba19b7.png)

#### Release Note

NONE

2022-10-13 18:44 UTC, mattermod commented
Hello @Yordaniss,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-13 18:44 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-14 11:10 UTC, M-ZubairAhmed commented
/release-note-none

2022-10-14 18:27 UTC, saturninoabril requested changes
Thanks @Yordaniss! Please see comments.

2022-10-14 18:27 UTC, saturninoabril commented on e2e/cypress/tests/integration/enterprise/bot_accounts/managing_bot_accounts_spec.ts
> +        });
Please update to latest master for it has [`DeepPartial` applied to apiUpdateConfig](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/tests/support/api/system.d.ts#L100). Then revert the workaround wrapping with `cy.apiGetConfig()`.

2022-10-14 18:27 UTC, saturninoabril commented on e2e/cypress/tests/support/api/bots.ts
> +function apiCreateBot({prefix, bot = createBotPatch(prefix)}): Cypress.Chainable<{bot: Bot & {fullDisplayName: string}}> {
We're no longer using types from `mattermost-redux`. Instead, you may use directly from the Cypress namespace where types are imported in one place ([here](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/tests/support/index.d.ts#L7-L35)).
```suggestion
function apiCreateBot({prefix, bot = createBotPatch(prefix)}): Cypress.Chainable<{bot: Cypress.Bot & {fullDisplayName: string}}> 
```

2022-10-14 18:27 UTC, saturninoabril commented on e2e/cypress/tests/support/api/bots.ts
> +function apiGetBots(): Cypress.Chainable<{bots: Bot[]}> {
Same here, please use `Cypress.Bot`.

2022-10-14 20:30 UTC, Yordaniss commented
Hello @saturninoabril Thank you for feedback. 👍  I have updated the master branch and adjusted my PR.

2022-10-15 05:26 UTC, saturninoabril requested changes
Thanks @Yordaniss, sorry last couple comments and I'm all good, thanks!

2022-10-15 08:16 UTC, Yordaniss commented
@saturninoabril Sure, no problem. I already pushed the changes.

2022-10-21 14:11 UTC, furqanmlk commented
/update-branch

2022-10-21 14:11 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2022-10-21 14:11 UTC, furqanmlk commented
/e2e-test

2022-10-21 14:11 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/253384

2022-10-21 15:07 UTC, furqanmlk approved these changes
Thanks @Yordaniss 
LGTM !

2022-10-21 16:15 UTC, Yordaniss commented
@furqanmlk Glad to help 😊

2022-11-01 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-03-02 21:20 UTC, lieut-data commented
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

2023-03-02 21:20 UTC, closed without merging