avoid calling getState() twice within the action creator
mattermost/mattermost-webapp pull request #11356
Opened 2022-10-13 21:58 UTC by pradeepmurugesan

#### Summary
Avoid calling `getState()` as much as possible.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21334

2022-10-13 21:58 UTC, mattermod commented
Hello @pradeepmurugesan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-13 21:58 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-13 22:00 UTC, pradeepmurugesan commented
/release-note-none

2022-10-14 11:05 UTC, M-ZubairAhmed commented on actions/post_actions.ts
> +        if (post.id === getSelectedPostId(state as GlobalState)) {
@mattermost/web-platform this is the type casting we keep getting in many places, as the shared redux store globalstate is different from the webapp specific global state. How can we improve this.

2022-10-14 11:06 UTC, M-ZubairAhmed approved these changes
💯 It looks good to me. Thank you 🎉

2022-10-17 12:07 UTC, koox00 requested changes

2022-10-17 12:07 UTC, koox00 commented on actions/post_actions.ts
> +        if (post.id === getSelectedPostCardId(state as GlobalState)) {
We need to get the changed state after dispatching `SELECT_POST` so calling `getState()` again is needed in this case.

2022-10-17 12:22 UTC, koox00 commented on actions/post_actions.ts
> +        if (post.id === getSelectedPostCardId(state as GlobalState)) {
hmm, my mistake, I didn't read the full block, it seems that the previous action won't affect the next one.

Still, I don't really get what we are trying to achieve here..

2022-10-18 15:28 UTC, AshishDhama commented
@nevyangelova Could you please confirm if this is what we wanted to change?

2022-10-18 19:49 UTC, nevyangelova commented
Sorry for the long wait on this, I updated the ticket and have been talking to @pradeepmurugesan in DM as well. We would ideally be calling getState as long as it's coming from a thunk inside the component. We don't want to import it from stores/redux_store

```Proposed change in post_actions.jsx:

// get the state from getState
  ......
  dispatch({
            type: SearchTypes.RECEIVED*SEARCH*POSTS,
            data: {posts, order: newResults},
        });
} 
...
dispatch(addPostToSearchResults(postId));
```

2022-10-19 06:19 UTC, AshishDhama commented
@pradeepmurugesan Thanks for the effort.
closing the pr as changes aren’t required.

2022-10-19 06:19 UTC, closed without merging