avoid multiple getState calls
mattermost/mattermost-webapp pull request #11357
Opened 2022-10-13 22:28 UTC by pradeepmurugesan

#### Summary
avoid multiple getState calls in `actions/views/create_comment.tsx`

#### Ticket Link
Fixes - https://github.com/mattermost/mattermost-server/issues/21348

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note
NONE
```

2022-10-13 22:28 UTC, mattermod commented
Hello @pradeepmurugesan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-13 22:28 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-14 07:12 UTC, m1lt0n approved these changes
Looks good!

2022-10-17 04:19 UTC, M-ZubairAhmed reviewed
I do not see what has been changed here. This file doesnt seem to have call to `stores/redux_store` 🤔

2022-10-17 12:13 UTC, koox00 requested changes
Blocking merging the PR until we an answer the question about `getMessageInHistory`

2022-10-17 12:13 UTC, koox00 commented on actions/views/create_comment.tsx
> +        const nextMessageInHistory = getMessageInHistory(state);
I'm a bit skeptical on this one, are we sure that we don't want to pass in `getMessageInHistory` the updated `state`, do the above actions change what's returned?

2022-10-18 19:50 UTC, nevyangelova commented
Sorry for the long wait on this, I updated the ticket and have been talking to @pradeepmurugesan in DM as well. We would ideally be calling getState as long as it's coming from a thunk inside the component. We don't want to import it from stores/redux_store

2022-10-19 06:18 UTC, closed without merging