Migrate "components/suggestion/menu_action_provider.jsx" to Typescript
mattermost/mattermost-webapp pull request #11399
Opened 2022-10-19 15:40 UTC by babinderrathi

#### Summary
Migration of components/suggestion/menu_action_provider.jsx to Typescript

#### Ticket Link

Fixes: https://mattermost.atlassian.net/browse/MM-47070
Fixes: https://github.com/mattermost/mattermost-server/issues/21129

#### Related Pull Requests
NONE

#### Screenshots
NONE

#### Release Note
NONE

2022-10-19 15:40 UTC, mattermod commented
Hello @babinderrathi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-19 15:40 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-20 19:10 UTC, sinansonmez approved these changes
Good work, thanks for the support. LGTM 🎉

2022-10-21 06:58 UTC, M-ZubairAhmed requested changes
Just one small nit

2022-10-21 06:58 UTC, M-ZubairAhmed commented on components/suggestion/menu_action_provider.tsx
> +    options: Array<Record<string, any>>;
```suggestion
    private options: Array<Record<string, any>>;
```

2022-10-26 04:56 UTC, mattermod commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2022-10-26 05:16 UTC, M-ZubairAhmed approved these changes
💯 It looks good to me. Thank you 🎉

2022-10-26 05:17 UTC, merged