Add popover for user groups
mattermost/mattermost-webapp pull request #11437
Opened 2022-10-25 15:15 UTC by cyrilzhang-mm

#### Summary

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note

```

2022-10-26 20:44 UTC, cyrilzhang-mm commented
/update-branch

2022-10-28 14:04 UTC, BenCookie95 requested changes
This is amazing, can't wait to use it once it's merged. 2 very minor style comments

2022-10-28 14:04 UTC, BenCookie95 commented on components/user_group_popover/user_group_popover.tsx
> +    height: 24px;
I think the hover effect is a little small and needs to be 28px, that would match it with the figma

2022-10-28 14:04 UTC, BenCookie95 commented on components/user_group_popover/user_group_popover.tsx
> +                            inputPrefix={<i className={'icon icon-magnify'}/>}
The padding-left on the prefix should be 11px

2022-10-28 20:47 UTC, matthewbirtch requested changes
Nice work @cyrilzhang-mm! This is great. A few minor things from me, but it's really close:

1. The group display name in the popover should be using `Metropolis` as the font
2. For the • character that divides the mention name and members count, can we reduce the space on either side of the • to 6 instead of 8?
3. Can you make the size of the pencil icon button 28x28 instead of 24x24? The icon itself is correct, but the button container should be 28x28. You may need to adjust the alignment of the icon within button as well as the position within the header after you make that change. Changing this may also affect the space between group title and mention name below so that may need some adjustment too.
4. Can you make the border that divides the header and the user list 8% opacity instead of 16%?
5. For the search input, it looks like you'll need to use the smaller version of the search input. The design has an input with 32px height, but this looks to be 40px in height. In addition, the font-size and padding within the search input seem not quite right. Also, you can add a margin of `margin: 0 -6px` to the input container so that the field spans a bit wider as designed

<img width="542" alt="image" src="https://user-images.githubusercontent.com/2040554/198729702-de2d7d43-d5db-4971-9784-992f58ee6842.png">

2022-10-31 16:10 UTC, cyrilzhang-mm commented
Updated to address design feedback. Screenshot:
<img width="280" alt="Screen Shot 2022-10-31 at 11 40 34 AM" src="https://user-images.githubusercontent.com/112951043/199055362-b787dfaf-0179-488c-902e-50464a0861ca.png">

2022-11-01 13:54 UTC, matthewbirtch approved these changes
UI updates look good @cyrilzhang-mm, thanks for resolving those!

2022-11-02 15:13 UTC, BenCookie95 approved these changes

2022-11-07 20:00 UTC, mkraft approved these changes

2022-11-07 20:08 UTC, cyrilzhang-mm commented on reducers/views/search.ts
> +    case UserTypes.LOGOUT_SUCCESS:
I think I just copied it from the `modalSearch` above, but I think you're right, it's not necessary.

2022-11-07 20:11 UTC, cyrilzhang-mm commented on components/user_group_popover/group_member_list/group_member_list.tsx
> +        const res = await actions.getUsersInGroup(group.id, nextPage, USERS_PER_PAGE);
Yes, that's true. Alternatively if we have no design for the failure case I can make it stay as the loading indicator?

2022-11-08 18:56 UTC, cyrilzhang-mm commented on components/user_group_popover/group_member_list/group_member_list.tsx
> +        const res = await actions.getUsersInGroup(group.id, nextPage, USERS_PER_PAGE);
@matthewbirtch and I have discussed this and decided on a design, which has been added to Figma.

2022-11-08 18:57 UTC, cyrilzhang-mm commented
Marking PR as draft while I work on the design updates.

2022-11-09 15:22 UTC, matthewbirtch commented on components/user_group_popover/group_member_list/group_member_list.tsx
> +        const res = await actions.getUsersInGroup(group.id, nextPage, USERS_PER_PAGE);
@mkraft FYI I've been discussing this with @cyrilzhang-mm and these should be addressed in the updates

2022-11-09 20:47 UTC, cyrilzhang-mm commented
Updated with the new designs. Sorry about the number of commits, I had some merge issues. 

<img width="280" alt="Screen Shot 2022-11-09 at 2 35 38 PM" src="https://user-images.githubusercontent.com/112951043/200938297-4a883815-f166-4c2a-9b04-46e9be25ac9a.png">

<img width="280" alt="Screen Shot 2022-11-09 at 2 35 54 PM" src="https://user-images.githubusercontent.com/112951043/200938295-adebdb30-fbef-4fe8-bdae-5ba2d58ae576.png">

<img width="280" alt="Screen Shot 2022-11-09 at 2 36 53 PM" src="https://user-images.githubusercontent.com/112951043/200938289-71f182e1-1fa8-459f-aed0-90a22470460f.png">

<img width="280" alt="Screen Shot 2022-11-09 at 2 36 34 PM" src="https://user-images.githubusercontent.com/112951043/200938292-9556c434-b0fe-496a-a5ea-d4e0eb19f674.png">

2022-11-09 21:40 UTC, matthewbirtch requested changes
Nice work @cyrilzhang-mm. It's looking great with the changes you made.

One small thing:
1. Can we add the clear `x` icon within the search field on the right side so that users can clear the search field with one click (like they can in global search)

![image](https://user-images.githubusercontent.com/2040554/200947544-807761ce-a2b4-44d7-b0fa-f604430550ea.png)

2022-11-09 21:42 UTC, matthewbirtch commented on components/user_group_popover/user_group_popover.tsx
> +    align-items: center;
Can we bump the close button 4 pixels to the right? One way to do that:
```
position: relative;
right: -4px;
```

2022-11-10 14:53 UTC, cyrilzhang-mm commented
@matthewbirtch I updated the close button and search bar. I ended up using a different input component for the search bar, so I had to re-style it again. I tried to match it to the previous one as well as the text input Figma document as much as possible but please let me know if I missed anything!

2022-11-10 15:02 UTC, matthewbirtch requested changes
Just a few minor tweaks and I think we're good!

2022-11-10 15:02 UTC, matthewbirtch commented on components/user_group_popover/user_group_popover.tsx
> +        width: 14px;
adjust width to 18px

2022-11-10 15:02 UTC, matthewbirtch commented on components/user_group_popover/user_group_popover.tsx
> +        margin: 0 11px;
change margin to 
```
margin: 0 6px;
```

2022-11-10 15:29 UTC, matthewbirtch requested changes
Sorry, just tested a dark theme and it looks like there is an issue in the search input on dark themes: 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/2040554/201135912-24762ff4-9d65-48dc-8fa6-51af33e4cd59.png">

I think you just may need to put the `center-channel-bg` color as a background color on the input

2022-11-10 16:03 UTC, cyrilzhang-mm commented
Thanks for catching that @matthewbirtch!

2022-11-10 16:22 UTC, matthewbirtch approved these changes

2022-11-11 15:41 UTC, mkraft approved these changes

2022-11-11 19:04 UTC, BenCookie95 approved these changes
LGTM!

2022-11-11 19:04 UTC, mattermod commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2022-11-11 20:43 UTC, furqanmlk commented
Hi @BenCookie95  can you please conflict

2022-11-11 21:00 UTC, cyrilzhang-mm commented
@furqanmlk Fixed the conflicts, sorry about that!

2022-11-16 21:11 UTC, furqanmlk reviewed
I see the following issues

1. Name is not sorted, when first name and last name is selected in profile settings.
<img width="470" alt="image" src="https://user-images.githubusercontent.com/6909890/202295006-0f1fad7a-826a-4358-966e-419139190dee.png">

2. Popover is hiding profile picture and merging into LHS 
**Figma**
<img width="676" alt="image" src="https://user-images.githubusercontent.com/6909890/202278463-5c6f875b-1263-4553-911e-65ce1352b373.png">
**PR**
<img width="965" alt="image" src="https://user-images.githubusercontent.com/6909890/202279091-2ffcc2c0-c8ab-4b1d-9acb-6d223bd17258.png">

2022-11-21 13:58 UTC, cyrilzhang-mm commented
@furqanmlk Pushed a PR that will sort users by display name. It should fix the first issue.

I believe the second one isn't an issue. It behaves the same way as the existing profile popovers.

2022-11-21 18:37 UTC, furqanmlk reviewed
Hi @cyrilzhang-mm , I noticed few ui issues

1.In  Search loading state, spinner icon is different
 **PR**

<img width="821" alt="image" src="https://user-images.githubusercontent.com/6909890/203127654-6f629d5e-2da4-4594-af13-b6b413982d43.png">

**Figma**
<img width="707" alt="image" src="https://user-images.githubusercontent.com/6909890/203127857-a8fc209a-cf57-4370-9573-35781027d2a1.png">

2. In no search result, search icon is different
**PR**
<img width="729" alt="image" src="https://user-images.githubusercontent.com/6909890/203128680-fcf0a755-5d5e-4d81-93c1-893d5fab4904.png">

**Figma**
<img width="724" alt="image" src="https://user-images.githubusercontent.com/6909890/203128756-5630a5d6-a44b-40e2-ba03-910981fb3049.png">

3. Can u look at  the gif to confirm user group popover ui
the first group id popover is hiding avater
**PR**

https://user-images.githubusercontent.com/6909890/203131734-21d8ed77-90c7-4060-96df-86ee6512f260.mp4

2022-11-21 18:48 UTC, cyrilzhang-mm commented
Hi @furqanmlk the gif looks good to me, the popovers are centered with the mention link. It's a limitation of the popover library we use and it matches the behaviour of the profile popover. 

The icons are okay too. They are the same icons as what's already used in the app which @matthewbirtch approved. Thanks :)

2022-11-21 19:40 UTC, merged