Release7.5
mattermost/mattermost-webapp pull request #11477
Opened 2022-10-29 18:04 UTC by ctlaltdieliet

#### Summary
Cherry-picking translations from master
#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/11458

#### Release Note
```release-note
NONE
```

2022-10-29 18:04 UTC, mattermod commented
Hello @ctlaltdieliet,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-29 18:04 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-31 09:58 UTC, m1lt0n requested changes
Hey @ctlaltdieliet 

The comment below is not related specifically to the cherry picked changes, so I'll go ahead and approve. Having said that, 
running some sanity checks with a script, I found a few small issues (mostly with singular/plural) in messages (about 14 messages, so a small number). Specifically:

Discrepancy in key postlist.toast.newMessages in file it.json
Discrepancy in key admin.billing.subscription.freeTrial.lessThan3Days.description in file ro.json
Discrepancy in key admin.data_retention.channel_team_counts in file ro.json
Discrepancy in key admin.data_retention.retention_days in file ro.json
Discrepancy in key admin.data_retention.retention_years in file ro.json
Discrepancy in key admin.license.trialCard.description in file ro.json
Discrepancy in key globalThreads.threadPane.unselectedTitle in file ro.json
Discrepancy in key reaction.usersAndOthersReacted in file ro.json
Discrepancy in key postlist.toast.newMessages in file ko.json
Discrepancy in key admin.bleve.percentComplete in file fa.json
Discrepancy in key admin.elasticsearch.percentComplete in file fa.json
Discrepancy in key postlist.toast.newMessages in file fa.json
Discrepancy in key team_member_modal.members in file fa.json
Discrepancy in key admin.team_channel_settings.removeConfirmModal.messageChannel in file es.json

My script checks for unmatched count of opened/closed braces ({ }). In all cases it's either a missing brace in the end or an extra one.

2022-10-31 10:00 UTC, m1lt0n approved these changes

2022-10-31 17:00 UTC, ctlaltdieliet commented
Thanks @m1lt0n for this check and for sharing your script.
For Fa where it was unclear where to add the extra }, I removed the translation for that string.
The others are fixed. I'll use your script to check it on master as well so that we don't run in this issue again.

2022-11-01 12:29 UTC, merged