[MM-48027] improve use case window style
mattermost/mattermost-webapp pull request #11523
Opened 2022-11-03 17:31 UTC by mhd-sln

#### Summary
For a high level understanding of the feature. Please view the parent PR. This PR improves the styling of use-case window based on https://www.figma.com/proto/xS2v61Rlq2DiLG8QF3fIPU/MMO-MVP?node-id=200%3A159143&scaling=min-zoom&page-id=193%3A104002&starting-point-node-id=243%3A163187

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48027

#### Video
https://www.loom.com/share/f762eadbcc7641bea820be8c631d42db

#### Release Note
```release-note
NONE
```

2022-11-03 17:57 UTC, JulienTant reviewed
This is magic to me! 🤯 

Only issue I found was the padding around the text seems off

![image](https://user-images.githubusercontent.com/785518/199798781-aec6940c-4ebe-4aa1-bfad-253522a34fc4.png)

2022-11-03 21:13 UTC, julmondragon reviewed
Looks good!

2022-11-03 21:13 UTC, julmondragon commented on components/worktemplates/components/menu/use_case.tsx
>      .name {
Please make sure to match styles for this section from figma design in all the states: https://www.figma.com/file/xS2v61Rlq2DiLG8QF3fIPU/MMO-MVP?node-id=592%3A194495

2022-11-08 14:24 UTC, julmondragon requested changes

2022-11-08 14:24 UTC, julmondragon commented on components/worktemplates/components/menu/use_case.tsx
>              color: rgba(var(--center-channel-color), 0.72);
```suggestion
            color: rgba(var(--center-channel-text-rgb), 0.72);
```

2022-11-08 22:18 UTC, JulienTant approved these changes

2022-11-09 22:01 UTC, julmondragon approved these changes
Thanks @mhd-sln !

2022-11-10 08:16 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/260548

2022-11-11 19:20 UTC, stevemudie approved these changes
This looks and works _really_ good. Nice work @mhd-sln!

2022-11-14 17:00 UTC, mhd-sln commented
Discussed this with @JulienTant and we thought that it might be a good idea to merge this and https://github.com/mattermost/mattermost-webapp/pull/11557 into https://github.com/mattermost/mattermost-webapp/pull/11475.
We would be revisiting the code from UX review perspective later as well once the Work Template Modal would be feature ready in the future. @annelieseklein

2022-11-14 17:00 UTC, merged