MM-47079: Migrate "components/suggestion/search_user_provider.jsx" to Typescript
mattermost/mattermost-webapp pull request #11528
Opened 2022-11-04 07:27 UTC by babinderrathi

#### Summary
Migrate of search_user_provider.jsx" to Typescript

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/21090
 Fixes https://mattermost.atlassian.net/browse/MM-47079

#### Related Pull Requests
None

#### Screenshots
none

#### Release Note

```release-note
NONE
```

2022-11-04 07:27 UTC, mattermod commented
Hello @babinderrathi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-11-04 07:27 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-11-04 07:29 UTC, babinderrathi commented on components/suggestion/search_user_provider.tsx
> +    autocompleteUsersInTeam: (username: string) => any;
Due to type mismatching, I am unable to find any solution which can replace 'any' here .

2022-11-04 21:03 UTC, sinansonmez requested changes
Thanks for the effort @babinderrathi I just have one suggestion to eliminate the usage of `any`

2022-11-04 21:03 UTC, sinansonmez commented on components/suggestion/search_user_provider.tsx
> +    constructor(userSearchFunc: (username: string) => DispatchFunc) {
If you track back `userSearchFunc` func, you will see that it is returning `UserAutocomplete` as seen below.

https://github.com/mattermost/mattermost-webapp/blob/7d527c9c852f9e931cf253c16f663371340738d5/packages/client/src/client4.ts#L913-L916

Therefore, this change should do the trick. 
```suggestion
    autocompleteUsersInTeam: (username: string) => Promise<UserAutocomplete>;
    constructor(userSearchFunc: (username: string) => Promise<UserAutocomplete>) {
```

You also need to change the return type of `autocompleteUsersInTeam` in line below 
https://github.com/mattermost/mattermost-webapp/blob/7d527c9c852f9e931cf253c16f663371340738d5/components/search/types.ts#L54

2022-11-07 20:37 UTC, sinansonmez approved these changes
LGTM, thanks for the effort @babinderrathi

2022-11-08 07:13 UTC, M-ZubairAhmed requested changes

2022-11-08 07:13 UTC, M-ZubairAhmed commented on components/search/types.ts
> +import {UserAutocomplete} from '@mattermost/types/autocomplete';
nit
```suggestion
import {Channel} from '@mattermost/types/channels';
import {ServerError} from '@mattermost/types/errors';
import {UserAutocomplete} from '@mattermost/types/autocomplete';

import {SearchType} from 'types/store/rhs';

```

2022-11-08 07:13 UTC, M-ZubairAhmed commented on components/suggestion/search_user_provider.tsx
> +    autocompleteUsersInTeam: (username: string) => Promise<UserAutocomplete>;
nit : 
```suggestion
    private autocompleteUsersInTeam: (username: string) => Promise<UserAutocomplete>;
```

2022-11-08 07:14 UTC, M-ZubairAhmed commented on components/suggestion/search_user_provider.tsx
> +    node?: HTMLDivElement | null;
nit :
```suggestion
    private node?: HTMLDivElement | null;
```

2022-11-09 07:15 UTC, M-ZubairAhmed approved these changes
💯 It looks good to me. Thank you 🎉

2022-11-09 07:17 UTC, mattermod commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2022-11-09 07:23 UTC, merged