MM-48573 : "Back to Team" link from system console is crashing after "needs_team" is migrated to "team_controller"
mattermost/mattermost-webapp pull request #11635
Opened 2022-11-23 17:21 UTC by M-ZubairAhmed

#### Summary
In `needs_team` [this action](https://github.com/mattermost/mattermost-webapp/pull/11635/files#diff-38d42996b7b1a0fa816b756d86b0b67729cb6e1d6eb3cc8c850828683ee22ccaL278) had to be moved to componentDidMount from constructor. This caused a slight delay in receiving current team details. This delay would mean `currentTeam` or `currentChannel` would be briefly `undefined` till initial few renders. The problem occurs when the RHS with any content is left open and user moves to system console and comes back. The team/channel being undefined in first render would crash the app. This pr solves that problem by adding a loading indicator in RHS which will check if either team or channnel are undefined.
In addition the loading indicator of Center channel is centered. Some unused styles are removed.

Separated by commits for easy review
- 🚀 [Code fix ](https://github.com/mattermost/mattermost-webapp/pull/11635/files/a5d978dd537de369f3c958e333d83a7cab1cbf66)
- 1️⃣ [Unit tests](https://github.com/mattermost/mattermost-webapp/pull/11635/commits/49a4fe5ccdcdcbc00164983590c6c1f1b0dbf67a)
- 🔚  [E2e test](https://github.com/mattermost/mattermost-webapp/pull/11635/commits/d0661cffa6060ec916ec5fbc89e6e2c2e44accd4)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48573

#### Related Pull Requests
n/a

#### Screenshots
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/17708702/203620736-c9888d88-074d-4c5e-ac92-4cc450b17222.png">

#### Release Note

```release-note
Loading indicator in RHS.
```

2022-11-23 17:22 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-11-23 17:34 UTC, M-ZubairAhmed commented on components/sidebar_right/sidebar_right.tsx
> -            this.props.teamId !== prevProps.teamId ||
This functionality is already present in https://github.com/mattermost/mattermost-webapp/blob/6caf3dcbafc309f0fc24bdb5b708d4452caf8a0a/components/needs_team/needs_team.tsx#L226-L228 . And the identification of team and closing RHS is caught way top in parent component.

2022-11-23 17:35 UTC, M-ZubairAhmed commented on sass/components/_post.scss
> -    .post-list__loading {
unused styles

2022-11-23 17:37 UTC, M-ZubairAhmed commented on components/needs_team/needs_team.tsx
> +        if (this.state.team) {
It was added here https://github.com/mattermost/mattermost-webapp/pull/11135/files#r973003979 but reverted to solve the issue temporarily.

2022-11-23 21:30 UTC, matthewbirtch commented
@M-ZubairAhmed this still seems to be crashing for me on the test server when I open the `Recent Mentions` or `Saved Messages` RHS, go to System console, and come back. This doesn't happen with the `Channel info` RHS though, so that seems to be fixed

2022-11-24 13:22 UTC, M-ZubairAhmed commented
@matthewbirtch sorry missed that. Adding the e2e to clamp down on expected behavior

2022-11-24 13:49 UTC, M-ZubairAhmed commented on components/sidebar_right/sidebar_right.tsx
> -        window.addEventListener('resize', this.determineTransition);
these listener is not needed any more since we are not controlling this components open and close with component state, but through prop.

2022-11-24 15:47 UTC, M-ZubairAhmed commented
/update-branch

2022-11-24 16:14 UTC, M-ZubairAhmed commented
/update-branch

2022-11-28 05:35 UTC, M-ZubairAhmed commented
/update-branch

2022-11-28 15:32 UTC, JulienTant approved these changes
Nice improvement @M-ZubairAhmed

2022-11-28 19:39 UTC, matthewbirtch approved these changes

2022-11-29 05:35 UTC, M-ZubairAhmed commented
/e2e-test

2022-11-29 05:35 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/268248

2022-11-29 06:27 UTC, M-ZubairAhmed commented
/update-branch

2022-11-29 07:03 UTC, calebroseland requested changes
Overall a great set of changes!

On the prior crashing: I'm a bit concerned that the only thing now preventing a potential hard-crash is a loading screen in `sidebar_right`. We probably need to refine the types around some selectors to give us build time errors to show us where we should be more resilient by using conditional access methods.

2022-11-29 10:21 UTC, M-ZubairAhmed commented on components/sidebar_right/sidebar_right.tsx
> +        const isLoading = !channel || !team;
This is a very interesting case, which i was not aware of thank you for pointing it out @calebroseland . I feel you are absolutely right about having correct return types for the selectors, we discussed this here https://community.mattermost.com/core/pl/43ptntnrqtrq9knrmn6bddy7mr and we are going to take this up as KR for upcoming quarter.

I will follow your suggestion to fix the problem temporarily.

2022-11-29 10:21 UTC, M-ZubairAhmed commented on components/loading_screen.tsx
> +    inMiddle?: boolean;
✅  Updated as per request/discussion

2022-11-29 11:12 UTC, M-ZubairAhmed commented
/update-branch

2022-11-29 11:32 UTC, M-ZubairAhmed commented
/e2e-test

2022-11-29 11:32 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/268370

2022-11-29 13:00 UTC, M-ZubairAhmed commented
/e2e-test

2022-11-29 13:00 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/268396

2022-11-30 08:24 UTC, M-ZubairAhmed commented
Verified e2e report https://automation-dashboard.vercel.app/cycles/27909cc1-f141-4250-82a5-0cf326e9e96a doesnt contain failures due to this pr

2022-11-30 08:25 UTC, merged

2022-12-01 19:25 UTC, amyblais commented
/cherry-pick release-7.6

2022-12-01 19:25 UTC, mattermod commented
Cherry pick is scheduled.