[MM-44347] Use new display name parameter to fetch users in group
mattermost/mattermost-webapp pull request #11690
Opened 2022-11-30 22:41 UTC by cyrilzhang-mm

#### Summary

Use new display name parameter to fetch users in group, so that they are loaded in order of display name.

#### Ticket Link

Intended to be used for this feature: [Jira ticket](https://mattermost.atlassian.net/browse/MM-44347)

#### Related Pull Requests

Requires https://github.com/mattermost/mattermost-server/pull/21775

#### Release Note

```release-note
NONE
```

2022-12-02 09:27 UTC, plant99 requested changes
If possible, can we please remove the order in https://github.com/mattermost/mattermost-webapp/blob/e4a68f66a80a1b9246cf1cca1c75eeaf9cb06f02/components/user_group_popover/group_member_list/group_member_list.test.tsx#L48-L54? Our test data is already ordered, w.r.t username, displayname, first/last names, that's why we don't see snapshot mismatch with this PR.

2022-12-02 20:47 UTC, cyrilzhang-mm commented
@plant99 I think the code you suggested wouldn't work because the `members` array is just passed to `GroupMemberList` as-is, rather than putting it in the mock state. I'm not seeing a way to test the selector here, because there is a type error if I omit the `members` array when passing props to `GroupMemberList`. Do you have any ideas?

2022-12-04 15:48 UTC, plant99 commented
> @plant99 I think the code you suggested wouldn't work because the `members` array is just passed to `GroupMemberList` as-is, rather than putting it in the mock state. I'm not seeing a way to test the selector here, because there is a type error if I omit the `members` array when passing props to `GroupMemberList`. Do you have any ideas?

Ah thanks for clearing it up @cyrilzhang-mm.

Things look good to me now - since we're not mocking API calls anywhere, no other change requests!

2022-12-04 15:48 UTC, plant99 approved these changes

2022-12-07 14:54 UTC, BenCookie95 approved these changes

2022-12-12 13:56 UTC, mattermod commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/274605) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/274605)

2022-12-15 15:40 UTC, furqanmlk approved these changes

2022-12-19 16:31 UTC, merged