Encourage downloading original instead of preview
mattermost/mattermost-webapp pull request #11773
Opened 2022-12-09 01:02 UTC by Roy-Orbison

#### Summary
Prevents accidental downloads of preview files rather than originals from the image preview modal.

Image previews are useful for bandwidth saving but the normal intent of sharing a file is for the recipient to get the original. It is natural for many users to save images via their context menu. The problem is that the context options are those of the low-res (and sometimes wrong type of) image.

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/21230 fixed the obvious cosmetic issue related to transparent images, but leaves opaque JPEGs, etc. unaffected. [This comment](https://mattermost.atlassian.net/browse/MM-36295?focusedCommentId=114695) and the line "Also, it displayed incorrectly after downloading it locally." from [the original issue for that PR](https://github.com/mattermost/mattermost-server/issues/19947) provides evidence that people are not expecting to get a modified file from that interface.

#### Screenshots
The appearance of the interface is unchanged, it is only the behaviour of clicking that differs.

#### Release Note
```release-note
Image in preview modal now links to original.
```

2022-12-09 01:02 UTC, mattermod commented
Hello @Roy-Orbison,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-12-09 16:14 UTC, nevyangelova requested changes
Thanks @Roy-Orbison you will need to manually update the failing test, otherwise LG!

2022-12-12 02:37 UTC, Roy-Orbison commented
@nevyangelova Looks like this patch as it is would reintroduce [this issue](https://mattermost.atlassian.net/browse/MM-19954). I could add the required attributes (and change the tests), but it looks like they were all deliberately removed in 5b9a289d38db51b5942c6e800021c13889329b04. I will just simplify this to only block saving the preview, so users get the original from the link and download buttons.

2022-12-12 09:02 UTC, nevyangelova approved these changes
Thanks!

2022-12-12 09:02 UTC, nevyangelova commented
/e2e-test

2022-12-12 09:02 UTC, mattermod commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/274501) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/274501)

2022-12-12 15:19 UTC, nevyangelova commented
the fix for the benchmark tests is already on master

2022-12-13 11:05 UTC, michelengelen approved these changes
just a code-style comment ... otherwise LGTM

2022-12-13 11:05 UTC, michelengelen commented on components/file_preview_modal/image_preview.jsx
> +            />
```suggestion
            <span className='image_preview__save_helper'/>
```

2022-12-13 20:30 UTC, matthewbirtch commented
@Roy-Orbison my concern with this solution is that we can no longer right-click on the image in the preview mode to save the image and creates an unexpected behavior for users who are used to browser's standard context menus for images. Is that desirable? I'm not quite sure I understand why we would want to do this.

The context menu for images in this PR
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2040554/207436777-56cdca11-2409-4e1b-94a7-69801fe97925.png">

The context menu for images in the current product
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2040554/207436810-d2d361ea-54ee-4c83-96ec-c2970f5f1b71.png">

2022-12-14 01:13 UTC, Roy-Orbison commented
@matthewbirtch Yes, that's the entire purpose. This is because all the images shown are not the originals, and I firmly believe it is _more unexpected_ to save the presented image, and get something other than the original. I have resolved several issues with people getting the "wrong" image for something simply because they were sent via Mattermost (for convenience, despite there being more appropriate channels), and then saved by right-clicking the preview.

I am okay with changing the link from `#` to the original, and the tests, which would mitigate the lack of context menu options, but then I should first know why they were removed to begin with (in 5b9a289d38db51b5942c6e800021c13889329b04), rather than the buttons being _in addition to_ the existing link.

2022-12-14 01:20 UTC, Roy-Orbison commented
The fact that is shows any "save link", etc., options at all is a consequence of retaining the `<a>` even though it ceased to be semantic when its link attributes were removed.

2022-12-21 01:39 UTC, Roy-Orbison commented
So what resolution do you want here? The save/copy link context options have been broken since the removal of the link to the original (they point to the current Mattermost page rather than the file).

2022-12-23 21:05 UTC, matthewbirtch commented
> I should first know why they were removed to begin with (in [5b9a289](https://github.com/mattermost/mattermost-webapp/commit/5b9a289d38db51b5942c6e800021c13889329b04)), rather than the buttons being _in addition to_ the existing link.

I have no idea why the link would have been removed to begin with. Maybe @AshishDhama knows since he worked on that.

Either way, if we are going to go the route that this PR suggests and prevent the standard browser behavior of saving the optimized image, changing the `#` seems important.

2022-12-24 08:00 UTC, AshishDhama commented
@Roy-Orbison I have removed this as we added a download button. Second, when you right, click browser gives you the option to `Open image in a New tab` or `save as image` are the more likely button to be clicked by the user instead of `open in a new tab` (First option) which any way opens up the preview image. I think this bias of usage is Maybe because that's how I do it; feels more natural to me. (Refer to Image)
<img width="388" alt="207436810-d2d361ea-54ee-4c83-96ec-c2970f5f1b71" src="https://user-images.githubusercontent.com/16203333/209426429-65c8cd65-6f94-45a0-beeb-869eeca6c78d.png">
That being said, I think it would best to just revert the changes, instead of restricting the user.

File to be reverted.
https://github.com/mattermost/mattermost-webapp/blob/65238a2de23ed3f3b5b063fa96f5d1d7fd72fc3f/components/file_preview_modal/image_preview.jsx#L29

Original code
``` 
<a
href={fileUrl}
target='_blank'
rel='noopener noreferrer'
download={!isExternalFile}
className='image_preview'
>
```

2023-01-03 23:42 UTC, Roy-Orbison commented
> when you right, click browser gives you the option to `Open image in a New tab` or `save as image` are the more likely button to be clicked by the user instead of `open in a new tab` (First option) which any way opens up the preview image. I think this bias of usage is Maybe because that's how I do it; feels more natural to me.

Which is exactly the problem, it *is* natural to right-click the image, but that provides users the *wrong image*.

I will add back the attributes.

2023-01-20 04:37 UTC, Roy-Orbison commented
Looks like the last failure is unrelated to this PR. Any clues?

2023-01-31 01:04 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-02-01 06:23 UTC, AshishDhama commented
@asaadmahmood Could you, please take look

2023-02-01 07:28 UTC, michelengelen approved these changes

2023-02-01 08:40 UTC, asaadmahmood commented
@Roy-Orbison This is what I see, is this expected.
<img width="1173" alt="Screenshot 2023-02-01 at 1 37 39 PM" src="https://user-images.githubusercontent.com/11034289/215992254-021373f8-6a13-4353-9a9a-220d8189269d.png">

So I see no image context things. I can't open the image in a new tab, I can't copy a link to the image.
I see a copy link address option, but since I don't see any image related options, I'm not sure if this link would copy what I intend it to copy (the image).

And I understand that previously the user was copying the wrong image, but now the user can't copy anything.
If I wanted to just share something quickly, how would that happen now?

All image specific things are lost.
<img width="302" alt="Screenshot 2023-02-01 at 1 39 31 PM" src="https://user-images.githubusercontent.com/11034289/215992739-c4f5ecdc-51f5-42db-95b8-f13a1b47e107.png">

2023-02-01 09:03 UTC, asaadmahmood commented
@Roy-Orbison Wouldn't it be possible to actually overlay the original image on top of this one with 0 opacity.
Even if the image doesn't load completely, they'll be able to see all the options we need them to see, and when they use the options in the menu, they would be for the actual image.

While we can keep the original image in the back, that works to structure the layout of the image modal, and also there for the users to see visually.

2023-02-02 00:10 UTC, Roy-Orbison commented
@asaadmahmood

> This is what I see, is this expected.
> ...
> So I see no image context things. I can't open the image in a new tab, I can't copy a link to the image. I see a copy link address option, but since I don't see any image related options, I'm not sure if this link would copy what I intend it to copy (the image).

Yes, that is the point. _All_ image context options are for preview image files, i.e. not the expected attachments. Using any of them will lead the user to obtain/share the wrong file. I have witnessed high-res web assets, that are set to specific sizes, optimised with Guetzli, etc., get "lost in transit" because the receiver used those very image context options, and got an inferior quality image with smaller dimensions.

> but now the user can't copy anything. If I wanted to just share something quickly, how would that happen now?

This is incorrect. After this patch, the copy/open link options already present are again related to the original image rather than the current channel, so using those will interact with the correct file.

> Wouldn't it be possible to actually overlay the original image on top of this one with 0 opacity. Even if the image doesn't load completely, they'll be able to see all the options we need them to see, and when they use the options in the menu, they would be for the actual image.

Possible, but would defeat the entire purpose of using a preview image. Despite being invisible to the user, that would cause the browser/app to fetch **both** the preview and the original, which is worse than using the original alone.

If retaining the image context options is deemed critical UI by Mattermost, then it would be better to display only the original. I wouldn't drop the preview system in favour of that as the performance impact would be significant. Obviously you have no obligation to accept this patch, but I am still of the opinion that removing image-specific context menu options is much less problematic than providing users the wrong file, especially given there are already dedicated Mm UI buttons that perform the same functions as the removed context menu options.

2023-02-02 00:24 UTC, Roy-Orbison commented
I've converted this back to draft because the blocking overlay is not required on external images (link and preview are same), and it should also be on the inline preview in the channel.

2023-02-02 07:25 UTC, asaadmahmood commented
@Roy-Orbison 
> Possible, but would defeat the entire purpose of using a preview image. Despite being invisible to the user, that would cause the browser/app to fetch both the preview and the original, which is worse than using the original alone.

The purpose of the preview was to have an image for the user to see as soon as they can.
If we have a 10mb image, that's taking too long to load, the user would not have to wait for it to see the preview, and would have his preview image (smaller size) infront of him.

No one is suggesting that we remove it.
Yes, it would make the app fetch both the images, but I don't think it's the lesser of two evils, I'd prefer not to sacrifice on UX and user expectations.

And when he right clicks the image, he'll be interacting with the larger image, which probably is still loading, or maybe has loaded by that time. Even if it hasn't loaded, he'll still get the correct image probably since it would be overlaying.

> This is incorrect. After this patch, the copy/open link options already present are again related to the original image rather than the current channel, so using those will interact with the correct file.

Maybe I didn't see it, what I saw was this menu.
<img width="601" alt="Screenshot 2023-02-02 at 12 19 28 PM" src="https://user-images.githubusercontent.com/11034289/216257696-69521128-3edd-4949-b1c6-aefcc8e2f071.png">

And this appears on a link I think, so the menu itself doesn't tell me that the link is for an image, as far as I'm concerned it could be for anything.

This is what Discord, Slack, Asana, Github etc show, and I'm expecting something similar.

**Discord**
![Uploading Screenshot 2023-02-02 at 12.21.06 PM.png…]()

**Slack**
<img width="837" alt="Screenshot 2023-02-02 at 12 21 32 PM" src="https://user-images.githubusercontent.com/11034289/216258620-40c34086-9ee7-4f0d-b107-9cdbf0f7e870.png">

**Asana**
<img width="1188" alt="Screenshot 2023-02-02 at 12 24 54 PM" src="https://user-images.githubusercontent.com/11034289/216258709-d2ab0251-cc74-41cd-a7d6-61d6d5eefb7d.png">

**Github**
<img width="1089" alt="Screenshot 2023-02-02 at 12 25 15 PM" src="https://user-images.githubusercontent.com/11034289/216258767-f6967e6e-1797-464d-9976-16818957aa1c.png">


All of them are showing image specific options and I'd prefer to have the same.

2023-02-03 01:01 UTC, Roy-Orbison commented
@asaadmahmood 

> The purpose of the preview was to have an image for the user to see as soon as they can.

Which will be hindered if you have markup that loads both preview and full at the same time, again defeating the purpose of previews.

> > This is incorrect. After this patch, the copy/open link options already present are again related to the original image rather than the current channel, so using those will interact with the correct file.
> 
> Maybe I didn't see it, what I saw was this menu.

You wrote "but now the user can't copy anything", which is what i said was incorrect.

> This is what Discord, Slack, Asana, Github etc show, and I'm expecting something similar.

I just tested a post of a large image in an old Slack account. The resized thumbnail present in the channel showed no image context menu options, they block them with an `::after` pseudo-element, which is actually a better solution than I wrote. All the link options were directly to the full sized image:

![thread context](https://user-images.githubusercontent.com/28617290/216484153-e5577895-27da-4ef8-aeee-8a6413dcc926.png)

In Slack, Expanding that preview shows the original image, unlike Mattermost which still shows the preview version in the expanded view. I hadn't tested this in Slack before now, and their choice validates what I was trying to accomplish here. I think they have it right and Mattermost doesn't. Thus, I no longer think this specific patch is the correct solution.

The current situation is bad, and loading both preview and full is objectively worse. I'm not interested in amending this patch to do things I disagree with, so I suggest you follow Slack's lead in this case.

2023-02-03 01:01 UTC, closed without merging

2023-02-03 06:53 UTC, asaadmahmood commented
Sounds good @Roy-Orbison I'll bring this up with the team and see if we want to implement a full original image solution.
And will also keep an eye out for users reporting this particular issue to understand the severity of it.

2023-02-03 07:32 UTC, asaadmahmood commented
Also @Roy-Orbison on your comment:
> Which will be hindered if you have markup that loads both preview and full at the same time, again defeating the purpose of previews.

My intention was not to load both the images together, rather first have the preview image loaded, and then begin loading the larger one. So the user feels no difference from how the app functions right now.

But as mentioned, will be talking about this with the team as well.