Remove user id from bindings request
mattermost/mattermost-webapp pull request #11822
Opened 2022-12-16 08:19 UTC by mickmister

#### Summary

The frontend is attaching a query parameter `user_id` to every request to fetch bindings. This value isn't used in the Apps plugin, since the user's token is used instead, to identify the user. It adds noise in browser dev tools, as this parameter is always the first one occurring in the request URL

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-49165

#### Release Note

```release-note
NONE
```

2022-12-16 10:49 UTC, hanzei requested changes

2022-12-16 10:49 UTC, hanzei commented on packages/client/src/client4.ts
>      getAppsBindings = async (userID: string, channelID: string, teamID: string) => {
Should `userID` also get removed here?

2023-02-02 15:14 UTC, hanzei approved these changes

2023-02-02 15:14 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-02-02 15:47 UTC, julmondragon requested changes
Changes looks good @mickmister !

However some tests needs to be updated: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/64872/workflows/f09204d3-0516-4e63-82a5-1a6ca2fa5dd7/jobs/440642

And there is a lint issue: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/64872/workflows/f09204d3-0516-4e63-82a5-1a6ca2fa5dd7/jobs/440641

2023-02-06 23:37 UTC, julmondragon approved these changes
Thank you @mickmister !

2023-02-13 15:32 UTC, mickmister commented
/update-branch

2023-02-13 15:33 UTC, mattermost-build commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2023-02-14 15:08 UTC, hanzei commented
/update-branch

2023-02-14 15:23 UTC, merged