fixing layout when error occurs
mattermost/mattermost-webapp pull request #11990
Opened 2023-01-13 16:51 UTC by BenCookie95

#### Summary
Fixing layout issue when banner appears on the following pages: 
/login
/access_problem
/signup_user_complete
/should_verify_email
/do_verify_email

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49587

#### Screenshots
![Screen Shot 2023-01-13 at 11 50 47 AM](https://user-images.githubusercontent.com/14115924/212374757-4ffc6302-0f9f-4d3a-9cc3-9d8748efac75.png)

#### Release Note

```release-note
NONE
```

2023-01-13 18:41 UTC, kostaspt requested changes
It looks like it's still broken for smaller screens.

https://user-images.githubusercontent.com/684680/212394893-f4fd3bbd-35fa-4a12-bb2b-4f57d5214919.mp4

2023-01-13 18:42 UTC, BenCookie95 commented
> It looks like it's still broken for smaller screens.
> 
>  Kapture.2023-01-13.at.20.40.03.mp4

Nice find!

2023-01-13 19:30 UTC, BenCookie95 commented
> It looks like it's still broken for smaller screens.
> 
>  Kapture.2023-01-13.at.20.40.03.mp4

Fixed, the announcement banner also completely broke the mobile view of channels too

2023-01-13 19:42 UTC, kostaspt approved these changes
Looks good now 👍🏼

2023-01-13 19:43 UTC, kostaspt commented
This probably fixes more issues, for example: https://mattermost.atlassian.net/browse/MM-49501

2023-01-14 04:28 UTC, calebroseland requested changes
Looks right for `header-footer-route` 👍.  Just one duplicate on the mobile grid part.

2023-01-14 04:28 UTC, calebroseland commented on sass/base/_structure.scss
> +        }
This should be fixed once #11920 is merged.

```suggestion
```

2023-01-17 15:38 UTC, calebroseland approved these changes

2023-01-17 15:39 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-02-06 16:24 UTC, BenCookie95 commented
@amyblais @furqanmlk Closing this PR as it was already fixed here https://github.com/mattermost/mattermost-webapp/pull/11867

2023-02-06 16:24 UTC, closed without merging