The HTML tag always has lang="en" even if the language in settings is set to a different language
mattermost/mattermost-webapp pull request #12159
Opened 2023-02-06 16:56 UTC by gitstart

### Summary
The HTML tag always has lang="en" even if the language in settings is set to a different language

#### Demo video
https://www.loom.com/share/19060c7452614ae984e31bc3fb757223

#### Release note
```release-note
Updates HTML lang attribute when a user updates locale
```

2023-02-06 16:56 UTC, mattermost-build commented
Hello @gitstart,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-02-06 16:56 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-02-07 13:47 UTC, M-ZubairAhmed commented on components/root/root_provider.tsx
> +    const locale = useSelector(getCurrentLocale);
better place for this could be `components/root/root.tsx` instead here

2023-02-08 11:32 UTC, gitstart commented
@hmhealey You can have a look. Thanks.

2023-02-13 21:14 UTC, hmhealey requested changes
This looks pretty good to me, but could we actually move this logic into a subcomponent into a different component to avoid adding more logic to the `Root` component? The `IntlProvider` component `components/intl_provider` already deals with some stuff around the locale, so I think it would make sense to have it there.

Could you also add a unit test to that component to ensure that the lang is updated correctly when `currentLocale` changes?

2023-02-14 09:30 UTC, collinewait commented
> This looks pretty good to me, but could we actually move this logic into a subcomponent into a different component to avoid adding more logic to the `Root` component? The `IntlProvider` component `components/intl_provider` already deals with some stuff around the locale, so I think it would make sense to have it there.
> 
> Could you also add a unit test to that component to ensure that the lang is updated correctly when `currentLocale` changes?

@hmhealey This has been addressed. Thanks.

2023-02-15 16:48 UTC, hmhealey requested changes
Thanks for making that change! That looks perfect to me.

One last thing though, could we actually remove the `lang="en"` from `root.html`? I think it's better to not set it at all until the `IntlProvider` is loaded

2023-02-15 17:51 UTC, gitstart commented
@hmhealey root.html has been updated.

2023-02-15 18:37 UTC, M-ZubairAhmed approved these changes

2023-02-16 19:57 UTC, hmhealey approved these changes
Thanks! This looks good to me

2023-02-16 21:41 UTC, stevemudie commented
/e2e-test

2023-02-16 21:41 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/303809) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/303809)

2023-02-17 15:01 UTC, stevemudie commented
/e2e-test

2023-02-17 15:01 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/304095) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/304095)

2023-02-17 21:37 UTC, stevemudie commented
@hmhealey The E2E won't run and the Spinwick won't build either so I'm not able to complete tests on this.

As a guess it has something to do with the failed check listed below?

2023-02-21 21:37 UTC, hmhealey commented
I'll try updating this to the latest version of master again. I assume that there's something here broken by the new CI process

/update-branch

2023-03-06 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-03-23 10:56 UTC, M-ZubairAhmed commented
Hey there!, Thank you for your PR.
Webapp is now part of mattermost monorepo now at https://github.com/mattermost/mattermost-server/tree/master/webapp Would you be interested in opening the PR over there?

2023-03-27 07:17 UTC, gitstart commented
@hmhealey This PR has been moved to the monorepo https://github.com/mattermost/mattermost-server/pull/22677. cc @M-ZubairAhmed

2023-03-27 07:52 UTC, closed without merging