MM-49368 - When pasting a link from github it clears the undo history
mattermost/mattermost-webapp pull request #12206
Opened 2023-02-14 15:30 UTC by gitstart

**DEMO VIDEO**
https://www.loom.com/share/5bb0587f30964a84b3a3cd44916b7c10

### Release note
```release-note
Fixes undo history bug when pasting a link from GitHub
```

2023-02-14 15:30 UTC, mattermost-build commented
Hello @gitstart,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-02-14 15:30 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-02-14 15:47 UTC, gitstart commented on components/advanced_create_post/advanced_create_post.tsx
> +        document.execCommand('insertText', false, formattedMessage);
From docs

<img width="785" alt="Screenshot 2023-02-14 at 18 12 59" src="https://user-images.githubusercontent.com/1501599/218784278-ae2718f6-eeae-4af8-abb4-157b65792bd1.png">

2023-02-16 07:46 UTC, AshishDhama approved these changes

2023-02-16 10:43 UTC, nevyangelova approved these changes
LGTM!

2023-02-16 22:01 UTC, hmhealey requested changes
Thanks for the PR! I have some feedback about how to change this, but I like the approach used here.

Also, this component is only used in the centre channel, but not when replying from the RHS. Could you also make the same changes to `AdvancedCreateComment` as well so that it has the same behaviour?

2023-02-20 17:40 UTC, gitstart commented
@hmhealey feedback has been addressed.

2023-02-21 21:49 UTC, hmhealey requested changes
Thanks for updating all those tests!

Could you also address 
> Also, this component is only used in the centre channel, but not when replying from the RHS. Could you also make the same changes to `AdvancedCreateComment` as well so that it has the same behaviour?

2023-02-24 11:22 UTC, gitstart commented
@hmhealey changes have been made to `AdvancedCreateComment`

2023-02-27 22:05 UTC, hmhealey approved these changes
Thanks for adding that to the RHS. I've gone through and double-checked that it works in the centre channel, RHS, and Threads view in Firefox, Chrome, and Safari on Mac

2023-03-10 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-03-20 17:59 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/315844) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/315844)

2023-03-23 10:54 UTC, M-ZubairAhmed commented
Hey there!, Thank you for your PR.
Webapp is now part of mattermost monorepo now at https://github.com/mattermost/mattermost-server/tree/master/webapp Would you be interested in opening the PR over there?

2023-03-23 20:15 UTC, hmhealey commented
The web app now lives in the `webapp/channels` over in https://github.com/mattermost/mattermost-server. We decided to move it to be a monorepo to make both development and our CI pipelines easier, but it's unfortunately disruptive right now. We've updated [our setup docs](https://developers.mattermost.com/contribute/developer-setup/) and added [some steps for migrating to working with the monorepo](https://developers.mattermost.com/contribute/monorepo-migration-notes/).

Copying the changes over there hopefully shouldn't be too hard. There's a few changes to file paths (such as the code living in a dedicated `src` subdirectory), but most things should look the same as they do now. 

Let us know if you could use any help with this. Hopefully the process is smooth.

2023-03-29 07:41 UTC, gitstart commented
@hmhealey This PR has been moved  to the monorepo https://github.com/mattermost/mattermost-server/pull/22719 cc @M-ZubairAhmed

2023-03-29 20:32 UTC, closed without merging