Migrate "components/suggestion/suggestion.jsx" to Typescript #21099
mattermost/mattermost-webapp pull request #12287
Opened 2023-03-01 11:12 UTC by gitstart

Summary
Migrate "components/suggestion/suggestion.jsx" to Typescript

Ticket Link
https://mattermost.atlassian.net/browse/MM-46944

### Release note
```release-note
Migrate "components/suggestion/suggestion.jsx" to Typescript
```

2023-03-01 11:12 UTC, mattermost-build commented
Hello @gitstart,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-03-01 11:12 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-03-01 11:40 UTC, m1lt0n approved these changes

2023-03-03 20:42 UTC, hmhealey requested changes
Thanks for the PR!

Is this ready for review, or does it still need work? I did a preliminary review of what's here at least

2023-03-03 20:42 UTC, hmhealey commented on components/suggestion/at_mention_provider/at_mention_suggestion.tsx
> +class AtMentionSuggestion extends Suggestion<Props> {
Should we be passing a second type parameter to `Suggestion` like `Suggestion<Props, Item>`?

2023-03-03 20:42 UTC, hmhealey commented on components/suggestion/generic_user_provider.tsx
> +class UserSuggestion extends Suggestion<ProviderResults> {
Same thing here. It might be enough to use the default `Item` type in this case though

2023-03-03 20:42 UTC, hmhealey commented on components/suggestion/search_channel_suggestion/index.ts
> +        currentUser: getCurrentUserId(state) as string,
Are these type assertions necessary? `teammate` should be optional based on the code for `SearchChannelSuggestion`, and I think `getCurrentUserId` always returns a string

2023-03-03 20:42 UTC, hmhealey commented on components/suggestion/search_date_suggestion/index.ts
> +            currentDate: currentDate as Date,
Similarly, `SearchDateSuggestion` can handle when `currentDate` is undefined, so I think this prop should be optional as well

2023-03-03 20:42 UTC, hmhealey commented on components/suggestion/suggestion_date.tsx
> +export type SuggestionItem = {
Does this still need to be exported? I can't see it being used anywhere else in this PR

2023-03-14 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-03-23 10:53 UTC, M-ZubairAhmed commented
Hey there!, Thank you for your PR.
Webapp is now part of mattermost monorepo now at https://github.com/mattermost/mattermost-server/tree/master/webapp Would you be interested in opening the PR over there?

2023-03-29 07:43 UTC, gitstart commented
@M-ZubairAhmed this PR had been moved to a monorepo https://github.com/mattermost/mattermost-server/pull/22725 cc @hmhealey

2023-03-30 00:45 UTC, closed without merging