MM-49214 Hide bot users from user picker dropdown in app fw
mattermost/mattermost-webapp pull request #12297
Opened 2023-03-01 20:01 UTC by qvarnstr0m

#### Summary
This issue involves updating the user picker functionality in the Mattermost web app's app framework. Currently, bot users are being displayed in the user picker for forms, which is not desired. The goal is to hide bot users from the user picker dropdown and only show real users. This can be achieved by filtering out any user that is a bot using the user.is_bot property. The necessary changes have been made in the apps_form_select_field.tsx file, specifically in the loadDynamicUserOptions function, which has been updated to filter out bot users using .filter((user) => !user.is_bot).  
  
Manual testing has been done, no new tests have been added, all existing tests have passed.

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-server/issues/22123

#### Related Pull Requests

#### Screenshots

#### Release Note
```release-note
NONE
```

2023-03-01 20:01 UTC, mattermost-build commented
Hello @qvarnstr0m,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-03-01 20:01 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-03-02 17:13 UTC, nevyangelova requested changes

2023-03-02 17:13 UTC, nevyangelova commented on components/apps_form/apps_form_field/apps_form_select_field.tsx
> +        return null;
nit: remove white space

2023-03-02 17:14 UTC, nevyangelova commented
Thanks @qvarnstr0m just a minor nit on my end!

2023-03-02 20:58 UTC, mickmister approved these changes
Thanks for this improvement @qvarnstr0m!

LGTM :+1:

I have just one non-blocking concern to remove a comment that seems a bit redundant

2023-03-02 22:36 UTC, mickmister approved these changes

2023-03-03 09:35 UTC, koox00 approved these changes

2023-03-06 15:50 UTC, ghost approved these changes
LGTM!

2023-03-19 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-03-23 10:53 UTC, M-ZubairAhmed commented
Hey there!, Thank you for your PR.
Webapp is now part of mattermost monorepo now at https://github.com/mattermost/mattermost-server/tree/master/webapp Would you be interested in opening the PR over there?

2023-03-23 20:12 UTC, hmhealey commented
The web app now lives in the `webapp/channels` over in https://github.com/mattermost/mattermost-server. We decided to move it to be a monorepo to make both development and our CI pipelines easier, but it's unfortunately disruptive right now. We've updated [our setup docs](https://developers.mattermost.com/contribute/developer-setup/) and added [some steps for migrating to working with the monorepo](https://developers.mattermost.com/contribute/monorepo-migration-notes/).

Copying the changes over there hopefully shouldn't be too hard. There's a few changes to file paths (such as the code living in a dedicated `src` subdirectory), but most things should look the same as they do now. 

Let us know if you could use any help with this. Hopefully the process is smooth.

2023-03-23 20:36 UTC, qvarnstr0m commented
Alright, I will try!

2023-03-23 20:47 UTC, closed without merging

2023-03-23 21:13 UTC, qvarnstr0m commented
I have forked the new mattermost-server and opened a new pull request over there.