[MM-50976] - Contact Support to redirect to Zendesk and pre-fill known information
mattermost/mattermost-webapp pull request #12304
Opened 2023-03-02 12:31 UTC by AGMETEOR

#### Summary
Makes changes such that all "Contact support" ctas redirect to zendesk and "Contact sales" ctas redirect to mm.com

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50976

#### Related Pull Requests
https://github.com/mattermost/customer-web-server/pull/1114

#### Release Note

```release-note
NONE
```

2023-03-03 15:23 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-03-03 23:20 UTC, marianunez requested changes
Code LGTM, mostly a comment about sending the email address in the case of self-hosted and tests need to be updated - unit tests and cypress tests are failing https://github.com/mattermost/mattermost-webapp/pull/12304#issuecomment-1451812850

2023-03-03 23:20 UTC, marianunez commented on utils/contact.ts
> +
nit: for the file name `contact_support_sales.ts`

2023-03-03 23:20 UTC, marianunez commented on utils/contact.ts
> +};
Are these used ?

2023-03-06 10:01 UTC, yasserfaraazkhan commented
Hi @AGMETEOR ,
was seeing this error on the spinwick,
<img width="710" alt="Screenshot 2023-03-06 at 3 30 17 PM" src="https://user-images.githubusercontent.com/15979783/223078269-c1c9c763-e384-4a36-b994-f21986b41538.png">

2023-03-06 15:46 UTC, marianunez commented on components/admin_console/feature_discovery/feature_discovery.tsx
> +    contactSalesFunc = () => {
Gotcha!

2023-03-06 16:16 UTC, marianunez commented on utils/contact.ts
> +};
Couldn't find any reference to `goToBillingGeneralSalesSupportForm`

2023-03-06 16:18 UTC, marianunez reviewed
Latest changes look good. Still pending tests to be updated - unit tests and cypress tests are failing https://github.com/mattermost/mattermost-webapp/pull/12304#issuecomment-1451812850

2023-03-06 16:19 UTC, marianunez commented on components/common/hooks/useOpenSalesLink.ts
> +    const companyName = customer?.name || '';
Sorry, second question was an implementation detail that Allan already took care of 👍

2023-03-06 17:38 UTC, yasserfaraazkhan commented
/e2e-test

2023-03-06 17:38 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/310663) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/310663)

2023-03-07 13:54 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/311033) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/311033)

2023-03-07 14:22 UTC, yasserfaraazkhan commented
/e2e-test

2023-03-07 14:22 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/311046) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/311046)

2023-03-08 20:23 UTC, marianunez approved these changes
Thank @AGMETEOR!

2023-03-09 11:13 UTC, yasserfaraazkhan commented
Hi @AGMETEOR @marianunez 
should we wait till this [MM-51018](https://mattermost.atlassian.net/browse/MM-51018) is merged ? Currently, not seeing the form filled when clicked on contact sales

2023-03-09 12:00 UTC, yasserfaraazkhan approved these changes
checked the navigation when clicked on contact sales, from console, pricing modal.
working as expected

2023-03-09 19:27 UTC, marianunez commented
> Hi @AGMETEOR @marianunez should we wait till this [MM-51018](https://mattermost.atlassian.net/browse/MM-51018) is merged ? Currently, not seeing the form filled when clicked on contact sales

@emdecr will be working on supporting these params in mattermost.com side. We can still move forward with completing the work here and if this is used before that ticket is complete they will still be redirected to the correct form but without the field pre-populated. I don't think this is a blocker for this change. We can do the full validation of the prefilled info once published in mm.com

2023-03-09 23:33 UTC, emdecr commented
Thanks @marianunez 👍 

@yasserfaraazkhan I can send you a URL and creds for our development site if you want to check what the the decode looks like. I'll send a DM. I've got a in-progress branch up there.

2023-03-10 15:15 UTC, ConorMacpherson approved these changes
LGTM! Nice work. I just left two small comments that might require a change.

2023-03-10 18:57 UTC, nickmisasi approved these changes
Sorry for the delay. LGTM

2023-03-24 10:20 UTC, closed without merging