Support env var for playwright test directory
mattermost/mattermost-webapp pull request #12351
Opened 2023-03-09 18:02 UTC by mickmister

#### Summary

In order for other projects to use the Playwright testing environment implemented by the webapp repo, we can have the test runner support an arbitrary test directory via environment variable.

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-03-09 18:05 UTC, mickmister commented
@wiggin77 Given your point of not submitting PRs to the webapp repo, would something like this be okay?

The integrations team is working on using Playwright in individual plugin projects, and we're trying out sharing the Playwright configuration that the webapp repo currently holds. We'll structure our effort to assume that the tooling is moving to another project / folder structure.

2023-03-09 18:07 UTC, wiggin77 commented
> @wiggin77 Given your point of not submitting PRs to the webapp repo, would something like this be okay?
> 

Yes, that is easy to redo in the mono-repo branch.

2023-03-09 23:24 UTC, saturninoabril requested changes
Thanks @mickmister, just one request and I'm all good.

2023-03-09 23:24 UTC, saturninoabril commented on e2e/playwright/playwright.config.ts
> +    testDir: process.env.PLAYWRIGHT_TEST_DIR || 'tests',
Please move to [test.config.ts](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/playwright/test.config.ts#L51-L54) as common entry point from env variables. Then here could be: `testDir: testConfig.testDir,`.
For env name, please change to `PW_TEST_DIR`.

2023-03-10 02:09 UTC, saturninoabril approved these changes
Or I'd say non-blocking on my previous comment and we can address separately after monorepo.

2023-03-10 02:10 UTC, saturninoabril commented
@mickmister Feel free to merge.

2023-03-24 15:19 UTC, mickmister commented
Closing in favor of https://github.com/mattermost/mattermost-server/pull/22651

2023-03-24 15:19 UTC, closed without merging