[MM] Update message when an existing guest user is added to a single channel
mattermost/mattermost-webapp pull request #3555
Opened 2019-08-29 11:58 UTC by streamer45

#### Summary

Updates the message when an existing guest user is added to a single channel to properly support plurals.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-17924

2019-08-29 15:13 UTC, jespino commented on components/invitation_modal/invitation_modal_confirm_step_row.jsx
> +                    <FormattedMessage
This is not a valid approach, you are using the dynamically generated reason value to fill the `defaultMessage` but you are using the same key all the time, what means that is going to translate it wrongly. Or you pass all the data without translated and use here to build the FormattedMessage, or you pass the final translated version.

2019-08-29 15:24 UTC, jespino requested changes
You have to change the approach probably the simplest option is to generate 2 different reason messages based on the number of channels, and pass the generated reason message there.

2019-08-29 19:40 UTC, streamer45 commented
Looks like the proposed solution is not compatible with how translations are handled during build. mmjstool failing to extract the translation id.

2019-08-29 19:52 UTC, jespino commented
@streamer45 Yes, you have to wrap the id inside the `t()` function to mark the text as something that you can translate.

2019-08-30 10:29 UTC, jespino approved these changes
LGTM

2019-09-01 15:35 UTC, reflog approved these changes
👍

2019-09-03 07:35 UTC, srkgupta approved these changes
Changes looks good and will be tested once the code is merged into master.

2019-09-03 07:35 UTC, merged