MM-20904 Add E2E tests for custom categories
mattermost/mattermost-webapp pull request #5981
Opened 2020-07-23 18:55 UTC by sudheerDev

#### Summary
 * Tests for create, delete and rename categories

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20904

2020-07-24 13:27 UTC, hmhealey commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +        });
Actually, there's a new `uiCloseWhatsNewModal` added by https://github.com/mattermost/mattermost-webapp/pull/5984

2020-07-24 13:33 UTC, sudheerDev commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +        cy.get('#editCategoryModal input').type(newCategoryName).type('{enter}');
wierd, let me check that

2020-07-24 13:35 UTC, Willyfrog commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +        cy.apiUpdateConfig({
```suggestion
    before(() => {
        // # Enable channel sidebar organization
        cy.apiUpdateConfig({
```

2020-07-24 13:36 UTC, Willyfrog commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +        // # create a category from cateory menu
```suggestion
        // # create a category from category menu
```

2020-07-27 12:47 UTC, sudheerDev commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +        });
Done

2020-07-27 13:01 UTC, sudheerDev commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +        cy.get('#editCategoryModal input').type(newCategoryName).type('{enter}');
ya, changes to master made this invalid, Added ID to the modal, it already has a generic modal id such as labels might as well add one to the modal

2020-07-28 19:23 UTC, hmhealey commented
Does this need QA review? I don't know what the process usually is for those

2020-07-31 08:39 UTC, sudheerDev commented
going to add TM4J id's for tests

2020-09-25 14:34 UTC, jgilliam17 requested changes

2020-09-25 14:34 UTC, jgilliam17 commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +    it('should create a new category from sidebar menu', () => {
```suggestion
    it('MM-T3161_1 should create a new category from sidebar menu', () => {
```

2020-09-25 14:34 UTC, jgilliam17 commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +    it('should create a new category from category menu', () => {
```suggestion
    it('MM-T3161_2 should create a new category from category menu', () => {
```

2020-09-25 14:34 UTC, jgilliam17 commented on e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
> +    it('move an existing channel to a new category', () => {
```suggestion
    it('MM-T3161_3 move an existing channel to a new category', () => {
```

2020-09-25 15:19 UTC, jgilliam17 approved these changes
Thank you @sudheerDev 
Looks good to merge.
- Updated related TM4J test case steps, details and links.

2020-09-25 17:08 UTC, merged