MM-T399 Invalidate Pending Email Invitations
mattermost/mattermost-webapp pull request #6267
Opened 2020-08-25 15:34 UTC by josephk96

I created a test to check that invites a user to a team, ensures the user can sign up via the email link provided, invite two more users, invalidate their invites, retrieve the email of the second user and go to the provided sign up link and validate that the correct error message is shown.

Test case: https://automation-test-cases.vercel.app/test/MM-T399

2020-08-26 16:04 UTC, saturninoabril requested changes
Thanks @josephk96! Please see comments.

2020-08-26 16:04 UTC, saturninoabril commented on e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
> +        cy.wait(TIMEOUTS.FIVE_SEC);
I think it should click "Done" to complete the process.
```suggestion
        cy.findByText('Done').should('be.visible').click();
```

2020-08-26 16:04 UTC, saturninoabril commented on e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
> +        cy.get('#headerTeamName').should('contain.text', testTeam.display_name);
I'm getting random failing test here which can be solved by adding a timeout option.
```suggestion
        cy.get('#headerTeamName', {timeout: TIMEOUTS.HALF_MIN}).should('contain.text', testTeam.display_name);
```

2020-08-26 16:04 UTC, saturninoabril commented on e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
> +        cy.apiAdminLogin();
I think it needs to reload a page after login.

2020-08-26 16:04 UTC, saturninoabril commented on e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
> +        checkIfLicensed();
```suggestion
        // # Open the 'Invite People' full screen modal
        cy.findByLabelText('main menu').should('be.visible').click();
        cy.findByText('Invite People').should('be.visible').click();
```

2020-09-02 14:33 UTC, josephk96 commented
@saturninoabril ,  I updated the `team_settings/helpers.js` file to be in sync with https://github.com/mattermost/mattermost-webapp/pull/6263/files and used the methods there in this test. I hope that it would be fine, since I am in the `onboarding` directory but am importing and using functions from another directory. If it isn't, please let me know and I will refactor this. I also added the signup page visibility check in the verifyEmailInviteAndVisitLink function :)

@josephbaylon, please let me know if the test is still failing for you :)

2020-09-02 14:35 UTC, josephbaylon commented
/update-branch

2020-09-02 14:38 UTC, josephk96 commented
I also tested MM-T389 and MM-T386 to use the `verifyEmailInviteAndVisitLink` function with the newly included signup section visibility check and they are working

2020-09-02 14:54 UTC, josephk96 commented
Thanks @josephbaylon ! Btw, I'm a big fan of your name, it's super cool💯

2020-09-02 14:56 UTC, josephbaylon commented
@josephk96 Hahaha. Likewise 🤣

2020-09-02 16:10 UTC, saturninoabril approved these changes
Thanks @josephk96!

2020-09-02 16:10 UTC, merged