Mm 27817 e2e add user to gm
mattermost/mattermost-webapp pull request #6278
Opened 2020-08-26 14:42 UTC by Willyfrog

#### Summary

e2e test for adding a user to an existing GM

#### Ticket Link

[MM-27817](https://mattermost.atlassian.net/browse/MM-27817)

#### aditional notes
since i renamed the file for consistency, let me know if you prefer to have a separate file, but those cases seemed related to me

2020-08-27 09:55 UTC, sudheerDev requested changes

2020-08-27 09:55 UTC, sudheerDev commented on e2e/cypress/integration/multi_team_and_dm/gm_add_user_spec.js
> +        cy.contains('.post-message__text', 'historical').should('not.be.visible');
One of the expected test steps is that it. should show. the message `This is the start of your group message history...".` after creating the group. Can you add it?

2020-08-27 15:44 UTC, sudheerDev approved these changes
LGTM

2020-08-28 09:57 UTC, Willyfrog commented
sorry @prapti I forgot to push the last changes

2020-09-29 10:14 UTC, Willyfrog commented
/update-branch

2020-09-29 10:14 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2020-10-02 00:16 UTC, prapti approved these changes
Looks great! Thank you for adding the tests @Willyfrog!

2020-10-02 00:17 UTC, merged