MM-T1786 Dismissing the toast using Jump to
mattermost/mattermost-webapp pull request #6302
Opened 2020-08-28 05:42 UTC by openmohan

#### Summary

MM-T1786 Dismissing the toast using Jump to

#### Ticket Link

https://automation-test-cases.vercel.app/test/MM-T1786

2020-08-28 11:06 UTC, saturninoabril requested changes
Thanks @openmohan. Tested and passed, except for minor comments.

2020-08-28 11:06 UTC, saturninoabril commented on e2e/cypress/integration/toast/new_messages_toast_spec.js
> +        // # Scroll up on the channej
```suggestion
        // # Scroll up on the channel
```

2020-08-28 11:06 UTC, saturninoabril commented on e2e/cypress/integration/toast/new_messages_toast_spec.js
> +            // # Post messages as other users
```suggestion
            // # Post messages as other user
```

2020-08-28 18:21 UTC, saturninoabril approved these changes
Thanks @openmohan! Tested and passed!

2020-09-09 00:52 UTC, prapti approved these changes
Looks good to me. Thank you for your contribution @openmohan!

2020-09-09 00:52 UTC, merged