[MM-27822] e2e/desktop_notifications: add MM-T487
mattermost/mattermost-webapp pull request #6303
Opened 2020-08-28 11:34 UTC by isacikgoz

#### Summary
Adds MM-T487: end Desktop Notifications - For all activity with apostrophe, emoji, and markdown in notification.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27822

2020-08-28 17:53 UTC, saturninoabril requested changes
@isacikgoz LGTM, except for couple of requests.  Thanks!

2020-08-28 17:53 UTC, saturninoabril commented on e2e/cypress/integration/notifications/desktop_notifications_spec.js
> +        cy.apiCreateUser({}).then(({user}) => {
nit: this could also be
```suggestion
        cy.apiCreateUser().then(({user}) => {
```

2020-08-28 17:53 UTC, saturninoabril commented on e2e/cypress/integration/notifications/desktop_notifications_spec.js
> +                stubNotificationAs('withNotification', 'granted');
I think this should move above after the user logged in. If not, this test case is dependent to previous test. You'll see it fails when you do `it.only`. We usually aim that each test is independent from other test so it's easier to maintain if we need to quickly check a particular test case.

2020-09-01 09:57 UTC, saturninoabril approved these changes
Thanks @isacikgoz, LGTM. Tested and passed.

2020-09-03 09:00 UTC, lindy65 approved these changes
Thanks @isacikgoz - Looks good to me 👍

2020-09-07 09:34 UTC, grundleborg approved these changes

2020-09-07 09:35 UTC, grundleborg commented
@isacikgoz sorry for the delayed review - I think this needs a manual update branch but then it's good to merge.

2020-09-07 10:23 UTC, merged