MM-T254 Rehydrate mention badge after post is marked as Unread
mattermost/mattermost-webapp pull request #6318
Opened 2020-08-29 10:31 UTC by openmohan

#### Summary

MM-T254 Rehydrate mention badge after post is marked as Unread

#### Ticket Link

https://automation-test-cases.vercel.app/test/MM-T254

2020-08-31 13:41 UTC, srkgupta requested changes
Hi @openmohan 
Thanks. The test looks great. Just one suggestion observed.

2020-08-31 13:41 UTC, srkgupta commented on e2e/cypress/integration/mark_as_unread/unread_toast_count_spec.js
> +        });
The test is missing the following assertion:
`In particular, at-here should mention the user even if they were offline when the post was originally made.`

Suggested changes:
```
        cy.get(`#sidebarItem_${currentChannel.name}`).
            scrollIntoView().
            find('#unreadMentions').
            should('be.visible').
            and('have.text', '1');
```

Note: You need to declare and assign the variable currentChannel before.

2020-09-01 11:52 UTC, srkgupta approved these changes
Thanks for the changes @openmohan. The changes looks good. Approving the PR.

2020-09-01 15:09 UTC, saturninoabril requested changes
Thanks @openmohan! Tested and passed. LGTM, except for minor suggestions.

2020-09-01 15:09 UTC, saturninoabril commented on e2e/cypress/integration/mark_as_unread/unread_toast_count_spec.js
> +                    });
```suggestion
                        channelId: channel.id,
                    });
```

2020-09-01 15:09 UTC, saturninoabril commented on e2e/cypress/integration/mark_as_unread/unread_toast_count_spec.js
> +    it('MM-T254 Rehydrate mention badge after post is marked as Unread', () => {
nit,
```suggestion
    });

    it('MM-T254 Rehydrate mention badge after post is marked as Unread', () => {
```

2020-09-02 16:02 UTC, openmohan commented
Thanks, @saturninoabril for the review and suggestions.

2020-09-02 16:04 UTC, saturninoabril commented
/update-branch

2020-09-02 16:04 UTC, saturninoabril approved these changes
Thanks @openmohan! LGTM

2020-09-02 16:04 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-09-02 16:22 UTC, merged