MM-T338 Image Attachment Upload in Mobile View
mattermost/mattermost-webapp pull request #6321
Opened 2020-08-29 23:08 UTC by M-ZubairAhmed

#### Summary
This PR adds end to end tests to codebase which tries to verify if image attachments in mobile view are correctly rendered pre and post sending of message.

#### Ticket Link
MM-T338

#### Related Pull Requests
none

#### Screenshots
none

2020-09-01 10:44 UTC, saturninoabril requested changes
Thanks @M-ZubairAhmed.  Please see comments.

2020-09-01 10:44 UTC, saturninoabril commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> +        // # Attach an image but dont post it yet
```suggestion
        // # Attach an image but don't post it yet
```

2020-09-01 10:44 UTC, saturninoabril commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> +            equal(`${httpContext};filename="${filename}"; filename*=UTF-8''${filename}`);
Could you confirm if all are passing on you? I've got failing test here.  See screenshot.
<img width="684" alt="Screen Shot 2020-09-01 at 6 34 20 PM" src="https://user-images.githubusercontent.com/5334504/91839597-e8ddae80-ec81-11ea-9104-5cdf59108325.png">

2020-09-01 10:44 UTC, saturninoabril commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> +    it.only('MM-T345 Public links for common file types should open in a new browser tab', () => {
```suggestion
    it('MM-T345 Public links for common file types should open in a new browser tab', () => {
```

2020-09-01 10:44 UTC, saturninoabril commented on e2e/cypress/support/ui_commands.js
> +Cypress.Commands.add('postMessageQuickly', (message) => {
Please change to `uiPostMessageQuickly` to easily check at a glance that this is done via UI. It's our recent convention for UI commands, although not many were migrated yet. Also, please add types at `ui_commands.d.ts`.  Thanks!

2020-09-01 14:22 UTC, M-ZubairAhmed commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> +        ['bmp-image-file.bmp', 'png-image-file.png', 'jpg-image-file.jpg', 'gif-image-file.gif', 'tiff-image-file.tif'].
This particular tests bought in its own set of images, Images as per the docs (@saturninoabril google drive) were provided in this PR, i replaced those in this test and removed now redundant images from fixtures

2020-09-01 14:23 UTC, M-ZubairAhmed commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> -                    verifyLinkHasDownloadProperties(fileAttachment, image);
`verifyLinkHasDownloadProperties` was changed and improved in this PR, so made the change

2020-09-03 00:02 UTC, prapti requested changes
Thank you for working on these tests @M-ZubairAhmed! Great improvements on things that affect the previous tests you've worked on :) 

A couple of comments and questions before I can approve it:
1. I think it's a good idea to separate both the tests for MM-T338 and MM-T345 in new spec files each.
2. It looks like MM-T345 is missing some test steps as mentioned in the [test case](https://automation-test-cases.vercel.app/test/MM-T345), esp. steps 6 (Click on "Copy Link"), and 8 (Click on the link to verify that the file opens in a new browser tab), unless I'm missing something? Please let me know if I've overlooked any details. Thanks!

2020-09-07 01:54 UTC, saturninoabril commented
@M-ZubairAhmed Let us know status of this PR, thanks!

2020-09-07 08:29 UTC, M-ZubairAhmed commented
Hi @prapti , thank you for your review
1. I have a contrary opinion on that, since all of them belongs to some form of upload, i have placed them in the same file. They both also share the same `downloadAttachmentAndVerifyItsProperties` function.
2. Here are the steps with respect to code line numbers
- Account Settings ➜ Display ➜ Image Previews ➜ Expanded : https://github.com/mattermost/mattermost-webapp/pull/6321/files#diff-c9a96f255e269faf4adce4e32b2b0bb7R358
- Make a post with an attachment of any of the following types jpeg, png, bmp, .tiff, gif, avi, mpeg, mp4, mpeg, or wav: https://github.com/mattermost/mattermost-webapp/pull/6321/files#diff-c9a96f255e269faf4adce4e32b2b0bb7R377
- Click on the image preview : https://github.com/mattermost/mattermost-webapp/pull/6321/files#diff-c9a96f255e269faf4adce4e32b2b0bb7R384
- Click on "Get public link" : https://github.com/mattermost/mattermost-webapp/pull/6321/files#diff-c9a96f255e269faf4adce4e32b2b0bb7R392
- Click on "Copy link", then on "Close" : https://github.com/mattermost/mattermost-webapp/pull/6321/files#diff-c9a96f255e269faf4adce4e32b2b0bb7R402 & https://github.com/mattermost/mattermost-webapp/pull/6321/files#diff-c9a96f255e269faf4adce4e32b2b0bb7R409
- Paste the link into the message input box and hit "Enter" to make the post : https://github.com/mattermost/mattermost-webapp/pull/6321/files#diff-c9a96f255e269faf4adce4e32b2b0bb7R415
- Click on the link: https://github.com/mattermost/mattermost-webapp/pull/6321/files#diff-c9a96f255e269faf4adce4e32b2b0bb7R418

2020-09-09 08:54 UTC, saturninoabril requested changes
Thanks @M-ZubairAhmed! Overall looks good to me, except for last couple comments.

2020-09-09 08:54 UTC, saturninoabril commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> -});
With the changes on files, L233 failed on me when running all tests in this spec. It should now be:
```diff
- const attachmentFilename = 'image-file.jpg';
+ const attachmentFilename = 'jpg-image-file.jpg';
```

Please run all the tests and let me know if all are consistently passing on you.

2020-09-09 08:54 UTC, saturninoabril commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> +                const imageURL = imageDiv.css('background-image').replace('url(', '').replace(')', '').replace(/"/gi, '');
I suggests,
```suggestion
                const imageURL = imageDiv.css('background-image').split('"')[1];
```

2020-09-10 05:04 UTC, saturninoabril commented
Hello Zubair, let us know once ready for review.  Thanks!

2020-09-10 07:24 UTC, M-ZubairAhmed commented
@saturninoabril i made the changes, i ran them individually. Can you please run them collectively?

2020-09-10 07:35 UTC, saturninoabril approved these changes
Thanks @M-ZubairAhmed! Tested and all passed. LGTM.

2020-09-10 22:44 UTC, prapti approved these changes
LGTM. Thank you for the improvements @M-ZubairAhmed!

2020-09-10 22:45 UTC, merged