MM-T550 Words that trigger mentions - @-icon still shows mentions list if all triggers deselected
mattermost/mattermost-webapp pull request #6324
Opened 2020-08-30 08:04 UTC by josephk96

Summary

As a new user, I deselected all 'Words that trigger mentions', and with the sysadmin account I made sure that typing '@' in town square would still show the user's name, and typed a message tagging the user. I also verified that the @ button is visible, and clicking it would show the recent mentions in the RHS, along with the username in the search bar.
 
Test case: https://automation-test-cases.vercel.app/test/MM-T550

2020-09-01 11:32 UTC, saturninoabril requested changes
@josephk96 LGTM, except that I don't see the test user added to private channel. Please take a look again.  Thanks!

2020-09-01 11:32 UTC, saturninoabril commented on e2e/cypress/integration/notifications/at_icon_still_shows_mentions_list_with_deactivated_triggers_spec.js
> +        // * Ensure that the user's name is in the search box after clicking on the @ buton
```suggestion
        // * Ensure that the user's name is in the search box after clicking on the @ button
```

2020-09-03 00:49 UTC, prapti commented
/update-branch

2020-09-03 01:12 UTC, prapti requested changes
@josephk96 There seems to be a mismatch in the title and test case linked to this PR [MM-T550](https://automation-test-cases.vercel.app/test/MM-T550), and the test that has been implemented. Also the `it` statement says 'MM-T546'. Could you please recheck these?
@saturninoabril The test steps for MM-T550 where it says "Deselect all words that trigger mentions" -- I understood this test as going into Account Settings > Notifications > Words That Trigger Mentions and unselecting all the options. Then verifying that clicking the '@' button by the search box still showed the mentions. Do you think that's true or should we clarify the test case with someone?

2020-09-03 02:16 UTC, josephk96 commented
Hi @prapti , you are absolutely right, I used the wrong test case in the `it` statement. I'll fix it when I get home :) Thanks for pointing this out!

2020-09-03 06:23 UTC, saturninoabril commented
@prapti Yeah, I think it's true but feel to clarify. And thanks for catching up the mismatch. That explains why I'm not seeing user being added to private channel 'cause I'm looking at the wrong MM-T546 test case :)

2020-09-03 11:52 UTC, josephk96 commented
I fixed the test case description. Sorry again for the mistake

2020-09-03 13:47 UTC, saturninoabril approved these changes
Thanks @josephk96! LGTM, tested and passed.

2020-09-03 22:52 UTC, prapti approved these changes
Thank you both for revisiting!
Looks great! Approving 🎉

2020-09-03 22:53 UTC, merged