MM-T564 New message bar - Own user posts a reply while scrolled up in a channel
mattermost/mattermost-webapp pull request #6328
Opened 2020-08-30 14:31 UTC by josephk96

Summary

This test checks that when a user is scrolled up in a channel and replies to a message in the channel, the 'Jump To New Messages' button does not appear.

Test case: https://automation-test-cases.vercel.app/test/MM-T562

2020-09-01 16:19 UTC, saturninoabril requested changes
Thanks @josephk96! Please see comments.

2020-09-01 16:19 UTC, saturninoabril commented on e2e/cypress/integration/notifications/own_user_posts_reply_while_scrolled_up_spec.js
> +            // * Verify that 'Jump to New Messages' is not visible and that the new reply exists in the channel
I'm not seeing verification to "the new reply exists in the channel".

2020-09-01 16:19 UTC, saturninoabril commented on e2e/cypress/integration/notifications/own_user_posts_reply_while_scrolled_up_spec.js
> +            cy.get(`#postMessageText_${postId}`).should('exist');
Seems like this fell short in verifying the last post. Maybe,
```javascript
// # Post a reply in RHS
const message = 'This is a test message';
cy.postMessageReplyInRHS(message);
...
    // * Message gets posted in Town Square
    cy.uiWaitUntilMessagePostedIncludes(message);
```

2020-09-04 07:45 UTC, saturninoabril commented
/update-branch

2020-09-04 07:45 UTC, saturninoabril approved these changes
Thanks @josephk96, LGTM.

2020-09-09 16:15 UTC, prapti approved these changes
Looks good to me. Thank you @josephk96. I just have one question before I go ahead and merge it: should the test case linked in this PR's description be https://automation-test-cases.vercel.app/test/MM-T564 instead of https://automation-test-cases.vercel.app/test/MM-T562? That was the only confusion I had otherwise, the test itself looks great!

2020-09-09 16:15 UTC, prapti commented
/update-branch

2020-09-10 05:05 UTC, saturninoabril commented
/update-branch

2020-09-10 05:26 UTC, merged