MM-T346 Public link related to a deleted post should no longer open t…
mattermost/mattermost-webapp pull request #6331
Opened 2020-08-30 18:49 UTC by M-ZubairAhmed

…he file

#### Summary

This PR includes an end to end test for verifying the deleted post attachment are indeed deleted when we try to visit their public links

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

2020-08-31 17:54 UTC, M-ZubairAhmed commented
@josephbaylon Hi, thanks for bringing this up, unfortunately my computer doesnt handle running more than one test simulataneously. Also i see that the problem seems to be in beforeEach. If you can let me know i will gladly be able to fix

2020-08-31 18:30 UTC, josephbaylon commented
@M-ZubairAhmed I tried locally and just needs `cy.apiAdminLogin();` before `cy.apiInitSetup()..` to reset to admin

2020-09-01 10:54 UTC, M-ZubairAhmed commented
@josephbaylon build is failing due to some node error. Can you please check, all other are working fine, is there something i should do from here?

2020-09-02 01:20 UTC, saturninoabril requested changes
Thanks @M-ZubairAhmed. LGTM, except for one request.

2020-09-02 01:20 UTC, saturninoabril commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> +            });
I think this is a bonus but it's missing the UI verification on "You should see an error displayed "Error, Unable to get the file info, Back to Mattermost".

2020-09-03 07:22 UTC, saturninoabril requested changes

2020-09-03 07:22 UTC, saturninoabril commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> +    it.only('MM-T346 Public link related to a deleted post should no longer open the file', () => {
```suggestion
    it('MM-T346 Public link related to a deleted post should no longer open the file', () => {
```

2020-09-03 07:22 UTC, saturninoabril commented on e2e/cypress/integration/files_and_attachments/upload_files_spec.js
> +            });
Thanks for updating. Could you add action/check below and see if it works for you?
```javascript
// # Visit the public link
cy.visit(publicLinkOfAttachment, {failOnStatusCode: false});

// * Page should display an error
cy.findByText('Error').should('be.visible');
cy.findByText('Unable to get the file info.').should('be.visible');
cy.findByText('Back to Mattermost').should('be.visible').parent().should('have.attr', 'href', '/');
```

2020-09-04 22:08 UTC, saturninoabril approved these changes
Thanks @M-ZubairAhmed, LGTM!

2020-09-04 22:08 UTC, merged