[Weblate] Remove empty/unchanged translation strings. Add Bulgarian language. Add general translation updates.
mattermost/mattermost-webapp pull request #6349
Opened 2020-09-01 09:23 UTC by metanerd

#### Summary
Remove empty/unchanged translation strings. Add Bulgarian language. Add general translation updates. 

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

2020-09-01 09:46 UTC, metanerd commented
/update-branch

2020-09-01 12:32 UTC, enahum commented on i18n/i18n.jsx
> +        order: 0,
please update the order of the other languages

2020-09-01 12:35 UTC, enahum commented
This one needs a QA review

2020-09-01 14:11 UTC, metanerd commented
> 1 - Bulgarian language addition looks good, except please also add test for it at: https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
> 
> 2 - Question: what does "general translation updates" refer to?
> 
> 3 - Two other comments below

1. Ah nice, will do!
2. These are the general updates from this PR: https://github.com/mattermost/mattermost-webapp/pull/6347 (I just cannot modify that PR. At least, I don't know how)
3. Thank you, will fix and enable sorting on weblate side.

2020-09-07 12:37 UTC, nevyangelova approved these changes
Translations look good although I will say they are quite formal and I thought the language we are keeping is more personal? There are some word shortenings that don't seem necessary IMO. But I won't block the PR just curious :) 

Also there's a test failing but I think you only need to update the snapshots.

2020-09-07 22:24 UTC, jasonblais commented on i18n/de.json
> +  "channel_modal.displayNameError": "Anzeigename muss mindestens 2 Zeichen lang sein.",
@metanerd These strings are still not in alphabetical order - will they be resolved in another PR? If so, I'm fine with that.

2020-09-07 22:26 UTC, metanerd commented
@jasonblais yes, upcoming PRs will fix the alphabetical order.

2020-09-07 22:29 UTC, jasonblais approved these changes

2020-09-07 22:29 UTC, jasonblais commented
@jgilliam17 this is ready for QA review

2020-09-08 20:05 UTC, jgilliam17 requested changes
Thank you @metanerd 
- Verified Bulgarian language has been added in Account Settings>Display>Language 
I noticed few issues with capitalization on account settings modal, extra icons on `more...` links on the old sidebar and the abbreviations and general language improvements Nevy mentioned.
I will create a separate ticket so these translations/changes can be addressed by the contributors.
Can we capitalize the first letter of the language name on the dropdown in this PR? 
<img width="514" alt="Screen Shot 2020-09-08 at 2 44 27 PM" src="https://user-images.githubusercontent.com/52937121/92521750-c13f9680-f1eb-11ea-8e02-bfce64d7ea73.png">
<img width="1333" alt="Screen Shot 2020-09-08 at 3 30 26 PM" src="https://user-images.githubusercontent.com/52937121/92522567-f4365a00-f1ec-11ea-9ee4-320dc8556809.png">

2020-09-10 00:03 UTC, jgilliam17 approved these changes
Thank you @metanerd 
- Verified Bulgarian language has been added in Account Settings>Display>Language, language title has been capitalized.
Follow up issue added for translation improvement (capitalization missing, abbreviations etc.) https://mattermost.atlassian.net/browse/MM-28522

2020-09-10 08:28 UTC, merged

2021-01-06 10:36 UTC, ctlaltdieliet reviewed
ok for me

2021-01-06 10:37 UTC, ctlaltdieliet reviewed
ok