[MM-27207] e2e archived channels I (3)
mattermost/mattermost-webapp pull request #6373
Opened 2020-09-03 13:33 UTC by Willyfrog

#### Summary

[MM-T1676] CTRL/CMD+K does not show private archived channels you are not a member of

#### Ticket Link
[MM-27207](https://mattermost.atlassian.net/browse/MM-27207)

Test:
- [MM-T1676](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1676)

#### Related Pull Requests
Requires:

https://github.com/mattermost/mattermost-webapp/pull/6362

https://github.com/mattermost/mattermost-webapp/pull/6358

2020-09-07 11:11 UTC, srkgupta requested changes
Hi @Willyfrog 

Great Work. Overall the test looks great and is working fine. However I have some minor comments suggested. Please do the needful.

2020-09-07 11:11 UTC, srkgupta commented on e2e/cypress/integration/channel/archived_channels_spec.js
> +            // Select CTRL/⌘+k) to open the channel switcher
Suggested change:

`// # Select`

2020-09-07 11:11 UTC, srkgupta commented on e2e/cypress/integration/channel/archived_channels_spec.js
> +            // Start typing the name of a private channel on this team that has been archived which the test user belongs to
Suggested change:

`// # Start typing....`

2020-09-07 11:11 UTC, srkgupta commented on e2e/cypress/integration/channel/archived_channels_spec.js
> +        // Start typing the name of a private channel on this team that has been archived which the test user belongs to
Comments should start with `#` for actions

2020-09-07 11:11 UTC, srkgupta commented on e2e/cypress/integration/channel/archived_channels_spec.js
> +        cy.contains('#suggestionList', 'archived-not-mine').should('not.exist');
Suggested change:

`cy.contains('#suggestionList', otherChannelName).should('not.exist');`

2020-09-18 13:12 UTC, srkgupta approved these changes
Thanks @Willyfrog. The test looks great and is working fine. Approving the PR.

2020-09-21 14:08 UTC, hmhealey approved these changes

2020-09-21 14:08 UTC, merged