[MM-28140] e2e/system_console/customization: add T1026
mattermost/mattermost-webapp pull request #6379
Opened 2020-09-03 14:40 UTC by mgdelacroix

#### Summary
Adds T1026: Custom Branding - Name character limit

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28140

2020-09-07 10:45 UTC, saturninoabril requested changes
Thanks @mgdelacroix! LGTM, same comment for folder and test ID.

2020-09-07 10:45 UTC, saturninoabril commented on e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
> +    it('T1026 - Custom Branding - Name character limit', () => {
```suggestion
    it('MM-T1026 - Custom Branding - Name character limit', () => {
```

2020-09-07 17:40 UTC, wiggin77 approved these changes
Test looks good to me.  I'm uneasy about just truncating the input field for sitename at 30 chars instead of error.

2020-09-09 15:40 UTC, saturninoabril approved these changes
Thanks @mgdelacroix! LGTM, tested and passed.

@wiggin77 Actual behavior is not truncating but not allowing to input more characters when exceeding the limit. But I agree to have an error shown rather than silently disallowing more inputs. Maybe bring up to UX for further consideration?

2020-09-10 08:51 UTC, lindy65 approved these changes
Thanks @mgdelacroix - looks good to me 👍 

@wiggin77 @saturninoabril - I've created https://mattermost.atlassian.net/browse/MM-28528 for UX to look at the issue of max characters in the Site Name and Site Description fields.

2020-09-10 08:52 UTC, merged