[MM-28179] Cypress/E2E: Automate backlogs - System Console > Reporting pt. 2
mattermost/mattermost-webapp pull request #6389
Opened 2020-09-07 13:34 UTC by streamer45

#### Summary

PR implements [MM-T908](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T908).

#### Ticket

https://mattermost.atlassian.net/browse/MM-28179

2020-09-08 09:49 UTC, isacikgoz approved these changes
LGTM 🚀

2020-09-08 10:06 UTC, saturninoabril requested changes
Thanks @streamer45. LGTM, except for few comments.

2020-09-08 10:06 UTC, saturninoabril commented on e2e/cypress/integration/system_console/reporting/server_logs_spec.js
> +import * as TIMEOUTS from '../../../fixtures/timeouts';
Should be
```suggestion
import * as TIMEOUTS from '../../../../fixtures/timeouts';
```

2020-09-08 10:06 UTC, saturninoabril commented on e2e/cypress/integration/system_console/reporting/server_logs_spec.js
> +        cy.get('.admin-logs-content button span').should('be.visible').should('contain', 'Reload');
nit: may use `and` for readability.
```suggestion
        cy.get('.admin-logs-content button span').should('be.visible').and('contain', 'Reload');
```

2020-09-08 10:06 UTC, saturninoabril commented on e2e/cypress/integration/system_console/reporting/server_logs_spec.js
> +        cy.get('.admin-logs-content div.log__panel').should('be.visible').should('not.empty');
```suggestion
        cy.get('.admin-logs-content div.log__panel').should('be.visible').and('not.empty');
```

2020-09-08 15:37 UTC, saturninoabril approved these changes
@streamer45 Thanks! LGTM, tested and passed.

2020-09-09 07:52 UTC, lindy65 approved these changes
Thanks @streamer45 - looks good to me 👍

2020-09-09 07:56 UTC, merged