Add custom slash command tests
mattermost/mattermost-webapp pull request #6391
Opened 2020-09-07 20:29 UTC by iomodo

#### Summary
This PR will add e2e tests for custom slash commands.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-28258

2020-09-08 11:04 UTC, saturninoabril requested changes
Thanks @iomodo! Overall looks good and all tests passed. But left a comment to use local node server instead of remote one as a test URL indicated in the test case.

2020-09-08 11:04 UTC, saturninoabril commented on e2e/cypress/integration/integrations/custom_slash_commands/slash_commands_spec.js
> +    cy.get('#url').type('http://hidden-peak-21733.herokuapp.com/test_inchannel');
I didn't know that there's a live URL like this but I suggest not to use it for Cypress testing. We usually spin a local node server for webhook testing by `npm run start:webhook`.

Then, url could be generated by,
```javascript
cy.apiGetChannelByName(testTeam.name, 'town-square').then((res) => {
    const url = `${Cypress.env('webhookBaseUrl')}/send_message_to_channel?channel_id=${res.body.id}`;
});
```

Be sure to add verification in before hook so it'll fail immediately when no node server is running/accessible.
```javascript
before(() => {
    cy.requireWebhookServer();
});
```

2020-09-08 15:55 UTC, saturninoabril approved these changes
Thanks @iomodo! LGTM, tested and passed, except for one last request. Approving now.

2020-09-08 15:55 UTC, saturninoabril commented on e2e/cypress/integration/integrations/custom_slash_commands/slash_commands_spec.js
> +        cy.get('#url').type('http://hidden-peak-21733.herokuapp.com/test_ephemeral');
One last request. Could you change all reference to this URL, maybe use `http://example.com` instead?  Thanks

2020-09-09 14:25 UTC, jfrerich approved these changes

2020-09-25 16:23 UTC, DHaussermann approved these changes
Tested and passed.
- Reviewed test to ensure guiltiness and practices are followed
- Ran tests locally - All ran green
LGTM!

2020-09-25 16:24 UTC, hanzei commented
/update-branch

2020-09-28 14:09 UTC, merged