[MM-25553] favicon added for unread messages without mention
mattermost/mattermost-webapp pull request #6431
Opened 2020-09-12 13:18 UTC by bhargav50

#### Summary

A new favicon is introduced when there are unread messages, but there is no mention

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15400

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

### Unread Messages, but no mention

![image](https://user-images.githubusercontent.com/15820702/92996207-9cb72780-f527-11ea-9def-f866ae5778c0.png)

2020-09-15 20:53 UTC, hmhealey approved these changes
Awesome, looks great to me! I appreciate that it's making it clear that something has to change for the favicon to be updated in the `componentDidUpdate` and that you removed some repeated code in `updateFavicon` as well.

2020-09-16 15:48 UTC, devinbinnie approved these changes
LGTM! Thanks @bhargav50!

2020-09-16 15:48 UTC, devinbinnie commented
/update-branch

2020-09-18 20:32 UTC, jgilliam17 commented
Thank you @bhargav50 
This is great, new favicon color looks awesome!
Question
I verified that * has been removed when unreads are present, should we remove the * for mentions?
<img width="489" alt="Screen Shot 2020-09-18 at 3 46 57 PM" src="https://user-images.githubusercontent.com/52937121/93641778-df1ab180-f9ca-11ea-9794-f0ff8741a9c3.png">

2020-09-18 21:36 UTC, esethna commented
@jgilliam17 yes we should remove it for mentions as well. Can you also help test on various browsers/operating systems?

2020-09-19 19:29 UTC, bhargav50 commented
@esethna shall I remove * for mentions in this PR?

2020-09-21 20:30 UTC, esethna commented
@bhargav50 yes please do.

2020-09-23 15:05 UTC, hmhealey commented
Hold on, we still need the * for browsers that don't support changing the Favicon, so that has to be re-added for those

2020-09-23 16:16 UTC, jgilliam17 commented
> Hold on, we still need the * for browsers that don't support changing the Favicon, so that has to be re-added for those

@hmhealey Is this only impacting Safari on macOS?

2020-09-24 14:25 UTC, jgilliam17 commented
Tested on Safari 14.0 (previous versions are not displaying favicons)
- It appears that favicon is not changing when unreads/mentions are present 
<img width="1095" alt="Screen Shot 2020-09-24 at 10 24 19 AM" src="https://user-images.githubusercontent.com/52937121/94158236-2a601480-fe50-11ea-9bb2-9312f8c64052.png">

2020-09-24 14:43 UTC, hmhealey commented
It was needed for Safari and Edge previously. I don't know if Edge's support for it changed with it switching to Chromium, but the code explicitly only enables it on Firefox and Chrome currently.

And for reference, Edge supported showing the favicon previously, but it had some weird caching behaviour, so the favicon wasn't updated reliably when the user received or read mentions.

2020-09-24 18:30 UTC, jgilliam17 commented
Tested on New Edge (chromium based, macOS and Windows) and the favicons display as expected. 
<img width="817" alt="Screen Shot 2020-09-24 at 2 22 09 PM" src="https://user-images.githubusercontent.com/52937121/94184095-65bf0b00-fe71-11ea-80ef-2731a69298c1.png">
![Screenshot 2020-09-24 142828](https://user-images.githubusercontent.com/52937121/94184703-4e345200-fe72-11ea-94a1-813f83a75333.png)
![Screenshot 2020-09-24 142444 (1)](https://user-images.githubusercontent.com/52937121/94184709-4ffe1580-fe72-11ea-8c99-16482f3c1cd7.png)

2020-09-24 18:50 UTC, bhargav50 commented
Shall I add * again then? :sweat_smile:

2020-09-25 14:16 UTC, jgilliam17 commented
> Shall I add * again then? 😅

Based on testing, I would recommend we have the `*` available on Safari since the favicon is not updating
cc: @esethna

2020-09-25 16:14 UTC, esethna commented
@bhargav50 apologies, I should have been more clear. On browsers that support the custom favicons we should remove the *, but for browsers that don't we should keep the *

2020-09-26 17:57 UTC, bhargav50 commented
@hmhealey * is added on unread messages in safari browser, one unit test is also added to assert this behavior in safari

2020-09-28 19:25 UTC, esethna approved these changes

2020-09-29 21:26 UTC, jgilliam17 approved these changes
Thank you @bhargav50 
Tested, looks good to merge. 
- Verified unread and mention custom favicons on Chrome, Edge and Firefox on macOS 
- Verified unread and mention custom favicons on Chrome, Edge and Firefox on Windows 
- Verified unread and mention custom favicons on Firefox on Ubuntu.
- Verified on Safari(macOS) main favicon color/style has been updated. We are continuing to use asterisk for both unreads and mentions, due to favicon not updating on Safari.
<img width="535" alt="Screen Shot 2020-09-29 at 5 24 17 PM" src="https://user-images.githubusercontent.com/52937121/94618204-c5a22100-0278-11eb-8b84-4d0c14fde374.png">

2020-10-01 15:07 UTC, hmhealey requested changes
Also, would you mind reverting the changes to package-lock.json to fix the conflict with master?

2020-10-01 19:40 UTC, bhargav50 commented on components/favicon_title_handler/favicon_title_handler.tsx
> +            const unreadTitle = UserAgent.isSafari() && unreads.messageCount > 0 ? '* ' : '';
I have moved this check to a getter and checked for firefox and chrome to disable updating * in the title

2020-10-02 13:37 UTC, hmhealey approved these changes
Thanks for changing that

2020-10-02 13:37 UTC, merged

2020-10-19 20:23 UTC, amyblais commented
/cherry-pick release-5.29

2020-10-19 20:23 UTC, mattermod commented
Cherry pick is scheduled.