Possible fix for accessibility test for support in buttons in channel header
mattermost/mattermost-webapp pull request #6445
Opened 2020-09-15 01:18 UTC by prapti

The error is happening because of the new plugin icon that is recently added. Since this is an accessibility test, the best way to test is using keyboard tab to verify that the buttons in channel header can be accessed as such. Therefore, instead of adding any complex solution, only adding a tab to verify that the pin button can be accessed as expected.

#### Screenshots
![Screen Shot 2020-09-14 at 6 16 14 PM](https://user-images.githubusercontent.com/691331/93153626-88edfb80-f6b6-11ea-95b7-dd5956ad0e8a.png)

2020-09-15 08:03 UTC, saturninoabril requested changes
Thanks @prapti. For me, the proper fix here is to disable incident response plugin by default at `partial_default_cofig.json`. This was recently enabled by https://github.com/mattermost/mattermost-server/pull/15360 (same as you mentioned earlier). There are several places where this affected some test, like in the main menu where it adds a plugin option -- made the cloud onboarding test failed too and probably other accessibility/permission tests there.

We can always do `cy.apiUpdateConfig` to enable the plugin on demand depending on test requirement.

2020-09-15 17:04 UTC, prapti commented
@saturninoabril I did think about that as well that the plugin would cause other failures, but the incident response plugin is going to be installed and enabled by default in the cloud servers from 5.28 going forward (because of the PR you mentioned). So I was thinking that the adjustments needed to be made to the other tests instead.
Thoughts?

2020-09-15 17:37 UTC, saturninoabril commented
My worry here is the difference between local development and CI. It's pre-packaged on compiled version but when running on source, like most contributors do, it needs to install manually. Not to mention but this will add overhead to external contributors since they are running without EE. That's why I think this should be enabled on demand, similar to NPS. Besides, there's a separate E2E for incident response to take care of tests and impact to core. But feel free to evaluate risk/impact and let us know.

2020-09-15 17:46 UTC, prapti commented
Thank you for putting that into perspective @saturninoabril. Yeah, in that case I think it only makes sense to disable the plugin esp. since the on-prem behavior is different from the cloud version :)
I'll go ahead and make those changes.

2020-09-15 18:05 UTC, saturninoabril approved these changes
Thanks Prapti for updating and considering my suggestion. Left non-blocking comment.

2020-09-15 18:05 UTC, saturninoabril commented on e2e/cypress/fixtures/partial_default_config.json
> +                "Enable":false
```suggestion
                "Enable": false
```

2020-09-16 13:14 UTC, srkgupta approved these changes
Thanks @prapti. The changes LGTM

2020-09-16 13:15 UTC, merged