[MM-28726] Add X to top right of Next Steps Tips for easy back-out
mattermost/mattermost-webapp pull request #6464
Opened 2020-09-16 17:54 UTC by nickmisasi

#### Summary
When in the Next Steps and Tips view, there was no easily noticeable way to back-out of it. This PR adds an X to the top right corner. When that X is clicked, it's the same behaviour as if the user clicked the X on the LHS - a modal appears stating that it will be added to the main menu.

Actually having it added to the main menu will come in a future PR, as part of ticket MM-28727 (which will build on this one)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28726

#### Related Pull Requests
n/a
#### Screenshots
![image](https://user-images.githubusercontent.com/12176405/93373909-02572c80-f824-11ea-8922-4f411c47e029.png)

2020-09-16 18:29 UTC, nickmisasi commented
@matthewbirtch we were unsure of whether the X button on the tips and next steps screen should mimic the behaviour of the LHS x button, or just hide the tips and next steps screen (ie, it would come back on next page refresh, and still be available on the LHS). 

I went with the former, you can try it out in the spinwick. Let me know if you'd like it to be the latter.

2020-09-16 18:55 UTC, matthewbirtch commented
@nickmisasi I think this works to behave consistently with the x in the LHS

2020-09-16 18:57 UTC, matthewbirtch requested changes
There appears to be an issue with the highlighted area being off-position
![image](https://user-images.githubusercontent.com/2040554/93380119-ceccd000-f82c-11ea-9179-ef51a5bb203a.png)

Other than that, I think we're good

2020-09-16 19:08 UTC, nickmisasi commented
@matthewbirtch highlighted area issue was because that spinwick was using the old sidebar, which isn't as wide. If you look now, it's good. I'll followup to make sure that the new sidebar is the only thing people will see in cloud.

2020-09-16 19:41 UTC, stevemudie approved these changes
LGTM

2020-09-16 19:46 UTC, ali-farooq0 approved these changes
👍

2020-09-16 19:46 UTC, ali-farooq0 commented on components/next_steps_view/next_steps_tips.tsx
> +
ahhh eslint -- hate when it complains about not having an empty line above the comment :P

2020-09-17 12:23 UTC, agnivade commented
My apologies for a completely unsolicited comment. But I got stuck in this step while signing up in https://hacktoberfest.cloud.mattermost.com/ and @ethervoid pointed me to this PR.

From what I understand, the big X button will just remove the tutorial. But there's no way to actually finish all the 3 steps in the progress bar in LHS. Which means there's _never_ a way for a user to get to see 3/3 steps completed, or something equivalent. This triggered my inner OCD and I kept helplessly clicking all the buttons possible, hoping for a way out of this challenge. :stuck_out_tongue_closed_eyes: 

As a user, I'll expect a Finish button of some sort to complete finish all the 3 steps after which the tutorial goes away, and if needed I can bring it back again from hamburger menu.

2020-09-17 13:15 UTC, matthewbirtch commented
> From what I understand, the big X button will just remove the tutorial. But there's no way to actually finish all the 3 steps in the progress bar in LHS. Which means there's _never_ a way for a user to get to see 3/3 steps completed, or something equivalent. This triggered my inner OCD and I kept helplessly clicking all the buttons possible, hoping for a way out of this challenge. 😝

@agnivade you should be able to complete all 3 steps if you go through them and click the actions each stesp is asking you to do. If you're not able to successfully complete all 3 steps, then that would be another issue separate from what this ticket is addressing. If you're able to reproduce the errors, it would be helpful to either have a screen recording or the steps you took.

2020-09-17 13:16 UTC, nickmisasi commented
@agnivade adding to Matt's comment, here's how your screen should look if you've interacted with all 3 steps on the first page: 
![image](https://user-images.githubusercontent.com/12176405/93475314-7518e400-f8c6-11ea-8617-f32c550d2c88.png)

2020-09-17 13:24 UTC, agnivade commented
Oh I know what the issue is. I _have_ to enable notifications, otherwise it never completes all the steps. Personally, I don't enable notifications from a website. But that's just my personal choice. IMO, it should be made clear that it's a compulsory step to complete the tutorial. I just thought that it was a recommendation. Sorry if it was obvious.

2020-09-17 14:00 UTC, matthewbirtch commented
> Oh I know what the issue is. I _have_ to enable notifications, otherwise it never completes all the steps. Personally, I don't enable notifications from a website. But that's just my personal choice. IMO, it should be made clear that it's a compulsory step to complete the tutorial. I just thought that it was a recommendation. Sorry if it was obvious.

Makes sense @agnivade. We're making a nuanced update to this actually. You have to click the button, but then once the 'allow desktop notifications' confirm comes up, we will mark the step as complete even if you choose not to allow notifications

2020-09-17 14:32 UTC, marianunez commented
> You have to click the button, but then once the 'allow desktop notifications' confirm comes up,

I see how someone may not even want to click "Allow Desktop Notifications" button at all given that they don't know they have an option to later click do not allow. It implies that it will be enabled as soon as it clicks. Should we have a secondary button there for Skip that step?

2020-09-17 14:33 UTC, nickmisasi commented
> > You have to click the button, but then once the 'allow desktop notifications' confirm comes up,
> 
> I see how someone may not even want to click "Allow Desktop Notifications" button at all given that they don't know they have an option to later click do not allow. It implies that it will be enabled as soon as it clicks. Should we have a secondary button there for Skip that step?

The label for that button could be changed from "Enable Notifications" to something like "Set Notification Preferences", would show the user they'll have a choice

2020-09-17 15:48 UTC, devinbinnie approved these changes

2020-09-17 18:01 UTC, matthewbirtch commented
> The label for that button could be changed from "Enable Notifications" to something like "Set Notification Preferences", would show the user they'll have a choice

Ya, that makes sense. Let's change it to 'Set up notifications'

2020-09-17 20:09 UTC, matthewbirtch approved these changes
> Let's change it to 'Set up notifications'

Approved with the change above

2020-09-17 21:01 UTC, merged