MM-24813 Add e2e tests for archive post menu options
mattermost/mattermost-webapp pull request #6571
Opened 2020-09-28 17:35 UTC by sudheerDev

#### Summary
Add e2e tests for archive channel post menu options

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28413

2020-09-29 10:11 UTC, Willyfrog approved these changes
minor nitpick, looking good

2020-09-29 10:11 UTC, Willyfrog commented on e2e/cypress/integration/archived_channel/post_menu_spec.js
> +        // # click to add a channel description
```suggestion
        // # Click to add a channel description
```

2020-09-30 08:00 UTC, saturninoabril requested changes
@sudheerDev LGTM, except for one request.  Thanks!

2020-10-01 16:32 UTC, sudheerDev commented on e2e/cypress/integration/archived_channel/post_menu_spec.js
> +            cy.get(`#permalink_${postId}`).should('be.visible');
@saturninoabril Thank you

2020-10-01 16:36 UTC, saturninoabril approved these changes
Thanks @sudheerDev! LGTM.

2020-10-02 08:41 UTC, merged