MM-29087: Migrate headerOverlay string refs to functional ones
mattermost/mattermost-webapp pull request #6590
Opened 2020-09-30 18:34 UTC by sowmiyamuthuraman

Fixes https://github.com/mattermost/mattermost-server/issues/15622

  JIRA: https://mattermost.atlassian.net/browse/MM-29087

2020-09-30 20:38 UTC, deanwhillier requested changes
@sowmiyamuthuraman, thanks so much for your contribution, much appreciated!

I have a comment below and it looks like you inadvertently missed replacing the string ref usage on line 492 with the new ref you created like follows:

Old:
```javascript
ref='headerOverlay'
```

New:
```javascript
ref={this.headerOverlayRef}

🙂

2020-09-30 20:38 UTC, deanwhillier commented on components/channel_header/channel_header.js
> +        this.headerOverlay = createRef();
Can we please group this with the other refs declared at the top of the constructor (ln. 96-98), include 'Ref' at the end of the variable name to match (i.e. `headerOverlayRef`) and settle on either using `React.createRef()` or `createRef()` directly for consistency? Might be best to just use `React.createRef()` in this case as that's how the rest of the file is using React methods.

2020-10-01 09:11 UTC, Willyfrog approved these changes
LGTM Thanks for working on the issue :D

2020-10-03 03:54 UTC, jgilliam17 approved these changes
Thank you @sowmiyamuthuraman 
Tested, looks good to merge.
- Verified channel header, checked edit description link, edit modal, description and popover - as expected.

2020-10-19 21:35 UTC, deanwhillier approved these changes
Argh, sincere apologies for the delay in reviewing this – it somehow slipped my notice!

LGTM, thanks so much for your contribution @sowmiyamuthuraman!

2020-10-19 21:36 UTC, deanwhillier commented
/update-branch

2020-10-20 09:13 UTC, merged