Migrate post_list_row component to typescript
mattermost/mattermost-webapp pull request #6593
Opened 2020-09-30 18:45 UTC by sowmiyamuthuraman

Fixes https://github.com/mattermost/mattermost-server/issues/15465

  JIRA: https://mattermost.atlassian.net/browse/MM-20476

2020-10-01 14:21 UTC, devinbinnie requested changes
Thanks for your contribution @sowmiyamuthuraman.
I've added a couple comments for you to review.

2020-10-01 14:21 UTC, devinbinnie commented on components/post_view/post_list_row/index.js
> +import PostListRow from './post_list_row';
This file should also be migrated to TypeScript.

2020-10-01 14:21 UTC, devinbinnie commented on components/post_view/post_list_row/post_list_row.tsx
> +    loadOlderPosts: () => any,
These shouldn't return type `any`. If we don't need the return type, use `void` instead.

2020-10-01 14:21 UTC, devinbinnie commented on components/post_view/post_list_row/post_list_row.tsx
> +        emitShortcutReactToLastPostFrom: (location:string) => any
Same here.

2020-10-02 13:28 UTC, devinbinnie approved these changes
Looking good now, I have some non-blocking comments but overall it's good.
Thanks @sowmiyamuthuraman!

2020-10-02 13:28 UTC, devinbinnie commented on components/post_view/post_list_row/index.ts
> +import {GlobalState} from '../../../types/store';
This can just be `types/store`, no need to use an explicit directory reference.

2020-10-02 13:28 UTC, devinbinnie commented on components/post_view/post_list_row/index.ts
> +function mapStateToProps(state:GlobalState, ownProps:Props) {
Nit: spacing between `:` and `GlobalState`. Also between `:` and `Props`

2020-10-02 13:28 UTC, devinbinnie commented on components/post_view/post_list_row/index.ts
> +function mapDispatchToProps(dispatch:Dispatch<GenericAction>) {
Same nit as above

2020-10-02 13:28 UTC, devinbinnie commented on components/post_view/post_list_row/post_list_row.tsx
> +        emitShortcutReactToLastPostFrom: (location:string) => void
Nit: spacing between `:` and `string`

2020-10-02 13:28 UTC, devinbinnie commented on components/post_view/post_list_row/post_list_row.tsx
> +    blockShortcutReactToLastPostForNonMessages(listId:string) {
Same nit as above

2020-10-02 16:47 UTC, mickmister approved these changes
LGTM, thanks @sowmiyamuthuraman!

2020-10-03 09:41 UTC, saturninoabril commented
Thanks @sowmiyamuthuraman! Tested and passed. LGTM.

2020-10-03 09:41 UTC, merged