[MM-20455] Migrate 'components/integrations/edit_incoming_webhook' module and associated tests to TypeScript
mattermost/mattermost-webapp pull request #6596
Opened 2020-10-01 03:14 UTC by didithilmy

#### Summary

Migrates the following files to TypeScript:
- `components/integrations/edit_incoming_webhook/index.ts`
- `components/integrations/edit_incoming_webhook/edit_incoming_webhook.tsx`
- `components/integrations/edit_incoming_webhook/edit_incoming_webhook.test.tsx`

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15485

#### Related Pull Requests

None

#### Screenshots

None

2020-10-01 14:14 UTC, devinbinnie approved these changes
LGTM! Thanks @didithilmy!

2020-10-05 11:01 UTC, larkox requested changes
LGTM! Thank you very much! Just one small thing about comments.

2020-10-05 12:27 UTC, didithilmy commented on components/integrations/edit_incoming_webhook/edit_incoming_webhook.tsx
> +    team: Team;
Good point, I think I forgot to move the comments. Should have been fixed now.

2020-10-05 12:30 UTC, larkox approved these changes
LGTM. Thanks!

2020-10-09 13:58 UTC, DHaussermann approved these changes
Tested and passed
- CRUD tested backstage UI for incoming webhooks
- No functional issues foung or JS console errors seen
- Tested on Chrome and desktop
LGTM!
Thanks @didithilmy for this improvement!

2020-10-13 07:10 UTC, hanzei commented
/update-branch

2020-10-13 07:24 UTC, merged

2020-10-13 07:25 UTC, hanzei commented
Thanks for the contribution @didithilmy. Looking forward to another more :rocket: