[MM-28415] - Add spec for public/archive channels search functionality
mattermost/mattermost-webapp pull request #6598
Opened 2020-10-01 11:32 UTC by nevyangelova

#### Summary
This PR adds an e2e test verifying that users are able to switch between public and archived channels within the 'More channels' modal and are able to search. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28415

2020-10-02 09:43 UTC, saturninoabril requested changes
Thanks @nevyangelova. Please see comments.

2020-10-02 09:43 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +            });
Does not match with the test case. I believe it should stay as "Show: Public Channels".

2020-10-02 09:43 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +            cy.get('#moreChannelsList').should('be.visible');
On step 1, it expects "matching Public channels are shown."

2020-10-02 09:43 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +            });
Step 2 is for "Show: Archived Channels".

2020-10-02 09:43 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +            cy.get('#searchChannelsTextbox').should('be.visible').type('a').wait(TIMEOUTS.HALF_SEC);
Step 2 does not mention typing any input.

2020-10-02 09:43 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +            cy.get('#moreChannelsList').should('be.visible');
Should validate "matching Public and Private archived channels are shown."

2020-10-04 20:14 UTC, nevyangelova commented
/update-branch

2020-10-08 07:25 UTC, saturninoabril requested changes
@nevyangelova Please see comments.

2020-10-08 07:25 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +    it('MM-T1702 Search works when changing public/archived options in the dropdown', () => {
For ease of test maintenance, each test block should be able to run in isolation. Please try to run this with `it.only` and ensure that it still work as expected.

2020-10-08 07:25 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +        });
Please add test data "... some public and private archived channels exist" per test case.

2020-10-08 07:25 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +        cy.get('#moreChannelsList').should('be.visible');
Please add verification for "On step #1, matching Public channels are shown."

2020-10-08 07:25 UTC, saturninoabril commented on e2e/cypress/integration/channel/more_channels_spec.js
> +                cy.wrap(el).should('contain', 'Show: Archived Channels');
Please add verification for "On step #2, matching Public and Private archived channels are shown."

2020-10-09 12:51 UTC, nevyangelova commented
Sorry @saturninoabril ! I think I finally understood the proper steps! :)

2020-10-12 07:41 UTC, saturninoabril approved these changes
@nevyangelova Thanks for updating and no worries. LGTM, tested and passed.

2020-10-12 09:17 UTC, sudheerDev approved these changes

2020-10-19 11:59 UTC, nevyangelova commented
@jgilliam17 reminder to review this

2020-10-19 13:07 UTC, jgilliam17 approved these changes
Thank you @nevyangelova 
Looks good to merge.
- Linked test case details, steps and links updated.

2020-10-19 14:24 UTC, merged