[GH-15620] Migrated string refs in signup_email
mattermost/mattermost-webapp pull request #6602
Opened 2020-10-01 14:59 UTC by varunks99

#### Summary
This pull request migrates all string-refs in _./components/signup/signupemail/signupemail.jsx_ to functional ones using the `createRef` API.

#### Ticket Link
This fixes mattermost/mattermost-server#15620.

2020-10-01 16:00 UTC, reflog requested changes
@varunks99 - thanks for you contribution!
Please run `npm run fix` to address linting issues.

2020-10-01 18:49 UTC, varunks99 commented on components/signup/signup_email/signup_email.jsx
> +        this.password = React.createRef();
@reflog, I renamed the refs and fixed the linting issues.

2020-10-02 08:21 UTC, reflog approved these changes
:100: Thanks, looking good!

2020-10-02 09:18 UTC, Willyfrog approved these changes
LGTM

2020-10-02 15:59 UTC, jgilliam17 approved these changes
Thank you @varunks99 
Tested, looks good to merge.
- Verified email sign-up works es expected.

2020-10-02 16:52 UTC, jfrerich commented
@reflog, If this looks good to you, would you mind merging?  Thanks!

2020-10-02 17:09 UTC, merged

2020-10-02 17:10 UTC, reflog commented
> @reflog, If this looks good to you, would you mind merging?  Thanks! 

Done