MM T134 visual verification of tooltips
mattermost/mattermost-webapp pull request #6604
Opened 2020-10-01 17:55 UTC by MikeworX

**Summary**
This PR validates that several tool-tips appear as expected in the main view when the associated element is hovered over. The tool-tips checked are for the following elements:

- Member icon
- Plug-in icon (the demo plugin is used)
- Pinned posts - Recent Mentions
- Flagged posts as well as
- Add to Favorites
- Remove from Favorites
- Unmute (visible when channel is muted )
- 'Download' on download file icon
- Long channel name (shown truncated on the LHS)

The PR creates a new instance, along with a test user and a test channel with a long name, then proceeds to validate the hover tool-tips. The demo plugin is also installed and enabled for testing of the plug-in tool-tip, then removed during the after-hook.

![Screen Shot 2020-10-01 at 1 51 40 PM](https://user-images.githubusercontent.com/586584/94845170-500b9180-03ed-11eb-868f-cd2adc917d1c.png)

Ticket Links
[vercel](https://automation-test-cases.vercel.app/test/MM-T134)
[TM4J](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T134)
This is a re-do of the [original](https://github.com/mattermost/mattermost-webapp/pull/6573) pr which had significant merge issues.

2020-10-02 10:33 UTC, saturninoabril requested changes
@MikeworX Overall looks good, except for last couple comments.

2020-10-02 13:10 UTC, saturninoabril approved these changes
@MikeworX Thanks and looks good to me. Left last comment but approving now.

2020-10-02 13:10 UTC, saturninoabril commented on e2e/cypress/integration/messaging/visual_verification_of_tooltips_on_top_nav,_channel_icons,_posts_spec.js
> +    after(() => {
Please separate with empty line for consistency.
```suggestion
    });

    after(() => {
```

2020-10-05 11:49 UTC, srkgupta requested changes
Hi @MikeworX 

Overall the test looks good and is working fine. Just one suggestion:

The file name of the cypress test currently contains `,` which looks a little odd. Can you please get rid of this and rename the file.

2020-10-05 14:03 UTC, srkgupta approved these changes
Thanks @MikeworX. LGTM

2020-10-05 14:04 UTC, srkgupta commented
/update-branch

2020-10-06 11:14 UTC, merged