[MM-28781] migrate string refs in channelView
mattermost/mattermost-webapp pull request #6607
Opened 2020-10-02 03:59 UTC by hardikmodi1

Summary
Migrate string refs in channelView

#### Ticket Link
JIRA - https://mattermost.atlassian.net/browse/MM-28781
ISSUE - https://github.com/mattermost/mattermost-server/issues/15517

2020-10-02 09:24 UTC, Willyfrog requested changes
thanks for contributing! Looking good, just a minor nit for consistency with other PRs

2020-10-02 09:24 UTC, Willyfrog commented on components/channel_view/channel_view.jsx
> +        this.channelView = React.createRef();
Could you rename it to 
```suggestion
        this.channelViewRef = React.createRef();
```

2020-10-02 09:24 UTC, Willyfrog commented
/update-branch

2020-10-05 14:21 UTC, Willyfrog reviewed
lgtm! thanks for contributing

2020-10-05 14:52 UTC, Willyfrog approved these changes

2020-10-06 07:58 UTC, sudheerDev approved these changes
LGTM

2020-10-06 18:07 UTC, jgilliam17 approved these changes
Thank you @hardikmodi1 
Tested, looks good to merge.
- Verified post creation - as expected.

2020-10-07 09:45 UTC, hanzei commented
/update-branch

2020-10-07 09:59 UTC, merged