Cypress/E2E: Automate backlogs - Messaging > Custom Emoji (9 test cases)
mattermost/mattermost-webapp pull request #6618
Opened 2020-10-02 23:19 UTC by catalintomai

#### Summary
Custom Emoji  tests.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28264

2020-10-08 12:25 UTC, saturninoabril requested changes
@catalintomai Thanks for these E2Es. Please see comments.

2020-10-08 12:25 UTC, saturninoabril commented on e2e/cypress/integration/emoji/custom_emoji_spec.js
> +            cy.get('#editPostEmoji').should('be.visible').click();
Step 4 is not via editing a post but reacting to a post -- "React again to that post by clicking emoji picker, typing the first three letters of the custom emoji name in search, and clicking the custom emoji". May open reaction to a post by,
```javascript
cy.clickPostReactionIcon(postId);
```
<img width="113" alt="Screen Shot 2020-10-08 at 8 02 33 PM" src="https://user-images.githubusercontent.com/5334504/95456020-452e9f00-09a1-11eb-9829-8d0c47331fd7.png">

2020-10-08 12:25 UTC, saturninoabril commented on e2e/cypress/integration/emoji/custom_emoji_spec.js
> +            cy.get('#editPostModal').should('be.visible');
Per test case [MM-T2187](https://automation-test-cases.vercel.app/test/MM-T2187), it should be done by post reaction and not by edit modal. Then, please verify if the last post has reaction.
<img width="89" alt="Screen Shot 2020-10-08 at 8 16 52 PM" src="https://user-images.githubusercontent.com/5334504/95457290-39dc7300-09a3-11eb-8e21-9cca2b3878ee.png">

2020-10-10 18:49 UTC, catalintomai commented on e2e/cypress/integration/emoji/custom_emoji_spec.js
> +            cy.fixture(largeEmojiFile).then((overrideImage) => {
added the resized version - still puzzled how did the tests pass before on my box.

2020-10-10 18:54 UTC, catalintomai commented on e2e/cypress/integration/emoji/custom_emoji_spec.js
> +        cy.postMessage(messageText);
@saturninoabril , yes, I find this test description a bit unclear: Step 3 mentions the reaction with an upper-case builtin emoji name (which does not work in the current codebase - should we open a bug for it?) While the expected result section only mentions "Emoji search is not case-sensitive" - while there is no step (other than 4 which deal with the custom emoji) that does emoji search. In here I've added code for the current behavior.

2020-10-12 07:30 UTC, saturninoabril commented on e2e/cypress/integration/emoji/custom_emoji_spec.js
> +        cy.postMessage(messageText);
Ticket filed - https://mattermost.atlassian.net/browse/MM-29543. For step 3, I thought the expectation was that it should successfully react to the last post but let's how does the ticket be resolved and we'll update the test case as need.

2020-10-12 07:33 UTC, saturninoabril approved these changes
@catalintomai Thanks for updating! LGTM, tested and passed.

2020-10-16 20:58 UTC, DHaussermann commented
/update-branch

2020-10-16 21:58 UTC, DHaussermann approved these changes
Tested and passed
- Tests created are consistent with JM4T test cases
- All tests run Green

LGTM!

2020-10-16 22:48 UTC, merged