[MM-20479] Migrate 'components/post_view/commented_on_files_message' module and associated tests to TypeScript
mattermost/mattermost-webapp pull request #6626
Opened 2020-10-04 20:45 UTC by jakubnovak998

#### Summary
- Rename the files to their associated TypeScript extensions (ie. js to ts, jsx to tsx)
- Update any components using those to the correct imports
- Fix any errors generated by the TypeScript compiler. You can run make check-types to display any errors.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/15462

2020-10-04 20:46 UTC, mattermod commented
Hello @jakubnovak998,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-04 22:57 UTC, jasonblais commented
Thanks @jakubnovak998 for the contribution! It looks like the automated tests are failing, would you be open to help take a look? If you have any questions, let us know, happy to help :)

2020-10-06 10:14 UTC, nevyangelova approved these changes

2020-10-06 10:16 UTC, nevyangelova commented
Thanks @jakubnovak998 thanks for the PR 🎉  LGTM minus the linter issues ;)

2020-10-12 09:24 UTC, sudheerDev requested changes

2020-10-12 09:24 UTC, sudheerDev commented on components/post_view/commented_on_files_message/commented_on_files_message.tsx
> +    fileInfos?: Array<any>
Can you check if `Array<FileInfo>` is appropriate?

2020-10-12 09:25 UTC, sudheerDev commented
@jakubnovak998 Thanks for the contribution, Can you also update the snapshots for tests?

2020-10-21 12:18 UTC, hanzei commented
Hey @jakubnovak998, I just wanted to check if you have any questions about the feedback above.

2020-10-31 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-02 01:14 UTC, jfrerich commented
Hi @jakubnovak998!  Thanks for your contribution!  Do you have any questions or need any help completing this PR?

2021-03-26 14:55 UTC, devinbinnie commented
Closing this PR as inactive, @jakubnovak998 let us know if you still plan on finishing this up.

2021-03-26 14:55 UTC, closed without merging