MM-29347: E2E Cypress Tests - System Console > Enterprise > Group Mentions (Part 1)
mattermost/mattermost-webapp pull request #6652
Opened 2020-10-06 13:13 UTC by srkgupta

#### Summary
MM-29347: E2E Cypress Tests - System Console > Enterprise > Group Mentions (Part 1)

#### Ticket Link
JIRA Ticket: 
[MM-29347](https://mattermost.atlassian.net/browse/MM-29347)

TM4J Tests:
[MM-T2456](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2456)
[MM-T2457](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2457)
[MM-T2458](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2458)
[MM-T2459](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2459)

#### Related Pull Requests
None

#### Screenshots
![Screenshot 2020-10-06 at 6 35 32 PM](https://user-images.githubusercontent.com/1429138/95205975-bcc6c780-0803-11eb-9b34-cb6f6b30025c.png)

2020-10-07 15:41 UTC, josephbaylon approved these changes
LGTM. All tests passed locally. Thanks @srkgupta !!

2020-10-07 15:52 UTC, josephbaylon requested changes

2020-10-07 15:52 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
> +import TIMEOUTS from '../../../fixtures/timeouts';
```suggestion
import * TIMEOUTS from '../../../fixtures/timeouts';
```

2020-10-07 16:13 UTC, josephbaylon requested changes
Please consider adding the timeouts after `cy.visit`. Cypress server runs usually fail on those.

2020-10-07 16:13 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
> +        cy.get('#board_group').then((el) => {
```suggestion
        cy.get('#board_group', {timeout: TIMEOUTS.ONE_MIN}).then((el) => {
```

2020-10-07 16:13 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
> +        cy.visit('/admin_console/user_management/permissions/system_scheme');
```suggestion
        cy.visit('/admin_console/user_management/permissions/system_scheme');
        cy.get('.admin-console__header', {timeout: TIMEOUTS.ONE_MIN}).should('be.visible').and('have.text', 'System Scheme');
```

2020-10-07 16:13 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
> +        cy.get('#group_users').scrollIntoView();
```suggestion
        cy.get('#group_users', {timeout: TIMEOUTS.ONE_MIN}).scrollIntoView();
```

2020-10-07 16:57 UTC, srkgupta commented
Thanks @josephbaylon. Addressed your comments and added additional timeouts after cy.visit. Please recheck.

2020-10-07 17:37 UTC, josephbaylon approved these changes
LGTM. Thanks @srkgupta !!

2020-10-08 14:09 UTC, saturninoabril requested changes
Thanks @srkgupta! Left couple of suggestions.

2020-10-08 14:09 UTC, saturninoabril commented on e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
> +        cy.apiAdminLogin();
This can be removed since up until here it's logged in as sysadmin.
```suggestion
```

2020-10-08 14:09 UTC, saturninoabril commented on e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
> +            cy.apiSaveUserPreference(preferences, user.id);
May use `cy.apiSaveTutorialStep(user.id, '999');`

2020-10-13 18:14 UTC, josephbaylon commented
/update-branch

2020-10-14 13:21 UTC, srkgupta commented
Thanks @saturninoabril for your feedback. Committed the requested changes. Please recheck. Thanks.

2020-10-14 13:23 UTC, saturninoabril approved these changes
@srkgupta Thanks for updating! LGTM, tested and passed.

2020-10-14 13:23 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-10-14 13:34 UTC, merged