Migrate refs of create_post component
mattermost/mattermost-webapp pull request #6653
Opened 2020-10-06 13:54 UTC by sridhar02

#### Summary

Migrates the refs of textbox in create_post.jsx to new syntax 

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/15796

2020-10-06 13:54 UTC, mattermod commented
Hello @sridhar02,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-07 10:16 UTC, Willyfrog requested changes
Thanks for contributing! it is looking good, but can we rename it for consistency?

2020-10-07 10:16 UTC, Willyfrog commented on components/create_post/create_post.jsx
> +        this.textbox = React.createRef();
can you rename it for consistency with other PRs
```suggestion
        this.textboxRef = React.createRef();
```

2020-10-07 10:52 UTC, nevyangelova approved these changes
Thanks! LGTM apart from @Willyfrog 's comment

2020-10-07 16:45 UTC, Willyfrog requested changes
there are other string references in this file, would you mind to migrate those too so we don't have to go over this same file again?
I can see: fileUpload, topDiv and createPostControls

2020-10-08 14:33 UTC, Willyfrog reviewed
Looking good, could you please remove the eslint disabling comment to prevent people from adding string refs in the future. it looks like:
```/* eslint-disable react/no-string-refs */```

2020-10-13 10:19 UTC, Willyfrog approved these changes
LGTM! thanks for your contribution!

2020-10-13 10:19 UTC, Willyfrog commented
/update-branch

2020-10-20 09:46 UTC, Willyfrog commented
/update-branch

2020-10-21 16:16 UTC, stevemudie approved these changes
LGTM

2020-10-21 18:47 UTC, merged