MM-20554 Migrate 'components/delete_post_modal' module and associated tests to TypeScript
mattermost/mattermost-webapp pull request #6656
Opened 2020-10-06 14:55 UTC by anchepiece

#### Summary
This pull request migrates 'components/delete_post_modal' to TypeScript.
All tests pass locally, suggestions on improvement welcome.

#### Ticket Link
Fixes mattermost/mattermost-server#13687
JIRA https://mattermost.atlassian.net/browse/MM-20554

2020-10-06 16:40 UTC, devinbinnie requested changes
Thanks @anchepiece! Just a few comments to resolve.

2020-10-06 16:40 UTC, devinbinnie commented on components/delete_post_modal/delete_post_modal.tsx
> +    deletePostBtn: React.RefObject<HTMLButtonElement> = React.createRef();
`React.createRef()` needs to happen in the constructor.

2020-10-06 16:40 UTC, devinbinnie commented on components/delete_post_modal/delete_post_modal.tsx
> +        let commentWarning : React.ReactNode | string = '';
`React.ReactNode` includes `string`, so you don't need to union this.

2020-10-06 16:40 UTC, devinbinnie commented on components/delete_post_modal/index.ts
> +
Nit: extra space

2020-10-06 19:08 UTC, devinbinnie approved these changes
LGTM! Thanks @anchepiece!

2020-10-08 15:31 UTC, hmhealey approved these changes
Thanks for helping with this migration. Looks good to me!

2020-10-13 07:23 UTC, hanzei commented
/update-branch

2020-10-13 21:46 UTC, stevemudie approved these changes
LGTM

2020-10-14 10:45 UTC, merged