[MM-29403] migrate string-refs in custom_theme_chooser
mattermost/mattermost-webapp pull request #6681
Opened 2020-10-07 14:04 UTC by filipghorbani

#### Summary

Replace this.refs to using React.createRef in custom_theme_chooser.jsx

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15842
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29403

#### Related Pull Requests

#5753

2020-10-07 14:04 UTC, mattermod commented
Hello @filipghorbani,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-07 16:37 UTC, Willyfrog requested changes
hi there! thanks for contributing
added a comment for naming consistency
also I didn't see the references being assigned to a dom object, you will have to do that in places like in https://github.com/mattermost/mattermost-webapp/blob/b012a3a9cdbc1ae0bc04c819156fbdbbb3c2b6fc/components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx#L336
take a look at the reference PR if you need.

2020-10-07 16:37 UTC, Willyfrog commented on components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
> +        this.textarea = React.createRef();
In order to have consistency with other PRs, can we rename the reference? Can you do the same with the other refs?
```suggestion
        this.textareaRef = React.createRef();
```

2020-10-08 14:22 UTC, sudheerDev approved these changes
LGTM, Thank you @filipghorbani

2020-10-08 14:22 UTC, sudheerDev commented
@filipghorbani Can you also remove `/* eslint-disable react/no-string-refs */` instances from the file

2020-10-19 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-10-19 08:46 UTC, Willyfrog commented
@filipghorbani sorry it took me a while to come back to your PR, looks good but it is now conflicting with another PR removing jquery. can you update this to fix the conflict?

2020-10-20 09:33 UTC, Willyfrog requested changes
Hi! it is conflicting with the jquery migration that is happening at the same time, could you update this PR so we don't loose the jquery change? (I added a comment previously but forgot to mark it as a change request)

2020-11-16 10:58 UTC, Willyfrog commented
@filipghorbani let me know if I can help you with the conflict somehow! I'm happy to help

2021-02-26 14:23 UTC, Willyfrog commented
closing for inactivity, feel free to ask to work on it again and thanks for the efforts :)

2021-02-26 14:23 UTC, closed without merging