Removed usage of this.refs.errorMessage (Migrate string-refs to functional ones)
mattermost/mattermost-webapp pull request #6684
Opened 2020-10-07 14:45 UTC by Raj-Datta-Manohar

Fixes https://github.com/mattermost/mattermost-server/issues/15849

2020-10-07 14:45 UTC, mattermod commented
Hello @Raj-Datta-Manohar,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-07 16:26 UTC, Willyfrog requested changes
looking good, added a request for consistency

2020-10-07 16:26 UTC, Willyfrog commented on components/admin_console/schema_admin_settings.jsx
> +        this.errorMessage = React.createRef();
for consistency with the rest of PRs can we rename this to:
```suggestion
        this.errorMessageRef = React.createRef();
```

2020-10-08 12:30 UTC, Willyfrog reviewed
looking good! I just noticed I forgot to mention to remove the comment that disables the eslint rule, can you remove it? is in line 3 and looks like:
```/* eslint-disable react/no-string-refs */```

2020-10-08 14:09 UTC, sudheerDev commented
@Raj-Datta-Manohar Can you update the snapshots for tests?

2020-10-12 09:26 UTC, sudheerDev approved these changes
Thank you @Raj-Datta-Manohar 🎉

2020-10-13 09:48 UTC, Willyfrog approved these changes
LGTM! thanks for helping with this issue!

2020-10-21 14:42 UTC, stevemudie approved these changes
LGTM

2020-10-21 18:46 UTC, hanzei commented
/update-branch

2020-10-21 18:59 UTC, merged

2020-10-21 19:01 UTC, hanzei commented
Thanks for helping us with improving the code quality :+1: