Migrate string-refs
mattermost/mattermost-webapp pull request #6685
Opened 2020-10-07 15:14 UTC by Raj-Datta-Manohar

Removed usage of this.refs.customcheck and this.refs.custommentions  

Fixes https://github.com/mattermost/mattermost-server/issues/15844

2020-10-07 15:14 UTC, mattermod commented
Hello @Raj-Datta-Manohar,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-07 17:32 UTC, hahmadia requested changes
Thanks for contribution! Code looks good for most part but we follow camelCase naming convention so that's all that needs changed. Thanks! Once change, let me know and I will approve the PR. 👍

2020-10-07 17:32 UTC, hahmadia commented on components/user_settings/notifications/user_settings_notifications.jsx
> +        this.customcheck = React.createRef();
```suggestion
        this.customCheck = React.createRef();
```

2020-10-07 17:32 UTC, hahmadia commented on components/user_settings/notifications/user_settings_notifications.jsx
> +        this.custommentions = React.createRef();
```suggestion
        this.customMentions = React.createRef();
```

2020-10-07 19:22 UTC, hahmadia approved these changes
LGTM!

2020-10-08 12:19 UTC, Willyfrog requested changes
Hi! thanks for contributing!
I left a comment for consistency regarding this kind of PRs
Could you also remove the comment for disabling the slint rule in https://github.com/mattermost/mattermost-webapp/pull/6685/files#diff-26695f8c40a0d3beab0e24d9ab748a22R3

2020-10-08 12:19 UTC, Willyfrog commented on components/user_settings/notifications/user_settings_notifications.jsx
> +        this.customMentions = React.createRef();
in order to be consistent with the rest of PRs, could you rename the references?
```suggestion
        this.customCheckRef = React.createRef();
        this.customMentionsRef = React.createRef();
```

2020-10-08 12:21 UTC, Willyfrog commented
fixes https://github.com/mattermost/mattermost-server/issues/15844

2020-10-08 13:48 UTC, Willyfrog commented
> Hi! thanks for contributing!
> I left a comment for consistency regarding this kind of PRs
> Could you also remove the comment for disabling the slint rule in https://github.com/mattermost/mattermost-webapp/pull/6685/files#diff-26695f8c40a0d3beab0e24d9ab748a22R3

could you do this too? so it prevents people from using string-refs in the future

2020-10-08 14:29 UTC, Willyfrog requested changes
seems we missed a couple of refs and for that the tests are failing.
see
https://github.com/mattermost/mattermost-webapp/blob/d69380ad78872b64487a4dc429cf7c10bca53acd/components/user_settings/notifications/user_settings_notifications.jsx#L891
https://github.com/mattermost/mattermost-webapp/blob/d69380ad78872b64487a4dc429cf7c10bca53acd/components/user_settings/notifications/user_settings_notifications.jsx#L914

2020-10-08 14:32 UTC, Raj-Datta-Manohar commented
Thanks @Willyfrog !

2020-10-09 15:24 UTC, hmhealey commented
Removing myself for reviews since we've got two dev reviewers already.

2020-10-13 10:15 UTC, Willyfrog commented
/update-branch

2020-10-13 10:16 UTC, Willyfrog reviewed
LGTM! thanks for contributing :)

2020-10-13 10:16 UTC, Willyfrog approved these changes

2020-10-20 14:05 UTC, hahmadia commented
/update-branch

2020-10-20 14:34 UTC, jgilliam17 commented
Thank you @Raj-Datta-Manohar 
I am not seeing `Automatic Direct Message Replies` section in Account Settings>Notifications 
Can you please take a look? Thanks.
<img width="1141" alt="Screen Shot 2020-10-20 at 10 29 40 AM" src="https://user-images.githubusercontent.com/52937121/96601161-bfbfbe80-12bf-11eb-9ab1-c797ee7b07d9.png">

2020-10-21 13:56 UTC, jgilliam17 commented
@Raj-Datta-Manohar - Ah, I didn't check the System Console setting for Auto replies, it was off 😞
Sorry about that!

Tested, looks good to merge.
- Verified notifications, words that trigger mentions, custom notifications etc. - as expected.
@Willyfrog can you please help merge? Thanks.

2020-10-21 14:00 UTC, merged

2020-10-21 17:30 UTC, Raj-Datta-Manohar commented
@jgilliam17 , wasn't online, glad that it's figured out