migrate post and corresponding components to ts
mattermost/mattermost-webapp pull request #6719
Opened 2020-10-09 18:19 UTC by dudupopkhadze

#### Summary
Migrated  components/post_view/post/ index.js and post.jsx to typescript
also migrated corresponding test

Some notable points:

- Had to use `Any` type here, because could not infer  type from component created with  `injectIntl`

- Modified following compoonents because props that are passed with redux-connect function were marked as Proptype.isRequired and because of this  typescript compiler was throwing errors  

1.  components/post_view/post_body/post_body.jsx
2. components/post_view/post_header/post_header.jsx
3. components/post_profile_picture/post_profile_picture.jsx

All tests passing - No ts errors

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/15464
JIRA:  https://mattermost.atlassian.net/browse/MM-20477

2020-10-09 18:19 UTC, mattermod commented
Hello @dudupopkhadze,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-19 15:16 UTC, mkraft approved these changes

2020-10-21 01:31 UTC, mickmister requested changes
Awesome work @dudupopkhadze :+1: Just a few requests and questions

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/index.ts
> +    const getReplyCount = makeGetReplyCount() as ((sate: GlobalState, post: Post) => number);
```suggestion
    const getReplyCount = makeGetReplyCount() as ((state: GlobalState, post: Post) => number);
```

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/index.ts
> +    const createAriaLabelForPost = makeCreateAriaLabelForPost() as ((sate: GlobalState, post: Post) => (...args: any[]) => any);
```suggestion
    const createAriaLabelForPost = makeCreateAriaLabelForPost() as ((state: GlobalState, post: Post) => (...args: any[]) => any);
```

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> +    replyCount: number,
This prop went from optional to required. Is this intentional?

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> +    togglePostMenu: (value: boolean) => void,
This prop also went from optional to required

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> +    channelIsArchived?: boolean,
This prop went from required to optional. Is this intentional?

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> -    };
Why do we not need the `defaultProps` anymore?

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> +        // e.preventDefault();
Can we remove this commented out code if it's unnecessary?

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> +        if (this.props.channelIsArchived) {
Why did the conditional logic here change to not include `post.system_post_ids`?

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> +        if (this.state.alt && !(this.props.channelIsArchived)) {
Same question here about `post.system_post_ids`

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> +                    post={post}
Can we move `post` back above `userId` to minimize the diff?

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post/post.tsx
> +            <PostContext.Provider value={{handlePopupOpened: this.handleDropdownOpened} as any}>
Do we have to use `as any` here?

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post_body/post_body.jsx
> +        enablePostUsernameOverride: PropTypes.bool,
Why is this no longer required?

2020-10-21 01:31 UTC, mickmister commented on components/post_view/post_header/post_header.jsx
> +        isGuest: PropTypes.bool,
Why are these no longer required?

2020-10-31 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-02 01:29 UTC, jfrerich commented
Hi, @dudupopkhadze! Could you please fix the conflicting files and address the suggestions from @mickmister?  Thanks for your contribution!

2020-11-02 07:07 UTC, closed without merging