MM 27448 remove jquery from root
mattermost/mattermost-webapp pull request #6730
Opened 2020-10-10 18:25 UTC by CEOehis

#### Summary

This PR removes the usage of jQuery from the following files in the web app:

components/logged_in/logged_in.jsx
components/root/root.jsx
components/tutorial/tutorial_view.jsx
#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-27448

2020-10-10 18:25 UTC, mattermod commented
Hello @CEOehis,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-12 08:04 UTC, hanzei commented
Awesome, great to see more removal of jquery. Heads up that one test is failing with:
```
Summary of all failing tests
 FAIL  components/logged_in/logged_in.test.jsx
  ● components/logged_in/LoggedIn › should render loading state without user

    TypeError: Cannot read property 'setAttribute' of null

      83 | 
      84 |         if (!this.props.currentUser) {
    > 85 |             document.getElementById('root').setAttribute('class', '');
         |             ^
      86 |             GlobalActions.emitUserLoggedOutEvent('/login?redirect_to=' + encodeURIComponent(this.props.location.pathname), true, false);
      87 |         }
      88 | 

      at LoggedIn.componentDidMount (components/logged_in/logged_in.jsx:85:13)
      at fn (node_modules/enzyme/src/ShallowWrapper.js:429:22)
      at Object.batchedUpdates (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:771:16)
      at new ShallowWrapper (node_modules/enzyme/src/ShallowWrapper.js:428:26)
      at shallow (node_modules/enzyme/src/shallow.js:10:10)
      at Object.it (components/logged_in/logged_in.test.jsx:38:25)
```

2020-10-15 15:02 UTC, hmhealey requested changes

2020-10-18 17:08 UTC, nickmisasi approved these changes
Sorry for the delay. Everything looks good to me! Thanks @CEOehis!

2020-10-20 20:16 UTC, hmhealey commented
/update-branch

2020-10-21 15:13 UTC, josephbaylon requested changes
@CEOehis Thanks for your contribution!! Just a couple of minor request changes on the E2E.

2020-10-21 15:13 UTC, josephbaylon commented on e2e/cypress/integration/keyboard_shortcuts/backspace_spec.js
> +        cy.get('#post_textbox').clear().type('This is a normal sentence.').type('{backspace}{backspace}').blur();
Please add a verification that the last 2 characters of the message have been removed.

2020-10-21 15:18 UTC, josephbaylon commented on e2e/cypress/integration/keyboard_shortcuts/backspace_spec.js
> +        cy.get('#post_textbox').clear().type('This is a normal sentence.').type('{backspace}{backspace}').blur();
Also after the focus has been removed from post input, add another verification that no further truncation happened to the message in the input.

2020-10-21 19:04 UTC, josephbaylon approved these changes
LGTM. Test passed locally. Thanks @CEOehis !!

2020-10-22 09:32 UTC, merged

2020-10-22 09:33 UTC, hanzei commented
Thanks for the awesome contribution @CEOehis :+1: