[GH-15885] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 613
mattermost/mattermost-webapp pull request #6736
Opened 2020-10-11 10:59 UTC by tony-ho

#### Summary

Remove changeCss() for `.nav-pills__unread-indicator svg`.
This is no longer required as CSS variable `--mention-color` is already used.

https://github.com/mattermost/mattermost-webapp/blob/c3f01ee92ca30d6bedf62aa93b6e117efd37f9a4/sass/layout/_sidebar-left.scss#L421

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15885

2020-10-11 10:59 UTC, mattermod commented
Hello @tony-ho,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-12 20:18 UTC, calebroseland commented
Thanks for this, @tony-ho! You're right that its already in `_sidebar-left.scss`, but would you also mind adding it to `_legacy-sidebar-left.scss`? If you disable the new sidebar (Account Settings > Sidebar), it won't color the icon properly 
<img width="185" alt="Screen Shot 2020-10-12 at 15 16 55" src="https://user-images.githubusercontent.com/11724372/95786883-0b5de100-0c9e-11eb-8444-3eeb47277735.png">

2020-10-12 20:18 UTC, calebroseland requested changes
Thanks for this, @tony-ho! You're right that its already in `_sidebar-left.scss`, but would you also mind adding it to `_legacy-sidebar-left.scss`? If you disable the new sidebar (Account Settings > Sidebar), it won't color the icon properly 
<img width="185" alt="Screen Shot 2020-10-12 at 15 16 55" src="https://user-images.githubusercontent.com/11724372/95786883-0b5de100-0c9e-11eb-8444-3eeb47277735.png">

2020-10-13 04:37 UTC, tony-ho commented
Thanks @calebroseland, good pickup. I've added the `fill` property in `_sidebar-left.scss`.

2020-10-14 00:58 UTC, deanwhillier commented
QA for this PR will be done when the campaign branch is merged to master.

2020-10-15 17:55 UTC, hmhealey approved these changes
Thanks for helping with this! I'm looking forward to when we can get rid of the old sidebar so that we won't need to repeat these styles between both of them

2020-10-15 17:55 UTC, merged