[MM-20502] Migrate 'components/post_view/date_separator' module and a…
mattermost/mattermost-webapp pull request #6746
Opened 2020-10-12 18:45 UTC by cinlloc

…ssociated tests to TypeScript

#### Summary
Migrate 'components/post_view/date_separator' module and associated tests to TypeScript. 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15439

#### Note
Was already migrated to Typescript except index. Just renamed one file.

2020-10-12 18:45 UTC, mattermod commented
Hello @cinlloc,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-13 14:30 UTC, hanzei requested changes
The changes in `package-lock.json` seem unrelated. Can you remove them please?

2020-10-14 11:06 UTC, hanzei approved these changes

2020-10-15 01:37 UTC, gabrieljackson approved these changes

2020-10-15 18:04 UTC, stevemudie approved these changes
LGTM

2020-10-16 10:56 UTC, merged

2020-10-16 10:56 UTC, hanzei commented
Thank you very much for helping Mattermost with migrating to Typescript.