MM-27229 - Cypress/E2E: Automate backlogs - BOT Accounts - Part 06 (10 test cases)
mattermost/mattermost-webapp pull request #6772
Opened 2020-10-14 08:29 UTC by reflog

#### Summary
automated:
MM-T1861
MM-T1862
MM-T1863
MM-T1864
MM-T1865
MM-T1866
MM-T1867
MM-T1868
MM-T1869
MM-T1870

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-27229
#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

2020-10-21 20:22 UTC, calebroseland reviewed
There are some errors on local execution of `managing_bot_accounts_spec.js`. Is `cypress/fixtures/com.github.matterpoll.matterpoll.tar.gz` missing?

2020-10-22 06:15 UTC, reflog commented
@calebroseland - this and some other tests require downloading files . see `poll_spec.js` line 10

2020-10-23 15:19 UTC, calebroseland approved these changes

2020-10-28 10:22 UTC, reflog commented
/update-branch

2020-11-05 22:24 UTC, prapti commented
/update-branch

2020-11-06 01:54 UTC, prapti approved these changes
Test passed in subsequent runs (might need to look into this again but they're passing now).
Steps and changes look good to me!
Approving.

2020-11-06 01:55 UTC, prapti commented
/update-branch

2020-11-06 03:24 UTC, prapti requested changes
Actually, after running the tests again because they were failing intermittently, it looks like adding the timeout will take care of those failures.

2020-11-06 03:24 UTC, prapti commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +                    cy.get(`#postMessageText_${post1.id}`).should('contain', msg1);
```suggestion
                    cy.get(`#postMessageText_${post1.id}`, {timeout: TIMEOUTS.ONE_MIN}).should('contain', msg1);
```

2020-11-06 03:24 UTC, prapti commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +                    cy.get(`#postMessageText_${post2.id}`).should('contain', msg2);
```suggestion
                    cy.get(`#postMessageText_${post2.id}`, {timeout: TIMEOUTS.ONE_MIN}).should('contain', msg2);
```

2020-11-06 03:24 UTC, prapti commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +                cy.get(`#postMessageText_${postId}`).should('contain', msg1);
```suggestion
                cy.get(`#postMessageText_${postId}`, {timeout: TIMEOUTS.ONE_MIN}).should('contain', msg1);
```

2020-11-06 03:24 UTC, prapti commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +                cy.get(`#postMessageText_${postId}`).find('.mention--highlight').should('be.visible');
```suggestion
                cy.get(`#postMessageText_${postId}`, {timeout: TIMEOUTS.ONE_MIN}).find('.mention--highlight').should('be.visible');
```

2020-11-06 03:24 UTC, prapti commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +                    cy.get(`#postMessageText_${postId}`).should('contain', msg1);
```suggestion
                    cy.get(`#postMessageText_${postId}`, {timeout: TIMEOUTS.ONE_MIN}).should('contain', msg1);
```

2020-11-06 08:45 UTC, reflog commented
thanks @prapti !

2020-11-06 22:05 UTC, prapti approved these changes
Thanks Eli! LGTM!

2020-11-06 22:09 UTC, prapti commented
Took a quick look at why lint is complaining here and looks like the following may need to be addressed as well:
`/root/mattermost/mattermost-webapp/e2e/cypress/integration/bot_accounts/managing_bot_accounts_spec.js
  287:10  error  'createCustomAdmin' is defined but never used  no-unused-vars
  288:26  error  'generateRandomUser' is not defined            no-undef`

2020-11-15 22:01 UTC, DHaussermann approved these changes
Tested and passed
- All tests return green after deploying the latest version
- Ensured that TM4J tests are accurately captured by these Cy tests
- No issues found 
LGTM!

All corresponding TM4J task have Cy status correctly set to `update`.

2020-11-16 07:19 UTC, merged