MM-T569 Integrations Page resize and check links
mattermost/mattermost-webapp pull request #6776
Opened 2020-10-14 15:31 UTC by MikeworX

**_Summary_**

This PR validates that the integration's page sidebar and icon links are visible and continue to function when the browser window is shrunk down to a smaller size (500 x 500) from the default (1300 x 600).

Each element is confirmed to be visible and working, starting with the left side-bar, then moving to the main links.

<img width="413" alt="Screen Shot 2020-10-14 at 11 30 34 AM" src="https://user-images.githubusercontent.com/586584/96011262-b1315d00-0e10-11eb-8ac2-cd63ac94951d.png">

**_Links_**

[vercel](https://automation-test-cases.vercel.app/test/MM-T569)
[TM4J](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T569)

2020-10-16 12:51 UTC, saturninoabril requested changes
Thanks @MikeworX. LGTM, except for a couple of suggestions.

2020-10-16 12:51 UTC, saturninoabril commented on e2e/cypress/integration/integrations/integrations_page_spec.js
> +        // # Login, create incoming webhook for Team A
This seems to be not accurate. How about?
```suggestion
        // # Setup with the new team
```

2020-10-16 12:51 UTC, saturninoabril commented on e2e/cypress/integration/integrations/integrations_page_spec.js
> +        // * Bot Accounbts link is visible and works
```suggestion
        // * Bot Accounts link is visible and works
```

2020-10-16 13:55 UTC, saturninoabril approved these changes
Thanks @MikeworX! LGTM.

2020-10-17 00:05 UTC, prapti approved these changes
Looks great!

2020-10-17 00:05 UTC, merged