MM-T612 Regenerate token
mattermost/mattermost-webapp pull request #6808
Opened 2020-10-15 20:39 UTC by MikeworX

**_Summary_**

This PR validates that the out-going web-hook's token is indeed regenerated/changed when the user clicks the Regenerate Token link on the Outgoing Webhook's integrations page. This test:

- creates a test team, channel, user, 
- creates an outgoing webhook integration with a trigger word
- isolates the token and stores in a variable
- posts the trigger word to force a bot message from the integration that contains the token value
- validates that the token value is present 
- returns to the integrations page and regenerates the token, also storing it in a variable
- posts the trigger word again, and validating that the second token appears in the message, not the first token

Note: this test requires the webhook server to be running (`npm run start:webhook`)

![Screen Shot 2020-10-15 at 4 39 05 PM](https://user-images.githubusercontent.com/586584/96183520-fa62d900-0f04-11eb-94ea-2f0dff1202a0.png)

**_Links_**

[vercel](https://automation-test-cases.vercel.app/test/MM-T612)
[TM4J](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T612)

2020-10-15 20:39 UTC, mattermod commented
Hello @MikeworX,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-16 13:28 UTC, saturninoabril requested changes
Thanks @MikeworX! LGTM, except for few requests.

2020-10-16 13:28 UTC, saturninoabril commented on e2e/webhook_serve.js
> + * @route "POST /post_outgoing_webhook?override_username=={username}&override_icon_url={iconUrl}&response_type={comment}"
```suggestion
 * @route "POST /post_outgoing_webhook?override_username={username}&override_icon_url={iconUrl}&response_type={comment}"
```

2020-10-16 13:28 UTC, saturninoabril commented on e2e/webhook_serve.js
> + * @query override_icon_url= the user icon url that overrides the user icon url defined by the outgoing webhook
```suggestion
 * @query override_icon_url - the user icon url that overrides the user icon url defined by the outgoing webhook
```

2020-10-16 13:28 UTC, saturninoabril commented on e2e/webhook_serve.js
> + * @query response_type= -
```suggestion
 * @query response_type - "in_channel" (default) or "comment"
```

2020-10-19 15:10 UTC, josephbaylon commented
/update-branch

2020-10-19 15:10 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2020-10-19 15:10 UTC, josephbaylon commented
@MikeworX Please fix conflicts. Thanks

2020-10-19 15:14 UTC, MikeworX commented
@josephbaylon Thanks! I was just consulting Saturn to insure I completed it correctly.

2020-10-19 15:58 UTC, saturninoabril approved these changes
Thanks @MikeworX! LGTM.

2020-10-19 20:36 UTC, josephbaylon approved these changes
LGTM. Test passed. Thanks @MikeworX !!

2020-10-19 20:36 UTC, merged