Migrate changeCSS() use of sidebarBg to CSS variable in utils/utils.jsx
mattermost/mattermost-webapp pull request #6809
Opened 2020-10-16 00:35 UTC by ng29

Migrate changeCSS() to CSS variable: --sidebar-bg

#### Summary

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

2020-10-16 00:35 UTC, mattermod commented
Hello @ng29,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-10-16 00:52 UTC, ng29 commented
/check-cla

2020-10-16 10:10 UTC, asaadmahmood requested changes
Thanks for the contribution @ng29.
One thing, the rule applied in the css file is on the 480px media query, whereas it was 768 in utils file.

Plus the rules are a bit more elaborate excluding specific classes as well.

2020-10-16 13:50 UTC, ng29 commented
> Thanks for the contribution @ng29.
> One thing, the rule applied in the css file is on the 480px media query, whereas it was 768 in utils file.
> 
> Plus the rules are a bit more elaborate excluding specific classes as well.

Hey @asaadmahmood 

Could you relate it more specifically as i just started CSS and unable to find 480px in the mobile.scss file ??

2020-10-16 15:56 UTC, asaadmahmood commented
@ng29 The css you've included in inside: `@media screen and (max-width: 480px) {` tag.
And since the media query used in the utils file pointed to 768px, we should add this rule inside the `@media screen and (max-width: 768px) {` wrapper.

2020-10-16 16:03 UTC, ng29 commented
> @ng29 The css you've included in inside: `@media screen and (max-width: 480px) {` tag.
> And since the media query used in the utils file pointed to 768px, we should add this rule inside the `@media screen and (max-width: 768px) {` wrapper.

Ahh,  mah bad @asaadmahmood now i get the correct position and just cross checking that it should be implemented in line 409 block, correct me if i am wrong? 

and one more doubt that there is not such hierarchy as i implemented previously from util

2020-10-16 16:35 UTC, asaadmahmood commented
@ng29 You should push a commit, and define that same hierarchy in the css file if its not already available in the 768px rule.

2020-10-16 21:05 UTC, ng29 commented
> @ng29 You should push a commit, and define that same hierarchy in the css file if its not already available in the 768px rule.

Thanks for the info @asaadmahmood , i have made the changes as per my understanding in the 768px rule. 

Kindly review and merge if no changes are required.

2020-10-18 07:41 UTC, asaadmahmood requested changes
Based on the code in the utils file.
I think the code should be:

```
        .modal {
            .settings-modal {
                &:not(.settings-modal--tables) {
                    &:not(.display--content) {
                        .modal-content {

                        }
                    }
                }
            }
        }
```

2020-10-18 10:44 UTC, ng29 commented
> Based on the code in the utils file.
> I think the code should be:
> 
> ```
>         .modal {
>             .settings-modal {
>                 &:not(.settings-modal--tables) {
>                     &:not(.display--content) {
>                         .modal-content {
> 
>                         }
>                     }
>                 }
>             }
>         }
> ```

Got it @asaadmahmood , thanks for correcting. I have made the requested changes kindly review again 👍

2020-10-18 10:47 UTC, asaadmahmood approved these changes
Looks good, but I think there's an extra bracket. Just verify.

2020-10-18 10:51 UTC, ng29 commented
> Looks good, but I think there's an extra bracket. Just verify.

I reckon thats closure of app body, so no extra ones

2020-10-18 10:52 UTC, asaadmahmood approved these changes

2020-10-21 07:56 UTC, sudheerDev approved these changes
LGTM @ng29 Thank you

2020-10-21 07:57 UTC, merged