MM-29686: Migrate changeCSS() to CSS variable in utils/utils.jsx, ln.…
mattermost/mattermost-webapp pull request #6810
Opened 2020-10-16 04:30 UTC by seongwon-kang

… 673

#### Summary

Adds `bg-text-200` class near `.more-modal__gm-icon` (all elements uses `bg-text-200` uses `.more-modal__gm-icon`, and replaces `utils/utils.jsx` to use `--center-channel-color` CSS variables.

#### Ticket Link

Github Issue: https://github.com/mattermost/mattermost-server/issues/15961
JIRA Ticket: https://mattermost.atlassian.net/browse/MM-29686

2020-10-16 04:30 UTC, mattermod commented
Hello @seongwon-kang,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-10-16 04:32 UTC, seongwon-kang commented
/check-cla

2020-10-16 04:39 UTC, seongwon-kang commented
/check-cla

2020-10-16 10:11 UTC, asaadmahmood requested changes
You should use the `center-channel-color-rgb` variable.

2020-10-18 07:42 UTC, asaadmahmood approved these changes

2020-10-21 07:57 UTC, sudheerDev approved these changes
@seongwon-kang Thank you!

2020-10-21 07:57 UTC, merged