[MM-29688] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 675
mattermost/mattermost-webapp pull request #6814
Opened 2020-10-16 06:09 UTC by seongwon-kang

#### Summary

Fixes #15963, MM-29688

Fixed  `.app__body .svg-text-color` class to use CSS variables.
It is generally used with channel-icon , so css was added in _channel-icon.scss.

#### Ticket Link
Github Issue: #15963
JIRA Ticket: MM-29688

2020-10-16 06:09 UTC, mattermod commented
Hello @seongwon-kang,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-16 10:13 UTC, asaadmahmood requested changes
This should only be applied on svgs inside `.app__body`.

2020-10-18 07:41 UTC, asaadmahmood approved these changes

2020-10-21 07:58 UTC, sudheerDev approved these changes

2020-10-21 07:58 UTC, merged