MM-20524: Migrate 'components/rename_channel_modal' module to TypeScript
mattermost/mattermost-webapp pull request #6822
Opened 2020-10-16 20:51 UTC by mathiasvr

#### Summary

Migrate `components/rename_channel_moda` module and associated tests to TypeScript.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13716
https://mattermost.atlassian.net/browse/MM-20524

-------

Hello there!

I have been unable to figure out how to pass type checking without explicitly specifying the `intl` attribute on the `RenameChannelModal` element in the tests when using the `shallowWithIntl` function.

I assume I'm supposed to do this since e.g. [sidebar_direct_channel.test.tsx](https://github.com/mattermost/mattermost-webapp/blob/master/components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx) is able to use `shallowWithIntl` without explicitly specifying the `intl` attribute.

I hope someone might be able to help, thanks!

2020-10-16 20:51 UTC, mattermod commented
Hello @mathiasvr,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-19 09:58 UTC, Willyfrog approved these changes
LGTM

2020-10-19 17:27 UTC, devinbinnie requested changes
Looks good overall, just a couple comments.
Thanks for the contribution @mathiasvr!

2020-10-19 17:27 UTC, devinbinnie commented on components/rename_channel_modal/rename_channel_modal.test.tsx
> +    const channel: Channel = {
For future reference, we have a full `Channel` object mocked out in `utils/test_helper` if you wanted to use that.

2020-10-19 17:27 UTC, devinbinnie commented on components/rename_channel_modal/rename_channel_modal.test.tsx
> +    const team: Team = {
Same with `Team`.

2020-10-19 17:27 UTC, devinbinnie commented on components/rename_channel_modal/rename_channel_modal.tsx
> -        /**
Can we keep these comments when transferring from `PropTypes` over to the type?

2020-10-19 17:27 UTC, devinbinnie commented on components/rename_channel_modal/rename_channel_modal.tsx
> +    displayNameError: JSX.Element | string;
There's a React provided type called `React.ReactNode` that includes both these types and any others that you can render to the DOM.

2020-10-19 20:34 UTC, mathiasvr commented
Thanks @Willyfrog and @devinbinnie.
I have addressed the comments, let me know if more changes are needed! 👍

2020-10-19 20:35 UTC, devinbinnie approved these changes
Looking good now, thanks @mathiasvr!

2020-10-21 13:35 UTC, saturninoabril commented
/update-branch

2020-10-21 13:36 UTC, saturninoabril commented
@mathiasvr LGTM, tested and passed. Thank you for your contribution!

2020-10-21 13:36 UTC, saturninoabril approved these changes

2020-10-21 13:36 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-10-21 13:54 UTC, mattermod commented
Trying to auto merge this PR.

2020-10-21 13:54 UTC, merged

2020-10-21 13:54 UTC, mattermod commented
Pull Request successfully merged
SHA: 14a048ee6eda91f93c950d690a69c7c29b73b28c