Migrate post view module to typescript
mattermost/mattermost-webapp pull request #6830
Opened 2020-10-19 03:35 UTC by sridhar02

#### Summary

Conver all files related to post view to typescript

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/15445

2020-10-19 03:35 UTC, mattermod commented
Hello @sridhar02,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-19 10:31 UTC, jespino commented on components/post_view/post_view.test.tsx
> +import PostView from './post_view.js';
I think this should be just `'./post_view;'`

2020-10-19 10:32 UTC, jespino requested changes
I tiny change needed, but otherwise, looks good to me.

2020-11-02 18:18 UTC, lieut-data approved these changes
Looks good, just a few formatting questions.

2020-11-02 18:18 UTC, lieut-data commented on components/post_view/index.ts
> +type State ={
nit: Is there a missing space after `=` here?

2020-11-02 18:18 UTC, lieut-data commented on components/post_view/index.ts
> +export const isChannelLoading = (params: Params, channel: Channel, team: Team, teammate: UserProfile, teamMemberships:TeamMembership) => {
nit: Is there a missing space after `teamMemberships:` here?

2020-11-02 18:18 UTC, lieut-data commented on components/post_view/post_view.tsx
> +type State ={
nit: Is there a missing space after `=` here?

2020-11-02 18:18 UTC, lieut-data commented on components/post_view/post_view.tsx
> +        this.setState(
Are the whitespace changes here required? Subjectively, the previous formatting seemed more familiar within this codebase.

2020-11-17 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-18 20:49 UTC, jfrerich commented
@sridhar02, can you address the PR provided feedback? Also, there is a failing build. You can find these failures [here](https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/29557/workflows/54b7c33e-4b1a-4e23-81ca-a47a4716c125/jobs/195534) or on the `Details` link next to the failing checks.  Those will need to be passing with a green check before we can merge.  Thanks!

2020-11-23 16:40 UTC, sridhar02 commented
@jfrerich I was busy with some other work I will update the PR in few days.

2021-02-26 18:12 UTC, devinbinnie commented
@sridhar02 Are you still planning on finishing up this PR?

2021-03-03 16:19 UTC, sridhar02 commented
@devinbinnie not getting enough time on this I am unassigning myself from the issue.

2021-03-03 16:32 UTC, devinbinnie commented
Closing this PR and re-opening the issue.

2021-03-03 16:32 UTC, closed without merging