Add e2e test for /join command
mattermost/mattermost-webapp pull request #6831
Opened 2020-10-19 07:18 UTC by seongwon-kang

#### Summary

Adds test case for `/join` command:
* Privileged user try to `/join` to private channel with channel name
* Privileged user try to `/join` to private channel with tilde(~) + channel name

* Unprivileged user try to `/join` to private channel with channel name
* Unprivileged user try to `/join` to private channel with tilde(~) + channel name

#### Ticket Link
Github Issue: Resolves https://github.com/mattermost/mattermost-server/issues/15698
JIRA Ticket: MM-T662

2020-10-19 07:18 UTC, mattermod commented
Hello @seongwon-kang,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-20 07:33 UTC, larkox approved these changes
LGTM. Thanks!

2020-10-20 18:41 UTC, saturninoabril requested changes
Thanks @seongwon-kang and welcome! Looks good to me except for minor suggestions.

2020-10-20 18:41 UTC, saturninoabril commented on e2e/cypress/integration/integrations/slash_commands_spec.js
> +        const privateChannelName = user1.username;
nit: Please use name other than the username. Could be,
```suggestion
        const privateChannelName = 'private-channel';
```

2020-10-20 18:41 UTC, saturninoabril commented on e2e/cypress/integration/integrations/slash_commands_spec.js
> +        // # User with privilege try join command without tilde
```suggestion
        // # User with privilege try /join command without tilde
```

2020-10-20 18:41 UTC, saturninoabril commented on e2e/cypress/integration/integrations/slash_commands_spec.js
> +        // * private channel should be active
nit: Please capitalize comment
```suggestion
        // * Private channel should be active
```

2020-10-20 18:41 UTC, saturninoabril commented on e2e/cypress/integration/integrations/slash_commands_spec.js
> +        // # User with privilege try join command with tilde
```suggestion
        // # User with privilege try /join command with tilde
```

2020-10-20 18:41 UTC, saturninoabril commented on e2e/cypress/integration/integrations/slash_commands_spec.js
> +        // # User without privilege try join command without tilde
```suggestion
        // # User without privilege try /join command without tilde
```

2020-10-20 18:41 UTC, saturninoabril commented on e2e/cypress/integration/integrations/slash_commands_spec.js
> +        // # User without privilege try join command with tilde
```suggestion
        // # User without privilege try /join command with tilde
```

2020-10-21 00:27 UTC, seongwon-kang commented on e2e/cypress/integration/integrations/slash_commands_spec.js
> +        // # User without privilege try join command with tilde
Thanks for review, @saturninoabril!

2020-10-21 01:24 UTC, seongwon-kang commented
Thanks for review @saturninoabril!

2020-10-21 01:30 UTC, saturninoabril approved these changes
Thanks @seongwon-kang! Looks good to me.

2020-11-02 09:53 UTC, saturninoabril commented
/update-branch

2020-11-02 09:54 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-11-02 10:07 UTC, mattermod commented
Trying to auto merge this PR.

2020-11-02 10:07 UTC, merged

2020-11-02 10:07 UTC, mattermod commented
Pull Request successfully merged
SHA: dd24e5770586fe906e28feed49a3e75218d0eee7