Migrate String Refs to Functional ones - MM 16039
mattermost/mattermost-webapp pull request #6865
Opened 2020-10-21 07:24 UTC by Spotts9

#### Summary
Migrate String Refs to functional ones within `./components/adminconsole/remove_file_setting.jsx`

Fixes https://github.com/mattermost/mattermost-server/issues/16039

https://mattermost.atlassian.net/browse/MM-29856

2020-10-21 07:25 UTC, mattermod commented
Hello @Spotts9,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-21 13:51 UTC, mkraft approved these changes

2020-10-29 16:22 UTC, deanwhillier requested changes
@Spotts9, thanks so much for the contribution, much appreciated!

One item to consider below when you have a minute! 🙂

2020-10-29 16:22 UTC, deanwhillier commented on components/admin_console/remove_file_setting.jsx
> +        this.remove_button = React.createRef();
Two things regarding naming here:
1.  We prefer to use lower camel case for variables names
2. Typically we append 'Ref' to the end of these variable names

Could we please get the name of this variable changed to something like `removeButtonRef`?

```suggestion
        this.removeButtonRef = React.createRef();
```

2020-10-29 16:23 UTC, deanwhillier commented
/update-branch

2020-10-30 00:47 UTC, deanwhillier approved these changes
LGTM, thanks @Spotts9!

2020-11-06 16:12 UTC, stevemudie approved these changes
LGTM

2020-11-09 11:07 UTC, hanzei commented
/update-branch

2020-11-09 12:27 UTC, merged

2020-11-09 12:29 UTC, hanzei commented
Thank you for the contribution @Spotts9