MM-T614 Search on Outgoing Webhooks page
mattermost/mattermost-webapp pull request #6873
Opened 2020-10-21 16:41 UTC by MikeworX

**_Summary_**

This PR validates that the search functionality on the Integrations>Outgoing Web-hooks page is working as intended.

**_Steps_**

- 3 outgoing web-hooks are created, each with different names and trigger words
- asserts  are done on names, case, partial, common name, special character, no results, to insure expected web-hooks are displayed (or not)

This test requires webhook_serve.js to be running.

<img width="683" alt="Screen Shot 2020-10-21 at 12 39 48 PM" src="https://user-images.githubusercontent.com/586584/96750894-860fb600-139a-11eb-9310-269d4cecf18d.png">

**_Links_**

[vercel](https://automation-test-cases.vercel.app/test/MM-T614)
[TM4J](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T614)

2020-10-21 16:41 UTC, mattermod commented
Hello @MikeworX,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-22 11:24 UTC, saturninoabril requested changes
@MikeworX Thanks. Test flow looks good, except for few comments.

2020-10-22 11:24 UTC, saturninoabril commented on e2e/cypress/integration/integrations/outgoing_webhook/search_on_outoing_webhooks_spec.js
> +        });
No need to do `.then`. I suggests,
```suggestion
        cy.get('#searchInput').type('alpha');
        cy.get('.backstage-list__item').should('not.contain', triggerB).should('not.contain', triggerC).contains(triggerA);
```

2020-10-22 11:24 UTC, saturninoabril commented on e2e/cypress/integration/integrations/outgoing_webhook/search_on_outoing_webhooks_spec.js
> +        });
Revisiting the page multiple times will make the test longer. I suggest to just clear the input then type again.
```suggestion
        cy.get('#searchInput').clear().type('BRAVO');
        cy.get('.backstage-list__item').should('not.contain', triggerA).should('not.contain', triggerC).contains(triggerB);
```

Same comment below.

2020-10-23 12:42 UTC, saturninoabril commented on e2e/cypress/integration/integrations/outgoing_webhook/search_on_outoing_webhooks_spec.js
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
Please remove this file.

2020-10-23 12:45 UTC, saturninoabril requested changes
Thanks @MikeworX for updating. Tested and passed, except for a request to remove old file. I'm all good after that.

2020-10-23 14:06 UTC, MikeworX commented
Ah - thanks - missed that. I forgot that rename ≠remove.

2020-10-23 15:14 UTC, saturninoabril approved these changes
Thanks @MikeworX! LGTM, tested and passed.

2020-10-24 01:03 UTC, catalintomai approved these changes

2020-10-31 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-02 01:35 UTC, jfrerich commented
@prapti, gentle reminder for review.

2020-11-03 14:53 UTC, saturninoabril commented
/update-branch

2020-11-05 04:56 UTC, prapti approved these changes
LGTM!

2020-11-05 04:56 UTC, merged