[MM-27231]: e2e for T1880 - deleted token cannot be used to post
mattermost/mattermost-webapp pull request #6901
Opened 2020-10-23 14:27 UTC by ashishbhate

#### Summary

- Update `apiAccessToken` to return full token response
- Add  `apiRevokeAccessToken` method to revoke token
- cypress test for T1880 - deleted token cannot be used to post

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-27231

2020-10-28 15:56 UTC, josephbaylon commented
/update-branch

2020-10-28 16:43 UTC, josephbaylon requested changes
Hi @ashishbhate Thanks!! Just minor change requests.

2020-10-28 16:43 UTC, josephbaylon commented on e2e/cypress/support/api_commands.js
> +Cypress.Commands.add('apiRevokeAccessToken', (tokenId) => {
Please move `apiRevokeAccessToken` and `apiAccessToken` to `e2e/cypress/support/api/user.js` and also add corresponding entries to `e2e/cypress/support/api/user.d.ts`

2020-10-28 16:43 UTC, josephbaylon commented on e2e/cypress/integration/bot_accounts/token_spec.js
> +                // Revoke bot token
```suggestion
                // # Revoke bot token
```

2020-11-04 16:04 UTC, josephbaylon approved these changes
LGTM. Awesome work @ashishbhate !! Thanks!

2020-11-09 19:48 UTC, josephbaylon commented
/update-branch

2020-11-09 20:42 UTC, calebroseland approved these changes
LGTM (sorry it took so long, @ashishbhate)

2020-11-12 19:51 UTC, josephbaylon commented
@ogi-m I'll go ahead and merge this PR and update the TM4J and JIRA tickets

2020-11-12 19:51 UTC, merged