MM-27315 Cypress tests for Integrations > Slash command auto-complete (7 test cases)
mattermost/mattermost-webapp pull request #6909
Opened 2020-10-23 21:26 UTC by jfrerich

#### Summary
Cypress tests for MM-27315 

Test Cases: 
[MM-T2829](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2829)
[MM-T2830](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2830)
[MM-T2831](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2831)
[MM-T2832](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2832)
[MM-T2833](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2833)
[MM-T2834](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2834)
[MM-T2835](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2835)

#### Additional Notes
I created the `integrations/slash_commands` folder for these new tests

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27315

2020-10-28 06:59 UTC, saturninoabril commented
Thanks @jfrerich! Sorry for the delay. Will find time to review later today (just finishing somethig).

2020-10-28 13:43 UTC, jfrerich commented
No worries @saturninoabril.  I can't imagination how busy y'all are with hacktoberfest

2020-10-29 20:17 UTC, DHaussermann commented
- Tested to ensure all tests work
- Ensured what the tests are doing matches the TM4J intentions - For simplicity different pluign was used on dynamic argument that is more practical than the TM4J test

This test relies on code in the demo plugin that has not yet been released. Once the next release is published, this test should be changed to install the plugin via URL. Until then these tests cannot return green without manual intervention.
@saturninoabril I have added a do no merge label for now as these tests would not be able to be promoted to production until we have a Demo plugin release Jason can use.  Let me know if you think tis is okay or have alternative suggestions.

2020-10-30 00:59 UTC, saturninoabril commented
Thanks @DHaussermann! I agree. I don't have any other suggestion than to have the new demo plugin release soon.

2020-11-10 15:36 UTC, DHaussermann commented
@jfrerich we now have a Demo Plugin release `0.9.0` that you can install via the release URL.
Is it possible for you to implement this change?

2020-11-11 22:20 UTC, jfrerich commented
Hey @DHaussermann! I have implemented installing the plugins via the URL.  This is ready for re-review!

2020-11-13 01:50 UTC, saturninoabril requested changes
Thanks @jfrerich for updating! Tested and passed. Left couple comments and I'm all good after that.

2020-11-13 01:50 UTC, saturninoabril commented on e2e/cypress/integration/slash_commands/autocomplete_spec.js
> +    it('T2829 Test an example of plugin that uses sub commands', () => {
Please include full TM4J ID. Same for other `it` blocks.
```suggestion
    it('MM-T2829 Test an example of plugin that uses sub commands', () => {
```

2020-11-13 01:50 UTC, saturninoabril commented on e2e/cypress/integration/slash_commands/autocomplete_spec.js
> +        // * Verify suggestion list is visible with at three children (issue, instance, info)
```suggestion
        // * Verify suggestion list is visible with three children (issue, instance, info)
```

2020-11-16 17:11 UTC, saturninoabril approved these changes
Thanks Jason! LGTM.

2020-11-16 21:56 UTC, DHaussermann approved these changes
Tested last round of changes.
LGTM!

Moved some of the corresponding TM4J tickets form `ticket open` to `update`

2020-11-17 02:35 UTC, merged