MM-T615 Only public channels available in outgoing web-hooks setup
mattermost/mattermost-webapp pull request #6953
Opened 2020-10-28 17:01 UTC by MikeworX

**_Summary_**

This PR validates that only public channels are displayed in the outgoing web-hook's channel select drop-down box. In addition, a new api command is added to cypress, **cy.apiRemoveUserFromChannel()**.

**_Steps_**

A regular user creates a new team as well as:
- a second user for a direct message channel
- a public channel they are a member of
- a public channel they are not a member of
- a private channel
- a public channel that is immediately archive
- it is then asserted that only the public channel they are a member of, appears in the drop-down.

**_NOTE_**

The archive test above will currently fail due to this [bug](https://mattermost.atlassian.net/browse/MM-30069). 

[vercel](https://automation-test-cases.vercel.app/test/MM-T615)
[TM4J](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T615)

2020-10-28 17:01 UTC, mattermod commented
Hello @MikeworX,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-30 15:50 UTC, josephbaylon commented
/update-branch

2020-10-30 18:01 UTC, josephbaylon requested changes
@MikeworX I'm getting the following error below consistently. Also just minor comment suggestions.

![Screen Shot 2020-10-30 at 11 00 04 AM](https://user-images.githubusercontent.com/487991/97740955-39fdf900-1a9f-11eb-954e-682733e8b2df.png)

2020-11-02 15:52 UTC, MikeworX commented on e2e/cypress/integration/integrations/outgoing_webhook/only_public_channels_available_in_webhook_spec.js
> +        // Assert that a direct message channel does not appear in the drop-down
Thanks @josephbaylon for the review! The test is failing at that point due to this [bug](https://mattermost.atlassian.net/browse/MM-30069).

2020-11-13 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-18 19:56 UTC, jfrerich commented
Hi @MikeworX! Is this ready for a re-review?

2020-11-18 20:48 UTC, MikeworX commented
@jfrerich Hi there - this one will fail until https://mattermost.atlassian.net/browse/MM-30069 is fixed. Should I just close this PR and wait on the ticket?

2020-11-18 20:51 UTC, jfrerich commented
@MikeworX Thanks for letting me know! I'll apply the appropriate label letting us know it is waiting on another PR. You don't need to close this PR :)

2021-05-26 08:55 UTC, lindy65 commented
Hi @MikeworX - I'm helping review stale PRs and will be closing this PR for now as https://mattermost.atlassian.net/browse/MM-30069 is still not in progress. I've sent the ticket back to Global Triage for prioritization.

//cc @saturninoabril @josephbaylon

2021-05-26 08:55 UTC, closed without merging