[MM-29500] Migrate changeCSS() to CSS variable in utils/utils.jsx
mattermost/mattermost-webapp pull request #6959
Opened 2020-10-29 14:36 UTC by oliverJurgen

#### Summary

A description of what this pull request does.

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/15887

  Jira: https://mattermost.atlassian.net/browse/MM-29500.

If I have to make changes in the PR, please do tell me. Thanks

2020-10-29 14:36 UTC, mattermod commented
Hello @oliverJurgen,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-30 18:16 UTC, asaadmahmood requested changes
Please use it like this:
```
.channel-view {
        &#channel-view {
            background: var(--center-channel-bg);
        }
    }
```

Also please see if we need so much specificity or just `.channel_view` works.

2020-10-30 20:23 UTC, calebroseland requested changes
~~Thanks for the PR, @oliverJurgen! Would you mind moving `background` to the plain `.channel-view` towards the bottom?~~

2020-10-30 20:23 UTC, calebroseland commented on sass/base/_structure.scss
> +            background: var(--center-channel-bg);
Could `background: var(--center-channel-bg);` go to plain `.channel-view` below around :83?

2020-10-31 05:03 UTC, oliverJurgen commented
I applied the changes

2020-11-02 14:51 UTC, asaadmahmood approved these changes

2020-11-05 02:59 UTC, oliverJurgen commented
@calebroseland Hello, any more changes I should do?

2020-11-05 03:05 UTC, calebroseland commented
@oliverJurgen I think it would be a good chance to simplify and put in just `.channel-view` down by :80. If you wouldn't mind, that be great :)

2020-11-05 03:38 UTC, oliverJurgen commented
sounds good, will do that :)

2020-11-13 12:04 UTC, oliverJurgen commented
please check my latest change @calebroseland  :)

2020-11-13 15:23 UTC, calebroseland approved these changes
Thanks, @oliverJurgen!

2020-11-24 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-25 21:43 UTC, jasonblais commented
@calebroseland @asaadmahmood is this ready to merge?

2020-11-25 21:46 UTC, calebroseland commented
@jasonblais yes, my bad.

2020-11-25 21:46 UTC, merged