Mm 20404
mattermost/mattermost-webapp pull request #6976
Opened 2020-10-30 20:03 UTC by tianlangwu

#### Summary
Migrate 'components/announcement_bar/version_bar' module and associated tests to TypeScript

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/16167
JIRA https://mattermost.atlassian.net/browse/MM-20404

2020-10-30 20:03 UTC, mattermod commented
Hello @tianlangwu,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-02 16:28 UTC, crspeller requested changes

2020-11-02 16:28 UTC, crspeller commented on components/announcement_bar/version_bar/version_bar.tsx
> +interface IMyComponentProps {
Usually we name these just `Props` and `State` if it's not exported, there is no need to be specific.

2020-11-02 16:28 UTC, crspeller commented on components/announcement_bar/version_bar/version_bar.tsx
> +    serverVersion?: string,
Are these really optional? I think we might be able to get away without the `?`

2020-11-02 16:28 UTC, crspeller commented on components/announcement_bar/version_bar/index.ts
> +function mapStateToProps(state:any) {
Instead of `any` we can do `GlobalState` form 'types/store`

2020-11-02 17:37 UTC, tianlangwu commented
Hi, thanks for the advice! I have fixed the three problems you mentioned. Could you tell me where is "version_bar" in the web app preview?

2020-11-02 18:05 UTC, crspeller commented
@tianlangwu The version bar appears when a new version of the server is detected. I think you can make it appear by updating your sever to a new version without refreshing the browser.

2020-11-02 18:08 UTC, crspeller approved these changes

2020-11-03 10:12 UTC, agarciamontoro approved these changes
Thank you for your contribution, @tianlangwu! This looks good to me :tada:

2020-11-03 10:12 UTC, agarciamontoro commented
/update-branch

2020-11-12 21:45 UTC, jgilliam17 commented
/update-branch

2020-11-12 22:06 UTC, jgilliam17 approved these changes
Thank you @tianlangwu 
Tested, look good to merge.
- Verified new version available announcement banner - no change in functionality.
@agarciamontoro can you please help merge? Thanks 🙂

2020-11-13 17:16 UTC, merged