[MM-20414] Migrated NavbarInfoButton to Typescript
mattermost/mattermost-webapp pull request #6980
Opened 2020-10-31 00:08 UTC by Saucistophe

#### Summary
Migrate Navigation bar Info Button to Typescript.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/16159
https://mattermost.atlassian.net/browse/MM-20414

2020-10-31 00:08 UTC, mattermod commented
Hello @Saucistophe,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-02 15:07 UTC, hahmadia reviewed
@Saucistophe 

Code looks good! 

I guess my only question is why in some places was `ChannelInfoButton` renamed to `NavbarInfoButton` ? 
Why couldn't we just keep the name `ChannelInfoButton` as it was? 

I'm not 100% understanding those changes. Thanks!

2020-11-02 21:18 UTC, Saucistophe commented
> I guess my only question is why in some places was `ChannelInfoButton` renamed to `NavbarInfoButton` ?
> Why couldn't we just keep the name `ChannelInfoButton` as it was?

The class is named NavbarInfoButton, so it felt wrong importing `NavbarInfoButton` as `ChannelInfoButton` in the tests. I'm not sure which one is the best :shrug:

2020-11-13 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-13 22:58 UTC, calebroseland commented
/update-branch

2020-11-14 17:28 UTC, calebroseland requested changes
> > I guess my only question is why in some places was `ChannelInfoButton` renamed to `NavbarInfoButton` ?
> > Why couldn't we just keep the name `ChannelInfoButton` as it was?
> 
> The class is named NavbarInfoButton, so it felt wrong importing `NavbarInfoButton` as `ChannelInfoButton` in the tests. I'm not sure which one is the best 🤷

@Saucistophe I guess the file was originally named `navbar_info_button`, but got renamed to `channel_info_button` somewhere along the way. I agree having a consistent file/classname is best. 

My vote would be to use `ChannelInfoButton` where possible, possibly even changing `.navbar-info-button` to `.channel-info-button`  in the HTML. (I'm not seeing `.navbar-info-button` used in CSS or selectors elsewhere.)

2020-11-14 17:28 UTC, calebroseland commented on components/channel_header_mobile/channel_info_button/channel_info_button.tsx
> +        openModal: (modalData: {modalId: string; dialogType: any; dialogProps?: any}) => void;
This one seems different than the one in the index? 

```diff
- => void
+ => Promise<{data: boolean}>
```

2020-11-14 17:28 UTC, calebroseland commented on components/channel_header_mobile/channel_info_button/index.ts
> +}
One option could be to use `ComponentProps<T>` to extract the types from the component itself. 0/5
```tsx
type Actions = ComponentProps<typeof ChannelInfoButton>['actions'];
```

2021-03-26 15:26 UTC, devinbinnie commented
Closing this PR as inactive, @Saucistophe let us know if you plan on finishing this up.

2021-03-26 15:26 UTC, closed without merging