Campaign/applytheme center channel color
mattermost/mattermost-webapp pull request #6988
Opened 2020-10-31 18:46 UTC by HeroicHitesh

#### Summary
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 710

#### Ticket Link
Fixes #16180
GitHub - https://github.com/mattermost/mattermost-server/issues/16180
Jira - https://mattermost.atlassian.net/browse/MM-30176

2020-10-31 18:46 UTC, mattermod commented
Hello @HeroicHitesh,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-02 20:41 UTC, hmhealey approved these changes
Thanks for the PR, @HeroicHitesh! We appreciate the help getting rid of `applyTheme`.

2020-11-13 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-13 16:57 UTC, hmhealey commented
@deanwhillier Could you take a look at this when you get a chance?

2020-11-13 21:09 UTC, deanwhillier requested changes
Thanks for the contribution @HeroicHitesh! One slight adjustment needed below.

2020-11-13 21:09 UTC, deanwhillier commented on sass/components/_popover.scss
> +        border-color: var(--center-channel-color);
Just a small tweak to add the opacity from the original changeCss line. :)
```suggestion
        border-color: rgba(var(--center-channel-color-rgb), 0.2);
```

2020-11-13 21:18 UTC, deanwhillier commented on sass/components/_popover.scss
> +        border-color: var(--center-channel-color);
Took the liberty of committing the change directly for you since it took me a bit to get to this review, hope that's okay!

2020-11-13 21:59 UTC, deanwhillier requested changes
Actually, looking at this a bit more closely on the test server, I think we actually need to replace the 'transparent' value in the `.first` class definition:

So this:

```scss
    .popover__row {
        margin: 0 -15px 0;
        padding: 9px 15px 0;

        &.first {
            border-top: 1px solid transparent;
            margin-top: 4px;
        }

        > a {
            i {
                margin-right: 5px;
            }
        }
    }
```

Would become this:

```scss
    .popover__row {
        margin: 0 -15px 0;
        padding: 9px 15px 0;

        &.first {
            border-top: 1px solid rgba(var(--center-channel-color-rgb), 0.2);;
            margin-top: 4px;
        }

        > a {
            i {
                margin-right: 5px;
            }
        }
    }
```

2020-11-27 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-12-02 15:10 UTC, hmhealey commented
@deanwhillier Can you do your followup review when you get a chance? If you're busy, we can always re-assign

2020-12-02 15:23 UTC, deanwhillier approved these changes
Thanks again @HeroicHitesh! Just removing my initial suggestion in favour of the second update.

2020-12-02 15:23 UTC, deanwhillier commented on sass/components/_popover.scss
> +        }
We don't need this one anymore, the addition of the color to the .first selector is sufficient ... my bad so I'm removing! 😛
```suggestion
```

2020-12-02 16:06 UTC, merged