Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 705
mattermost/mattermost-webapp pull request #6994
Opened 2020-11-01 05:12 UTC by IanvsPoplicola

#### Summary
Migrate a CSS variable for popover from `utils/utils.jsx` into `sass/components/_popover.scss`

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/16175

2020-11-01 05:12 UTC, mattermod commented
Hello @IanvsPoplicola,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-02 21:01 UTC, hmhealey requested changes
Thanks for the PR, @IanvsPoplicola. I'm seeing some weird behaviour where the popover arrow is now visible in places that it wasn't before like above the channel members popover.
![Screen Shot 2020-11-02 at 3 58 44 PM](https://user-images.githubusercontent.com/3277310/97918689-81e18200-1d24-11eb-9b50-e850d4f29f2c.png)
For reference, there's no arrow on the latest release
![Screen Shot 2020-11-02 at 3 59 12 PM](https://user-images.githubusercontent.com/3277310/97918738-96257f00-1d24-11eb-944d-97dd1390ddab.png)

2020-11-02 21:06 UTC, IanvsPoplicola commented on sass/components/_popover.scss
> -    &.bottom,
Thanks for the review! I'll look into this.

2020-11-03 04:50 UTC, IanvsPoplicola commented on sass/components/_popover.scss
> -    &.bottom,
Okay I see what the problem is, I've misread the CSS and deleted the wrong stuff 🤦  Apologies! I've added it back now :)

2020-11-03 05:13 UTC, IanvsPoplicola commented on sass/components/_popover.scss
> -    &.bottom,
The arrow issue's fixed on the deployed test website from what I can see!

2020-11-04 18:40 UTC, hmhealey approved these changes

2020-11-13 21:50 UTC, calebroseland approved these changes
LGTM

2020-11-13 23:36 UTC, merged