MM-T2503 Boolean value check
mattermost/mattermost-webapp pull request #7014
Opened 2020-11-04 02:28 UTC by MikeworX

Summary

This PR checks that true/false values returned by the /dialog form are indeed boolean. 

Steps
- the form is completed the first time with all values checked as true
- once the form is submitted, the true values are asserted to be true (not "true")
- the above is then repeated for false values

<img width="504" alt="Screen Shot 2020-11-03 at 9 25 14 PM" src="https://user-images.githubusercontent.com/586584/98062155-71f89980-1e1b-11eb-8e07-85edc44403c4.png">

Links

[vercel](https://automation-test-cases.vercel.app/test/MM-T2503)
[TM4J](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T2503)

2020-11-04 02:28 UTC, mattermod commented
Hello @MikeworX,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-05 12:09 UTC, srkgupta requested changes
Thanks @MikeworX. Instead of duplicating the steps in the testcase, can you write a function which accepts true/false as a parameter and then performs the steps accordingly.

2020-11-05 12:33 UTC, srkgupta commented on e2e/cypress/integration/interactive_dialog/boolean_value_check_spec.js
> +            cy.visit(`/${team.name}/channels/${testChannel.name}`);
Add an additional step to wait till postbox is visible. 
`cy.get('#post_textbox', {timeout: TIMEOUTS.ONE_MIN}).should('be.visible');`

2020-11-05 13:43 UTC, MikeworX commented
Hi @srkgupta - thank-you for reviewing. Are you referring to the 2 assertion steps or the form setup?

2020-11-05 13:55 UTC, srkgupta commented
> Hi @srkgupta - thank-you for reviewing. Are you referring to the 2 assertion steps or the form setup?

I mean from the steps from line 37 to 75 are almost the same except for the condition true or false. Hence you can just have one function and accept one parameter (true or false) and accordingly set the form values and then validate the tests, instead of duplicating these steps

2020-11-11 14:52 UTC, saturninoabril commented
I agree with Rohitesh. Ping me whenever ready for review.

2020-11-25 20:16 UTC, closed without merging