[MM-T561] Add e2e test for MM-T561
mattermost/mattermost-webapp pull request #7015
Opened 2020-11-04 08:05 UTC by seongwon-kang

#### Summary
Add test for: Browser tab and team sidebar - direct messages don't add indicator on team icon in team sidebar (but do in browser tab)

#### Ticket Link
Github Issues: Fixes https://github.com/mattermost/mattermost-server/issues/15700
Jira Ticket: MM-T561

2020-11-04 08:05 UTC, mattermod commented
Hello @seongwon-kang,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-05 13:04 UTC, srkgupta requested changes
Thanks @seongwon-kang. Please find the requested changes.

2020-11-05 13:08 UTC, seongwon-kang commented
Thanks @srkgupta! but what `id` parameter is needed to post DM? I tried `user2.id`, but it did'nt worked.

2020-11-05 13:16 UTC, srkgupta commented
> Thanks @srkgupta! but what `channelId` parameter is needed to post DM? I tried `user1.id` (or `user1.username`?), but it didn't worked.

You can use the following function to create a direct message with user1 and user2 and get the channelId and then use the same for posting the message. For example:

```
        cy.apiCreateDirectChannel([user1.id, user2.id]).then(({channel: ownDMChannel}) => {
            cy.postMessageAs({sender: user2, message: `@${user1.username}`, channelId: ownDMChannel.id});
       });
```

2020-11-06 08:02 UTC, seongwon-kang commented on e2e/cypress/integration/notifications/browser_tab_notification_spec.js
> +        cy.get('#publicChannelList').get('.unread-title').click();
I moved `# Remove mention notification (for initial channel).` to `before()`  in another PR.

2020-11-06 15:41 UTC, saturninoabril commented
/update-branch

2020-11-06 16:08 UTC, saturninoabril requested changes
Thanks @seongwon-kang! Overall test flow looks good to me except for one request.

2020-11-06 16:08 UTC, saturninoabril commented on e2e/cypress/integration/notifications/browser_tab_notification_spec.js
> +    it('MM-T561 Browser tab and team sidebar - direct messages don\'t add indicator on team icon in team sidebar (but do in browser tab)', () => {
If above clean up is a prerequisite of this test, then I'd suggest to move this into its own separate file. We don't encourage test dependencies with other test as it tends to introduce flaky result.

2020-11-10 16:26 UTC, saturninoabril requested changes
@seongwon-kang Thanks for updating. Test looks good to me. Left last comments and I'm all good after that.

2020-11-10 16:26 UTC, saturninoabril commented on e2e/cypress/integration/notifications/direct_messages_do_not_add_indicator.js
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
Please add `_spec` to filename so it'll be [included for testing](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress.json#L9).

2020-11-10 16:26 UTC, saturninoabril commented on e2e/cypress/integration/notifications/browser_tab_notification_spec.js
> +
Please revert this change since it's already moved into its own spec file.

2020-11-16 08:53 UTC, seongwon-kang commented
/update-branch

2020-11-16 10:11 UTC, saturninoabril approved these changes
Thanks @seongwon-kang! LGTM.

2020-11-17 08:54 UTC, srkgupta approved these changes
Thanks @seongwon-kang. Changes LGTM and test passed.

2020-11-17 08:55 UTC, merged