Moving header icons to the left of the header aside the channel description
mattermost/mattermost-webapp pull request #7030
Opened 2020-11-06 18:42 UTC by jespino

#### Summary
Moving header icons to the left of the header aside the channel description

This needs some review from UX and probably more specification around it.

2020-11-06 22:10 UTC, matthewbirtch requested changes
Thanks for this @jespino! This will help clean up the channel header. I have a number of tweaks to make. Happy to talk through any of this if needed. 

Here's the difference between what was designed and what's implemented:
![Frame 5](https://user-images.githubusercontent.com/2040554/98419038-34318600-2052-11eb-9152-4ebe40637ccd.png)

The figma file here can be used for reference. You can use the 'Inspect' dimensions by double clicking in to elements in Figma and hover over to see dimensions, but I've also outlined the dimensions as designed in the images below.
https://www.figma.com/file/SwCd4uBAt0gAWnGpgjfO92/?node-id=1468%3A17798

Here are the relevant dimensions as designed
![Spec](https://user-images.githubusercontent.com/2040554/98419155-7064e680-2052-11eb-9808-42044034db98.png)

Here are the desired hover states for the various buttons
![Spec-1](https://user-images.githubusercontent.com/2040554/98419123-63e08e00-2052-11eb-8862-24d015d7ea27.png)

Here are the desired active states for the various buttons
![Spec-2](https://user-images.githubusercontent.com/2040554/98419147-6d69f600-2052-11eb-8c02-449ea56c01f7.png)

A question about the icons: can we move toward using the `compass-icons` font rather than SVGs or is that something we should do in another PR? Forgive my ignorance, I'm unsure what the status of using compass icons is right now. cc @deanwhillier 

Once we nail the above down, I can review the various states types of channel headers

2020-11-07 09:27 UTC, jespino commented
Thanks @matthewbirtch, that is exactly what I needed.

2020-11-09 10:12 UTC, jespino commented
@matthewbirtch I think I addressed everything there (and also take a look to the "mute/unmute", and how it looks/feels in DMs and GMs).

2020-11-11 18:53 UTC, matthewbirtch requested changes
@jespino I added some notes in the css where I could - hopefully those changes are clear.  A few additional comments beyond that:

1. Can we update the star icon as per new compass icons used in the Figma file
2. Can we update the dropdown icon as per new compass icons used in the Figma file
3. The mute icon needs to be updated as per new compass icons used in the Figma file
3. Can the members popover menu, align to the left of the icon button so that it displays more to the right?

How it's showing right now:
![image](https://user-images.githubusercontent.com/2040554/98851815-ca83f400-2424-11eb-8d88-8f9acab1854b.png)

How I'm suggesting it should display:
![image](https://user-images.githubusercontent.com/2040554/98851883-dff91e00-2424-11eb-9761-aa680cb47e6f.png)

Once these updates are made, I'll review all the variations of the channel header as well. sorry to be so picky, but it's got to be right as it's a very important part of the UI

2020-11-11 18:53 UTC, matthewbirtch commented on sass/components/_channel-header__icon.scss
>      padding: 0 6px;
The pinned button is too wide because it has a min-width on it. add:
```
min-width: unset;
```

2020-11-11 18:53 UTC, matthewbirtch commented on sass/components/_channel-header__icon.scss
> +        height: 16px;
Icons are displaying much larger than designed.
Leave the `.icon` selector as you have it, but change the `svg` selector to use:
```
width:12px;
height: 12px;
```

2020-11-11 18:53 UTC, matthewbirtch commented on sass/layout/_headers.scss
For the `.channel-header__info .channel-header__description` selector, the height should be:
```
.channel-header__info .channel-header__description {
    height: 24px;
}
```

And can we add 4px margin on the left of the `.header-placeholder` selector?
```
.channel-header__info .channel-header__description .header-placeholder {
    margin-left: 4px;
}
```

2020-11-11 18:53 UTC, matthewbirtch commented on sass/layout/_headers.scss
Can we update the following as well? Just to make sure spacing is correct within the header.
```
channel-header .flex-parent {
    padding: 0 16px 0 8px;
}
```

```
.channel-header__info {
    margin-top: 8px;
}

2020-11-11 18:53 UTC, matthewbirtch commented on sass/layout/_headers.scss
Can we change the padding on the channel-header__trigger?
```
.channel-header .channel-header__trigger {
    padding: 4px 6px;
}
```

And update the type style on the channel-header heading

```
.channel-header .heading {
    font-size: 14px;
    line-height: 16px;
}
```

And change the following on the dropdown icon
```
.header-dropdown__icon {
    font-size: 16px;
    line-height: 16px;
    margin: 0 0 0 4px;
}
```

2020-11-18 19:52 UTC, jespino commented
@matthewbirtch addressed your comments, let me know if something else is needed :)

2020-11-18 23:16 UTC, esethna commented
@matthewbirtch should we do a live review session here? 0/5

cc// @andrewbrown00

2020-11-19 14:46 UTC, matthewbirtch commented
> @matthewbirtch should we do a live review session here? 0/5

I think that would be best. I'll look to schedule something.

2020-11-24 01:53 UTC, esethna approved these changes

2020-11-24 15:50 UTC, matthewbirtch requested changes
This is looking really great now @jespino! Thanks for the patience.

Two more really minor tweaks (which I thought we fixed on the call).

![image](https://user-images.githubusercontent.com/2040554/100116752-1af64b00-2e42-11eb-97f6-8e85d30e8db8.png)

- the status icon is now sitting too low
- the count number inside the pin button (and members button as well) is sitting 1px too low. When I add `line-height: 16px` it seems to resolve it

2020-11-24 16:35 UTC, jespino commented
@matthewbirtch this was only happenning in chrome, but now should be working.

2020-11-24 16:47 UTC, matthewbirtch approved these changes
Nailed it! Thanks for your work on this @jespino!

2020-11-24 17:29 UTC, asaadmahmood approved these changes

2020-12-02 09:15 UTC, jespino commented
/update-branch

2020-12-04 22:57 UTC, calebroseland reviewed
LGTM, just seems to be one issue with alignment 
![CleanShot 2020-12-04 at 16 53 02](https://user-images.githubusercontent.com/11724372/101223560-e8bec780-3651-11eb-8977-c4b8811c74f0.gif)

2020-12-09 20:27 UTC, esethna commented
@jespino looks like there's still some issues with the pop-over alignment:

![image](https://user-images.githubusercontent.com/14333569/101683571-f55c6a80-3a19-11eb-918b-69f4ea396dcf.png)

2020-12-10 22:19 UTC, esethna commented
@ogi-m can you help do a QA pass on this?

2020-12-17 10:56 UTC, jespino commented
@esethna it is working fine for me in Chromium and Firefox locally, can it be a cache problem from your side, can you try again after the cloud image is updated?

2020-12-17 15:27 UTC, jespino commented
@esethna sorry, now is fixed, @calebroseland can you take another look?

2020-12-17 15:49 UTC, calebroseland approved these changes
LGTM ✓
![CleanShot 2020-12-17 at 09 48 25](https://user-images.githubusercontent.com/11724372/102510359-23aafd00-404d-11eb-8b4e-4bd4d4d8d797.gif)

2020-12-17 17:21 UTC, esethna commented
@ogi-m just needs a QA review.

@jespino I think there's still a bug with the channel header pop-over on hover. @nevyangelova may be able to help here. Try testing the Release Discussion channel header on daily vs this PR:

```
[Release Testing Tickets assigned to Current User](https://mattermost.atlassian.net/issues/?filter=15292) | [v5.30 RC1 EE](https://releases.mattermost.com/5.30.0-rc1/mattermost-enterprise-5.30.0-rc1-linux-amd64.tar.gz) | [v5.30 RC1 TE](https://releases.mattermost.com/5.30.0-rc1/mattermost-team-5.30.0-rc1-linux-amd64.tar.gz) | [Testing Server](https://rc.test.mattermost.com) | [Process](https://handbook.mattermost.com/operations/research-and-development/product/release-process/feature-release) | [Release Checklist channel](https://community.mattermost.com/core/channels/release-checklist) | **NEXT RELEASE v5.30 - WEDNESDAY, 16 DECEMBER 2020**
- Fri, Dec 11: Code Freeze;
- Mon, Dec 14: Release Build Cut;
- Wed, Dec 16: Release Day 
**NEXT MOBILE APP RELEASE v1.38 - 16 DECEMBER 2020**
```

Community daily: 
https://gyazo.com/7a3de985f986c98f35d90e136d12b2d3

This PR: 
https://i.gyazo.com/7a3de985f986c98f35d90e136d12b2d3.gif

2020-12-18 12:56 UTC, jespino commented
@esethna fixed

2021-01-04 15:42 UTC, ogi-m commented
@jespino The only issue I'm seeing is with the text on the second line that's partially visible:

![header](https://user-images.githubusercontent.com/15314183/103552174-c7006c80-4eab-11eb-85ec-88a7e73e4902.jpg)

2021-01-11 12:06 UTC, jespino commented
@ogi-m fixed, can you try again?

2021-01-11 18:21 UTC, ogi-m commented
@jespino
1. The popover doesn't perfectly cover the text behind it now, it's slightly offset to the right:
![header1](https://user-images.githubusercontent.com/15314183/104221886-d77f8c80-5441-11eb-8cc3-926be1ff18e3.jpg)

2. "This channel has guests" text is not in alignment with the icons and the header text:
![header2](https://user-images.githubusercontent.com/15314183/104222151-29c0ad80-5442-11eb-91af-57e9478db97b.jpg)

2021-01-11 18:39 UTC, jespino commented
Very good catches, one of them was only happening on single-team + new sidebar, that wasn't my setup locally. I think both are fixed now.

2021-01-18 21:05 UTC, esethna commented
@ogi-m can we try to merge this today? Anything blocking?

2021-01-18 23:06 UTC, ogi-m commented
@jespino @esethna The popover issue is fixed, but the alignment issue with "This channel has guests" text is still present in Chrome and Desktop app.

2021-01-18 23:07 UTC, esethna commented
@ogi-m thoughts on filing as a separate ticket if that's the only issue so we can get this merged?

2021-01-18 23:09 UTC, ogi-m commented
@esethna  Sounds good to me. I'll approve and file a separate ticket.

2021-01-18 23:09 UTC, ogi-m approved these changes

2021-01-18 23:12 UTC, esethna commented
@amyblais please include with the cloud release branch tomorrow

2021-01-19 00:39 UTC, amyblais commented
Assigned to Jesus to merge.

2021-01-19 13:17 UTC, amyblais commented
@jespino ^

2021-01-19 14:48 UTC, jespino commented
/update-branch

2021-01-19 15:03 UTC, merged

2021-01-19 18:18 UTC, amyblais commented
Ticket https://mattermost.atlassian.net/browse/MM-32174