make a post be able to send when you do command enter when editing post
mattermost/mattermost-webapp pull request #7031
Opened 2020-11-06 19:24 UTC by hahmadia

#### Summary

This PR fixes when trying to edit a post and using `CMD + ENTER` on mac for all messages to send the message. Previously, it did nothing. Now, it sends the message. This matches the behaviour of when creating a post.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30226

2020-11-06 19:40 UTC, crspeller requested changes
Can we add a test for this case?

2020-11-06 20:31 UTC, hahmadia commented
> Can we add a test for this case?

@crspeller 
Yes we can! As the great Rudy Tomajnovich once said "Don't ever underestimate the heart of a CHAMPION". As long as you believe it can be done, it will be done! 😄 

![spongebobthumpsup](https://user-images.githubusercontent.com/17804942/98411997-232e4800-2045-11eb-8a19-f8179e00715a.gif)

2020-11-06 21:14 UTC, crspeller approved these changes

2020-11-09 14:09 UTC, nickmisasi approved these changes
LGTM! Sorry for the delay.

2020-11-09 17:39 UTC, furqanmlk approved these changes
Working as expected.

2020-11-09 17:40 UTC, merged