MM-27230  Cypress/E2E: Automate backlogs - BOT Accounts - Part 07 (10 test cases)
mattermost/mattermost-webapp pull request #7040
Opened 2020-11-09 14:53 UTC by reflog

#### Summary

Implemented: MM-T1872  MM-T1874 MM-T1875   MM-T1877 MM-T1878  MM-T1880
Not implemented (cases archived) : T1873 , T1876, T1879
Not implemented T1865 - duplicate of MM-T1871

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27230

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

2020-11-11 15:49 UTC, saturninoabril requested changes
Thanks @reflog! Please see comments.

2020-11-11 15:49 UTC, saturninoabril commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +        cy.apiAdminLogin();
This seems redundant since user session didn't change since `beforeEach`. Same for other `it` blocks.

2020-11-11 15:49 UTC, saturninoabril commented on e2e/cypress/support/api_commands.js
> +Cypress.Commands.add('apiCreatePost', (channelId, message, rootId, props, token = '', failOnStatusCode = true) => {
I understand that this is a generic API command for posting message via API but like to mention that there's an existing `cy.postBotMessage` command that do specifically for posting bot message. Maybe just need to [workaround to allow failing status](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/support/task_commands.js#L15). It acts like an external request where it doesn't change the current session. So no need to logout and login the existing user.

2020-11-11 15:49 UTC, saturninoabril commented on e2e/cypress/support/api_commands.js
> +Cypress.Commands.add('apiCreateToken', (userId) => {
We're organizing API commands into `/support/api` folder and match file structure with `api.mattermost.com`. With that, could you please move this command to `/support/api/user.js` and add corresponding type at `/support/api/user.d.ts`? TIA

2020-11-11 15:49 UTC, saturninoabril commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +                cy.visit(`/${newTeam.name}/channels/` + channel.name);
I recommend using `cy.postBotMessage` so no need to logout then login sysadmin. Like,
```javascript
const msg1 = 'this is a bot message ' + botName;

// # Create a post
cy.postBotMessage({token, channelId: channel.id, message: msg1 + ' to @sysadmin'});

// # Visit DM channel
cy.visit(`/${newTeam.name}/channels/` + channel.name);
```

Same for others.

2020-11-12 15:04 UTC, reflog commented
@saturninoabril thanks for great suggestions!

2020-11-12 19:08 UTC, saturninoabril requested changes
Thanks @reflog for updating! Overall looks good and consistently passing, left last requests. TIA.

2020-11-12 19:08 UTC, saturninoabril commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +                cy.postBotMessage({channelId: channel.id, message: msg2, token});
Per test case, this should fail ("On 6. Post fails") but I don't know if that's correct. I'm clarifying that to our QA team.

2020-11-16 10:08 UTC, saturninoabril commented on e2e/cypress/integration/bot_accounts/bot_api_spec.js
> +                cy.postBotMessage({channelId: channel.id, message: msg2, token});
Dylan confirmed this and the one you did is correct. Test case is updated and is now `On 6. Post succeeds`.

2020-11-16 14:03 UTC, DHaussermann commented
@reflog just a heads up on this - I realized for MM-T1878 the expected result for step 6. was wrong in TM4J script. 

The post in step 6. should succeed as the token is re-enabled. 

Sorry for the mix up. I have updated the test.

2020-11-16 15:01 UTC, saturninoabril approved these changes
Thanks @reflog! LGTM, tested and all passed.

2020-11-20 19:44 UTC, prapti commented
/update-branch

2020-11-21 00:02 UTC, prapti reviewed
@reflog Just one minor update on the test title so that it gets picked up correctly for reporting once promoted to prod, otherwise the tests look great and passed as well. 

One concern that's here though (that should probably be brought up to QA) is that MM-T1880 was already implemented in https://github.com/mattermost/mattermost-webapp/pull/6901. And if that was the case, not sure why it was picked up for e2e backlog automation again in the ticket -- I'll check with QA, but looks like your implementation here is a step closer to the test steps in TM4J, so might want to keep this one instead.

2020-12-01 11:33 UTC, reflog commented
/update-branch

2020-12-01 11:33 UTC, reflog commented
Hi @prapti , what's the status of this PR?

2020-12-23 11:24 UTC, reflog commented
@saturninoabril can we get this merged?

2020-12-23 11:38 UTC, saturninoabril commented
I love to but maybe @prapti can take a quick look again (whenever possible). With regards to MM-T1880, we (SDET) will handle it separately so don't worry about it. (Btw, good catch there Prapti!)

2020-12-30 19:41 UTC, prapti commented
/update-branch

2020-12-30 21:01 UTC, prapti approved these changes
Looks great! Thank you @reflog, as always, for this test! And apologies that this somehow slipped through the cracks. Approving 👍

2020-12-31 08:44 UTC, merged