MM-28153: Cypress/E2E: Automate backlogs - System Console > Environment (8 test cases)
mattermost/mattermost-webapp pull request #7049
Opened 2020-11-10 07:17 UTC by catalintomai

#### Summary
MM-28153: Cypress/E2E: Automate backlogs - System Console > Environment (8 test cases)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28153

2020-11-11 20:13 UTC, DHaussermann commented
@catalintomai these tests all run green and seem to line up with the TM4J script 

The one concern I have with this is that we might need some cleanup to make sure the server remain usable for other tests.
Changes to `"WebserverMode` and the S3 config make the server unusable if they get pulled in. These cause issues when I ran the test locally and I wonder if they could prevent Cypress from running followup tests

@saturninoabril any thoughts on best practices here?

2020-11-13 02:02 UTC, saturninoabril commented
Thanks for checking @DHaussermann! It's fine. We're resetting [some config values to known default](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/fixtures/partial_default_config.json#L53) including `"WebserverMode": "gzip"` and S3 config in the global `before` hook which executes before each spec file.

2020-11-13 10:02 UTC, saturninoabril requested changes
Thanks @catalintomai! Looks great! Just one request and I'm all good.

2020-11-13 10:02 UTC, saturninoabril commented on e2e/cypress/integration/system_console/environment_spec.js
> +        cy.apiRequireLicenseForFeature('Elasticsearch');
We're separating EE only from other tests. With that, please move this test into its own spec file at `e2e/cypress/integration/enterprise/system_console` folder. Can be of the same filename.

2020-11-17 09:53 UTC, saturninoabril approved these changes
Thanks @catalintomai! LGTM.

2020-11-28 17:47 UTC, DHaussermann commented
/update-branch

2020-11-28 18:36 UTC, DHaussermann approved these changes
Tested and passed
- Tests work as expected and return green
- Test steps consistent with TM4J

LGTM!

2020-11-29 01:23 UTC, merged