MM-30359: Cypress/E2E: Account Settings > Email
mattermost/mattermost-webapp pull request #7051
Opened 2020-11-11 07:37 UTC by agnivade

This PR automates the following test cases:

MM-T2066

MM-T2067

MM-T2068

MM-T2069

MM-T2070

MM-T2071

MM-T2072

MM-T2073

https://mattermost.atlassian.net/browse/MM-30359

```release-note
NONE
```

2020-11-11 07:38 UTC, agnivade commented on e2e/cypress/integration/account_settings/general/email_spec.js
> +    // });
These test cases are incorrect or already covered by other tests. I have raised a question in the ~UI Test Automation channel.

2020-11-13 11:00 UTC, saturninoabril commented on e2e/cypress/integration/account_settings/general/email_spec.js
> +    it('MM-T2069/MM-T2070/MM-T2071/MM-T2072 email address verification', () => {
Noted. I'll combine the test cases into one, matching the steps here so we can save the result into the TM4J.

2020-11-13 12:39 UTC, saturninoabril requested changes
Thanks @agnivade! LGTM. Tested and all passed. Left comment to update test title.

2020-11-13 12:39 UTC, saturninoabril commented on e2e/cypress/integration/account_settings/general/email_spec.js
> +    it('MM-T2069/MM-T2070/MM-T2071/MM-T2072 email address verification', () => {
Combined into [MM-T2069](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2069). Please update the title. Other test cases were archived.
```suggestion
    it('MM-T2069 Email: Can update email address and verify through email notification, () => {
```

2020-11-13 12:39 UTC, saturninoabril commented on e2e/cypress/integration/account_settings/general/email_spec.js
> +        // * Verify the announcement bar (MM-2071)
```suggestion
        // * Verify the announcement bar
```

2020-11-13 12:39 UTC, saturninoabril commented on e2e/cypress/integration/account_settings/general/email_spec.js
> +        // * Verify new email address (MM-2070)
```suggestion
        // * Verify new email address
```

2020-11-16 09:22 UTC, saturninoabril approved these changes
Thanks @agnivade!

2020-11-16 16:05 UTC, isacikgoz approved these changes
Looks good 👍

2020-11-17 03:17 UTC, agnivade commented
/update-branch

2020-11-17 04:55 UTC, merged