[MM-30317] add MANAGE_REMOTE_CLUSTERS permission
mattermost/mattermost-webapp pull request #7060
Opened 2020-11-12 16:52 UTC by isacikgoz

#### Summary
Add `MANAGE_REMOTE_CLUSTERS` to the system console (under `manage_shared_channels` group).

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30317

#### Related Pull Requests

- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/1294)
- Has server changes (https://github.com/mattermost/mattermost-server/pull/16252)

#### Screenshots

2020-11-13 15:20 UTC, mkraft approved these changes

2020-11-13 16:07 UTC, wiggin77 requested changes

2020-11-13 16:07 UTC, wiggin77 commented on i18n/en.json
> +  "admin.permissions.permission.manage_remote_clusters.description": "Add, remove and view remote clusters to share channels",
```suggestion
  "admin.permissions.permission.manage_remote_clusters.description": "Add, remove and view remote clusters for shared channels",
```

2020-11-16 14:20 UTC, wiggin77 approved these changes
LGTM :+1:

2020-11-17 16:26 UTC, furqanmlk commented
Working as expected

### **Before Changes**

**All Members**

![image](https://user-images.githubusercontent.com/6909890/99416971-68fdd280-28c7-11eb-9aef-f36e8553fa65.png)


![image](https://user-images.githubusercontent.com/6909890/99417278-bc702080-28c7-11eb-972b-e12ebef53fc1.png)


### **After Changes**

**All Members**

![Remote Cluster - All Members](https://user-images.githubusercontent.com/6909890/99416307-b9286500-28c6-11eb-9d88-7e4fcf1bd32c.jpg)

**Channel Admin**

![Remote Cluster - Channel Admin](https://user-images.githubusercontent.com/6909890/99416476-e07f3200-28c6-11eb-9172-55155939464b.jpg)

**Tean Admin**

![Remote Cluster - Team Admin](https://user-images.githubusercontent.com/6909890/99416607-04db0e80-28c7-11eb-8f37-0357ea0016d9.jpg)

**System Admin**

![Remote Cluster - System Admin](https://user-images.githubusercontent.com/6909890/99416661-158b8480-28c7-11eb-94ee-4171aee0eea4.jpg)

2020-11-17 16:27 UTC, furqanmlk approved these changes

2020-11-18 16:37 UTC, merged