MM-30355: Cypress/E2E: Automate backlogs - Account Settings > Username (6 test cases)
mattermost/mattermost-webapp pull request #7062
Opened 2020-11-12 19:46 UTC by catalintomai

#### Summary
Cypress/E2E: Automate backlogs - Account Settings > Username (6 test cases)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30355

2020-11-16 10:39 UTC, saturninoabril requested changes
Thanks Catalin! Overall looks good :100:, except for one missing step/verification on MM-T2053.

2020-11-16 10:39 UTC, saturninoabril commented on e2e/cypress/integration/account_settings/general/username_spec.js
> +    //Note: the test case mentions an error message that could not be found in the codebase: "This username is already taken. Please choose another." Added a note to the testcase to update the error
Thanks for checking! Looks like it was recently changed by https://github.com/mattermost/mattermost-server/pull/15563. I've update the test case to reflect the new error message: "Unable to find the existing account to update.".
```suggestion
```

2020-11-16 10:39 UTC, saturninoabril commented on e2e/cypress/integration/account_settings/general/username_spec.js
> +            });
I think it's fine to at-mention self but still missing the last step:
- "4. Click "@" beside the search box to view recent mentions" then verify "Recent mentions button searches for updated username"

2020-11-17 10:04 UTC, saturninoabril approved these changes
Thanks @catalintomai! LGTM.

2020-11-28 18:38 UTC, DHaussermann commented
/update-branch

2020-11-28 18:38 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2020-11-28 18:47 UTC, DHaussermann commented
@catalintomai  or @saturninoabril Sorry for the delay in testing this. Seem master can not merge into the branch automatically anymore. 

All tests work and run green. Could one of you please review this merge issue ☝️ and advise if this need another test pass after?

2020-11-29 02:39 UTC, catalintomai commented
> @catalintomai or @saturninoabril Sorry for the delay in testing this. Seem master can not merge into the branch automatically anymore.
> 
> All tests work and run green. Could one of you please review this merge issue ☝️ and advise if this need another test pass after?

@DHaussermann , I merged and hardened a bit the last test, please give it another test pass to make sure.

2020-11-29 21:51 UTC, DHaussermann approved these changes
Test and passed (after master merge)
- Test match TM4J intent
- All test run Green
- Updated TM4J Cypress status accordingly

LGTM!

2020-11-30 01:29 UTC, merged