MM-20371: Cypress/E2E: Automate backlogs - Keyboard Shortcuts part 2 (10 test cases)
mattermost/mattermost-webapp pull request #7112
Opened 2020-11-21 21:00 UTC by catalintomai

#### Summary
Cypress/E2E: Automate backlogs - Keyboard Shortcuts part 2 (10 test cases)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30371

2020-11-23 18:53 UTC, catalintomai commented
@saturninoabril 
MM-T1258 and MM-T1259 are missing from the PR.

MM-T1258 requires access to the native file uploader. According to https://github.com/cypress-io/cypress/issues/170 there is no current Cypress support - there is a plugin that fills the gap https://github.com/abramenal/cypress-file-upload , but not clear how it should be used/invoked when the shortcut is typed. 
Any ideas or should we treat this test case as a N/A wrt to Cypress?

MM-T1239 - for "CMD+["/"CMD+]" I tried many variations of this (with/without delay, wait time, etc.)
`cy.get('#post_textbox').type('{cmd}', {release: false}).type(']').type('{cmd}', {release: true}).wait(TIMEOUTS.HALF_SEC);`
 none worked so far (tried it on the Mac only). 
Any ideas of what else I can try or should we treat this test case as N/A wrt to Cypress?

cc: @DHaussermann

2020-11-24 14:08 UTC, saturninoabril commented
Thanks for trying @catalintomai! For file upload, looks like there's no other workaround. For MM-T1239, I'll play around once I get a chance to review this PR, probably later today.

2020-11-30 17:21 UTC, DHaussermann approved these changes
Tested and passed
- Test actions look correct
- All tests run Green
- Set all corresponding TM4J ticket Cypress status to `Update`

LGTM!

2020-12-02 14:18 UTC, saturninoabril commented
/update-branch

2020-12-02 16:14 UTC, saturninoabril requested changes
Thanks Catalin! Please see comments.

2020-12-02 16:14 UTC, saturninoabril commented on e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_two_spec.js
> +        // Step #2 - not clear what are the "new shortcuts" - verifying that 'Keyboard Shortcuts' show
I believe it's to verify if shortcuts for "Previous Team" "Next Team" and "Switch to a specific team" are displayed in Keyboard shortcuts dialog. I've updated the test case.
<img width="306" alt="Screen Shot 2020-12-02 at 11 51 25 PM" src="https://user-images.githubusercontent.com/5334504/100896823-011bce80-34fa-11eb-9ae1-5c6373341631.png">

2020-12-03 02:55 UTC, catalintomai commented on e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_two_spec.js
> +            // # Press CTRL/CMD+SHIFT+UP
My bad, should be present now.

2020-12-03 15:06 UTC, saturninoabril approved these changes
@catalintomai Thanks for updating! LGTM.

2020-12-03 15:07 UTC, merged