MM-30285: Add online status to the profile popover
mattermost/mattermost-webapp pull request #7116
Opened 2020-11-22 15:48 UTC by edvinnn

#### Summary
This pull request adds a status indicator on the profile popover. It will display the StatusIcon component after fullname, but if fullname is not set the StatusIcon will appear after the e-mail adress in the popover.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/16248

#### Screenshots
![mm-1](https://user-images.githubusercontent.com/14109085/99908317-377b7180-2ce2-11eb-9f17-7b0858a98eb0.png) ![mm-2](https://user-images.githubusercontent.com/14109085/99908319-38140800-2ce2-11eb-9868-8530c5c7cf56.png)

2020-11-22 15:48 UTC, mattermod commented
Hello @edvinnn,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-23 17:13 UTC, esethna commented
Thanks! Adding @matthewbirtch for a UX review ^

2020-11-23 19:07 UTC, matthewbirtch requested changes
Thanks for this @edvinn. A few tweaks to request:

1. Can we make the left margin on the status icon 4px (and remove the right margin)
2. Can we make the `max-height` on the svg `12px` to feel more balanced with the username

2020-12-04 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-12-04 20:59 UTC, esethna commented
@edvinnn hope all is well, any questions on the above tweaks requested?

2021-02-24 00:20 UTC, esethna commented
@asaadmahmood would you be able to help take this over and address Matt's feedback?

2021-03-16 12:57 UTC, asaadmahmood commented
@esethna This is being addressed in this PR:
https://github.com/mattermost/mattermost-webapp/pull/7246

2021-03-22 16:16 UTC, esethna commented
@asaadmahmood so should we close this PR?

2021-03-22 16:56 UTC, asaadmahmood commented
Yup @esethna

2021-03-22 16:56 UTC, closed without merging