[MM-31045] Fix Error when adding group on channel configuration screen
mattermost/mattermost-webapp pull request #7170
Opened 2020-12-04 20:36 UTC by hahmadia

#### Summary

Fix a small bug in typescript migration that was causing lots of issues

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-31045

**Note to QA**
Ensure that when you click edit on a channel, the channel loads fine and that all the functions on that page work (do not throw a error or white screen of death)

2020-12-04 20:42 UTC, hahmadia commented on components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
> +export const ChannelGroups: React.FunctionComponent<ChannelGroupsProps> = (props: ChannelGroupsProps): JSX.Element => {
This was a un-related deprecated function fix. (SFC is deprecated and need to use FunctionComponent)

2020-12-04 20:42 UTC, hahmadia commented
Couldn't really think of a way to add a test as there was already a big console error saying that `Channel ID is marked as required but received undefined`

2020-12-07 17:11 UTC, mkraft approved these changes

2020-12-07 20:29 UTC, sbishel approved these changes

2020-12-09 18:16 UTC, hahmadia commented
/update-branch

2020-12-10 19:05 UTC, furqanmlk requested changes
I am getting `NaN Members` instead of `0 Member`

![image](https://user-images.githubusercontent.com/6909890/101817632-a3d2df00-3af0-11eb-9dac-d462af5e3201.png)

2020-12-11 15:29 UTC, furqanmlk approved these changes
Could not reproduce this issue mentioned above.
During Cypress test case, group was deleted using API while UI is visible, so it is not normal behaviour. 
All test cases passed

2020-12-11 15:29 UTC, merged