[Cypress/E2E, MM-27222] Add test cases, fix makeClient, add/correct types
mattermost/mattermost-webapp pull request #7173
Opened 2020-12-07 08:45 UTC by calebroseland

#### Summary
- Add typings to `cy.makeClient`
- Fix `cy.makeClient`
- Correct assorted types in `support/api/*.d.ts files` (not every file)
- **MM-27222**:
  - MM-T1812: add test case
  - MM-T1813: add test case

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-27222

#### Screenshots
<img width="829" alt="CleanShot 2020-12-07 at 02 13 36@2x" src="https://user-images.githubusercontent.com/11724372/101325738-ddc28d80-3831-11eb-812a-ea8bb5ae7ab1.png">

<img width="916" alt="CleanShot 2020-12-07 at 01 44 40@2x" src="https://user-images.githubusercontent.com/11724372/101325605-a48a1d80-3831-11eb-8f8a-1419f5a04836.png">

2020-12-16 15:48 UTC, hmhealey reviewed
Interesting. I didn't know we could use async/await with Cypress. I thought the pseudo-promises they used wouldn't work with that.

Do the existing tests I added using `makeClient` need to be updated because the return type for it changed?

2020-12-16 21:28 UTC, calebroseland commented
> Interesting. I didn't know we could use async/await with Cypress. I thought the pseudo-promises they used wouldn't work with that.
> 

Indeed, awaiting a `cy` sequence/chain would not work and should not be done. Nor should the test body be an async function. But the other way around is true to an extent, as cypress will yield to/resolve promises in the same way it handles `cy.wrap(promise).then()`, and because of the general interoperability between async/await and promises, it should work when used appropriately.

> Do the existing tests I added using `makeClient` need to be updated because the return type for it changed?

The return type shouldn't have changed and I tested it out in `category_muting_spec`, so it should be ok.

2020-12-17 17:06 UTC, josephbaylon requested changes
Thanks @calebroseland !! I had some intermittent failures locally. So just minor suggestions to stabilize the tests. Also, please fix conflicting files. Thanks!

Note: I ran other tests that use `makeClient` and most pass except for `channel/archived_channels_spec` > `MM-T1687` (fails on some sidebar issue in this PR), which when I tried to run against master already fails due to a `promise` issue. We don't need to fix that in this PR as that's outside the scope but if you want to take a look, that would be awesome.

2020-12-17 21:00 UTC, calebroseland commented
@josephbaylon review changes committed 👍

Re: `makeClient` It's currently broken on `master` when I try to run either of the two tests that use it. I ended up using it a lot in these new tests, so I thought it would be appropriate to fix it here.

2020-12-17 22:18 UTC, josephbaylon requested changes
Thanks @calebroseland for the update. One last change request below

2020-12-17 22:18 UTC, josephbaylon commented on e2e/cypress/integration/bot_accounts/promote_demote_spec.js
> +            cy.get('#searchUsersInput').type(`${bot.username}`);
Sometimes the filter input displays before the modal list and typing gets cut-off. Just needed to make sure modal list is loaded before search is performed.

```suggestion
            cy.get('.more-modal__list').find('.more-modal__row').its('length').should('be.gt', 0);
            cy.get('#searchUsersInput').type(`${bot.username}`);
```

2020-12-18 00:06 UTC, josephbaylon approved these changes
LGTM. Tests passed locally. Thanks @calebroseland !!

2020-12-18 20:25 UTC, hmhealey approved these changes

2020-12-18 22:49 UTC, merged