Mm 30361
mattermost/mattermost-webapp pull request #7190
Opened 2020-12-08 20:25 UTC by furqanmlk

#### Summary
Cypress/E2E: Automate backlogs - LDAP Settings (5 test cases)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30361

#### Screenshots

![image](https://user-images.githubusercontent.com/6909890/101536631-43189a80-3968-11eb-9526-b41b8d14081c.png)

![image](https://user-images.githubusercontent.com/6909890/101537417-70197d00-3969-11eb-8d2a-a0d825d298fd.png)

2020-12-14 15:09 UTC, josephbaylon commented
/update-branch

2020-12-14 15:49 UTC, josephbaylon requested changes
@furqanmlk Thanks!! Please apply minor suggestions below for consistency and stability.

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +    it('MM-T2699 Connection test button - Successful', () => {
```suggestion

    it('MM-T2699 Connection test button - Successful', () => {
```

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +    it('MM-T2700 LDAP username required', () => {
```suggestion

    it('MM-T2700 LDAP username required', () => {
```

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +    it('MM-T2701 LDAP LoginidAttribute required', () => {
```suggestion

    it('MM-T2701 LDAP LoginidAttribute required', () => {
```

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +    it('MM-T2704 Create new LDAP account from login page', () => {
```suggestion

    it('MM-T2704 Create new LDAP account from login page', () => {
```

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        cy.findByText(/save/i).click();
```suggestion
        cy.findByRole('button', {name: /save/i}).click();
```

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        cy.findByText(/save/i).click();
```suggestion
        cy.findByRole('button', {name: /save/i}).click();
```

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        cy.findByText(/save/i).click();
```suggestion
        cy.findByRole('button', {name: /save/i}).click();
```

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        cy.get('[data-testid="LdapSettings.LoginIdAttributeinput"]').click().clear();
```suggestion
        cy.findByTestId('LdapSettings.LoginIdAttributeinput').click().clear();
```

2020-12-14 15:49 UTC, josephbaylon commented on e2e/cypress/support/ldap_commands.js
> +    cy.visit('/admin_console/authentication/ldap');
```suggestion
    cy.visit('/admin_console/authentication/ldap');
    cy.get('.admin-console__header').should('be.visible').and('have.text', 'AD/LDAP');
```

2020-12-14 19:46 UTC, furqanmlk commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        cy.findByText(/save/i).click();
✅

2020-12-14 19:47 UTC, furqanmlk commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        cy.findByText(/save/i).click();
✅

2020-12-14 19:48 UTC, furqanmlk commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        cy.findByText(/save/i).click();
✅

2020-12-14 21:06 UTC, josephbaylon requested changes
@furqanmlk Looks like some of the suggestions were missed. You can just click `Commit Suggestion` if you don't have further local changes.

2020-12-14 21:06 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        cy.findByText(/save/i).click();
```suggestion
        cy.findByRole('button', {name: /save/i}).click();
```

2020-12-14 21:06 UTC, josephbaylon commented on e2e/cypress/support/ldap_commands.js
> +    cy.visit('/admin_console/authentication/ldap');
```suggestion
    cy.visit('/admin_console/authentication/ldap');
    cy.get('.admin-console__header').should('be.visible').and('have.text', 'AD/LDAP')
```

2020-12-14 21:07 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        // Login as sysadmin
```suggestion
        // # Login as sysadmin
```

2020-12-14 21:07 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        // Check if server has license for LDAP
```suggestion
        // * Check if server has license for LDAP
```

2020-12-14 21:08 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        // click "AD/LDAP Test"
```suggestion
        // # Click "AD/LDAP Test"
```

2020-12-14 21:08 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        // * Set back to what it was
```suggestion
        // # Set back to what it was
```

2020-12-14 22:19 UTC, josephbaylon approved these changes
LGTM. Tests passed locally. Thanks @furqanmlk !!

2020-12-15 18:26 UTC, sbishel approved these changes
just a nit.

2020-12-15 18:26 UTC, sbishel commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        // * Verify user is logged in  Successfy
```suggestion
        // * Verify user is logged in  Successfully
```

2020-12-16 00:42 UTC, furqanmlk commented on e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
> +        // * Verify user is logged in  Successfy
Thanks:)

2020-12-16 20:37 UTC, merged