Fixed autocomplete bug
mattermost/mattermost-webapp pull request #7231
Opened 2020-12-15 23:07 UTC by shFrank

fixed the bug that autocomplete would disappear if there are spaces between the channel name

The problem is caused by the regex because the previous version did not consider the situation when there are spaces between the channel name.
ex: 
before: when typing "IN: Town Squ" at the search box, the autocomplete would disappear
Now:  when typing "IN: Town Squ" at the search box, the autocomplete would still be there

#### Summary

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

2020-12-15 23:07 UTC, mattermod commented
Hello @shFrank,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-12-18 17:06 UTC, hmhealey requested changes
Thanks for the PR, @shFrank. 

I'm seeing an issue here that we used to hit with the `~channel` autocomplete in the post textbox. Once you use `in:` and fill in a channel name, it will keep searching for autocomplete results as you continue to type more into the textbox.

https://user-images.githubusercontent.com/3277310/102640454-7b6a6680-4128-11eb-9e6d-04ee3ba63b82.mov

You'll want to look at the `ChannelMentionProvider` to see how we solved it there. I think it was by tracking the previous captured text and whether or not that returned results so we could avoid sending a request if we're just adding to something that doesn't return results.

Also, if you watch closely in the video I posted above, it seems to stop returning autocomplete results once I've typed `in: display ` with a space at the end until I get to `in: display na`. I'm not sure if that is a server or clientside issue though.

2020-12-29 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-01-04 18:12 UTC, jfrerich commented
@shFrank, thanks for the PR!  Could you address the feedback from @hmhealey? Feel free to ping him with any questions.

2021-01-15 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-01-19 18:04 UTC, jfrerich commented
Hi @shFrank!  We would love to get this merged or open the issue back up for another contributor.  Please let us know :)

2021-01-30 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-02-02 21:16 UTC, hmhealey commented
Closing this to let others have a shot at it.

Thanks again for your work on this, @shFrank! If you'd like to work on this again, let us know, and we can open this back up. 🙂

2021-02-02 21:16 UTC, closed without merging