[GH-16131] - Migrate 'components/integrations/edit_command' module and associated tests to TypeScript
mattermost/mattermost-webapp pull request #7251
Opened 2020-12-19 18:46 UTC by lucievr

#### Summary
- Migrated `components/integrations/edit_command` module and test files to TypeScript
- Renamed files to have TypeScript extensions and updated incorrect imports
- Created a test helper method for mocking a command in `utils/test_helper.ts` which is then used in `components/integrations/edit_command` test file
- Check-types check returned no errors

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/16126

2020-12-19 18:46 UTC, mattermod commented
Hello @lucievr,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-12-19 18:55 UTC, lucievr commented on components/integrations/edit_command/__snapshots__/edit_command.test.tsx.snap
> +      "create_at": 1499722850203,
Assumed this timestamp was supposed to be a number as defined here https://github.com/mattermost/mattermost-redux/blob/master/src/types/integrations.ts

2020-12-30 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-01-05 14:49 UTC, devinbinnie requested changes
Thanks for the PR @lucievr! Looks good, I just have one change to request.

2021-01-05 14:49 UTC, devinbinnie commented on components/integrations/edit_command/index.ts
> +    getCustomTeamCommands: (teamId: string) => Promise<any>;
This returns an array of `Command` objects, so we don't have to use `any` here.

2021-01-06 21:53 UTC, hmhealey approved these changes
Looks good except for the other change requested.

Thanks for the help on this migration, @lucievr!

2021-01-08 12:28 UTC, lucievr commented
/update-branch

2021-01-08 12:43 UTC, lucievr commented
Thank you @devinbinnie and @hmhealey for the review and comments! I've made the requested change and tweaked the test file a bit too as it was otherwise throwing errors with the new change. Hope all is good now.

2021-01-08 14:25 UTC, devinbinnie approved these changes

2021-01-08 14:26 UTC, devinbinnie commented
LGTM! Thanks @lucievr!

2021-01-11 23:02 UTC, DHaussermann approved these changes
Tested and passed
- Regression tested creating updating and deleting of custom slash commands
- Tested on desktop and browser
- I did see an intermittent JS error but it was unrelated to this PR and will be addressed by https://mattermost.atlassian.net/browse/MM-31515 
- No other functional or JS issues found.

LGTM!
No new release tests needed to cover this change.
Thanks @lucievr for this PR!

2021-01-12 14:43 UTC, merged