[MM-30384] Implement Cypress test cases
mattermost/mattermost-webapp pull request #7265
Opened 2020-12-31 13:26 UTC by streamer45

#### Summary

PR implements the following test cases:

[MM-T2855](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2855)
[MM-T2857](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2857)
[MM-T2862](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2862)
[MM-T2863](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2863)
[MM-T2871](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2871)
[MM-T2876](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2876)
[MM-T2878](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2878)
[MM-T2900](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2900)
[MM-T2908](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2908)

#### Ticket

https://mattermost.atlassian.net/browse/MM-30384

2021-01-05 14:25 UTC, saturninoabril requested changes
Thanks @streamer45! Tested and all passed. Left few requests.

2021-01-05 14:25 UTC, saturninoabril commented on e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
> +        cy.findByLabelText('main menu').should('be.visible').click().wait(TIMEOUTS.HALF_SEC);
fyi, there's now `cy.uiOpenMainMenu()` that does the same action. This can remain as is but will eventually change using such convenient command.

2021-01-05 14:25 UTC, saturninoabril commented on e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
> +        cy.get('#channelHeaderDropdownIcon').should('be.visible').click().wait(TIMEOUTS.HALF_SEC);
Same here as `cy.uiOpenChannelMenu()`

2021-01-07 13:47 UTC, isacikgoz approved these changes
LGTM 👍

2021-01-08 07:19 UTC, lindy65 approved these changes
Thanks @streamer45 - looks good to me 👍

2021-01-08 08:22 UTC, merged