Cover with cypress tests server search display scenarios part 1
mattermost/mattermost-webapp pull request #7288
Opened 2021-01-07 11:29 UTC by nronas

#### Summary
What it says on the tin

#### Ticket Link
implements: https://mattermost.atlassian.net/browse/MM-30385

2021-01-07 11:30 UTC, mattermod commented
Hello @nronas,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-01-07 11:34 UTC, nronas commented on e2e/cypress/integration/search/post_search_display_spec.js
> +        cy.wait(TIMEOUTS.HALF_SEC);
```suggestion
```

2021-01-07 11:34 UTC, nronas commented on e2e/cypress/integration/search/post_search_display_spec.js
> +        const testMessage = 'Hello World!!!';
```suggestion
        const testMessage = 'Hello World!!!';
```

2021-01-14 17:15 UTC, saturninoabril requested changes
Thanks @nronas! Looks good to me except for few requests.

2021-01-14 17:15 UTC, saturninoabril commented on e2e/cypress/integration/search/post_search_display_spec.js
>  // Stage: @prod
Please remove this prod metadata. We'll add it back once we found the tests added here to be stable for production test.
```suggestion
```

2021-01-14 17:15 UTC, saturninoabril commented on e2e/cypress/integration/search/post_search_display_spec.js
> +        // # Search for search term in:town-square{space}
```suggestion
        // # Search for `Hell*`
```

2021-01-14 18:53 UTC, nronas commented on e2e/cypress/integration/search/post_search_display_spec.js
> +        cy.get('#searchBox').type('hello').type('{enter}').should('have.value', 'hello');
Will do, thanks a lot for looking into it.

2021-01-19 14:32 UTC, saturninoabril approved these changes
Thanks @nronas! Tested and all passed. LGTM.

2021-01-19 14:36 UTC, merged