[MM-30806] Account Settings - Setting to limit number of DMs/GMs shown in new sidebar
mattermost/mattermost-webapp pull request #7343
Opened 2021-01-18 21:24 UTC by devinbinnie

#### Summary
The Account Settings section that allows the user to set the limit on DMs/GMs in the new sidebar.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30806

2021-01-18 23:02 UTC, jgilliam17 commented
Thank @devinbinnie 
Seeing one issue + need to confirm 2. is not expected.

1. There is no `All` option in the Account Settings and should 20 have default text e.g `20 (default)` 
<img width="856" alt="Screen Shot 2021-01-18 at 5 23 59 PM" src="https://user-images.githubusercontent.com/52937121/104967797-3f8a2180-59b2-11eb-9b35-edb513576e0d.png">

When `All` is selected on the direct messages sidebar menu acct. settings page shows 10000
<img width="832" alt="Screen Shot 2021-01-18 at 5 24 36 PM" src="https://user-images.githubusercontent.com/52937121/104967988-b45d5b80-59b2-11eb-93d8-c9e0ee8b306b.png">

2. Mockup images are slightly different, let me know if I need to disregard the following 
a) Not showing any offset on the left, when looking at the expanded view (see above image from the test server)
b) title is bolded
c) Size of the dropdown is different 
Note: Offset, bold text and dropdown match what we use on other account settings screens
Mockup image below (not from test server)
<img width="641" alt="Screen Shot 2021-01-18 at 5 31 43 PM" src="https://user-images.githubusercontent.com/52937121/104968148-11591180-59b3-11eb-9dc4-26308de45e4b.png">

2021-01-19 14:29 UTC, hmhealey approved these changes
Looks good pending the issues Jelena found

2021-01-19 14:40 UTC, nevyangelova approved these changes

2021-01-19 14:49 UTC, devinbinnie commented
@jgilliam17 

> Thank @devinbinnie
> Seeing one issue + need to confirm 2. is not expected.
> 
> 1. There is no `All` option in the Account Settings and should 20 have default text e.g `20 (default)`

This should now be fixed.

> 1. Mockup images are slightly different, let me know if I need to disregard the following
>    a) Not showing any offset on the left, when looking at the expanded view (see above image from the test server)
>    b) title is bolded
>    c) Size of the dropdown is different
>    Note: Offset, bold text and dropdown match what we use on other account settings screens
>    Mockup image below (not from test server)
> 
> <img alt="Screen Shot 2021-01-18 at 5 31 43 PM" width="641" src="https://user-images.githubusercontent.com/52937121/104968148-11591180-59b3-11eb-9dc4-26308de45e4b.png">

I'll leave this one up to @matthewbirtch, I'm using the same styles currently provided by the Account Settings dialog, which is what was also used for the Group unreads settings as well. I just figure whatever we choose we should be consistent.

2021-01-19 14:56 UTC, matthewbirtch commented
> I'll leave this one up to @matthewbirtch, I'm using the same styles currently provided by the Account Settings dialog, which is what was also used for the Group unreads settings as well. I just figure whatever we choose we should be consistent.

@devinbinnie this is fine to stay consistent with the existing account settings styles/layout. Keep it as you have it.

2021-01-19 15:04 UTC, matthewbirtch requested changes
Everything looks good. Only one issue I see:

When I open the dropdown menu it seems to be shifting - likely due to the scrollbar being added. Any way we can prevent this shifting?
![2021-01-19 10 00 44](https://user-images.githubusercontent.com/2040554/105052228-a43e8e00-5a3d-11eb-9c49-1c905d5100a7.gif)

2021-01-19 15:06 UTC, devinbinnie commented
> Everything looks good. Only one issue I see:
> 
> When I open the dropdown menu it seems to be shifting - likely due to the scrollbar being added. Any way we can prevent this shifting?
> ![2021-01-19 10 00 44](https://user-images.githubusercontent.com/2040554/105052228-a43e8e00-5a3d-11eb-9c49-1c905d5100a7.gif)

@matthewbirtch Not sure how you're getting a scrollbar there, the only way I can get a scrollbar is by shrinking the window height down below 535px, which is way smaller than any modern screen. What resolution are you working with?

2021-01-19 15:08 UTC, matthewbirtch commented
> What resolution are you working with?

1920x1080. To be clear, the scrollbar only shows on the account settings modal when I open the dropdown

Here's a shot of the whole screen
![image](https://user-images.githubusercontent.com/2040554/105052791-46f70c80-5a3e-11eb-9205-b30c86ba5ac9.png)

2021-01-19 15:20 UTC, devinbinnie commented
> > What resolution are you working with?
> 
> 1920x1080. To be clear, the scrollbar only shows on the account settings modal when I open the dropdown
> 
> Here's a shot of the whole screen
> ![image](https://user-images.githubusercontent.com/2040554/105052791-46f70c80-5a3e-11eb-9205-b30c86ba5ac9.png)

@matthewbirtch Okay gotcha, I've made it so the scrollbar shouldn't show much anymore and the dropdown should flow above and out of the modal such that no scrolling is needed.

2021-01-19 17:24 UTC, jgilliam17 approved these changes
Thank you @devinbinnie 
Tested, looks good to merge.
- Verified new account setting option to set limit to number of DMs/GMs on the sidebar.
- Verified Auto close DMs option is removed when legacy sidebar is disabled.
There is an issue with Auto close DM setting having to be re-enabled, I will file separately add link here shortly.

2021-01-19 17:25 UTC, merged