[MM-32193] Removed unnecessary transform from team sidebar button
mattermost/mattermost-webapp pull request #7356
Opened 2021-01-20 19:54 UTC by devinbinnie

#### Summary
A CSS statement transforming the base team sidebar button container (`transform: translate(0, 0)`) was causing the desktop `Copy Link` context menu to not be rendered correctly.

Since it shouldn't be necessary to set an initial translate value, I've removed the statement and the menu item works again.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32193

2021-01-20 21:58 UTC, deanwhillier requested changes
One accidental removal that I think needs to be brought back.

2021-01-20 21:58 UTC, deanwhillier commented on sass/layout/_team-sidebar.scss
> -                    @include opacity(1);
I think this still needs to be there. Unless you removed it separately from our conversation.

2021-01-20 22:04 UTC, deanwhillier approved these changes

2021-01-20 22:28 UTC, jgilliam17 approved these changes
Thanks @devinbinnie 
Tested, looks good to merge.
- Verified Team sidebar copy link is shown as expected.
- Verified Team sidebar no longer has a horizontal scroll bar on desktop app.

2021-01-21 14:14 UTC, nevyangelova commented
@devinbinnie @jgilliam17 this was made so the badges can transition as well with the container when they are moved down on click. With this change I don't see the unread badges at all.

2021-01-21 14:15 UTC, nevyangelova requested changes
@devinbinnie @jgilliam17 this was made so the badges can transition as well with the container when they are moved down on click. With this change I don't see the unread badges at all.

2021-01-21 14:20 UTC, hmhealey approved these changes

2021-01-21 14:22 UTC, devinbinnie commented
@nevyangelova I can see the unread badges just fine, there's a fix from @deanwhillier that fixes the bad CSS on the unread badges.

2021-01-21 14:24 UTC, hmhealey requested changes
In addition to Nevy's PR, that doesn't fix the horizontal scrollbar on long channels in the desktop app
![Screen Shot 2021-01-21 at 9 24 18 AM](https://user-images.githubusercontent.com/3277310/105363820-75095780-5bca-11eb-9d50-23e8880cc161.png)

2021-01-21 14:27 UTC, nevyangelova requested changes
the unread badges disappear for me in this PR after clicking between the teams.

2021-01-21 14:37 UTC, nevyangelova approved these changes

2021-01-21 14:50 UTC, hmhealey approved these changes

2021-01-21 14:50 UTC, merged

2021-01-21 14:50 UTC, mattermod commented
Cherry pick is scheduled.

2021-01-21 14:50 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.114.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
   b5a5e986f..bffa60b39  MM-31914-use-new-renewal-link -> upstream/MM-31914-use-new-renewal-link
   20a038163..19709b5db  MM-32192_fix-team-button-mention-badge -> upstream/MM-32192_fix-team-button-mention-badge
   2fdf2376d..a76bcc3e4  cloud              -> upstream/cloud
   96ce72fbc..dd6c640f2  disablecomp        -> upstream/disablecomp
 * [new branch]          fix-t1461          -> upstream/fix-t1461
 * [new branch]          hh_revert-MM-27260 -> upstream/hh_revert-MM-27260
   dfb8860bd..756d3c544  master             -> upstream/master
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
!!! 'upstream/release-5.32' not found. The second argument should be something like upstream/release-0.21.
    (In particular, it needs to be a valid, existing remote branch that I can 'git checkout'.)

+++ Returning you to the master branch and cleaning up.

```

2021-01-21 15:24 UTC, amyblais commented
/cherry-pick cloud