GH-10232 improved timezone selector
mattermost/mattermost-webapp pull request #7384
Opened 2021-01-22 22:42 UTC by IndushaS

Summary
Improved timezone selector located in account settings -> display -> timezone

1. Updated manual timezone component to a drop down list:
2. When "Automatic" is selected, dropdown list is disabled and automatic value is displayed. 

GitHub issue:
Fixes https://github.com/mattermost/mattermost-server/issues/10232

Screenshots:
![image](https://user-images.githubusercontent.com/35474916/105556985-2bf3f900-5cd9-11eb-900d-ca6f15c8d929.png)
![image](https://user-images.githubusercontent.com/35474916/105556913-0830b300-5cd9-11eb-93fe-ce07f9a836eb.png)
![image](https://user-images.githubusercontent.com/35474916/105556950-1e3e7380-5cd9-11eb-8fe8-a11d10868748.png)

2021-01-22 22:42 UTC, mattermod commented
Hello @IndushaS,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-01-25 18:27 UTC, esethna approved these changes
Thanks @IndushaS, is there a follow-up ticket for updating the timezone list?

2021-01-25 18:29 UTC, esethna commented
@IndushaS please note there should be some padding between the checkbox and the dropdown list:

![image](https://user-images.githubusercontent.com/14333569/105749363-29bbb580-5ef8-11eb-855b-2a8411418340.png)

2021-01-25 19:07 UTC, IndushaS commented
Hello Eric,

To my knowledge there is no ticket for that yet. Also thank you for taking a look at the PR, I must have not seen the padding I'll be sure to fix that sorry.

Kindest Regards,
Indusha
________________________________
From: Eric Sethna <notifications@github.com>
Sent: 25 January 2021 1:29 PM
To: mattermost/mattermost-webapp <mattermost-webapp@noreply.github.com>
Cc: Indusha Menaji Semba Kuttiarchchige <indusha.menaji.semba.kuttiarchchige@uwaterloo.ca>; Mention <mention@noreply.github.com>
Subject: Re: [mattermost/mattermost-webapp] GH-10232 improved timezone selector (#7384)


@IndushaS<https://github.com/IndushaS> please note there should be some padding between the checkbox and the dropdown list:

From design:
[image]<https://user-images.githubusercontent.com/14333569/105749363-29bbb580-5ef8-11eb-855b-2a8411418340.png>

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/mattermost/mattermost-webapp/pull/7384#issuecomment-767021324>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIOU3ZGVQE444KI4ALK4BC3S3W2A3ANCNFSM4WPEMXIA>.

2021-01-25 19:18 UTC, esethna commented
Thanks, please share the follow-up ticket once opened :)

2021-01-25 22:49 UTC, IndushaS commented
> Thanks, please share the follow-up ticket once opened :)

Hello @esethna, I added the padding as you mentioned. I'm not sure how to create a ticket maybe you could tell me the general steps?

2021-01-26 14:49 UTC, gabrieljackson commented
@IndushaS and @esethna, I will create the follow-up ticket and let you know when it is ready.

2021-02-06 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-02-11 17:39 UTC, emilyacook commented
@gabrieljackson gentle ping :)

2021-02-11 19:12 UTC, gabrieljackson commented
@emilyacook Sorry about the delay. New issue created here: https://github.com/mattermost/mattermost-server/issues/16918

2021-02-12 17:17 UTC, nevyangelova requested changes

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/index.ts
> +function mapStateToProps(state:GlobalState) {
nit: spaces

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/index.ts
> +export default connect(mapStateToProps,mapDispatchToProps)(ManageTimezones);
Same here. Can you configure your eslint to match our configuration?

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +    times:string[];
nit: space

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +            selectedOption: {label:props.manualTimezone, value: props.manualTimezone},
nit: space

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +    onChange = (selectedOption:ValueType<SelectedOption>) => {
nit: spaces

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +        console.log(this.props.times);
nit: remove console.log

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +            modalBody?.classList.remove('no-scroll');
Please avoid using query selector and use classNames, We’re aiming to have a declarative codebase where possible. Also we have a pattern of identifying model you can take a look at examples in `edit_channel_header_modal.jsx`

We have close and open actions for modals as well as modal identifiers here 
`import {openModal, closeModal} from 'actions/views/modals';`

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +        const modalBody = document.querySelector('.modal-body');
Please avoid using query selector and use classNames, We’re aiming to have a declarative codebase where possible. Also we have a pattern of identifying model you can take a look at examples in edit_channel_header_modal.jsx

We have close and open actions for modals as well as modal identifiers here
import {openModal, closeModal} from 'actions/views/modals';

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +        const modalBody = document.querySelector('.modal-body');
same here

2021-02-12 17:17 UTC, nevyangelova commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +        const modalBody = document.querySelector('.modal-body');
and here

2021-02-16 16:59 UTC, devinbinnie commented
Hey @IndushaS, thanks for your contribution! Couple things I'd like you to do before I review your PR:

1) Please sign the Contributor License Agreement found here: http://www.mattermost.org/mattermost-contributor-agreement/. When that's done, comment `/check-cla`.
2) Run `make check-style` and `make i18n-extract` and make sure there are no lint issues or missing translations. It looks like there are some errors around those.
3) Merge the latest `master` into your branch and fix any merge conflicts.

2021-02-18 21:25 UTC, devinbinnie approved these changes
LGTM! Thanks @IndushaS!
Just one non-blocking comment

2021-02-18 21:25 UTC, devinbinnie commented on components/user_settings/display/manage_timezones/manage_timezones.tsx
> +        /*const timezoneRegion = (
We can probably just remove this commented code

2021-02-19 08:44 UTC, nevyangelova approved these changes
Thank you 🎉 looks great

2021-02-23 14:33 UTC, jgilliam17 approved these changes
Thank you @IndushaS 
Tested, looks good to merge.
- Verified time zone list drop down; when "Automatic" is selected, dropdown is disabled and shows the auto selected timezone in it. 
The timezone list will be updated/addressed in the follow up issue MM-32804.

2021-02-23 14:36 UTC, devinbinnie commented
/update-branch

2021-02-23 14:53 UTC, merged