[MM-32098] Add Cypress Test for Support Packet Generation
mattermost/mattermost-webapp pull request #7558
Opened 2021-02-19 17:15 UTC by hahmadia

#### Summary

Adds Cypress Test for Support Packet Generation

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-32098

2021-02-22 17:35 UTC, josephbaylon requested changes
Thanks @hahmadia !! Please apply suggestions below

2021-02-22 17:35 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
> +    it('MM-T3818 - Commercial Support Dialog UI - Links', () => {
I updated MM-T3818 to only have one step to match this cypress case

2021-02-22 17:35 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
> +    it('MM-T3817-Step2And3 - Commercial Support Dialog UI', () => {
I merged step 2 and step 3 into one step and created new ticket MM-T3849 to match cypress case

```suggestion
    it('MM-T3849 - Commercial Support Dialog UI - E10/E20 License', () => {
```

2021-02-22 17:35 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
> +    it('MM-T3817-Step1 - Commercial Support Dialog UI', () => {
Please move `MM-T3817` to its own non-enterprise file: `e2e/cypress/integration/system_console/support_packet_generation_spec.js`

```suggestion
    it('MM-T3817 - Commercial Support Dialog UI - No License', () => {
```

2021-02-22 17:35 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
> +        });
Please move to `before`

```suggestion
```

2021-02-22 17:35 UTC, josephbaylon commented on e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
> +        });
Please move to `before`

```suggestion
```

2021-02-23 21:10 UTC, hahmadia commented
Salamat @josephbaylon for helping me clean up my tests. I've addressed your comments.

2021-02-23 21:18 UTC, josephbaylon approved these changes
@hahmadia Haha! How'd you figure I would understand `salamat` 😆  .. you're welcome 👍 

LGTM. Just need to remove `@enterprise` tag from the non-enterprise file. Salamat!

2021-02-23 21:18 UTC, josephbaylon commented on e2e/cypress/integration/system_console/support_packet_generation_spec.js
> +// Group: @enterprise @system_console
```suggestion
// Group: @system_console
```

2021-02-24 20:22 UTC, furqanmlk approved these changes
thanks @hahmadia 
All test cases passed ✅ 
just one small type 

![image](https://user-images.githubusercontent.com/6909890/109060497-75a67980-76b3-11eb-84d9-6faa14fd7c65.png)

![image](https://user-images.githubusercontent.com/6909890/109060573-9242b180-76b3-11eb-8909-9f9cc84501b6.png)

2021-02-24 20:22 UTC, furqanmlk commented on e2e/cypress/integration/system_console/support_packet_generation_spec.js
> +// # Goes to the System Scheme page as System Admin
```suggestion
// # Go to the System Scheme page as System Admin
```

2021-02-24 20:48 UTC, BenCookie95 commented on e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
> +        cy.findByRole('link', {name: 'Download Support Packet'}).should('exist');
Nit: Could put the above 3 lines in a function because they're used in both tests

2021-02-24 21:02 UTC, BenCookie95 approved these changes
Looks good!

2021-02-24 21:03 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2021-02-24 21:22 UTC, mattermod commented
Trying to auto merge this PR.

2021-02-24 21:22 UTC, merged

2021-02-24 21:22 UTC, mattermod commented
Pull Request successfully merged
SHA: 63335c63fecc6972e127e0d8c5e73ba71a9999c9