MM-32773 - open file screen
mattermost/mattermost-webapp pull request #7621
Opened 2021-03-02 17:49 UTC by pvev

#### Summary
This PR covers the functionality for the open file screen from the import workspace project.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32773

2021-03-02 17:52 UTC, pablovelezvidal commented
For testing purposes I used these two files:
[test-files.zip](https://github.com/mattermost/mattermost-webapp/files/6070709/test-files.zip)

2021-03-04 13:39 UTC, AGMETEOR approved these changes
hey Pablo thanks for the good work. lays good foundation for the upcoming migration functionalities. LGTM and just a small comment

2021-03-04 13:39 UTC, AGMETEOR commented on components/admin_console/cloud_import/import_workspace.tsx
> +    // useInterval(() => {
forgot commented code. this puts some ununsed import on line 15

2021-03-09 04:40 UTC, marianunez requested changes
Great stuff with the drag and drop and optimizing the rendering while updating the status! 🎉

Some minor comments below mostly on code org a bit more the `openFile` component

2021-03-09 04:40 UTC, marianunez commented on components/admin_console/cloud_import/components/open_file.tsx
> +import AlertBanner from 'components/alert_banner';
To keep the imports organized, can we move these and the `UpgradeLink` above together with all the `components/...` imports above?

2021-03-09 04:40 UTC, marianunez commented on components/admin_console/cloud_import/components/open_file.tsx
> +    const handleDragOverCb = () => {
For readability, I would suggest `Cb` here on the naming. Doesn't provide any value and the `handle` naming convention may be explicit enough.
```suggestion
    const handleDragOver = () => {
```

2021-03-09 04:40 UTC, marianunez commented on components/admin_console/cloud_import/components/open_file.tsx
> +        </CardContainer>
Would it be more idiomatic React to make these functions `openFileStateInitialSection` and `openFileStateInitialSection` a functional component with props?

2021-03-09 04:40 UTC, marianunez commented on components/admin_console/cloud_import/components/open_file.tsx
> +const StepOne: React.FC<StepOneProps> = (props: StepOneProps) => {
Should this be called `OpenFile` or `OpenImportFile` given the filename `StepOne` doesn't seem to provide enough context at this component level.

2022-03-16 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-03-22 13:31 UTC, marianunez commented
@pvev should we close this PR for now? We can maybe bring back this branch when we resume this work (not scheduled at this time)

2022-03-22 19:36 UTC, closed without merging