Adding subsection permissions for Authentication
mattermost/mattermost-webapp pull request #7660
Opened 2021-03-08 19:54 UTC by BenCookie95

#### Summary
Adding subsection permissions for Authentication

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32349

#### Related Pull Requests

2021-03-09 15:34 UTC, hahmadia approved these changes
LGTM! Minor changes but great stuff.
Going to be adding Scott as a reviewer since this touches on the OpenID and I think it be nice to get his eyes on it too.

2021-03-09 15:34 UTC, hahmadia commented on components/admin_console/admin_definition.jsx
>                              it.not(it.isSystemAdmin),
No this attribute can make people a system admin allowing them to manipulate more than what they have control too. Leave it in.

2021-03-09 15:34 UTC, hahmadia commented on components/admin_console/admin_definition.jsx
>                              it.not(it.isSystemAdmin),
No this attribute can make people a system admin allowing them to manipulate more than what they have control too. Leave it in.

2021-03-09 15:34 UTC, hahmadia commented on e2e/cypress/support/api/role.js
> +        'sysconsole_read_authentication_guest_access',
Please also add any ancillary permissions that come with these.

2021-03-09 15:34 UTC, hahmadia commented on e2e/cypress/support/api/role.js
> +        'sysconsole_read_authentication_guest_access',
Please also add any ancillary permissions that come with these.

2021-03-09 15:34 UTC, hahmadia commented on e2e/cypress/support/api/role.js
> +        'sysconsole_read_authentication_guest_access',
Please also add any ancillary permissions that come with these.

2021-03-09 23:46 UTC, sbishel requested changes

2021-03-09 23:46 UTC, sbishel commented on components/admin_console/admin_definition.jsx
> +                            it.not(it.userHasWritePermissionOnResource(RESOURCE_KEYS.AUTHENTICATION.LDAP)),
No, only a "SystemAdmin" can update permissions which changes "SystemAdmins".  Therefore this check should remain. No additional check is necessary.

2021-03-09 23:46 UTC, sbishel commented on components/admin_console/admin_definition.jsx
> +                            // Should this one be removed?
No, see above.

2021-03-09 23:46 UTC, sbishel commented on components/admin_console/admin_definition.jsx
> +                        isDisabled: it.not(it.userHasWritePermissionOnResource(RESOURCE_KEYS.AUTHENTICATION.LDAP)),
This allows a user to request a trial license. Therefore, the user requires "manage_license_information" permission which is tied to ABOUT.EDITION_AND_LICENSE. 
The ABOUT PRs may need merged first.

```suggestion
                        isDisabled: it.not(it.userHasWritePermissionOnResource(RESOURCE_KEYS.ABOUT.EDITION_AND_LICENSE)),
```

2021-03-09 23:46 UTC, sbishel commented on components/admin_console/admin_definition.jsx
> +                it.not(it.userHasReadPermissionOnResource(RESOURCE_KEYS.AUTHENTICATION.LDAP)),
I don't think we want a check on this resource. I believe everyone should be able to see it.

2021-03-09 23:46 UTC, sbishel commented on components/admin_console/admin_definition.jsx
> +                it.not(it.userHasReadPermissionOnResource(RESOURCE_KEYS.AUTHENTICATION.SAML)),
Again feature discovery, no permission necessary.

2021-03-09 23:46 UTC, sbishel commented on components/admin_console/admin_definition.jsx
> +                        isDisabled: it.not(it.userHasWritePermissionOnResource(RESOURCE_KEYS.AUTHENTICATION.SAML)),
Allows to create a trial license. Will require write permisson on ABOUT_ EDITION_AND_LICENSE

2021-03-09 23:46 UTC, sbishel commented on e2e/cypress/support/api/role.js
> +        'sysconsole_write_user_management_channels',
adding twice, also on line 61

2021-03-09 23:46 UTC, sbishel commented on plugins/test/__snapshots__/main_menu_action.test.jsx.snap
> +          "sysconsole_read_compliance_custom_terms_of_service",
I added these with "integrations" as well. Just FYI in case of merge conflicts.

2021-03-11 16:31 UTC, hahmadia requested changes
One minor change

2021-03-11 16:31 UTC, hahmadia commented on components/admin_console/admin_definition.jsx
> +                            it.not(it.userHasReadPermissionOnResource(RESOURCE_KEYS.AUTHENTICATION.LDAP)),
This should be a Write Permission and not a read as Max pointed out in the Server PR.

2021-03-11 16:35 UTC, hahmadia commented on components/admin_console/admin_definition.jsx
> +                            it.not(it.userHasReadPermissionOnResource(RESOURCE_KEYS.AUTHENTICATION.LDAP)),
Give the ancillary of this endpoint to WRITE_AUTH instead of READ_AUTH on server side

2021-03-17 19:14 UTC, hahmadia approved these changes

2021-03-18 14:24 UTC, maxerenberg approved these changes

2021-03-18 22:39 UTC, sbishel commented
/update-branch

2021-03-19 18:24 UTC, sbishel approved these changes
@BenCookie95, @hahmadia Please review the last commit. Fixes a couple issues - 
- When only OpenId has access, section was hidden.
- if access to any authentication section, but not OpenId, threw javascript error

2021-03-19 18:37 UTC, hahmadia commented
Looks good @sbishel . Seems a test just needs to be fixed.

2021-03-19 19:52 UTC, merged