MM-30407: improve slow typing
mattermost/mattermost-webapp pull request #7685
Opened 2021-03-11 21:21 UTC by lieut-data

#### Summary
Skip rendering the sidebar channel menu until open. This goes hand-in-hand with the [linked Redux PR](https://github.com/mattermost/mattermost-redux/pull/1407) to address significant performance issues with the (new) sidebar that ultimately affect typing performance on busy servers.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-30407

2021-03-11 21:29 UTC, lieut-data commented
(Will fix tests re: not rendering the menu when not open.)

2021-03-12 15:22 UTC, hmhealey commented
Ah, the menu component. We meet again. This sounds good to me. I'd be slightly worried about this breaking any opening/closing animation, but I can't actually confirm that there was an animation previously. If there is one and it's not just my eyes tricking me, the closing animation would be messed up by this, but I'm pretty sure it doesn't actually have one.

2021-03-12 15:22 UTC, hmhealey approved these changes

2021-03-12 15:36 UTC, devinbinnie approved these changes

2021-03-12 15:36 UTC, devinbinnie commented on components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
> +                {isMenuOpen && this.renderDropdownItems()}
Well, hindsight is 20/20 I suppose :P

2021-03-15 21:39 UTC, jgilliam17 requested changes
Thanks @lieut-data 
- Characters are rendering as I type; I didn't notice any excessive slowness, although typing/rendering seems to be faster for me on Firefox, than it is on Chrome and Desktop app.
- One issue with the menus - `Move to` sub-menu opens on top of channel menu options
<img width="510" alt="Screen Shot 2021-03-15 at 5 31 46 PM" src="https://user-images.githubusercontent.com/52937121/111224290-9f690700-85b4-11eb-81d3-d75a80d16c75.png">

2021-03-17 14:29 UTC, hmhealey commented
I see the issues with the menu positioning as well. It must mess up the position calculation by having no items on first render.

2021-03-17 14:39 UTC, lieut-data commented
Oops, ignore this one for now @jgilliam17 -- I clicked on the wrong PR. Still addressing your feedback here.

2021-03-18 17:57 UTC, lieut-data commented
Looping in @deanwhillier for the most recent changes, along with a second review requested from @devinbinnie. The delta from the first change rips out `xOffset` in favour of just using `left: 100%` (or `right: 100%` for the plugin post menu context). Across all the browsers I've tested, this seems to "just work", including addressing the issue that Jelena originally found.

To both @hmhealey and my surprise, it doesn't even change the mobile web behaviour, for whatever that's worth :D

2021-03-18 18:01 UTC, lieut-data commented
@jgilliam17, I hate to short-circuit QA review before the (second) dev review has completed, but I'm wondering if I can get your eyes on this one in parallel with developer review as it's somewhat high profile and impacting multiple customers. The sidebar positioning /should/ now be resolved :)

2021-03-18 19:06 UTC, devinbinnie approved these changes

2021-03-18 21:44 UTC, jgilliam17 approved these changes
Thank you @lieut-data 
Tested, look good to merge.
- Verified menu issue is fixed. 
- When testing without network or CPU throttle, typing is working as expected. I was able to get some activity on the test server while typing, but it wasn’t enough to make any noticeable change in rendering of the text as I typed.  
- With CPU 4X (and 6X) slowdown I could see some slowness, more so on Ubuntu VM, but I would think that is expected. 
Per our conversation earlier, I'll try using 4x CPU throttle after this is merged to daily and update you on the results.

2021-03-18 21:45 UTC, merged

2021-03-18 21:45 UTC, lieut-data commented
Thanks so much, @jgilliam17!

2021-03-22 13:24 UTC, amyblais commented
@lieut-data v5.33.1 was just completed, this is ready to be cherry-picked to both v5.33 and v5.31 (based on https://community.mattermost.com/private-core/pl/fjsui3k7yjbx3gqic38k7wu95o).

2021-03-22 14:16 UTC, lieut-data commented
Thanks, @amyblais! I'll prepare the backports.

2021-03-22 15:24 UTC, lieut-data commented
/cherry-pick release-5.33

2021-03-22 15:24 UTC, mattermod commented
Cherry pick is scheduled.

2021-03-22 15:24 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
 * [new branch]          MM-33609              -> upstream/MM-33609
 * [new branch]          MM-33748              -> upstream/MM-33748
   ba7703a39..e471414ac  SectionsToSubSections -> upstream/SectionsToSubSections
   acb92f1f7..6e21569e0  cloud                 -> upstream/cloud
   95f8fd36a..64092c78e  feature/collapsed-reply-threads -> upstream/feature/collapsed-reply-threads
   76091620e..3fe62b033  master                -> upstream/master
 * [new branch]          proposal-epics        -> upstream/proposal-epics
   5d94391be..2a29620b2  update-status_dropdown_spec -> upstream/update-status_dropdown_spec
 * [new tag]             v5.33.1               -> v5.33.1
Fetching origin
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-webapp-#7685-upstream-release-5.33-1616426688
Switched to a new branch 'automated-cherry-pick-of-mattermost-webapp-#7685-upstream-release-5.33-1616426688'
Branch 'automated-cherry-pick-of-mattermost-webapp-#7685-upstream-release-5.33-1616426688' set up to track remote branch 'release-5.33' from 'upstream'.

+++ About to attempt cherry pick of PR #7685 with merge commit eb12f73a071bd0a4b49c4fa5b1cf673ac251521a.

error: could not apply eb12f73a0... MM-30407: improve slow typing (#7685)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU package-lock.json
UU package.json
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2021-03-22 16:17 UTC, amyblais commented
@lieut-data Is your preference to cherry-pick this to ``cloud`` or separately to v5.34 branch once it's created based on March 24th cloud release? (I'm guessing the latter)

2021-03-22 16:20 UTC, lieut-data commented
Ahh, hmm. At a minimum, yes to cherry-picking to the `v5.34` branch. I'm 0/5 on whether we push directly to cloud now or wait for it to get picked up organically. Thoughts, @amyblais?

2021-03-22 16:22 UTC, amyblais commented
@lieut-data I think cherry-picking to ``cloud`` works too since this has already been soaking on daily for some days. Please help with the ``cloud`` cherry-pick.