MM-33796 - Updating channel switcher css system console
mattermost/mattermost-webapp pull request #7696
Opened 2021-03-14 07:59 UTC by asaadmahmood

#### Summary
MM-33796 - Updating channel switcher css system console
**I have also updated the elevations to use the correct color value.**

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33796

#### Screenshots
<img width="794" alt="Screenshot 2021-03-14 at 12 58 39 PM" src="https://user-images.githubusercontent.com/11034289/111061392-027b7080-84c5-11eb-94b0-3d4436291bc3.png">

2021-03-14 20:54 UTC, esethna commented
@amyblais

2021-03-15 13:08 UTC, devinbinnie requested changes

2021-03-15 13:08 UTC, devinbinnie commented on sass/components/_channel-switcher.scss
> +            background: #fff;
We should be using the System Console theme variables here.
```suggestion
            background: rgba(var(--sys-center-channel-bg-rgb), 1);
```

2021-03-15 13:08 UTC, devinbinnie commented on sass/components/_channel-switcher.scss
> +            border: 1px solid #ddd;
Same here (not sure if the opacity is right here)
```suggestion
            border: 1px solid rgba(var(--sys-center-channel-color-rgb), 0.16);
```

2021-03-15 13:14 UTC, asaadmahmood commented
Done @devinbinnie

2021-03-15 13:16 UTC, nevyangelova approved these changes

2021-03-15 13:25 UTC, devinbinnie approved these changes

2021-03-15 15:57 UTC, asaadmahmood commented
@devinbinnie @nevyangelova Looks like the ticket also pointed out another issue in the system console, so fixing that as well.
We can get your reviews again when @michaelgamble has approved this.

2021-03-16 13:54 UTC, jgilliam17 commented
@asaadmahmood Search is not returning results on `Add people to channel` modal. Can you please take a look? Thanks.

2021-03-16 13:57 UTC, asaadmahmood commented
@jgilliam17 Do you have users added?
I just added some users and see the results.
Plus, that part is not changed here, it's only visual css changes.

<img width="727" alt="Screenshot 2021-03-16 at 6 57 20 PM" src="https://user-images.githubusercontent.com/11034289/111321094-723a5880-8689-11eb-8177-4f9efde4d079.png">

2021-03-16 14:36 UTC, michaelgamble approved these changes
Took a look with Assad, looks like the issues are resolved:
- input field focus state color looks correct
- Chip design looks correct
- pop-over adhering to the correct theme looks correct

2021-03-16 14:59 UTC, jgilliam17 commented
@asaadmahmood one small issue 
- `X` to cancel modal seems to be using one og the current theme variables
<img width="641" alt="Screen Shot 2021-03-16 at 9 57 13 AM" src="https://user-images.githubusercontent.com/52937121/111330792-a3456980-8646-11eb-9838-d4e7a2e7bd95.png">

2021-03-16 15:04 UTC, asaadmahmood commented
Should be fixed now @jgilliam17

2021-03-16 15:33 UTC, jgilliam17 approved these changes
Thank you @asaadmahmood 
Tested, looks good to merge.
- Verified theme of the dropdown and close `x`, input field focus and user chip are per design.

2021-03-16 16:56 UTC, amyblais commented
@devinbinnie Please help review as a priority.

2021-03-16 16:57 UTC, devinbinnie approved these changes

2021-03-16 16:58 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2021-03-16 17:18 UTC, mattermod commented
Trying to auto merge this PR.

2021-03-16 17:18 UTC, merged

2021-03-16 17:18 UTC, mattermod commented
Pull Request successfully merged
SHA: 4127c3bba7e0206e3d739ea01b071acb25327bfd

2021-03-16 17:18 UTC, mattermod commented
Cherry pick is scheduled.

2021-03-16 17:18 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
   812570d7f..aca7c82fd  MM-29959_Only_Sysadmin_Assigns_Roles -> upstream/MM-29959_Only_Sysadmin_Assigns_Roles
   b8afbfbcb..a6bc26efe  MM-32347-SITE-SUBSECTIONS -> upstream/MM-32347-SITE-SUBSECTIONS
   853df97f7..0bc8605ce  MM-32349_authentication -> upstream/MM-32349_authentication
   f48ae4c91..84c1eb641  MM-32350-integrations -> upstream/MM-32350-integrations
   c13ab8f3b..b72994015  MM-32351-Compliance   -> upstream/MM-32351-Compliance
   6b53158eb..2743ddc08  MM-32771-tips-and-nextsteps-improvements -> upstream/MM-32771-tips-and-nextsteps-improvements
 * [new branch]          MM-33540_button-warning -> upstream/MM-33540_button-warning
 * [new branch]          MM-33648              -> upstream/MM-33648
   c836db210..d9dcc8e2a  SectionsToSubSections -> upstream/SectionsToSubSections
 * [new branch]          TypeOnPath-larkox     -> upstream/TypeOnPath-larkox
   6bf8ff2ca..753df6ee6  cloud                 -> upstream/cloud
   0e0a5c3e8..4127c3bba  master                -> upstream/master
   00a959122..c756342e8  release-5.33          -> upstream/release-5.33
 * [new branch]          webapp-command-parser-sync -> upstream/webapp-command-parser-sync
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-webapp-#7696-upstream-release-5.33-1615915115
Switched to a new branch 'automated-cherry-pick-of-mattermost-webapp-#7696-upstream-release-5.33-1615915115'
Branch 'automated-cherry-pick-of-mattermost-webapp-#7696-upstream-release-5.33-1615915115' set up to track remote branch 'release-5.33' from 'upstream'.

+++ About to attempt cherry pick of PR #7696 with merge commit 4127c3bba7e0206e3d739ea01b071acb25327bfd.

error: could not apply 4127c3bba... [MM-33796][MM-33780] Updating channel switcher css system console (#7696)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU sass/components/_react-select.scss
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2021-03-16 17:19 UTC, amyblais commented
@asaadmahmood @devinbinnie Can you help cherry-pick to ``release-5.33`` and ``cloud`` branches please as a priority?