[GH-16717]
mattermost/mattermost-webapp pull request #7702
Opened 2021-03-15 09:45 UTC by aggmoulik

Signed-off-by: Moulik Aggarwal <qwertymoulik@gmail.com>

#### Summary

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes [redux](https://github.com/mattermost/mattermost-redux/pull/1412)
- Has mobile changes (please link here)

#### Screenshots

2021-03-15 09:45 UTC, mattermod commented
Hello @aggmoulik,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-03-15 17:46 UTC, devinbinnie commented
Hey @aggmoulik, thanks so much for the contribution!
I'm seeing seeing some TS compiler errors at this time, would you be able to fix them before I review? Let me know if you need help with any of them.

```
components/signup/signup_controller/index.ts:28:31 - error TS2339: Property 'NoAccounts' does not exist on type 'Partial<ClientConfig>'.

28     const noAccounts = config.NoAccounts === 'true';
                                 ~~~~~~~~~~

components/signup/signup_controller/signup_controller.test.tsx:59:14 - error TS2322: Type '{ location: { search: string; pathname: string; hash: string; }; noAccounts: boolean; loggedIn: boolean; isLicensed: boolean; isCloud: boolean; enableOpenServer: boolean; enableSAML: boolean; enableLDAP: boolean; ... 10 more ...; subscriptionStats: { ...; }; }' is not assignable to type 'Readonly<Props>'.
  Types of property 'subscriptionStats' are incompatible.
    Type '{ remainingSeats: number; isPaidTier: string; }' is missing the following properties from type 'SubscriptionStats': remaining_seats, is_paid_tier

59             <SignupController {...baseProps}/>,
                ~~~~~~~~~~~~~~~~

components/signup/signup_controller/signup_controller.test.tsx:71:14 - error TS2322: Type '{ isLicensed: boolean; location: { search: string; pathname: string; hash: string; }; noAccounts: boolean; loggedIn: boolean; isCloud: boolean; enableOpenServer: boolean; enableSAML: boolean; enableLDAP: boolean; ... 10 more ...; subscriptionStats: { ...; }; }' is not assignable to type 'Readonly<Props>'.
  Types of property 'subscriptionStats' are incompatible.
    Type '{ remainingSeats: number; isPaidTier: string; }' is not assignable to type 'SubscriptionStats'.

71             <SignupController {...props}/>,
                ~~~~~~~~~~~~~~~~

components/signup/signup_controller/signup_controller.test.tsx:95:14 - error TS2322: Type '{ location: { search: string; pathname: string; hash: string; }; actions: { addUserToTeamFromInvite: Mock<any, any>; getInviteInfo: Mock<any, any>; removeGlobalItem: Mock<any, any>; getTeamInviteInfo: Mock<...>; }; ... 16 more ...; subscriptionStats: { ...; }; }' is not assignable to type 'Readonly<Props>'.
  Types of property 'subscriptionStats' are incompatible.
    Type '{ remainingSeats: number; isPaidTier: string; }' is not assignable to type 'SubscriptionStats'.

95             <SignupController {...props}/>,
                ~~~~~~~~~~~~~~~~

components/signup/signup_controller/signup_controller.test.tsx:132:14 - error TS2322: Type '{ isCloud: boolean; location: { search: string; pathname: string; hash: string; }; subscriptionStats: { isPaidTier: string; remainingSeats: number; }; actions: { addUserToTeamFromInvite: Mock<any, any>; getInviteInfo: Mock<...>; removeGlobalItem: Mock<...>; getTeamInviteInfo: Mock<...>; }; ... 14 more ...; ldapLogin...' is not assignable to type 'Readonly<Props>'.
  Types of property 'subscriptionStats' are incompatible.
    Type '{ isPaidTier: string; remainingSeats: number; }' is missing the following properties from type 'SubscriptionStats': remaining_seats, is_paid_tier

132             <SignupController {...props}/>,
                 ~~~~~~~~~~~~~~~~

components/signup/signup_controller/signup_controller.test.tsx:158:14 - error TS2322: Type '{ location: { search: string; pathname: string; hash: string; }; actions: { addUserToTeamFromInvite: Mock<any, any>; removeGlobalItem: Mock<any, any>; getTeamInviteInfo: Mock<any, any>; }; ... 16 more ...; subscriptionStats: { ...; }; }' is not assignable to type 'Readonly<Props>'.
  Types of property 'subscriptionStats' are incompatible.
    Type '{ remainingSeats: number; isPaidTier: string; }' is not assignable to type 'SubscriptionStats'.

158             <SignupController {...props}/>,
                 ~~~~~~~~~~~~~~~~

components/signup/signup_controller/signup_controller.tsx:115:20 - error TS2339: Property 'isPaidTier' does not exist on type 'SubscriptionStats'.

115             const {isPaidTier, remainingSeats} = this.props.subscriptionStats;
                       ~~~~~~~~~~

components/signup/signup_controller/signup_controller.tsx:115:32 - error TS2339: Property 'remainingSeats' does not exist on type 'SubscriptionStats'.

115             const {isPaidTier, remainingSeats} = this.props.subscriptionStats;
```

2021-03-15 19:09 UTC, aggmoulik commented
Hy @devinbinnie These errors can be solved after merging the redux PR. Will you be kind to check for QA then it will be a great help.

2021-03-15 20:50 UTC, devinbinnie commented
> Hy @devinbinnie These errors can be solved after merging the redux PR. Will you be kind to check for QA then it will be a great help.

Ahh sorry, didn't notice that. My mistake. I've taken a look at that PR as well.

2021-03-18 18:49 UTC, devinbinnie requested changes
Thanks for the PR @aggmoulik, I've added some comments for you to review.

2021-03-18 18:49 UTC, devinbinnie commented on components/signup/signup_controller/signup_controller.tsx
> +    handleInvalidInvite = (err: { server_error_id: string; message: unknown }): void => {
Should this also be `ServerError`?

2021-03-18 18:49 UTC, devinbinnie commented on components/signup/signup_controller/signup_controller.tsx
> +    renderSignupControls = (): unknown[] | void => {
Shouldn't this always return an array?

2021-03-18 18:49 UTC, devinbinnie commented on components/signup/signup_controller/signup_controller.tsx
> +        let signupControls: any = [];
This should probably be of type `React.ReactNode[]`

2021-03-18 18:49 UTC, devinbinnie commented on components/signup/signup_controller/signup_controller.tsx
> +            let buttonText: any = (
Use type `React.ReactNode` here

2021-03-18 18:49 UTC, devinbinnie commented on components/signup/signup_controller/signup_controller.tsx
> +            let LDAPText: any = (
Same here

2021-03-18 18:49 UTC, devinbinnie commented on components/signup/signup_controller/signup_controller.tsx
> +        let locationSearch;
Can we avoid this block and just use the coalesce block below?

2021-03-18 18:49 UTC, devinbinnie commented on components/signup/signup_controller/signup_controller.tsx
> +                                to={'/login' + locationSearch}
```suggestion
                                to={'/login' + (this.props.location?.search || '')}
```

2021-03-25 17:35 UTC, lieut-data approved these changes
Nothing to add beyond @devinbinnie's comments above -- let us know if we can help @aggmoulik :)

2021-03-26 08:00 UTC, aggmoulik commented
Yeah, I just didn't get time from the office last week. So, will update on weekends.

2021-03-28 17:26 UTC, aggmoulik commented on components/signup/signup_controller/signup_controller.tsx
> +    isLicensed?: boolean;
Actually I tried but I am getting error from the `index.ts` file as I have changed it to `React.ComponentClass` as they want everything to be optional. I was hoping if you may know about it.

2021-03-28 17:34 UTC, aggmoulik commented on components/signup/signup_controller/signup_controller.tsx
> +                usedBefore = props?.usedBefore ? props.usedBefore : usedBefore;
```suggestion
                usedBefore = props?.usedBefore ?? usedBefore;
```
I prefer to use `??` nullish coalescing operator as `| |` does check for falsy values like `0` , `false` etc.

2021-03-28 17:59 UTC, aggmoulik commented on components/signup/signup_controller/signup_controller.tsx
> +            data: any;
I couldn't find type from the `mattermost-redux`, can you please help me out here .

2021-04-08 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2022-09-29 22:50 UTC, M-ZubairAhmed commented
file do not exists any more

2022-09-29 22:50 UTC, closed without merging