Fix error when root post has been deleted
mattermost/mattermost-webapp pull request #7767
Opened 2021-03-26 17:39 UTC by ThiefMaster

#### Summary
When posts were deleted in bulk there may be posts whose root post doesn't exist anymore. I believe this usually happens when posts are deleted due to an EE data retention policy.

This caused a JS error when clicking the reply button on the remaining post from the thread because it tried to get the `reply_count` from a `null` (or `undefined`, I don't remember).

#### Ticket Link
MM-34310

2021-03-26 17:39 UTC, mattermod commented
Hello @ThiefMaster,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-03-29 05:53 UTC, nevyangelova approved these changes

2021-03-29 12:32 UTC, mkraft requested changes
The code change looks good and we just need a test to prove that it fixes the bug.

2021-03-29 12:46 UTC, ThiefMaster commented
iirc. there aren't any existing tests for this particular logic so if someone more familiar with the webapp code added them it'd probably be faster

2021-03-29 13:13 UTC, Willyfrog approved these changes
LGTM! Thanks!

+1 on tests

2021-03-29 13:19 UTC, mkraft commented
> iirc. there aren't any existing tests for this particular logic so if someone more familiar with the webapp code added them it'd probably be faster

Thanks @ThiefMaster, I've sent the request for the development of the tests to the appropriate team.

2021-03-29 13:30 UTC, ThiefMaster commented
I had another look, and I think I managed to add a test that covers it. Easier than I expected it to be in the end.

Tye only thing I don't like yet is the fact that the mock is global, but when doing it inside the test function it didn't apply (the test did not fail without my fix).

2021-03-29 13:49 UTC, ThiefMaster commented on components/rhs_thread/rhs_thread.test.tsx
> +        (Utils.getRootPost as any).mockImplementation(() => undefined);
I don't like the `(... as any)` here but vscode was showing a type violation. The tests succeed anyway. Let me know if you prefer it without the typecast.

2021-04-09 13:43 UTC, mkraft approved these changes

2021-04-14 19:47 UTC, jgilliam17 commented
Thank you @ThiefMaster I am not sure how to test. Deleting a parent post via api didn't work as it removes replies. Any suggestions? Thanks.

2021-04-14 19:50 UTC, ThiefMaster commented
In my case I deleted it directly via the database - I think that's the only quick way to do this. If you have database access just get the post id and run `DELETE FROM posts WHERE id = 'xxx';` and then reload the page.

Using an EE retention policy *may* work as well, but I'm not sure how fine-grained it is, so using that to test may be a bit tedious and take too long...

2021-04-14 22:13 UTC, jgilliam17 commented
Thanks @ThiefMaster I'm re-assigning to @furqanmlk for testing.

2021-04-19 19:19 UTC, furqanmlk reviewed
![image](https://user-images.githubusercontent.com/6909890/115291267-8a871280-a122-11eb-9dc1-da7fd8200454.png)

Unable to reproduce error

2021-05-01 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-05-04 12:24 UTC, Willyfrog commented
@ThiefMaster can you help @furqanmlk with the process to reproduce the error

2021-05-04 12:25 UTC, ThiefMaster commented
Since https://github.com/mattermost/mattermost-webapp/pull/7175 got merged (where the developer cherrypick/ported the changes from my PR) my guess would be that my PR is no longer necessary...

2021-05-04 12:43 UTC, Willyfrog commented
> Since #7175 got merged (where the developer cherrypick/ported the changes from my PR) my guess would be that my PR is no longer necessary...

is it ok to close the PR then? double checking just in case you weren't meaning that :)

2021-05-04 12:45 UTC, ThiefMaster commented
Yes, I would say so. Maybe @calebroseland can confirm that his change indeed fully covers what I changed here though.

2021-05-04 12:58 UTC, Willyfrog commented
ok, if @calebroseland doesn't confirm, we can always reopen. Still! thanks for the PR!

2021-05-04 12:58 UTC, closed without merging

2021-05-04 20:47 UTC, calebroseland commented
> Yes, I would say so. Maybe @calebroseland can confirm that his change indeed fully covers what I changed here though.

Yep, the picked/ported [change](https://github.com/mattermost/mattermost-webapp/commit/e93ecd995fe6643896563f418ab7e78ad43f3277) should fully cover this. (`rootPost && ...` merged into the changes #7175 did.)