Promote and Update
mattermost/mattermost-webapp pull request #7810
Opened 2021-03-31 23:07 UTC by furqanmlk

#### Summary

Promoted ```custom_emoji_2_spec.js``` to prod
Added unstable test case to ```custom_emoji_3_spec.js``` 
Fixed ```MM-T1391 Verify the manage options displayed for Guest User```

2021-04-01 14:45 UTC, josephbaylon requested changes
@furqanmlk Please fix lint issues

2021-04-01 22:54 UTC, josephbaylon approved these changes
LGTM

2021-04-02 01:32 UTC, prapti requested changes
Hi Furqan,
I'm not too sure about promoting `custom_emoji_3` yet. In the last 5 runs, looks like the only test that's been stable is T2183.
T2184 has failed in 2 runs (builds 4061 and 3972).
T2185 has failed in 2 runs (builds 4012 and 3948).
Should we wait on promoting that spec until we take a deeper look?

2021-04-02 02:10 UTC, furqanmlk commented
Hi @prapti, 
I think you misunderstood. 
custom_emoji_3_spec.js did get promoted. I added unstable test cases to this spec.

> Hi Furqan,
> 
> I'm not too sure about promoting `custom_emoji_3` yet. In the last 5 runs, looks like the only test that's been stable is T2183.
> 
> T2184 has failed in 2 runs (builds 4061 and 3972).
> 
> T2185 has failed in 2 runs (builds 4012 and 3948).
> 
> Should we wait on promoting that spec until we take a deeper look?

2021-04-02 17:28 UTC, prapti commented
Oh sorry @furqanmlk I meant `custom_emoji_2` (not `custom_emoji_3`). Since you're promoting that spec, and only one test in that file (T2183) seems stable but not the other two (T2184 which is still in that file, and T2185 which you're moving the unstable `custom_emoji_3`) are both quite unstable.

2021-04-07 11:13 UTC, saturninoabril approved these changes
Not sure if moving around test case (like `MM-T2185`) is something that we should normally do. In my mind, move test either a passing/failing test into a new spec file to isolate but a fix should be made to the failing test on the same PR, unless such failed test is a known issue like product bug, or any limitation in our test infra.

I'm good as is but open for discussion as a group.

2021-04-07 19:15 UTC, furqanmlk commented on e2e/cypress/integration/emoji/custom_emoji_2_spec.js
> +
```suggestion
```

2021-04-07 19:19 UTC, furqanmlk commented
> Oh sorry @furqanmlk I meant `custom_emoji_2` (not `custom_emoji_3`). Since you're promoting that spec, and only one test in that file (T2183) seems stable but not the other two (T2184 which is still in that file, and T2185 which you're moving the unstable `custom_emoji_3`) are both quite unstable.

Thanks @prapti 
Yes you are right, I moved T2183 to wrong file. 
I have moved T2183 to `custom_emoji_1` as it is now stable, rest I did not change.

2021-04-07 19:21 UTC, furqanmlk commented
> Not sure if moving around test case (like `MM-T2185`) is something that we should normally do. In my mind, move test either a passing/failing test into a new spec file to isolate but a fix should be made to the failing test on the same PR, unless such failed test is a known issue like product bug, test compatibility issue among server edition/license (Cloud, E20, TE) or a limitation in our test infra.
> 
> I'm good as is but open for discussion as a group.

Thanks @saturninoabril , yes you are right I misplaced the stable test case to wrong file.
everything is back to original file except T2183, it has moved to `custom_emoji_1` as it is stable.

2021-04-08 01:05 UTC, prapti approved these changes
Agree with Saturn's argument.
Looks good for now.
Thank you for fixing it @furqanmlk!

2021-04-08 01:06 UTC, merged