MM-23120 Custom status issues
mattermost/mattermost-webapp pull request #7843
Opened 2021-04-08 14:26 UTC by manojosh

#### Summary

- Fixed MM-34095 Show recent statuses on the set status confirmation screen for more efficient status switching
- Fixed MM-33149 Updated "Mobile Push Notifications" text in Account Settings
- Fixed MM-33195  Custom Status emoji misaligned in profile popover
- Fixed MM-33246 Custom Status Modal: increase max height so that all default options are visible without scrolling
- Fixed MM-33433 Custom statuses should appear in channel switcher
- Fixed MM-34571 Tooltip for custom status without text has emoji misaligned
- Fixed MM-33431 Custom status emoji size match the emoji size used in reactions and alignment needs tweaking
- Fixed MM-33214 With RHS open, pin icon and channel description overlap statuses in lower browser widths
- Fixed MM-33220 Reduce opacity of custom status emoji in LHS DMs

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34095
https://mattermost.atlassian.net/browse/MM-33149
https://mattermost.atlassian.net/browse/MM-33195
https://mattermost.atlassian.net/browse/MM-33246
https://mattermost.atlassian.net/browse/MM-33433
https://mattermost.atlassian.net/browse/MM-34571
https://mattermost.atlassian.net/browse/MM-33431
https://mattermost.atlassian.net/browse/MM-33214
https://mattermost.atlassian.net/browse/MM-33220

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/7750

2021-04-08 14:26 UTC, mattermod commented
Hello @manojosh,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-04-08 15:32 UTC, matthewbirtch requested changes
Thanks @manojosh! Nice work resolving these issues. I just have a few really minor points:

1. In the Channel Switcher, can we make the left margin on the custom status 8px instead of 4px? It feels like it needs a bit more space there
2. This may not be related to this PR, but the bullet after the status in the DM channel header feels odd now. I wonder if we should just consider removing this since the spacing may provide enough differentiation here
<img width="218" alt="Screen Shot 2021-04-08 at 11 29 20 AM" src="https://user-images.githubusercontent.com/2040554/114054295-bde1bb80-985d-11eb-85d0-7abacbfd1065.png">
3. For the reduced opacity emojis in the left sidebar, can we make them full opacity when you hover over them?

2021-04-08 18:32 UTC, esethna commented
Thanks @manojosh, one thing I noticed: The modal height should dynamically resize to accommodate all selections as noted in the ticket (note that the max options showing would be 10: 5 recent and 5 suggestions), right now it is scrolling to reveal all options: https://mattermost.atlassian.net/browse/MM-33246
![image](https://user-images.githubusercontent.com/14333569/114078484-da7df380-985d-11eb-8c41-6173206e2717.png)

2021-04-09 08:22 UTC, manojosh commented
@matthewbirtch All the changes are done.

@esethna If we don't want any scrolling to accommodate all the 10 suggestions then the modal looks like this.

![Screenshot from 2021-04-09 13-36-32](https://user-images.githubusercontent.com/77336594/114149671-c9ee7b80-9938-11eb-9651-315e3ccc1ea8.png)

So we have to change the positioning of the modal. Right now, it's done by giving margin-top to the modal as **calc(50vh - 240px)**
I thought of changing it to **calc(50vh - 320px)**. Here is how it looks

![Screenshot from 2021-04-09 13-47-09](https://user-images.githubusercontent.com/77336594/114151207-8563df80-993a-11eb-8e9a-ac5d22a7c173.png)
![Screenshot from 2021-04-09 13-47-27](https://user-images.githubusercontent.com/77336594/114151225-898ffd00-993a-11eb-9ed1-ce0149de1464.png)

Is this fine or do you want it to be dynamically changed as the no. of recent statuses increase? If so, what is the minimum value of margin-top which I should use?

2021-04-09 14:30 UTC, matthewbirtch commented
> @matthewbirtch All the changes are done.
> 
> @esethna If we don't want any scrolling to accommodate all the 10 suggestions then the modal looks like this.
> 
> ![Screenshot from 2021-04-09 13-36-32](https://user-images.githubusercontent.com/77336594/114149671-c9ee7b80-9938-11eb-9651-315e3ccc1ea8.png)
> 
> So we have to change the positioning of the modal. Right now, it's done by giving margin-top to the modal as **calc(50vh - 240px)**
> I thought of changing it to **calc(50vh - 320px)**. Here is how it looks
> 
> ![Screenshot from 2021-04-09 13-47-09](https://user-images.githubusercontent.com/77336594/114151207-8563df80-993a-11eb-8e9a-ac5d22a7c173.png)
> ![Screenshot from 2021-04-09 13-47-27](https://user-images.githubusercontent.com/77336594/114151225-898ffd00-993a-11eb-9ed1-ce0149de1464.png)
> 
> Is this fine or do you want it to be dynamically changed as the no. of recent statuses increase? If so, what is the minimum value of margin-top which I should use?

@esethna I think we should consider this effort as a separate PR if we want to merge this in for the next release. Accommadating for 10 options without scrolling makes for a pretty tall modal and I don't think we should do this. Also, it wouldn't work well for people on smaller resolution. Can we leave it as-is for now and create a follow-up ticket to look in to dynamically resizing if we feel strongly?

2021-04-09 14:53 UTC, esethna commented
@matthewbirtch @manojosh okay that's fine, we can leave as is. But I'm not clear on what changed in this PR from the existing behaviour? Can we just update the ticket to reflect what changed so QA can test appropriately?

2021-04-09 15:16 UTC, manojosh commented
@esethna Actually what changed was the min and max height of the modal. Earlier if any one of the suggestions was present in the recents then the **Recents** title would appear along with the scrollbar but now the height is adjusted to accommodate all the suggestions along with the **Recents** and **Suggestions** titles.

Refer to the gif here https://mattermost.atlassian.net/browse/MM-33246

2021-04-09 16:04 UTC, matthewbirtch commented
> 1. In the Channel Switcher, can we make the left margin on the custom status 8px instead of 4px? It feels like it needs a bit more space there
> 2. This may not be related to this PR, but the bullet after the status in the DM channel header feels odd now. I wonder if we should just consider removing this since the spacing may provide enough differentiation here
> 
> <img alt="Screen Shot 2021-04-08 at 11 29 20 AM" width="218" src="https://user-images.githubusercontent.com/2040554/114054295-bde1bb80-985d-11eb-85d0-7abacbfd1065.png">
> 
> 3. For the reduced opacity emojis in the left sidebar, can we make them full opacity when you hover over them?

These changes all look to be resolved now. I'll approve

2021-04-09 16:04 UTC, matthewbirtch approved these changes

2021-04-09 16:59 UTC, esethna commented
> height is adjusted to accommodate all the suggestions along with the **Recents** and **Suggestions** titles.

Got it, I adjusted the ticket description, thanks

2021-04-09 17:00 UTC, esethna commented
@michelengelen @Willyfrog for dev review, thanks!

2021-04-12 06:30 UTC, michelengelen approved these changes
Only a small suggestion from my side ... otherwise LGTM! Thanks for your contribution! 🙇🏻‍♂️

2021-04-12 06:30 UTC, michelengelen commented on components/custom_status/custom_status_modal.tsx
> +
couldn't this be simpified by using nullish coalescent?

```suggestion
    const showSuggestions = !isStatusSet || (currentCustomStatus?.emoji === emoji && text && currentCustomStatus?.text === text);
        
```

2021-04-12 10:24 UTC, Willyfrog approved these changes
LGTM

2021-04-16 15:56 UTC, esethna commented
Friendly ping @ogi-m for QA review.

2021-04-16 19:27 UTC, ogi-m commented
#### Verified the following:
- MM-34095
- MM-33149
- MM-33195
- MM-33433
- MM-34571
- MM-33431
- MM-33214
- MM-33220

#### Two questions:
1. The emoji seem to me like they're sitting too low now in the LHS header? @matthewbirtch
It's more apparent with squared emoji and not with faces.
PR vs master:
![PR](https://user-images.githubusercontent.com/15314183/115074392-f0448600-9ef9-11eb-8d2e-2ac423befceb.jpg) ![daily](https://user-images.githubusercontent.com/15314183/115074305-d0ad5d80-9ef9-11eb-8973-4929dbdb5ea0.jpg)


2. If I'm understanding correctly, [the ticket for showing all options](https://mattermost.atlassian.net/browse/MM-33246) hasn't been implemented in the PR and will be done separately? @esethna

2021-04-16 20:32 UTC, matthewbirtch commented
> 1. The emoji seem to me like they're sitting too low now in the LHS header? @matthewbirtch
>    It's more apparent with squared emoji and not with faces.
>    PR vs master:

It's weird the calendar emoji specifically seems to sit a bit low. Most other emojis seems to sit appropriately. I think it's fine.
![image](https://user-images.githubusercontent.com/2040554/115080778-4ea93e80-9ed1-11eb-86db-c4d469d01350.png)

2021-04-19 08:15 UTC, michelengelen approved these changes

2021-04-19 17:24 UTC, esethna commented
@ogi-m re # 2 ^, correct, it is not part of this PR

2021-04-19 17:26 UTC, ogi-m approved these changes
Thanks guys, all good then! Approving 👍🏻

2021-04-19 17:28 UTC, amyblais commented
@esethna Sure, why not in Cloud April 21st release?

2021-04-19 17:29 UTC, esethna commented
@amyblais sure if there's still time for that release please go ahead

2021-04-19 17:32 UTC, michelengelen commented
/update-branch

2021-04-19 17:44 UTC, Willyfrog commented
/update-branch

2021-04-19 17:45 UTC, mattermod commented
We don't have permissions to update this PR, please contact the submitter to apply the update.

2021-04-19 17:45 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2021-04-20 06:29 UTC, michelengelen commented
Hi @manojosh ... I am sorry, but current changes to master created conflicts with your branch. Could you please merge master again and resolve the conflicts? I will merge it as soon as changes are coming in! 

Again ... I am sorry this causes trouble for you! 🙇🏻‍♂️

2021-04-20 06:46 UTC, manojosh commented
No problem @michelengelen.. Resolving the conflicts

2021-04-20 07:33 UTC, michelengelen commented
Thanks a lot @manojmalik20 ... will merge it now!

2021-04-20 07:33 UTC, merged

2021-04-20 07:33 UTC, mattermod commented
Cherry pick is scheduled.

2021-04-20 07:33 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
   60d7119c5..383ce8b9b  MM-32962_dependency-updates -> upstream/MM-32962_dependency-updates
   92e045091..ba42ce9f4  MM-34758   -> upstream/MM-34758
 * [new branch]          MM-35021   -> upstream/MM-35021
   94428f45c..00baa5885  cloud      -> upstream/cloud
   9757eb1a6..c2c4725be  master     -> upstream/master
Fetching origin
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
!!! 'upstream/release-5.35' not found. The second argument should be something like upstream/release-0.21.
    (In particular, it needs to be a valid, existing remote branch that I can 'git checkout'.)

+++ Returning you to the master branch and cleaning up.

```

2021-04-20 09:59 UTC, Willyfrog commented
/cherry-pick cloud

2021-04-20 09:59 UTC, mattermod commented
Cherry pick is scheduled.

2021-04-20 09:59 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.112.4' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
   00baa5885..ce3a686e8  cloud      -> upstream/cloud
   142de1d1f..5a9f4cc08  master     -> upstream/master
Fetching origin
Failed to add the RSA host key for IP address '140.82.112.4' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-webapp-#7843-upstream-cloud-1618912769
Switched to a new branch 'automated-cherry-pick-of-mattermost-webapp-#7843-upstream-cloud-1618912769'
Branch 'automated-cherry-pick-of-mattermost-webapp-#7843-upstream-cloud-1618912769' set up to track remote branch 'cloud' from 'upstream'.

+++ About to attempt cherry pick of PR #7843 with merge commit c2c4725befd6265ab90f45c054aa9340fe8787b1.

error: could not apply c2c4725be... MM-23120 Custom status issues (#7843)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU components/suggestion/switch_channel_provider.jsx
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2021-04-20 12:20 UTC, amyblais commented
@Willyfrog Seems that the cherry-pick didn't work

2021-04-20 12:48 UTC, Willyfrog commented
yeah! I'll try to do that manually

2021-04-20 13:19 UTC, Willyfrog commented
actually @michelengelen can you do the cherry-picking? seems the reason for the conflict is that https://github.com/mattermost/mattermost-webapp/pull/7932 is not in both branches