Update en.json
mattermost/mattermost-webapp pull request #7854
Opened 2021-04-10 11:36 UTC by ctlaltdieliet

fixing typo

2021-04-10 11:36 UTC, mattermod commented
Hello @ctlaltdieliet,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-04-12 13:31 UTC, Willyfrog approved these changes

2021-04-12 13:32 UTC, Willyfrog requested changes
can you please  update the branch and fix the conflicts? other than that looks good

2021-04-12 14:11 UTC, lieut-data approved these changes

2021-04-12 14:13 UTC, lieut-data commented
(I took a stab at fixing the merge conflicts that occurred upstream.)

2021-04-12 14:20 UTC, Willyfrog approved these changes

2021-04-12 14:20 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2021-04-12 14:34 UTC, merged