[MM-34765][MM-34824][MM-34995][MM-34998] - Minor UX fixes
mattermost/mattermost-webapp pull request #7980
Opened 2021-04-23 11:31 UTC by nevyangelova

#### Summary
This PR addresses several minor UX fixes to borders and hard coded values. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34765
https://mattermost.atlassian.net/browse/MM-34824
https://mattermost.atlassian.net/browse/MM-34995
https://mattermost.atlassian.net/browse/MM-34998

```release-note
Added new API endpoints POST /api/v4/foo, GET api/v4/foo, and GET api/v4/foo/:foo_id.
```

```release-note
Added a new config setting ServiceSettings.FooBar. Added a new column Foo to the Users table.
```

```release-note
NONE
```
-->
```release-note
```

2021-04-23 15:08 UTC, matthewbirtch requested changes
Thanks @nevyangelova.

1. MM-34765 - border/divider - reduce opacity slightly
    - I think 8% maybe is too faint for dark themes, sorry. Is it possible to go to 12%? If not, I think we'll need to go to 16%
    - We should apply this color to the date separator line as well

2. MM-34824- Team Icon Active Border should display at full opacity
    - This is good to go 👍 

3. MM-34995 - Team Icon Background color is hard-coded
   - The default state looks better now (uses `--sidebar-text-16` 👍 )
    - I'm still seeing a hardcoded white for the hover state which doesn't seem to work with all themes
![image](https://user-images.githubusercontent.com/2040554/115889957-709b4780-a422-11eb-87b8-9c1d28f7cdcf.png)
    - Also, in the hover state, can you change the opacity on the outer border (box-shadow) to 16% rather than 32%?
    - The active state still has a hard-coded value for the background
![image](https://user-images.githubusercontent.com/2040554/115890990-9117d180-a423-11eb-9663-605c093c35b6.png)
    - If you want to sync up here for a live review that might be easier

4. MM-34998 - Invite users button in channel intro has incorrect padding
    - Can we adjust the left and right padding to 16px as per the [Button Component](https://www.figma.com/file/2uYWxjnMJ9IQDOba9b9bfV/Components-Buttons?node-id=1088%3A1091)?

2021-04-23 15:10 UTC, hmhealey requested changes

2021-04-23 15:10 UTC, hmhealey commented on sass/layout/_headers.scss
> +    border-bottom: 1px solid var(--center-channel-color-08);
We should use rgba instead of the transparent theme variables for anything new

2021-04-23 15:10 UTC, hmhealey commented on sass/layout/_sidebar-left.scss
> +    border-right: 1px solid var(--center-channel-color-08);
Same in these other files. We shouldn't be reverting to the transparent theme variables.

2021-04-26 06:43 UTC, michelengelen approved these changes
Other than the changes requested from @hmhealey this LGTM! 🎉 
Thanks!

2021-04-26 09:57 UTC, nevyangelova commented
@matthewbirtch fixed

2021-04-26 13:23 UTC, matthewbirtch approved these changes
Looks awesome @nevyangelova! Thanks for the great work.

2021-04-26 17:47 UTC, jgilliam17 approved these changes
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified divider borders, active border on team avatar, team icon background color and padding on invite users button.

2021-04-27 13:57 UTC, hmhealey requested changes

2021-04-27 13:57 UTC, hmhealey commented on components/widgets/team_icon/team_icon.scss
> +    background-color: var(--sidebar-text-16);
You missed a few more of these
```suggestion
    background-color: rgba(var(--sidebar-text-rgb), 0.16);
```

2021-04-27 13:57 UTC, hmhealey commented on components/widgets/team_icon/team_icon.scss
> +        box-shadow: 0 0 0 3px var(--sidebar-text-30);
```suggestion
        box-shadow: 0 0 0 3px rgba(var(--sidebar-text-rgb), 0.30);
```

2021-04-27 13:57 UTC, hmhealey commented on components/widgets/team_icon/team_icon.scss
> +        background-color:  var(--sidebar-text-30);
```suggestion
        background-color:  rgba(var(--sidebar-text-rgb), 0.30);
```

2021-04-27 13:57 UTC, hmhealey commented on components/widgets/team_icon/team_icon.scss
> +        background-color: var(--sidebar-text-30);
```suggestion
        background-color: rgba(var(--sidebar-text-rgb), 0.30);
```

2021-04-27 13:57 UTC, hmhealey commented on components/widgets/team_icon/team_icon.scss
> +        box-shadow: 0 0 0 3px rgba(var(--sidebar-text-active-border-rgb), 1);
```suggestion
        box-shadow: 0 0 0 3px var(--sidebar-text-active-border);
```

2021-04-27 13:57 UTC, hmhealey commented on components/widgets/team_icon/team_icon.scss
> +        box-shadow: 0 0 0 3px rgba(var(--sidebar-text-active-border-rgb), 1);
```suggestion
        box-shadow: 0 0 0 3px var(--sidebar-text-active-border);
```

2021-04-27 13:57 UTC, hmhealey commented on sass/layout/_team-button.scss
> +                background-color: var(--sidebar-text-08)
```suggestion
                background-color: rgba(var(--sidebar-text-rgb), 0.08)
```

2021-04-27 13:57 UTC, hmhealey commented on sass/layout/_team-button.scss
> +                background-color: var(--sidebar-text-16);
```suggestion
                background-color: rgba(var(--sidebar-text-rgb), 0.16);
```

2021-04-27 14:00 UTC, nevyangelova commented
sorry @hmhealey I wasn't sure about the other places..

2021-04-27 16:10 UTC, hmhealey approved these changes

2021-04-27 16:12 UTC, merged