remove URL slug for GMs in channel switcher
mattermost/mattermost-webapp pull request #8016
Opened 2021-04-28 14:45 UTC by michelengelen

#### Summary
removes the URL "slug" information for GM's in the channel switcher

#### Ticket Link
[MM-35085](https://mattermost.atlassian.net/browse/MM-35085)

#### Screenshots
<img width="620" alt="Screenshot 2021-04-28 at 16 43 20" src="https://user-images.githubusercontent.com/32863416/116423471-024eee80-a841-11eb-8bb6-c5a0bd09da72.png">

#### Release Note
```release-note
removes the URL "slug" information for GM's in the channel switcher
```

2021-04-28 15:11 UTC, matthewbirtch requested changes
Looks good @michelengelen. Slug is removed for GMs now

2021-04-28 15:11 UTC, matthewbirtch approved these changes
Looks good @michelengelen!

2021-04-28 20:52 UTC, devinbinnie approved these changes

2021-04-28 22:58 UTC, jgilliam17 approved these changes
Thanks @michelengelen 
Tested, looks good to merge.
- Verified GM slug on channel switcher has been removed.

2021-04-29 02:39 UTC, calebroseland approved these changes

2021-04-29 07:01 UTC, merged

2021-04-29 07:01 UTC, mattermod commented
Cherry pick is scheduled.

2021-04-29 12:57 UTC, amyblais commented
/cherry-pick cloud

2021-04-29 12:57 UTC, mattermod commented
Cherry pick is scheduled.