MM-T1128 Announcement Banner - Dismissible banner shows long text truncated
mattermost/mattermost-webapp pull request #8168
Opened 2021-05-26 21:00 UTC by M-ZubairAhmed

#### Summary

#### Ticket Link

https://automation-test-cases.vercel.app/test/MM-T1128

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note

```

2021-05-26 21:00 UTC, mattermod commented
Hello @M-ZubairAhmed,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-05-27 03:51 UTC, M-ZubairAhmed commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +            "Here's an announcement! It has a link: http://example.com. It's a really long announcement, because we have a lot to say. Be sure to read it all, click the link, then dismiss the banner,
> todo change this to bannerEmbeddedLink

2021-05-27 03:55 UTC, M-ZubairAhmed commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +            );
i missed one point from spec
> URL is a live link
i think if i just prove that anchor tag with href exists ?

2021-05-27 04:28 UTC, M-ZubairAhmed commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +            cy.get('input').should('be.visible').clear().type(bannerText);
when i wrote the invoke type for entering the text, the input text was vanishing as soon as input lost focus, 
so i had to resort to type methods

2021-05-28 16:53 UTC, hmhealey approved these changes
Looks good to me assuming you've addressed the things you wanted to in those comments.

2021-05-29 11:09 UTC, M-ZubairAhmed commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +            cy.get('input').should('be.visible').clear().type(bannerText);
figured it out, had to add type at the end

2021-05-29 11:10 UTC, M-ZubairAhmed commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +            );
added the url test too

2021-05-29 11:10 UTC, M-ZubairAhmed commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +            "Here's an announcement! It has a link: http://example.com. It's a really long announcement, because we have a lot to say. Be sure to read it all, click the link, then dismiss the banner,
done

2021-06-01 01:02 UTC, saturninoabril requested changes
Thanks @M-ZubairAhmed! Tested and passed. LGTM, except for one comment.

Note: I filed https://mattermost.atlassian.net/browse/MM-36095 to address UI polish in showing Announcement banner.

2021-06-01 01:17 UTC, saturninoabril commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +
```suggestion
import * as TIMEOUTS from '../../../fixtures/timeouts';

// Group: @enterprise @system_console @announcement_banner

```

2021-06-02 17:49 UTC, josephbaylon requested changes
Overall looks good. Please apply Saturn's latest suggestions. Thanks!

2021-06-04 20:14 UTC, M-ZubairAhmed commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +describe('Announcement Banner', () => {
✅  Updated as per request/discussion

2021-06-04 20:14 UTC, M-ZubairAhmed commented on e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
> +        cy.apiAdminLogin();
✅  Updated as per request/discussion

2021-06-04 20:17 UTC, josephbaylon approved these changes
LGTM. Thanks @M-ZubairAhmed !!

2021-06-04 22:37 UTC, josephbaylon commented
@saturninoabril I know you're out in the next 2 weeks but this PR won't allow me to merge unless you approve of it. Please take a look if you have the chance. Thanks!

2021-06-04 22:39 UTC, saturninoabril approved these changes
Thanks @M-ZubairAhmed!

2021-06-04 22:39 UTC, merged