MM-35932: changes strings due to re-packaging
mattermost/mattermost-webapp pull request #8170
Opened 2021-05-27 09:01 UTC by koox00

#### Summary

Updates in-product strings referencing E10 & E20 to new packaging.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-35932

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note
NONE
```

2021-06-24 15:49 UTC, wiersgallak commented on components/admin_console/feature_discovery/features/permissions.tsx
> +            titleDefault='Set team-based permissions with Mattermost Enterprise'
This should be 'Set team-based permissions with Mattermost Professional`

2021-06-24 15:51 UTC, wiersgallak commented on components/admin_console/feature_discovery/features/announcement_banner.tsx
> +            titleDefault='Create custom announcement banners with Mattermost Enterprise'
```suggestion
            titleDefault='Create custom announcement banners with Mattermost Professional'
```

2021-06-24 15:52 UTC, wiersgallak commented on components/admin_console/feature_discovery/features/permissions.tsx
> +            titleDefault='Set team-based permissions with Mattermost Enterprise'
```suggestion
            titleDefault='Set team-based permissions with Mattermost Professional'
```

2021-06-24 15:52 UTC, wiersgallak commented on i18n/en.json
> +  "admin.announcement_banner_feature_discovery.title": "Create custom announcement banners with Mattermost Enterprise",
```suggestion
  "admin.announcement_banner_feature_discovery.title": "Create custom announcement banners with Mattermost Professional",
```

2021-06-24 15:53 UTC, wiersgallak commented on i18n/en.json
> +  "admin.permissions_feature_discovery.title": "Set team-based permissions with Mattermost Enterprise",
```suggestion
  "admin.permissions_feature_discovery.title": "Set team-based permissions with Mattermost Professional",
```

2021-08-09 16:24 UTC, jwilander approved these changes
LGTM

2021-08-09 16:53 UTC, wiersgallak approved these changes
LGTM

2021-08-09 17:09 UTC, hahmadia approved these changes

2021-08-09 19:25 UTC, michaelgamble requested changes
Only one change that I see.. the font for headings aren't matching our updated design system / whats in the desing.

Currently the heading font is showing "Open Sans" - open sans is now only for body content.

The heading font should be "Metropolis"
![image](https://user-images.githubusercontent.com/31866506/128762563-c7c26245-87c7-4e64-883f-d244d7fc35c8.png)

2021-08-10 14:21 UTC, michaelgamble approved these changes
Looks good to me :)

2021-08-10 15:09 UTC, merged