MM-T947 When deactivating users in the System Console, email address should not disappear
mattermost/mattermost-webapp pull request #8175
Opened 2021-05-27 16:31 UTC by M-ZubairAhmed

#### Summary

#### Ticket Link

MM-T947 When deactivating users in the System Console, email address should not disappear
#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note

```

2021-05-27 16:31 UTC, mattermod commented
Hello @M-ZubairAhmed,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-06-02 15:41 UTC, hmhealey approved these changes

2021-06-02 17:36 UTC, josephbaylon requested changes
Overall looks good. Just one minor delay for test stability.

2021-06-02 17:36 UTC, josephbaylon commented on e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
> +            cy.findByPlaceholderText('Search users').should('be.visible').clear().type(user1.email);
Please add a delay here to account for async DOM refresh. The test is failing for me locally without this delay.

```suggestion
            cy.findByPlaceholderText('Search users').should('be.visible').clear().type(user1.email).wait(TIMEOUTS.HALF_SEC);
```

2021-06-03 00:52 UTC, josephbaylon approved these changes
LGTM. Test passed locally. Thanks @M-ZubairAhmed !!

2021-06-04 01:25 UTC, prapti approved these changes
Thank you so much yet again @M-ZubairAhmed! This is great: the test does exactly what's expected and is very clean.

2021-06-04 01:25 UTC, merged