MM-T2372 Deleting: Thread does not move when deleting post
mattermost/mattermost-webapp pull request #8176
Opened 2021-05-27 19:31 UTC by yulyanaR

Summary

Cypress test: MM-T2372 Deleting

Ticket Link

https://automation-test-cases.vercel.app/test/MM-T2372

2021-05-27 19:31 UTC, mattermod commented
Hello @yulyanaR,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-06-02 14:29 UTC, hmhealey approved these changes
Thanks for the PR, @yulyanaR. Looks good to me!

2021-06-02 14:30 UTC, hmhealey commented
/release-note none

2021-06-02 14:33 UTC, hmhealey commented
/release-note-none

2021-06-02 18:50 UTC, josephbaylon requested changes
Overall looks good. Just minor corrections below.

2021-06-02 18:50 UTC, josephbaylon commented on e2e/cypress/integration/scroll/deleting_scroll_spec.js
> +// Stage: @prod
Please remove for now.

```suggestion
```

2021-06-02 18:50 UTC, josephbaylon commented on e2e/cypress/integration/scroll/deleting_scroll_spec.js
> +describe('Deleting', () => {
```suggestion
describe('Scroll', () => {
```

2021-06-02 18:50 UTC, josephbaylon commented on e2e/cypress/integration/scroll/deleting_scroll_spec.js
> +    it('MM-T2372 Deleting', () => {
```suggestion
    it('MM-T2372 Post list does not scroll when the offscreen post is deleted', () => {
```

2021-06-03 00:53 UTC, josephbaylon commented
/update-branch

2021-06-03 00:55 UTC, josephbaylon requested changes
Please fix step and assertion indicators

2021-06-03 00:55 UTC, josephbaylon commented on e2e/cypress/integration/scroll/deleting_scroll_spec.js
> +            // * Get the text of the first visible post
```suggestion
            // # Get the text of the first visible post
```

2021-06-03 00:55 UTC, josephbaylon commented on e2e/cypress/integration/scroll/deleting_scroll_spec.js
> +            // * Get the text of the last visible post
```suggestion
            // # Get the text of the last visible post
```

2021-06-03 00:55 UTC, josephbaylon commented on e2e/cypress/integration/scroll/deleting_scroll_spec.js
> +            // Verify the first post is the same after deleting
```suggestion
            // * Verify the first post is the same after deleting
```

2021-06-03 00:55 UTC, josephbaylon commented on e2e/cypress/integration/scroll/deleting_scroll_spec.js
> +            // Verify the last post is the same after deleting
```suggestion
            // * Verify the last post is the same after deleting
```

2021-06-03 09:51 UTC, yulyanaR commented
> Please fix step and assertion indicators

Thanks, it's been updated.

2021-06-03 16:15 UTC, josephbaylon approved these changes
LGTM. Test passed locally. Thanks @yulyanaR !!

2021-06-03 22:50 UTC, furqanmlk approved these changes
Locally passed Thank you
![image](https://user-images.githubusercontent.com/6909890/120721701-5da57980-c49c-11eb-8779-b8f06c0b97bd.png)

2021-06-03 22:50 UTC, merged