[MM-34306] Migrate 'components/admin_console/brand_image_setting' and associated tests to TypeScript
mattermost/mattermost-webapp pull request #8260
Opened 2021-06-11 17:35 UTC by majidsajadi

#### Summary

migrated `brand_image_setting` to typescript.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/17244

#### Release Note

```release-note
NONE
```

2021-06-11 17:35 UTC, mattermod commented
Hello @majidsajadi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-06-14 16:51 UTC, hmhealey approved these changes
Thanks for the your continuing help with this migration! This PR looks good to me.

2021-06-14 16:52 UTC, hmhealey commented
@majidsajadi Would you be able to fix the merge conflict as well as the test? It looks like there's a couple test cases still using the old import path for the file.

2021-06-17 12:53 UTC, hahmadia approved these changes

2021-06-28 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-06-28 13:20 UTC, hahmadia commented
Hey! Could you fix the test and merge conflicts so we can pass onto QA for testing? Thanks

2021-07-05 11:41 UTC, majidsajadi commented
@hahmadia merged and resolved.

2021-07-07 07:16 UTC, saturninoabril requested changes
Thanks @majidsajadi! All looks good to me, except for one request then this is ready to merge.

2021-07-07 07:16 UTC, saturninoabril commented on components/admin_console/brand_image_setting/brand_image_setting.tsx
> +> {
nit: Please update as one-liner, thanks
```suggestion
export default class BrandImageSetting extends React.PureComponent<Props, State> {
```

2021-07-13 21:05 UTC, saturninoabril approved these changes
Thanks @majidsajadi!

2021-07-13 21:05 UTC, merged