Mm 36248 gitlab button fix
mattermost/mattermost-webapp pull request #8320
Opened 2021-06-29 07:18 UTC by engineereng

#### Summary
Fixes GitLab Button and Color config settings not being reflected in the UI

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36248

#### Related Pull Requests
- Has server changes (<link>)

#### Screenshots
None

#### Release Note
None

2021-06-29 18:53 UTC, engineereng commented
/check cla

2021-06-29 19:09 UTC, mkraft approved these changes

2021-07-07 13:15 UTC, BenCookie95 requested changes
We should probably add a snapshot test to check the configs are getting applied! Let me know if you need help with that!

Also, run `npm run fix` to fix/check your lint

2021-07-07 13:15 UTC, BenCookie95 commented on components/login/login_controller/login_controller.jsx
> +            />
The formatting looks off here, try running `npm run fix`

2021-07-15 17:32 UTC, BenCookie95 commented
@engineereng I don't think you pushed the snapshot updates from the __snapshot__ directory

2021-07-16 23:38 UTC, engineereng commented
> @engineereng I don't think you pushed the snapshot updates from the **snapshot** directory

Sorry about that! I pushed them yesterday.

2021-07-23 11:28 UTC, BenCookie95 approved these changes

2021-07-26 16:52 UTC, furqanmlk approved these changes
Locally Passed. Working as Expected.
![image](https://user-images.githubusercontent.com/6909890/127026645-f15c7aa1-b4c2-4642-9b86-a403d8e5d651.png)

![image](https://user-images.githubusercontent.com/6909890/127027858-b970dc72-f546-4f2c-aa68-e37372016f4e.png)

2021-07-28 02:23 UTC, merged