Mm 20382 typescript gifpicker searchgrid
mattermost/mattermost-webapp pull request #8466
Opened 2021-07-26 08:14 UTC by eunicode

#### Summary

This pull request migrates the SearchGrid component to Typescript. 
#### Ticket Link

This pull request closes issue #16724.

2021-07-26 08:14 UTC, mattermod commented
Hello @eunicode,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-07-26 08:49 UTC, Willyfrog commented
Hello @eunicode 

thanks for taking the time to go through the issue, can you please sign the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/) so we are able to review and merge this PR?

2021-07-27 17:49 UTC, eunicode commented
Hi @Willyfrog, I have signed the CLA!

2021-08-06 02:35 UTC, eunicode commented
Hi @Willyfrog, sorry to bother, I'd really appreciate some feedback!

2021-08-16 13:42 UTC, Willyfrog requested changes
Hello and sorry for the delay, I was away and I didn't noticed I was the only one assigned to the PR.

Can you remove the package-lock.json from the PR? we only make changes to that file if we also change the package.json (when we actually update a dependency)

2021-08-16 13:42 UTC, Willyfrog commented on components/gif_picker/components/SearchGrid/SearchGrid.tsx
> +    scrollPosition: number;
seems like the old props weren't being required, but now are requiring them, can we make them optional or make sure that they are always passed along?

2021-08-16 13:42 UTC, Willyfrog commented on components/gif_picker/components/SearchGrid/SearchGrid.tsx
> +    content_urls: {
this type seems like it can be broken into simpler pieces to ease reading about it, at least the `content_urls` property.

2021-08-16 13:42 UTC, Willyfrog commented on components/gif_picker/components/SearchGrid/SearchGrid.tsx
> +    numberOfColumns: number | undefined;
we tend to use the question mark for these cases
```suggestion
    containerHeight?: number;
    numberOfColumns?: number;
```

2021-08-16 13:42 UTC, Willyfrog commented on components/gif_picker/components/SearchGrid/SearchGrid.tsx
>          //const itemWidth = this.numberOfColumns === NUMBER_OF_COLUMNS_PORTRAIT ? 100 / NUMBER_OF_COLUMNS_PORTRAIT : 100 / this.numberOfColumns;
since we are already improving the code, can you remove this commented code? it seems unnecessary

2022-07-06 13:40 UTC, closed without merging