[MM-37377] - LHS does not update after Getting Started steps are complete
mattermost/mattermost-webapp pull request #8478
Opened 2021-07-27 09:24 UTC by AGMETEOR

#### Summary
- Makes sure that when Getting Started steps are finished, the sidebar updates to "Next Steps and Tips"
- Fixes Modal text when closing Getting Started and Next Steps and Tips

#### Ticket Link
[MM-37377](https://mattermost.atlassian.net/browse/MM-37377?atlOrigin=eyJpIjoiNzA4Y2VjNTQwODFiNGExMzkwYTRjMGJmNjRkNDI5NjkiLCJwIjoiaiJ9)

#### Release Note
```release-note
NONE

```

2021-07-27 12:45 UTC, pablovelezvidal approved these changes
LGTM! 🚢 , just one comment, I think the only translation file we modify is the en.json, maybe @marianunez can confirm that!

2021-07-27 17:09 UTC, marianunez requested changes
Can we cover this case with a cypress test as well?

2021-07-27 17:11 UTC, marianunez commented on i18n/en_AU.json
> +  "remove_next_steps_modal.mainText": "This will remove this section from your sidebar, but you can access it later in the {title} section of the Main Menu.",
That is correct, we should not update other translations files than `en.json`. The updates in the main file will be reflected in our translation servers and the specific languages will show up to be changed as well by translators.

2021-07-29 14:02 UTC, marianunez approved these changes
LGTM! Thanks @AGMETEOR!

2021-07-29 14:32 UTC, AGMETEOR commented
Hello @stevemudie QA steps are on the ticket for this one.

2021-07-29 18:34 UTC, stevemudie reviewed
@AGMETEOR Unfortunately, the tests fail.

**Getting Started** persists in the LHS at every point of the QA steps you described in the ticket.

2021-07-29 19:12 UTC, AGMETEOR commented
@stevemudie can't seem to reproduce locally. Maybe something is up with the spinwicks. I'll ask someone else to test locally as well to verify that the issue maybe with the spinwicks.

2021-07-29 19:36 UTC, AGMETEOR commented
@stevemudie we have confirmed that indeed the spinwick is not using the code for this PR. Maybe I'll ask someone from SRE to help out. 

As you can see the debugger below, the code deployed by the spinwick is different
-----
<img width="1792" alt="Screenshot 2021-07-29 at 22 33 51" src="https://user-images.githubusercontent.com/28563179/127554798-155dbd2d-6875-4d45-a3a9-a413aeec8024.png">

Thanks to @nickmisasi for helping to confirm

2021-07-30 08:18 UTC, AGMETEOR commented
> Mattermost test server created! 🎉
> 
> Access here: https://mattermost-webapp-pr-8478.test.mattermost.cloud
> 
> Account Type	Username	Password
> Admin	sysadmin	Sys@dmin123
> User	user-1	User-1@123

Hello @stevemudie the spinwick issue has been resolved correctly.

2021-07-30 11:34 UTC, stevemudie approved these changes
Tested and passed.

**Getting Started** changed to **Tips & Next Steps** as expected once the GS was complete including when dismissing the T&NS.

2021-07-30 12:42 UTC, merged

2021-07-30 12:42 UTC, mattermod commented
Cherry pick is scheduled.