MM-37299 - invite members ab testing
mattermost/mattermost-webapp pull request #8491
Opened 2021-07-28 20:40 UTC by pablovelezvidal

#### Summary
This PR adds the invite members button call to action. The button will be shown in different places and with different shapes depending on the value set in the feature flag InviteMembersButton.
The options are:
sticky_button: sticked to the bottom of the left hand side panel
lhs_button: Just below of the direct messages users list
user_icon: at the right side of the plus (more about channels) icon at the top of the left hand side panel
none: don't show any button

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37299

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/18016

#### Screenshots
User Icon:
<img width="1208" alt="Captura de pantalla 2021-07-28 a las 21 18 30" src="https://user-images.githubusercontent.com/10082627/127392555-86de111d-760e-4f68-a362-531b60c1c050.png">

Sticky:
<img width="880" alt="Captura de pantalla 2021-07-28 a las 21 18 57" src="https://user-images.githubusercontent.com/10082627/127392572-181509e7-bfba-460c-838c-b11dd10ac303.png">

Lhs_button:
<img width="1052" alt="Captura de pantalla 2021-07-28 a las 21 19 09" src="https://user-images.githubusercontent.com/10082627/127392576-8d07c83a-d616-49d9-9bc3-9262ca7ae8e7.png">

#### Release Note

```release-note
NONE
```

2021-07-29 01:03 UTC, marianunez requested changes
Looking great! 🎉 Would be ideal if we can also get a cypress test for these cases

2021-07-29 01:03 UTC, marianunez commented on components/sidebar/invite_members_button.tsx
> +const InviteMembersButton: React.FC<Props> = (props: Props): JSX.Element | null => {
Let's add some unit tests for this new component

2021-07-29 14:09 UTC, matthewbirtch commented
@pablovelezvidal how can I get the different tests to display so I can review?

2021-07-29 15:08 UTC, pablovelezvidal commented
> @pablovelezvidal how can I get the different tests to display so I can review?

Im working on getting the splitio values read from the spinwick server, once I get this done, I will let you know. If I can not get this done quickly, I can simulate the splitio value responses so you can validate the UX for this PR. I will keep you posted. @matthewbirtch

2021-07-30 10:39 UTC, AGMETEOR approved these changes
LGTM

2021-07-30 14:44 UTC, nickmisasi approved these changes

2021-07-30 16:19 UTC, pablovelezvidal commented
@stevemudie @matthewbirtch This other PR https://github.com/mattermost/mattermost-webapp/pull/8506 contains this same code + a pipeline change so the spinwick server is updated correctly. You can do your tests there. Currently the default value for splitio is User Icon. Let me know via DM when you want me to change the values so you can see the different variations the button has.

2021-07-30 16:51 UTC, stevemudie approved these changes
Worked with Pablo to test the different invite button locations and everything worked as expected.

Thanks @pablovelezvidal !

2021-07-30 17:26 UTC, pablovelezvidal commented
/update-branch

2021-07-30 17:41 UTC, matthewbirtch commented
Hey @pablovelezvidal a few things I've found:

### User Icon Option
1. The new icon next to the `+` icon is misaligned. It's sitting 1px too low
![image](https://user-images.githubusercontent.com/2040554/127688450-4d42961a-8d6c-4a33-b5b0-6328856d3d81.png)

### Sticky Button Option
1. The button's border and text color should be full opacity of the sidebar text color.
2. The hover state will just be adding a background of 8% sidebar text color
2. The button size is too small. An update was made recently (sorry I don't think that got communicated back to you). It should be 32px in height.
3. The font-weight on the button label should be `font-weight: 600`
4. The font-size on the button label should be `font-size: 12px`
5. The font-size on the icon should be `font-size: 14px`
6. Can we add 4px of space between the icon and the label within the button?
7. Can we adjust the spacing around the button so that there is 16px of space all the way around it? And it looks like there is a min-width set on the button to 90%. If we make this padding adjustment, we should be able to make the button width 100% of its container

### LHS button version
1. Can we mimic the style of a channel list item for this button?  The icon size, the spacing should align with the channel items above
![image](https://user-images.githubusercontent.com/2040554/127691479-129e6294-6b28-4d09-8e56-2a01e3ea7247.png)

2021-07-30 20:44 UTC, matthewbirtch approved these changes
Nice work @pablovelezvidal. Based on the changes we reviewed together, I think we're good to go.

2021-07-31 13:55 UTC, merged