[MM-37715] - Hide global header preference when the feature flag is d…
mattermost/mattermost-webapp pull request #8540
Opened 2021-08-09 15:13 UTC by nevyangelova

#### Summary
When the feature flag is disabled the global header option should not appear in account settings. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37715

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/8509#issuecomment-894425122

#### Release Note
```
NONE
```

2021-08-09 15:14 UTC, crspeller approved these changes

2021-08-09 16:00 UTC, amyblais commented
@jgilliam17 @hmhealey This is also a candidate to fix for this Wednesday's cloud release.

2021-08-09 18:00 UTC, calebroseland requested changes
Maybe something like `globalHeaderAllowed`?

The preference is only visible if already on; turning off makes it disappear and inaccessible.

2021-08-09 18:00 UTC, calebroseland commented on components/user_settings/display/index.ts
> +        globalHeaderEnabled: getGlobalHeaderEnabled(state),
```suggestion
        globalHeaderAllowed: getFeatureFlagValue(state, 'GlobalHeader') === 'true',
```

2021-08-09 18:00 UTC, calebroseland commented on components/user_settings/display/user_settings_display.test.tsx
> +        globalHeaderEnabled: true,
```suggestion
        globalHeaderAllowed: true,
```

2021-08-09 18:00 UTC, calebroseland commented on components/user_settings/display/user_settings_display.tsx
> +                    {this.props.globalHeaderEnabled && showGlobalHeader}
```suggestion
                    {this.props.globalHeaderAllowed && showGlobalHeader}
```

2021-08-09 18:00 UTC, calebroseland commented on components/user_settings/display/user_settings_display.tsx
> +    globalHeaderEnabled: boolean;
```suggestion
    globalHeaderAllowed: boolean;
```

2021-08-09 20:09 UTC, nevyangelova commented on components/user_settings/display/index.ts
> +        globalHeaderEnabled: getGlobalHeaderEnabled(state),
oh yes nice catch

2021-08-09 20:49 UTC, hmhealey approved these changes

2021-08-09 21:16 UTC, calebroseland approved these changes

2021-08-10 09:11 UTC, zefhemel commented
I've just tested this works on the spinwick and everything looks good: with the feature flag disabled there is no such option and the global header does not appear:

<img width="692" alt="CleanShot 2021-08-10 at 11 07 33" src="https://user-images.githubusercontent.com/59073/128840060-a33aa239-e6f2-4d07-8227-dee12e2051eb.png">

With the feature flag enabled the option is visible:

<img width="678" alt="CleanShot 2021-08-10 at 11 08 53" src="https://user-images.githubusercontent.com/59073/128840231-4063933a-a955-4603-82a4-70ad6494f5b3.png">

When I enable the Global Header with the feature flag enabled, and then switch off the feature flag again, the global header is hidden. As expected.

2021-08-10 09:28 UTC, zefhemel approved these changes

2021-08-10 11:39 UTC, jgilliam17 approved these changes
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified global header preference setting in account settings is hidden when flag is off.

2021-08-10 11:43 UTC, merged

2021-08-10 11:43 UTC, mattermod commented
Cherry pick is scheduled.

2021-08-10 11:43 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-webapp
   f370094f4..fb4ec07a6  MM-12104_file-preview-modal -> upstream/MM-12104_file-preview-modal
   046f6b4e0..9046ac38b  MM-22845_permalink-preview -> upstream/MM-22845_permalink-preview
   bb5f23f35..877d2075c  MM-32342_remove-legacy-sidebar -> upstream/MM-32342_remove-legacy-sidebar
 * [new branch]          MM-37333-fix-info-banner-colors -> upstream/MM-37333-fix-info-banner-colors
 * [new branch]          MM-37472_product_switcher_tip -> upstream/MM-37472_product_switcher_tip
 * [new branch]          MM-37473_settings-tip -> upstream/MM-37473_settings-tip
   380b78ee7..2b4c4d0c5  MM-37578              -> upstream/MM-37578
   059a9eabf..caefb841d  MM-37616              -> upstream/MM-37616
 * [new branch]          MM-37716_remove-boticon -> upstream/MM-37716_remove-boticon
   8001ece23..a857a814c  ParserOnProp          -> upstream/ParserOnProp
 * [new branch]          avoid-fetching-bindings -> upstream/avoid-fetching-bindings
   30e48682b..164746a2f  cloud                 -> upstream/cloud
   284e8e7f5..2054338ab  master                -> upstream/master
   046f6b4e0..9046ac38b  permalink-preview     -> upstream/permalink-preview
   6d8683673..949bafc5a  release-5.38          -> upstream/release-5.38
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.4' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-webapp-#8540-upstream-release-6.0-1628595817
Switched to a new branch 'automated-cherry-pick-of-mattermost-webapp-#8540-upstream-release-6.0-1628595817'
Branch 'automated-cherry-pick-of-mattermost-webapp-#8540-upstream-release-6.0-1628595817' set up to track remote branch 'release-6.0' from 'upstream'.

+++ About to attempt cherry pick of PR #8540 with merge commit 2054338ab15d26439443ad979ce0faa040a894ea.

error: could not apply 2054338ab... [MM-37715] - Hide global header preference when the feature flag is d… (#8540)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU components/user_settings/display/user_settings_display.test.tsx
UU components/user_settings/display/user_settings_display.tsx
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2021-08-10 12:02 UTC, amyblais commented
/cherry-pick cloud

2021-08-10 12:02 UTC, mattermod commented
Cherry pick is scheduled.