Add e2e test update
mattermost/mattermost-webapp pull request #8564
Opened 2021-08-11 18:07 UTC by neallred

#### Summary
Fills out e2e test for onboarding tutorial tip. These are changes that were mentioned, but accidentally not included, in https://github.com/mattermost/mattermost-webapp/pull/8544 . QA not needed for this PR: it adds implementation of an e2e test, but nothing else.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37472

#### Related Pull Requests
NONE

#### Screenshots

https://user-images.githubusercontent.com/13738432/129080556-a9efc91c-9a0e-475f-af3e-ac27b47151a7.mp4

#### Release Note

```release-note
NONE
```

2021-08-11 18:07 UTC, mattermod commented
Hello @neallred,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-08-11 21:10 UTC, pablovelezvidal approved these changes
LGTM! :shipit:

2021-08-11 21:11 UTC, pablovelezvidal commented on e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
> +const sel = {
nit: could we add a more descriptive name than sel? selectors would be ok, too.

2021-08-12 10:15 UTC, AGMETEOR requested changes

2021-08-12 10:15 UTC, AGMETEOR commented on e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
>          // tip 1: post message
Top of the file has a guide on how to make the comments

2021-08-12 10:15 UTC, AGMETEOR commented on e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
> +        cy.get(`#create_post ${selectors.tip}`).click();
We can add comments on every code block to tell what the intended action is like the existing e2e files

2021-08-12 10:15 UTC, AGMETEOR commented on e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
>          // tip 2: channels
Top of the file has a guide on how to make the comments

2021-08-12 10:15 UTC, AGMETEOR commented on e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
>          // tip 3: add channels
Top of the file has a guide on how to make the comments

2021-08-12 10:15 UTC, AGMETEOR commented on e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
> +        // tip 4: invite people/admin
Top of the file has a guide on how to make the comments

2021-08-16 14:43 UTC, marianunez commented
Adding @stevemudie here for tests visibility and help with Zephyr test numbers and here: https://github.com/mattermost/mattermost-webapp/pull/8544#discussion_r689443633

2021-08-17 14:43 UTC, AGMETEOR approved these changes
Nice @neallred . LGTM

2021-08-17 16:25 UTC, merged

2021-08-17 19:12 UTC, amyblais commented
@neallred Is this a requirement for v6.0? If yes, can you help cherry-pick to the ``cloud`` branch? https://community.mattermost.com/core/pl/cmqefh9ue7dnxgfm1cirbcj9se