add new branding graphics for tips & next steps
mattermost/mattermost-webapp pull request #8605
Opened 2021-08-16 21:58 UTC by deanwhillier

#### Summary

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37159

#### Screenshots

#### Release Note
```release-note
NONE
```

2021-08-17 17:07 UTC, andrewbrown00 requested changes
Thanks, @deanwhillier, small change:

- [ ] Remove the **Download the Desktop and Mobile Apps** section from the **Welcome to Mattermost** screen. 
   - It should only show on the **Tips & Next Steps** screen.
   ![image](https://user-images.githubusercontent.com/48559658/129770211-10c53c56-0292-4ca3-a357-0648bd723517.png)

2021-08-17 17:26 UTC, andrewbrown00 commented
@deanwhillier disregard the feedback, looks like there was an update to add the section https://github.com/mattermost/mattermost-webapp/pull/8523, it wasn't updated in the design file.

> Thanks, @deanwhillier, small change:
> 
> * [ ]  Remove the **Download the Desktop and Mobile Apps** section from the **Welcome to Mattermost** screen.
>   
>   * It should only show on the **Tips & Next Steps** screen.
>     ![image](https://user-images.githubusercontent.com/48559658/129770211-10c53c56-0292-4ca3-a357-0648bd723517.png)

2021-08-17 17:41 UTC, andrewbrown00 approved these changes
Thanks, @deanwhillier, changes look great 🙂 

* Verified backgrounds and illustrations updates align with new branding
* Verified the colors are correct when switching themes

Getting Started | Tips & Next Steps
---------- | ----------
![image](https://user-images.githubusercontent.com/48559658/129773414-9d42dae1-b2fa-4599-a450-26302eb0a1be.png) | ![image](https://user-images.githubusercontent.com/48559658/129773441-5ca884ae-0102-455d-8731-04e957644eb0.png)
![image](https://user-images.githubusercontent.com/48559658/129774442-26f3081c-a7f6-49e1-ad8b-c7d93f3c6076.png) | ![image](https://user-images.githubusercontent.com/48559658/129774343-dd563b58-e0ec-4244-9074-b9e5f93cf0f3.png)

2021-08-17 17:46 UTC, michelengelen approved these changes
really nice ... LGTM! :sparkles:

2021-08-17 17:46 UTC, michelengelen commented on components/next_steps_view/images/onboarding-bg-svg.tsx
> +            <g style={{transformOrigin: 'top left', transform: 'translate(184px, -772px) rotate(45deg)'}}>
nice improvement! (to all of the groups)

2021-08-17 18:13 UTC, esethna approved these changes

2021-08-18 11:33 UTC, nevyangelova approved these changes
LGTM

2021-08-18 19:50 UTC, jgilliam17 approved these changes
Thanks @deanwhillier 
Tested, looks good to merge.
- Verified new branding graphics and background for Welcome and Tips&Next Steps screens - looks good in both light and dark themes.

2021-08-18 19:51 UTC, merged

2021-08-18 19:52 UTC, deanwhillier commented
/cherry-pick cloud

2021-08-18 19:52 UTC, mattermod commented
Cherry pick is scheduled.