[MM-36789] Security: Post is not removed from the Threads view when post is deleted
mattermost/mattermost-webapp pull request #8708
Opened 2021-08-25 13:13 UTC by AshishDhama

#### Summary
Security: Post is not removed from the Threads view when post is deleted

#### Ticket Link
fixes [https://mattermost.atlassian.net/browse/MM-36789](https://mattermost.atlassian.net/browse/MM-36789)

#### Related Pull Requests
NONE

#### Screenshots
<img width="1792" alt="Screenshot 2021-08-25 at 6 38 59 PM" src="https://user-images.githubusercontent.com/16203333/130796300-08043c5f-3068-4194-9b99-1e2c12d6a0d3.png">

#### Release Note
```release-note
* Show ('message deleted') in global thread on root post message delete
```

2021-08-25 13:13 UTC, mattermod commented
Hello @AshishDhama,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-09-02 15:44 UTC, AshishDhama commented on components/threading/global_threads/thread_item/thread_item.tsx
> +    const renderMessage = formatMessage({id: 'post_body.deleted', defaultMessage: '(message deleted)'});
Yeah make sense, Done

2021-09-02 15:44 UTC, AshishDhama commented on components/threading/global_threads/thread_item/thread_item.tsx
> +                    message={post && post.state === Posts.POST_DELETED ? renderMessage : post.message}
Thanks

2021-09-02 15:50 UTC, koox00 approved these changes

2021-09-03 14:06 UTC, stylianosrigas commented
FYI the cloud server is crashing with the following error
```
{"timestamp":"2021-09-03 14:01:47.749 Z","level":"info","msg":"\u001b[36minfo\u001b[0m  [2021-09-03 14:01:47.749 Z] Server.Start                             \n\u001b[31merror\u001b[0m [2021-09-03 14:01:47.749 Z] server not bind to any port              \
```

2021-09-06 05:08 UTC, srkgupta approved these changes
Thanks @AshishDhama. The changes LGTM and is working fine. Just found one specific usecase which is causing the client to crash which I had Dm'd you. PTAL.

2021-09-06 05:10 UTC, srkgupta requested changes
Oops. Approved by mistake previously. Please see my comments above:

> Thanks @AshishDhama. Overall the changes LGTM and is working fine. Just found one specific usecase which is causing the client to crash which I had Dm'd you. PTAL.

2021-09-06 05:39 UTC, AshishDhama commented
> Thanks @AshishDhama. Overall the changes LGTM and is working fine. Just found one specific usecase which is causing the client to crash which I had Dm'd you. PTAL.

Thanks I don’t think crash is due to the changes I have done, But looking into it

2021-09-06 13:22 UTC, srkgupta approved these changes
I was able to reproduce the specified issue on latest master without this code change. Hence I have filed the issue as a separate ticket. Approving this PR. Thanks @AshishDhama

2021-09-06 13:30 UTC, AshishDhama commented
@jgilliam17 if we delete root post from Global threads RHS (CRT), app crashes which we are able to reproduce on master,  if this issue was already known please do the needful for the following ticket @srkgupta have created for this issue [https://mattermost.atlassian.net/browse/MM-38376](https://mattermost.atlassian.net/browse/MM-38376)

2021-09-07 18:47 UTC, jgilliam17 approved these changes
Thank you @AshishDhama 
Tested, looks good to merge.
- Verified post is removed from the Threads view after deletion. 
Thanks for filing the crash separately @srkgupta

2021-09-07 18:49 UTC, merged

2021-09-08 14:42 UTC, amyblais commented
/cherry-pick release-5.39

2021-09-08 14:42 UTC, mattermod commented
Cherry pick is scheduled.

2021-09-08 14:42 UTC, amyblais commented
/cherry-pick release-6.0

2021-09-08 14:42 UTC, mattermod commented
Cherry pick is scheduled.