MM-38093: updates notifications copy on CRT replies
mattermost/mattermost-webapp pull request #8778
Opened 2021-09-02 10:29 UTC by koox00

#### Summary

Desktop notifications title for replies when users have with CRT "on"
should include "Reply in " before the channel name.

e.g:
- Reply in Off-Topic
- Reply in Direct Message

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-38093

#### Related Pull Requests

- Has server changes (https://github.com/mattermost/mattermost-server/pull/18332)

#### Release Note

```release-note
NONE
```

2021-09-02 17:38 UTC, hmhealey requested changes

2021-09-02 17:38 UTC, hmhealey commented on actions/notification_actions.jsx
> +            title = Utils.localizeMessage('notification.crt', 'Reply in ') + title;
Concatenating the title onto `Reply in` might not work depending on the language. We can use `Utils.localizeAndFormatMessage` to let translators order the title the way they want

2021-09-03 09:49 UTC, Willyfrog approved these changes
other than @hmhealey suggestion, looks good

2021-09-07 15:56 UTC, hmhealey approved these changes

2021-09-08 16:59 UTC, koox00 commented
/update-branch

2021-09-10 08:11 UTC, merged

2021-09-13 16:07 UTC, amyblais commented
/cherry-pick release-6.0

2021-09-13 16:07 UTC, mattermod commented
Cherry pick is scheduled.