[MM-37694] - fixing getting started colors
mattermost/mattermost-webapp pull request #8805
Opened 2021-09-08 12:36 UTC by michelengelen

#### Summary
this fixes the colors for the getting started indicator element in the bottom of the left sidebar.

#### Ticket Link
[MM-37694](https://mattermost.atlassian.net/browse/MM-37694)

#### Screenshots

|  |  before  |  after  |
|-----|-----|-----|
|  hover  |<img width="255" alt="Screenshot 2021-09-08 at 14 34 08" src="https://user-images.githubusercontent.com/32863416/132510010-6ca19cd2-f230-4eb1-a776-8e59fcbf38d0.png">|<img width="255" alt="Screenshot 2021-09-08 at 14 29 29" src="https://user-images.githubusercontent.com/32863416/132509769-60284f07-4a05-4058-af67-4ff363b9fbdc.png">
|  active  |<img width="255" alt="Screenshot 2021-09-08 at 14 34 13" src="https://user-images.githubusercontent.com/32863416/132510045-db3d90f9-7568-482e-b7d2-26e9f6cee42b.png">|<img width="255" alt="Screenshot 2021-09-08 at 14 29 39" src="https://user-images.githubusercontent.com/32863416/132509819-68860db5-726b-44f8-8a9f-1beadc00edcc.png">

#### Release Note
```release-note
NONE
```

2021-09-08 13:42 UTC, devinbinnie approved these changes

2021-09-08 17:16 UTC, matthewbirtch commented
@michelengelen I seem to be having trouble with getting a test server up and running to verify this

2021-09-09 06:45 UTC, michelengelen commented
@matthewbirtch I think it is because the install job did fail. I restarted that to see if it fixes the issue

2021-09-09 12:15 UTC, matthewbirtch requested changes
@michelengelen I'm not seeing the active state border on the left side of the sidebar item:
![image](https://user-images.githubusercontent.com/2040554/132683018-eedb6cc5-9214-4f74-9e41-cafe2c1eae39.png)

Everything else looks good to go with the proper use of the theme colors

2021-09-09 12:42 UTC, michelengelen commented
@matthewbirtch it seems that one of the theme values is not stored as hex value (as it should be), so that broke the border for this. I have set it to the respective rgb value for now but will create a follow-up ticket to fix that as well.

2021-09-10 19:38 UTC, jgilliam17 approved these changes
Thanks @michelengelen 
Tested, looks good to merge.
- Verified LHS getting started item displays as expected on hover and in active state in light and dark themes.

2021-09-13 08:46 UTC, michelengelen commented
@nevyangelova kind reminder to review

2021-09-13 08:49 UTC, nevyangelova approved these changes
LGTM

2021-09-13 09:10 UTC, merged

2021-09-13 16:08 UTC, amyblais commented
/cherry-pick release-6.0

2021-09-13 16:08 UTC, mattermod commented
Cherry pick is scheduled.