Mm 38063 date to utc
mattermost/mattermost-webapp pull request #8846
Opened 2021-09-13 20:25 UTC by hamzaMM

#### Summary
Changed date to utc in the data retention policy table

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38063

2021-09-13 20:25 UTC, mattermod commented
Hello @hamzaMM,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-09-17 13:38 UTC, mkraft requested changes

2021-09-17 13:38 UTC, mkraft commented on components/admin_console/jobs/table.jsx
> +        const date = new Date(new Date(millis).toUTCString().substr(0, 25));
I think we should use a localized version of this date display using moment.js, which is already a JS package we ship with.

2021-09-17 13:41 UTC, BenCookie95 commented
@hamzaMM The package-lock.json changes shouldn't be there

2021-12-25 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @aspleenic

2023-02-22 15:12 UTC, closed without merging