WIP: [MM-24461] Show last active time of users when not online
mattermost/mattermost-webapp pull request #8889
Opened 2021-09-17 21:26 UTC by BenCookie95

#### Summary
Show when a user was last active

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24461

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
Show when a user was last online
```

2021-09-23 14:46 UTC, devinbinnie approved these changes

2021-09-23 14:46 UTC, devinbinnie commented on packages/mattermost-redux/src/utils/user_utils.ts
> +    const oneMin = 5 * 60 * 1000;
We might have a global constant for this.

2021-10-04 19:58 UTC, esethna commented
Friendly ping @mkraft to help review the web and server PRs for this feature

2021-10-07 20:44 UTC, BenCookie95 commented
> @BenCookie95 I don't see the last active status showing on the test server anywhere. Is there a setting that needs to be enabled?

@matthewbirtch Looks like there is an issue right now with the display settings, the settings page is crashing. I will probably need to sync with master and fix the conflicts

2021-11-01 14:48 UTC, BenCookie95 commented
@agnivade I just wanted to clarify with server. I added a new user setting (`show_last_active`) to `user.props`, this setting will be viewed by other users in order to determine whether we can display their last active time.

I added the field to `user.props` in order to avoid adding a new column to the users table. Is this the approach server wants us to take?

2021-11-01 15:30 UTC, agnivade commented
> I added the field to user.props in order to avoid adding a new column to the users table. Is this the approach server wants us to take?

@BenCookie95 - It all depends on the requirements for the new field. The decision to use a new column or not, is dictated by the query patterns on the data. Keep in mind that any data inside a jsonb blob takes more storage than a dedicated column and the query planner also does not store any statistics on it.

Which essentially means that if you are going to use that field in WHERE clauses, it will degrade performance than a usual column. Arguably, Postgres does allow you to index fields in a jsonb column, but for MySQL, you need to create a generated column and index on that. Supporting MySQL creates more complexity.

My suggestion would be that if this is treated purely as a metadata on the user object, and you are not going to perform any sort of queries on that field, then it's okay to add it as a prop. Otherwise, use a dedicated column.

2021-11-04 15:05 UTC, BenCookie95 commented
@devinbinnie & @mkraft I'm opening this up for re-review because there have been a number of changes since the last review. I am now using user.props to store the new configuration for each user. Previously I added a new column to the users table but I decided against it.

2021-11-08 16:20 UTC, furqanmlk commented
/update-branch

2021-11-09 15:39 UTC, devinbinnie approved these changes

2021-11-12 15:25 UTC, mkraft approved these changes

2021-11-12 16:47 UTC, matthewbirtch commented
@BenCookie95 let me know when the test server is in a place where I can review this from a UX standpoint. Thanks!

2021-11-12 17:47 UTC, BenCookie95 commented
@matthewbirtch should be good to go

2021-11-12 17:52 UTC, furqanmlk reviewed
Hi @BenCookie95 

All test conditions are passing except one,

1. If less than 1 minute, don’t show active status ✅ 

2. “Active [N] min(s) ago”, if >= 1 minute and < 60 minutes ✅ 
![image](https://user-images.githubusercontent.com/6909890/141512492-9a0d022e-016f-40d6-abca-cb329d49d054.png)

3. “Active [N] hr(s) ago”, if >= 1 hour and < 24 hrs ✅ 
**Note: Should it `1 Hour` or `1 Hours` ?**
<img width="425" alt="Pasted Graphic 15" src="https://user-images.githubusercontent.com/6909890/141511667-86af7a0f-261f-4bb7-9f54-26125e67b189.png">

4. “Active yesterday”, if >= 24 hrs and < 48 hrs ✅ 
<img width="427" alt="Pasted Graphic 16" src="https://user-images.githubusercontent.com/6909890/141511701-2d3a64e5-c2a9-4e0a-b777-68fe6e0549ed.png">

5. “Active [Friday]”, if >=48 hrs and < 7 days 🔴 --- **FAILED**
![image](https://user-images.githubusercontent.com/6909890/141512069-2dafa6e6-16c9-4225-be9b-dfa0592de2cf.png)

6. “Active [August 10]”, if >= 7 days ✅ 
![image](https://user-images.githubusercontent.com/6909890/141512222-8ddac935-6984-413f-bde7-38ef9052f022.png)

2021-11-12 19:14 UTC, matthewbirtch requested changes
This looks great. Thanks @BenCookie95 

Just a few minor things from me:
1. Can we change the time format to abbreviated? (e.g. 2 hrs ago, 5 mins ago, etc)
2. When a custom status is set, can we add some space to the left of it so that it's more separated? I think it needs about 8px of space to the left of the custom status
<img width="488" alt="Screen Shot 2021-11-12 at 2 06 45 PM" src="https://user-images.githubusercontent.com/2040554/141521530-68a4feaa-17b1-48bc-91b3-ba638823239e.png">
3. In the Settings, can we move the 'Share last active time' setting up under 'Show online availability on profile images'?
4. When I toggled the setting off it hid the last active status from other users as I expected. However, when I toggled it back on, it wouldn't save the setting properly. It seems that I am unable to turn it back on after turning it off.

I think that's it! Nice work.

2021-11-19 18:24 UTC, BenCookie95 commented
> This looks great. Thanks @BenCookie95
> 
> Just a few minor things from me:
> 
> 1. Can we change the time format to abbreviated? (e.g. 2 hrs ago, 5 mins ago, etc)
> 2. When a custom status is set, can we add some space to the left of it so that it's more separated? I think it needs about 8px of space to the left of the custom status
> 
> <img alt="Screen Shot 2021-11-12 at 2 06 45 PM" width="488" src="https://user-images.githubusercontent.com/2040554/141521530-68a4feaa-17b1-48bc-91b3-ba638823239e.png">
> 
> 3. In the Settings, can we move the 'Share last active time' setting up under 'Show online availability on profile images'?
> 4. When I toggled the setting off it hid the last active status from other users as I expected. However, when I toggled it back on, it wouldn't save the setting properly. It seems that I am unable to turn it back on after turning it off.
> 
> I think that's it! Nice work.

@matthewbirtch I think I have fixed most things from your comments. The only issue is with the abbreviations for minutes/hours. The library we are using seems to shorten to `min.` & `hr.` instead of `mins` & `hrs`

2021-11-19 18:24 UTC, BenCookie95 commented
> Hi @BenCookie95
> 
> All test conditions are passing except one,
> 
> 1. If less than 1 minute, don’t show active status ✅
> 2. “Active [N] min(s) ago”, if >= 1 minute and < 60 minutes ✅
>    ![image](https://user-images.githubusercontent.com/6909890/141512492-9a0d022e-016f-40d6-abca-cb329d49d054.png)
> 3. “Active [N] hr(s) ago”, if >= 1 hour and < 24 hrs ✅
> 
> <img alt="Pasted Graphic 15" width="425" src="https://user-images.githubusercontent.com/6909890/141511667-86af7a0f-261f-4bb7-9f54-26125e67b189.png">
> 
> 4. “Active yesterday”, if >= 24 hrs and < 48 hrs ✅
> 
> <img alt="Pasted Graphic 16" width="427" src="https://user-images.githubusercontent.com/6909890/141511701-2d3a64e5-c2a9-4e0a-b777-68fe6e0549ed.png">
> 
> 5. “Active [Friday]”, if >=48 hrs and < 7 days 🔴 --- **FAILED**
>    ![image](https://user-images.githubusercontent.com/6909890/141512069-2dafa6e6-16c9-4225-be9b-dfa0592de2cf.png)
> 6. “Active [August 10]”, if >= 7 days ✅
>    ![image](https://user-images.githubusercontent.com/6909890/141512222-8ddac935-6984-413f-bde7-38ef9052f022.png)

@furqanmlk I have fixed the broken test case for number 5.

2021-11-19 19:58 UTC, matthewbirtch commented
@BenCookie95 I can't seem to get the last active time to display. The setting is turned on for both users I'm testing with, but it's not showing the last active time anywhere

![image](https://user-images.githubusercontent.com/2040554/142684088-581abb89-0da1-4cd1-825a-676fdcf9f471.png)

![image](https://user-images.githubusercontent.com/2040554/142684105-6ea25dc7-fc39-4c91-a3ed-991f9dfe7f91.png)

2021-11-19 20:00 UTC, BenCookie95 commented
> @BenCookie95 I can't seem to get the last active time to display. The setting is turned on for both users I'm testing with, but it's not showing the last active time anywhere
> 
> ![image](https://user-images.githubusercontent.com/2040554/142684088-581abb89-0da1-4cd1-825a-676fdcf9f471.png)
> 
> ![image](https://user-images.githubusercontent.com/2040554/142684105-6ea25dc7-fc39-4c91-a3ed-991f9dfe7f91.png)

@matthewbirtch I'll take another look, I might have broken it on the last push

2021-11-19 20:12 UTC, BenCookie95 commented
@matthewbirtch seems to be working fine for me on the test server and locally. Is it ok now?

2021-11-19 20:13 UTC, matthewbirtch commented
@BenCookie95 seems to be showing now. Weird

2021-11-19 20:17 UTC, matthewbirtch commented
> 2\. When a custom status is set, can we add some space to the left of it so that it's more separated? I think it needs about 8px of space to the left of the custom status

Space looks better here, but it looks like space was added for all cases - not just when custom status is set?

2021-11-19 20:21 UTC, BenCookie95 commented
> > 2. When a custom status is set, can we add some space to the left of it so that it's more separated? I think it needs about 8px of space to the left of the custom status
> 
> Space looks better here, but it looks like space was added for all cases - not just when custom status is set?

Yeah that's true actually, that's a quick fix

2021-11-23 16:06 UTC, BenCookie95 commented
> > 2. When a custom status is set, can we add some space to the left of it so that it's more separated? I think it needs about 8px of space to the left of the custom status
> 
> Space looks better here, but it looks like space was added for all cases - not just when custom status is set?

@matthewbirtch Should this padding only be added to the custom status when the last active time is showing? or should it be applied to custom status no matter what is to the left of it?

2021-11-23 16:09 UTC, matthewbirtch commented
> > > 2. When a custom status is set, can we add some space to the left of it so that it's more separated? I think it needs about 8px of space to the left of the custom status
> > 
> > 
> > Space looks better here, but it looks like space was added for all cases - not just when custom status is set?
> 
> @matthewbirtch Should this padding only be added to the custom status when the last active time is showing? or should it be applied to custom status no matter what is to the left of it?

Good point, I think it would be good to be there no matter what

2021-11-23 16:16 UTC, BenCookie95 commented
> > > > 2. When a custom status is set, can we add some space to the left of it so that it's more separated? I think it needs about 8px of space to the left of the custom status
> > > 
> > > 
> > > Space looks better here, but it looks like space was added for all cases - not just when custom status is set?
> > 
> > 
> > @matthewbirtch Should this padding only be added to the custom status when the last active time is showing? or should it be applied to custom status no matter what is to the left of it?
> 
> Good point, I think it would be good to have the extra padding to the left of the custom status no matter what

Ok, that's fixed now

2021-11-23 16:27 UTC, matthewbirtch approved these changes
LGTM!

2021-11-23 17:49 UTC, esethna commented
@furqanmlk please help with testing when available. Thanks!

2021-11-23 17:50 UTC, esethna commented
We probably shouldn't show the last active time for your own DM: 
![image](https://user-images.githubusercontent.com/14333569/143077729-0886a8fc-5dfd-4f4e-a0f6-6e5141d16f35.png)

2021-11-23 21:24 UTC, furqanmlk approved these changes
Locally passed. Working as expected
![image](https://user-images.githubusercontent.com/6909890/143131253-ef8baa6d-9048-40eb-b8f0-35de8a5fb4ef.png)

2021-12-01 19:36 UTC, esethna commented
@BenCookie95 sounds like this is ready to merge?

2021-12-01 19:37 UTC, BenCookie95 commented
> @BenCookie95 sounds like this is ready to merge?

I'm going to merge latest master in first to ensure pipelines haven't broke and then I will merge afterwards

2021-12-01 19:37 UTC, BenCookie95 commented
/update-branch

2021-12-01 20:10 UTC, BenCookie95 commented
@esethna One final thought on this. I wonder if there should be a config to enable/disable this setting globally? i.e a config that make this setting available for the everyone in the org

2021-12-01 20:39 UTC, esethna commented
@BenCookie95 good call. I'm not opposed to adding that, maybe at the bottom of the users and teams section of the sys console. 

"Enable last active time"
"When enabled, last active time allows users to see when someone was last online.

2021-12-01 20:48 UTC, BenCookie95 commented
> @BenCookie95 good call. I'm not opposed to adding that, maybe at the bottom of the users and teams section of the sys console.
> 
> "Enable last active time" "When enabled, last active time allows users to see when someone was last online."
> 
> Defaulted to true

Yeah I can add that on Friday morning!

2021-12-03 21:10 UTC, BenCookie95 commented
@devinbinnie @mkraft I added a new config to admin console to control the last active label globally. Just though you might want a quick look so I asked for reviews again

2021-12-03 21:49 UTC, devinbinnie approved these changes

2021-12-06 16:18 UTC, mkraft commented on components/user_settings/display/user_settings_display.tsx
> +                    this.props.updateSection('');
Was this meant to have an empty string parameter?

2022-03-10 21:50 UTC, esethna commented
Same here @BenCookie95! Please go ahead an merge if we've got the reviews as needed :)

2022-03-11 21:28 UTC, BenCookie95 commented
> Same here @BenCookie95! Please go ahead an merge if we've got the reviews as needed :)

I had to do some code cleanup due to some performance issues so that will need a re-review. I also found a memory leak in the existing timestamp component, I think my changes are the only components that use the timestamp in this way so that's why the memory leak is only now visible. 

I'm going to fix the memory leak in this PR as well

2022-04-26 19:40 UTC, esethna commented
@BenCookie95 just checking in to see if you're still working on this?

2022-09-27 17:28 UTC, esethna commented
Chatted with @BenCookie95. He's going to take another glance at this before merging, but the memory leak issue does not seem to be related to this PR in particular, so reviews should be complete

2022-09-30 17:11 UTC, merged