Mm-38333 display users within a channel
mattermost/mattermost-webapp pull request #8913
Opened 2021-09-21 21:16 UTC by hamzaMM

#### Summary
Added users within a group to list view in add members

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38333

#### Related Pull Requests
NA

#### Release Note
```release-note
NONE
```

2021-10-05 15:12 UTC, BenCookie95 requested changes
Left a few small comments, can we also remove the package-lock.json changes?

2021-10-05 15:12 UTC, BenCookie95 commented on components/channel_invite_modal/channel_invite_modal.tsx
> +        this.props.actions.loadStatusesForProfilesList(this.props.profilesInCurrentChannel);
Can we concat the 2 arrays (this.props.profilesInCurrentChannel & this.props.profilesNotInCurrentChannel) and make this into one request?

2021-10-05 15:12 UTC, BenCookie95 commented on components/channel_invite_modal/channel_invite_modal.tsx
> +        this.props.actions.loadStatusesForProfilesList(this.props.profilesInCurrentChannel);
Can we concat the 2 arrays (this.props.profilesInCurrentChannel & this.props.profilesNotInCurrentChannel) and make this into one request?

2021-11-26 14:53 UTC, BenCookie95 approved these changes

2021-11-26 14:54 UTC, BenCookie95 commented
@mkraft Unsure who to add as QA because Malik is on PTO

2021-12-25 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @aspleenic

2022-04-26 19:36 UTC, esethna commented
Hi @hamzaMM, are you keen on finishing this PR?

2022-04-26 19:43 UTC, furqanmlk commented
/update-branch

2022-04-26 19:43 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2022-04-26 19:46 UTC, furqanmlk commented
@BenCookie95 can you please fix the conflict ?

2022-04-29 16:35 UTC, furqanmlk approved these changes
Working as expected.

**Before**

![image](https://user-images.githubusercontent.com/6909890/165984198-efc361fe-bb95-4c01-b316-e96688d83682.png)

**After**

![image](https://user-images.githubusercontent.com/6909890/165984369-50dc5da9-7042-457d-a307-fe3234e4f404.png)

2022-05-06 18:34 UTC, esethna commented
Awesome, lets get this merged! @BenCookie95 can you help and merge when possible?

2022-05-09 14:36 UTC, merged