Billing scenarios after subscription
mattermost/mattermost-webapp pull request #8936
Opened 2021-09-23 15:59 UTC by vinod-demansol

#### Summary
Billing functionalities performed after subscriptions

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37054
https://mattermost.atlassian.net/browse/MM-37051
https://mattermost.atlassian.net/browse/MM-37052

#### Release Note
```release-note
NONE
```

2021-09-23 15:59 UTC, mattermod commented
Hello @vinod-demansol,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-09-28 02:47 UTC, marianunez requested changes
Thanks @vinod-demansol! Instead of testing different areas of the System Console here after purchase, could we move the tests for eaach area (Subscription screen, payment info screen) into the cypress test files for each?

2021-09-28 02:49 UTC, marianunez commented on e2e/cypress/integration/enterprise/cloud/billing/after_subscription_spec.js
> +        it('MM-T4134 Downloading of invoice after subscription', () => {
As we discussed here: https://community-daily.mattermost.com/core/pl/x3qrge3j77n6tyqtz69zd6jyny The invoice will not show as soon as they subscribe so I believe this test would be that there is no invoice here as soon as you subscribe (you can comment the test until we get the fix for this in).

2021-10-04 03:31 UTC, vinod-demansol commented
> Thanks @vinod-demansol! Instead of testing different areas of the System Console here after purchase, could we move the tests for eaach area (Subscription screen, payment info screen) into the cypress test files for each?

 I feel it will be difficult to control of the sequence of test cases with the way existing e2e test suite currently being executed. So I clubbed all the "after subscription" scenario's in to single file. Please let me know if i am wrong here.

2021-10-16 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-11-01 06:50 UTC, AGMETEOR commented
> > > > @AGMETEOR gentle ping on this
> > > 
> > > 
> > > Going to run them and give feedback
> > 
> > 
> > > > @AGMETEOR gentle ping on this
> > > 
> > > 
> > > Going to run them and give feedback
> > 
> > 
> > <img alt="Screenshot 2021-10-26 at 17 01 32" width="1792" src="https://user-images.githubusercontent.com/28563179/138894957-95e4e7c6-121f-4a4b-b5c6-8965bb6517e0.png">
> > @vinod-demansol I am trying to run the tests locally. I am seeing some failure with `System Console - Subscription section`, see screenshot. Not sure why
> 
> @AGMETEOR , I have fixed the issue which you mentioned , Please check again and confirm.
> 
> ![image](https://user-images.githubusercontent.com/85981671/139260688-a57dc35c-ec4e-4039-ab39-9b7e1a12a3c0.png)
> 
> Please note : last test case is failing because of existing issue (https://mattermost.atlassian.net/browse/MM-39031)

Running them again...

2021-11-01 09:24 UTC, AGMETEOR commented
/update-branch

2021-11-01 09:53 UTC, AGMETEOR commented
Thanks @vinod-demansol . I updated your branch with the latest master. I found this failure
<img width="1786" alt="Screenshot 2021-11-01 at 12 49 46" src="https://user-images.githubusercontent.com/28563179/139653774-6fb2e2dc-eaca-4961-890e-d34cddda65cc.png">

Also, the the pdf test still fails on me. I am not sure why. 
<img width="1792" alt="Screenshot 2021-11-01 at 12 43 43" src="https://user-images.githubusercontent.com/28563179/139653865-a4d9926b-a7ce-4364-97cf-d204e402021a.png">

2021-11-01 18:43 UTC, vinod-demansol commented
@AGMETEOR , prerequisite for this script flow is trail period , could you please confirm that while executing this script , you are starting with trail period ?

2021-11-02 07:51 UTC, AGMETEOR commented
> @AGMETEOR , prerequisite for this script flow is trail period , could you please confirm that while executing this script , you are starting with trail period ?

Yes, I started from trial period. If the tests are passing fine for you, I can approve. It could be that I am getting some of the test failures due to set up.

2021-11-02 07:52 UTC, AGMETEOR approved these changes

2021-11-13 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-11-26 15:54 UTC, jasonblais commented
@AGMETEOR is this PR ready to merge?

cc @marianunez

2021-11-29 21:28 UTC, marianunez commented
/e2e-test

2021-11-29 21:28 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2021-11-30 19:28 UTC, marianunez commented
/e2e-test

2021-11-30 19:28 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2021-11-30 19:40 UTC, marianunez commented
/update-branch

2021-11-30 19:50 UTC, marianunez commented
/e2e-test

2021-11-30 19:50 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2021-11-30 21:59 UTC, marianunez commented
@saturninoabril I was trying to execute the E2E tests on this PR with the command above but doesn't seem to be kicking them off. What am I missing?

2021-12-03 06:59 UTC, saturninoabril commented
@marianunez Not yet as there are some small items that needs to address. We'll let you and others know once ready to use. Thanks for checking :)

2021-12-06 17:16 UTC, merged