MM-38540 - set consistent hover state for invite members button
mattermost/mattermost-webapp pull request #9005
Opened 2021-09-30 17:21 UTC by pablovelezvidal

#### Summary
This PR adds the css changes to make the LHS invite members button to behave consistently on the hover event with the chat members DM links.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38540

#### Screenshots
Before:
<img width="941" alt="Captura de pantalla 2021-09-30 a las 19 20 46" src="https://user-images.githubusercontent.com/10082627/135501761-95cf856f-2b60-4f61-9124-0b58ba6bb761.png">

After:
<img width="1057" alt="Captura de pantalla 2021-09-30 a las 19 20 20" src="https://user-images.githubusercontent.com/10082627/135501781-fb619de2-724f-4c2b-80f3-6cebccc4b422.png">

#### Release Note
```release-note
NONE
```

2021-09-30 17:28 UTC, esethna approved these changes
Looks good as long as the same hover state applies when the "invite members" button is unbolded

2021-09-30 17:32 UTC, pablovelezvidal commented
> Looks good as long as the same hover state applies when the "invite members" button is unbolded

yes, it looks the same:
![hover-state](https://user-images.githubusercontent.com/10082627/135503251-a25c1600-27d0-43f4-97f9-30f9e4c58d40.gif)

2021-09-30 17:58 UTC, neallred commented
Should the text color get brighter on hover now that the background changes on hover? https://github.com/mattermost/mattermost-webapp/pull/9005/files#diff-90fded696d50eef5af63163b66aaf08e3ee8190744429e674d8bad25d95a1e7fR728-R730

https://user-images.githubusercontent.com/13738432/135506821-42014aa3-4397-499c-9d8a-531c1a2b1632.mp4

2021-09-30 18:07 UTC, pablovelezvidal commented
> Should the text color get brighter on hover now that the background changes on hover? https://github.com/mattermost/mattermost-webapp/pull/9005/files#diff-90fded696d50eef5af63163b66aaf08e3ee8190744429e674d8bad25d95a1e7fR728-R730
> 
>  color-change.mp4

Not sure, what do you think @esethna ?

2021-09-30 18:30 UTC, esethna requested changes
@pablovelezvidal @neallred nice catch, the hover effect should match the hover on channels, so the text should **not** get brighter on hover

2021-09-30 19:03 UTC, neallred approved these changes
lgtm, thanks @pablovelezvidal !

2021-09-30 19:04 UTC, pablovelezvidal commented
> @pablovelezvidal @neallred nice catch, the hover effect should match the hover on channels, so the text should **not** get brighter on hover

thanks @neallred, good catch! this is fixed now!

![hover-state-2](https://user-images.githubusercontent.com/10082627/135515439-c7ba362a-0658-4f99-90a9-02cf922973aa.gif)

2021-09-30 19:39 UTC, esethna approved these changes

2021-09-30 19:40 UTC, esethna commented
Approving on behalf of UX

2021-09-30 20:15 UTC, nickmisasi approved these changes

2021-10-01 00:15 UTC, merged

2021-10-01 13:39 UTC, amyblais commented
/cherry-pick release-6.0

2021-10-01 13:39 UTC, mattermod commented
Cherry pick is scheduled.