Add Webapp E2E tests for "MM-T575 /invite-people"
mattermost/mattermost-webapp pull request #9063
Opened 2021-10-05 20:44 UTC by radiantly

#### Summary

Adds Webapp E2E tests for `/invite_people`

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/18521

#### Release Note

```release-note
NONE
```

2021-10-05 20:44 UTC, mattermod commented
Hello @radiantly,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-10-06 03:04 UTC, saturninoabril requested changes
Thanks @radiantly! Please see comments.

2021-10-06 03:04 UTC, saturninoabril commented on e2e/cypress/integration/integrations/builtin_commands/invite_people_command_spec.js
> +        cy.uiWaitUntilMessagePostedIncludes(`Email invite(s) sent`);
This is missing the following verification.
```
Both email addresses receive an invite to the team
```
See https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js#L89-L97 on how you could possibly verify email sent to each user.

2021-10-06 03:04 UTC, saturninoabril commented on e2e/cypress/integration/integrations/builtin_commands/invite_people_command_spec.js
> +        });
No need to do this here at `beforeEach` since there's only one `it` block. Please move into the `before` hook.

2021-10-07 19:29 UTC, merged

2021-11-05 17:14 UTC, emilyacook commented
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @radiantly