MM-32783: header & footer for threads in search
mattermost/mattermost-webapp pull request #9220
Opened 2021-10-20 23:00 UTC by pascalhein

#### Summary
Display "Thread in $channel" instead of the channel
name above a search result that belongs to a
thread (any message, root or child).

Also show the footer (same as for regular posts),
but only for thread roots.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/18782
JIRA: https://mattermost.atlassian.net/browse/MM-32783

#### Screenshots
![image](https://user-images.githubusercontent.com/5236894/138181321-9e16514c-9820-42e2-96fa-0b410a0c5581.png)

#### Release Note
```release-note
Added thread replies to search results (when collapsible reply threads are enabled)
```

2021-11-05 17:32 UTC, emilyacook commented
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @pascalhein

2021-11-16 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-11-19 19:27 UTC, jgilliam17 commented
Thanks @pascalhein 
This looks great!
Question for UX: @matthewbirtch please let me know your thoughts on the following. Thanks 🙂 
1. This is also added to pinned and saved rhs. Saved and Pinned search results are not specifically mentioned in the ticket, please let me know if this is expected. 
<img width="506" alt="Screen Shot 2021-11-19 at 12 46 56 PM" src="https://user-images.githubusercontent.com/52937121/142678597-4b351c8c-1e5f-46b0-8c46-d4043243c55f.png">

2. Direct Message header:
- 0/5 I personally expected singular `message` , instead of `messages` in  "Thread in Direct Messages(with user-1)" 
- We should also remove the parenthesis around user name

<img width="499" alt="Screen Shot 2021-11-19 at 1 17 06 PM" src="https://user-images.githubusercontent.com/52937121/142678506-3e4d2bd3-3100-46b7-8859-7078c6a4c3f4.png">

3. We are now showing 2 reply arrows on a root post on the RHS, please note they do behave differently and may cause confusion. 
<img width="401" alt="Screen Shot 2021-11-19 at 2 00 26 PM" src="https://user-images.githubusercontent.com/52937121/142677729-528c6df3-f587-481e-a08c-9369449343b9.png">

2021-11-19 20:06 UTC, matthewbirtch commented
> This is also added to pinned and saved rhs. Saved and Pinned search results are not specifically mentioned in the ticket, please let me know if this is expected.

@jgilliam17 yes, this is expected

> * 0/5 I personally expected singular `message` , instead of `messages` in  "Thread in Direct Messages(with user-1)"
> * We should also remove the parenthesis around user name

Agree with both of these

> We are now showing 2 reply arrows on a root post on the RHS, please note they do behave differently and may cause confusion.

This is a good catch @jgilliam17. I agree this is confusing and we should fix that. if CRT is one, we should hide the second reply arrow on the right. However, we should keep the behavior from that arrow and apply it to the thread footer because it gives users a way back to the search results/mentions/saved list.

![image](https://user-images.githubusercontent.com/2040554/142685020-4c6ca5a2-6a58-4eb6-b709-0dff0e6a28ab.png)

I'm not sure if the above is clear, so let me know. Really good catches @jgilliam17 - sorry I missed these in my review.

2021-11-19 20:46 UTC, jgilliam17 requested changes
Thanks @matthewbirtch 
@pascalhein let me know if you have any questions about the 3rd point above - remove post menu reply option on thread root post on the RHS and apply it's functionality to thread footer arrow. 
I added a suggestion for the DM header text change. Thanks again 🙂

2021-11-19 20:46 UTC, jgilliam17 commented on i18n/en.json
> +  "search_item.thread_direct": "Thread in Direct Messages (with {username})",
```suggestion
  "search_item.thread_direct": "Thread in Direct Message with {username}",
```

2021-11-19 20:46 UTC, jgilliam17 commented on components/search_results_item/search_results_item.jsx
> +                    defaultMessage='Thread in Direct Messages (with {username})'
```suggestion
                    defaultMessage='Thread in Direct Message with {username}'
```

2021-11-20 15:07 UTC, pascalhein commented on i18n/en.json
> +  "search_item.thread_direct": "Thread in Direct Messages (with {username})",
Done

2021-11-20 15:07 UTC, pascalhein commented on components/search_results_item/search_results_item.jsx
> +                    defaultMessage='Thread in Direct Messages (with {username})'
Done

2021-11-20 15:32 UTC, pascalhein commented
Hi @jgilliam17 and @matthewbirtch,
thanks for your feedback!

I've uploaded a new version to address your concerns. Please let me know if you have any comments.

2021-11-26 13:15 UTC, jgilliam17 commented
/update-branch

2021-11-26 17:41 UTC, matthewbirtch approved these changes

2021-11-29 22:04 UTC, jgilliam17 commented
/update-branch

2021-11-29 22:36 UTC, jgilliam17 commented
Thanks @pascalhein 
Manually tested, looks good.
Running [E2Es here](https://automation-dashboard.vercel.app/cycles/96afadda-aea9-41c4-9a01-339d8db8725e), will approve after report is posted.

2021-11-30 02:42 UTC, jgilliam17 approved these changes
Thank you @pascalhein 
Tested, looks good to merge.
- Verified "Thread in" displays as part of the title for search results items on the RHS. Resulting posts now also include the threads footer. Beside search, this functionality extends to mentions, pinned and saved posts.

2021-11-30 02:43 UTC, merged