Team sidebar in products
mattermost/mattermost-webapp pull request #9262
Opened 2021-10-26 06:14 UTC by harshilsharma63

#### Summary
Adds the ability to show team sidebar in products/

#### Ticket Link
https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/392c8889-6c8f-4cb7-8407-f5c57c1acfe8/680fc318-855a-4ad7-8471-fec5a79003e8

#### Related Pull Requests
A demo-only PR for interacting with the team sidebar from Boards - https://github.com/mattermost/focalboard/pull/1666/files

#### Screenshots
**Channels-** no change
<img width="948" alt="Screenshot 2021-10-26 at 11 41 14 AM" src="https://user-images.githubusercontent.com/18575143/138818865-3ba7bc29-8ca0-43d7-ab9e-3d8a67559475.png">

**Playbooks-** no change as the product doesn't request team sidebar
<img width="1147" alt="Screenshot 2021-10-26 at 11 41 36 AM" src="https://user-images.githubusercontent.com/18575143/138818919-8a77534a-0cbf-42f6-8589-cfafb8cbf15e.png">

**Boards-**
<img width="1147" alt="Screenshot 2021-10-26 at 11 42 47 AM" src="https://user-images.githubusercontent.com/18575143/138819070-6e8ab19a-f160-4436-a69f-3b0c84d2d0c2.png">

#### Release Note
```release-note
Added new flag showTeamSidebar in registerProducts, which, when set to true, displays the team sidebar in product.
```

2021-10-29 21:02 UTC, crspeller commented on plugins/registry.js
>          const id = generateId();
Ya that makes more sense. Then for playbooks we can verify before enabling.

2021-11-01 05:46 UTC, harshilsharma63 commented on plugins/registry.js
>          const id = generateId();
Exactly.

2021-11-01 14:43 UTC, crspeller commented
@harshilsharma63 Not sure about the type error but my guess is it has something to do with connect there. You could convert the component to functional with hooks to get around it 😄

2021-11-01 14:44 UTC, crspeller approved these changes

2021-11-02 05:48 UTC, harshilsharma63 commented on plugins/registry.js
>          const id = generateId();
Done.

2021-11-02 06:21 UTC, harshilsharma63 commented on components/team_sidebar/index.ts
> +        products,
@hmhealey I've undone this change to solve the "too complex type" error.

2021-11-02 06:22 UTC, harshilsharma63 commented
@hmhealey should I consider this as good to merge?

2021-11-03 21:35 UTC, hmhealey commented
The code looks good from my perspective, so once it's got a release note (or not), it's good to merge unless there's something for QA to review now.

Regarding the duplicated logic between hooks and not, that's only natural when trying to make new tech work with older code.

2021-11-15 07:41 UTC, harshilsharma63 commented
> The code looks good from my perspective, so once it's got a release note (or not), it's good to merge unless there's something for QA to review now.
> 
> Regarding the duplicated logic between hooks and not, that's only natural when trying to make new tech work with older code.

Who can I get this QAed by?

2021-11-16 22:24 UTC, hmhealey commented
I think it depends on who your team's QA is. I always assign mine to Jelena, but that's Web Platform

2021-11-18 05:38 UTC, harshilsharma63 commented
@ogi-m can you please test this?

This is the scope -
1. Channels should continue working as-is w.r.t. team sidebar.
2. Boards and Playbooks should NOT display team sidebar and continue working as-is.
3. This special [build of Boards](https://community-daily.mattermost.com/files/48xqz1dt3pyzxpnoif4q3636gh/public?h=pMdhyRKddnpvwhpL4JDyi5J6V9YIurCOIhxEHN_Ra9M) should display the team sidebar (it won't e used for anything though) and the Boards should continue working as-is.

2021-11-22 21:18 UTC, saturninoabril commented
/update-branch

2021-11-23 01:33 UTC, saturninoabril commented on selectors/products.ts
> +}
@harshilsharma63 See E2E tests [here](https://mattermost-cypress-report.s3.amazonaws.com/89397-5f06424-ee-ent-webapp-pr-9262-mm-ee-test:5f06424/mochawesome.html) and check if anything is related to this PR. One thing I noticed in the console log is likely thrown from this code block. See screenshot.
<img width="677" alt="Screen Shot 2021-11-23 at 9 29 54 AM" src="https://user-images.githubusercontent.com/5334504/142959110-6cb30e34-ef82-4345-8a3d-40fd8bb07677.png">

2021-11-24 19:50 UTC, saturninoabril commented on selectors/products.ts
> +}
This is now resolved. Thanks @harshilsharma63 for fixing!

2021-11-24 19:52 UTC, saturninoabril commented
@harshilsharma63 See [new E2E test result](https://mattermost-cypress-report.s3.amazonaws.com/89984-dbf62f4-ee-ent-webapp-pr-9262-mm-ee-test:dbf62f4/mochawesome.html). Related failed tests are those in "back stage" pages like Integrations, Incoming/Outgoing webhooks, Slash command and Custom Emoji.

2021-11-30 08:18 UTC, harshilsharma63 commented
@saturninoabril @ogi-m The tests look good now - https://automation-dashboard.vercel.app/cycles/4ecb42e5-c8c2-4de6-8369-047abab6c004 . Can you take a look?

2021-11-30 12:07 UTC, ogi-m approved these changes
Thanks @harshilsharma63 , LGTM 👍🏻

2021-12-02 01:53 UTC, saturninoabril approved these changes
Thank you @harshilsharma63! LGTM.

2021-12-02 02:23 UTC, saturninoabril commented
1. Text not visible in product menu in backstage page.
<img width="694" alt="Screen Shot 2021-12-02 at 10 05 57 AM" src="https://user-images.githubusercontent.com/5334504/144345781-624b8e95-ebe9-43d5-a32d-e5c974313d2c.png">

2021-12-02 02:25 UTC, saturninoabril commented
2. Theme not applied in backstage, like in modals (Settings, Profile...)
<img width="989" alt="Screen Shot 2021-12-02 at 10 08 46 AM" src="https://user-images.githubusercontent.com/5334504/144346069-fc7c2d1d-7efa-4788-b52d-fd965a7353e9.png">

2021-12-02 02:26 UTC, saturninoabril commented
3. Search bar is available in backstage but doing search does not do anything.
<img width="840" alt="Screen Shot 2021-12-02 at 10 09 31 AM" src="https://user-images.githubusercontent.com/5334504/144346190-b21c994b-a792-4b59-bf21-4c72c0599b3e.png">

2021-12-02 02:28 UTC, saturninoabril commented
4. Clicking on buttons such as at-mention and saved posts don't do anything in backstage.
<img width="245" alt="Screen Shot 2021-12-02 at 10 09 54 AM" src="https://user-images.githubusercontent.com/5334504/144346313-f40d4b87-acfa-4281-9c47-52fec0dfeb2b.png">

2021-12-02 02:32 UTC, saturninoabril requested changes
@harshilsharma63 I did check and found some UI discrepancies. Please take a look. Thanks!

2021-12-02 03:18 UTC, saturninoabril commented
@harshilsharma63 or @ogi-m I can't access the ticket link in the description above. I wonder if we need a Jira ticket as well since this is introducing change to the core webapp. Also, I'm curious if UI/UX needs review/approval here.

2021-12-02 23:33 UTC, ogi-m commented
You're probably right @saturninoabril, I've created a ticket for it - https://mattermost.atlassian.net/browse/MM-40464

2021-12-06 12:54 UTC, harshilsharma63 commented
Thanks, @saturninoabril , I'm taking a look.

2021-12-07 04:20 UTC, harshilsharma63 commented
@saturninoabril @ogi-m  the theme and font colour issues you mentioned are occurring because previously the global header is not intended to be shown on backstage pages. It's hidden on `master`. It shows up unintentionally in this branch. I'll hide it and that should fix the issues.

2021-12-07 12:58 UTC, saturninoabril approved these changes
Thanks @harshilsharma63! Tested and all looks good to me.

2021-12-09 08:20 UTC, merged

2021-12-21 14:27 UTC, amyblais commented
/cherry-pick release-6.3

2021-12-21 14:27 UTC, mattermod commented
Cherry pick is scheduled.