MM-T248 Mark DM post as Unread
mattermost/mattermost-webapp pull request #9446
Opened 2021-11-27 08:18 UTC by poflankov

#### Summary
Add the tests for marking DM post as Unread in central panel and RHS.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/18166

#### Release Note
```
NONE
```

2021-11-27 08:18 UTC, mattermod commented
Hello @poflankov,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-11-30 16:12 UTC, hmhealey commented
Thanks for the PR! This looks mostly good, but I'm not sure about the way we're chaining the Cypress calls since it's a different style than I've seen throughout the E2E tests I've seen. I'll defer to Saturn on that though since this is more his area.

2021-12-02 02:43 UTC, saturninoabril requested changes
Thank you @poflankov! Unfortunately, we're not going to use a different or mixed style in writing Cypress test at this stage, for some of the reasons:
- consistency in our codebase
- readability especially for non-technical reviewers (chaining is a bit overhead to them)

We use chaining for the built-in functions (`should`, `its`, `within`, etc) and it makes it easier to follow along but not when mixed up with custom commands.

Hope it's fine with you.

2021-12-02 20:14 UTC, poflankov commented
@hmhealey,  @saturninoabril
I fixed the code style. Will it fit this way?

2021-12-03 09:12 UTC, saturninoabril requested changes
Thanks @poflankov for updating! LGTM, except for few comments.

2021-12-03 19:52 UTC, poflankov commented on e2e/cypress/integration/mark_as_unread/helpers.js
>  }
Fixed

2021-12-03 19:52 UTC, poflankov commented on e2e/cypress/integration/mark_as_unread/mark_dm_post_as_unread_spec.js
> +        cy.then(() => markAsUnreadFromMenu(this.unreadFromHere.id));
Fixed

2021-12-06 21:59 UTC, hmhealey approved these changes
Yep, that looks good to me now. Thanks for changing all those!

2021-12-06 23:40 UTC, saturninoabril approved these changes
Thank you @poflankov! All looks good to me.

2021-12-06 23:41 UTC, merged