[POC] - Advanced markdown text editor
mattermost/mattermost-webapp pull request #9662
Opened 2022-01-18 09:46 UTC by nevyangelova

#### Summary
This is a POC PR for the Advanced text editor epic - https://mattermost.atlassian.net/browse/MM-21165

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21165

#### Screenshots

#### Release Note
```release-note
NONE
```

2022-01-18 10:22 UTC, zefhemel commented
This is super cool, I want this. Now. Let's ship it.

Here's some suggestions to make it even better:

1. There's no tooltip for the "A" button that enables this editor so you have to just click to see what will happen
2. I'd love to have a keyboard shortcut to toggle advanced mode
3. Advanced code editor in edit mode too please!

2022-01-18 19:42 UTC, esethna requested changes
@nevyangelova you knocked it out of the park! Awesome!! Let's polish and ship it asap 🎉 

A few notes or questions, mostly about polishing issues:

1. You've marked the PR as "POC" but is there anything holding us back from shipping it aside from some polish? 
1. The advanced editor should be **opened by default**. Then the state (open or closed) should persist through refreshes.
2. Tooltips missing on all buttons except bold, link and italics.
3. Tooltip is incorrect on the preview button. We also need to add a selected state on the preview button as per the designs.
4. Heading button is missing icon
5. ? button doesn't work
6. Icon set does not match designs https://mattermost.atlassian.net/wiki/spaces/ATE/pages/1015382021/UX+Documentation
7. Edit post modal should use the same editor (Perhaps we should coordinate with @michelengelen on his inline editing PR to avoid conflicts)
8. ... popover at smaller widths should disappear after a button is pressed in it

2022-01-19 04:30 UTC, mickmister commented
> it would be nice to make the editor itself feel like it "gets" markdown, e.g. with syntax highlighting. I know @mickmister had a prototype embedding the Monaco editor (used in VS Code) in the Mattermost UI. 

@zefhemel I've been looking at [CodeMirror](https://codemirror.net), which is a little more customizable on styling compared to Monaco. You can make header text bigger for example, which I think brings a lot of value. It still feels like a code editor but maybe the font style can change so it doesn't look grid-like. Here's an example from the note-taking app [Inkdrop](https://inkdrop.app):

<img width="400px" src="https://user-images.githubusercontent.com/6913320/150056434-5585b0ce-73dd-413a-bb7b-da3ac60c2ee7.png"/>

> This may be overkill (I'm sure it will add a lot to the bundle)

We can make the usage of the editor opt-in, and have the components lazy loaded so it's not fetched by default. We can support custom editors with a new plugin hook. I made this hook and I have some progress using a Monaco editor, with autocompletion for Mattermost channels and users. There's also a preview of the markdown using Mattermost's markdown component, which we can also add to the existing UX. I have a POC of this running [here](https://custom-editor.test.mattermost.cloud). After logging in, click the `Code` link on the bottom right of the text editor to check it out.

![image](https://user-images.githubusercontent.com/6913320/150059742-24529912-9d9b-4100-9384-55f435451e2f.png)

I'm thinking the default editor in Mattermost should look/feel more like a text editor than a code editor. 2/5 We should keep improving our existing editor and add things that are most requested. I brought this up as an item in the developers meeting, and the most prominent ask was "highlight multiple lines and tab to indent". The other asks were not related to the actual text editor.

@zefhemel In the meeting I think you mentioned having a real-time preview of the markdown as you type. Rendering the markdown outside of the editor should be simple, but highlighting text in the editor is not as simple. It may be possible to work into our text editor using some library that's meant to modify an existing `textarea`. I've mostly looked into the "off the shelf" editor solutions, and not so much the iterative solutions to apply to the current editor. That may be the best way to approach syntax highlighting if we have the right tools.

2022-01-19 12:08 UTC, nevyangelova commented
Hey guys thank you for your feedback! Temporarily pausing changes on this to focus on Growth spike. But I will work on it during any free time between my growth spike tasks.

2022-01-19 12:10 UTC, nevyangelova commented
> @nevyangelova you knocked it out of the park! Awesome!! Let's polish and ship it asap 🎉
> 
> A few notes or questions, mostly about polishing issues:
> 
> 1. You've marked the PR as "POC" but is there anything holding us back from shipping it aside from some polish?
> 2. The advanced editor should be **opened by default**. Then the state (open or closed) should persist through refreshes.
> 3. Tooltips missing on all buttons except bold, link and italics.
> 4. Tooltip is incorrect on the preview button. We also need to add a selected state on the preview button as per the designs.
> 5. Heading button is missing icon
> 6. ? button doesn't work
> 7. Icon set does not match designs https://mattermost.atlassian.net/wiki/spaces/ATE/pages/1015382021/UX+Documentation
> 8. Edit post modal should use the same editor (Perhaps we should coordinate with @michelengelen on his inline editing PR to avoid conflicts)
> 9. ... popover at smaller widths should disappear after a button is pressed in it

@esethna excellent points! I added the POC status because it needs some polish from UX perspective as well as probably some comments from developers regarding the markdown implementation for the other buttons. But I am convinced this will be a success!

2022-03-08 10:02 UTC, AshishDhama commented
> @esethna excellent points! I added the POC status because it needs some polish from UX perspective as well as probably some comments from developers regarding the markdown implementation for the other buttons. But I am convinced this will be a success!

@hmhealey Could you please take a look at this and raise some early red flags if there are any. Thanks.

2022-03-09 22:08 UTC, hmhealey commented
I haven't had a chance to look through the code for this yet, but we need to consolidate some of these efforts since there's at least a couple other ongoing things making large changes to this code. In particular, @larkox has been doing some refactoring in the area to clean up this code, and @mickmister has been looking at making this whole area pluggable. Also, we've already made some changes to this area as part of the performance fixes and the inline post editing feature, but those are already in and likely causing the conflicts on the existing branch. We need to coordinate all those efforts or else we're going to end up tripping over each other constantly as we're working on this

2022-03-10 03:15 UTC, mickmister commented
> @mickmister has been looking at making this whole area pluggable

PR for reference https://github.com/mattermost/mattermost-webapp/pull/9925

2022-04-19 13:13 UTC, Willyfrog commented
@AshishDhama what are the next steps on this PR?

2022-04-19 13:18 UTC, AshishDhama commented
@Willyfrog We need to implement a few shortcuts and fix edge cases. I will pick it up again next week. I have created another PR it was really difficult to resolve conflicts in this one. https://github.com/mattermost/mattermost-webapp/pull/10133

2022-04-25 07:59 UTC, AshishDhama commented
Closing this in favour of https://github.com/mattermost/mattermost-webapp/pull/10133

2022-04-25 07:59 UTC, closed without merging