[MM-40590] Fix inviting a guest guest to a channel where he's a member.
mattermost/mattermost-webapp pull request #9677
Opened 2022-01-19 16:20 UTC by JulienTant

#### Summary
This PR fixes the bug that caused inviting a guest to a channel where he's already a member to show a "Success" message instead of a message saying the guest is already present.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40590

#### Related Pull Requests
N/A

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

2022-01-19 17:14 UTC, neallred approved these changes
Good find and fixes! If I understand the issue, it is that the channel membership data may or may not be loaded yet, so when members was selected, it didn't necessarily show that some guests already belonged to the channel. This PR changes that by making sure the relevant data is loaded first.

2022-01-19 22:41 UTC, neallred commented on components/invitation_modal/add_to_channels.test.tsx
> +        it('should use townSqureDisplayName when not in a channel', () => {
Nice tests!

2022-01-19 22:41 UTC, neallred approved these changes

2022-01-20 03:36 UTC, saturninoabril commented
/e2e-test

2022-01-20 03:37 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-01-20 03:37 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/106757

2022-01-20 04:07 UTC, saturninoabril requested changes
Thanks @JulienTant! Tested and passed. Left minor comments but all good to me.

2022-01-20 22:24 UTC, saturninoabril approved these changes
Thanks @JulienTant. Tested and passed. LGTM.

2022-01-21 18:26 UTC, stevemudie approved these changes
Unable to invite a guest guest twice to the same channel as described in the PR title. 😛

Looks good @JulienTant!

2022-01-21 19:54 UTC, merged