Using moment.js to format dates
mattermost/mattermost-webapp pull request #9690
Opened 2022-01-22 01:05 UTC by mhblatch

#### Summary

#### Ticket Link

#### Related Pull Requests

#### Screenshots

#### Release Note

```release-note

```

2022-01-22 01:05 UTC, mattermod commented
Hello @mhblatch,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-01-25 22:12 UTC, hmhealey requested changes
Thanks for the PR, @mhblatch! This looks good to start with, but I have a few suggestions for things to be changed:
1. The `lint` check that's currently failing is because of some code styling issues if you could take a look at those
    ```
    /root/mattermost/mattermost-webapp/components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
    6:20  error  Strings must use singlequote        quotes
    184:44  error  Unexpected usage of doublequote     jsx-quotes
    185:44  error  There should be no space after '='  react/jsx-equals-spacing
    
   ✖ 3 problems (3 errors, 0 warnings)
    3 errors and 0 warnings potentially fixable with the `--fix` option.
    ```
2. Similarly, the `type-check` check is failing because the types for some of those fields is incorrect. In particular, I think we've defined `this.state.selectedDate` to be a Date, not a string, so you'd want to change that.
3. Separate from those, we've actually been trying to move away from moment.js since it's very large and we're not using enough of its features to be worth that. Could you perhaps change this to use [Luxon](https://moment.github.io/luxon/#/) instead? We're working on switching moment for Luxon throughout the code base right now.
4. Finally, could you change the date format to pad the day/month with a 0 so that they're always two digits long as per linked ticket?

Also, we aren't able to accept your submission unless you sign our CLA. If you take a look at the message from Mattermod above, it has instructions on how to do that.

2022-02-05 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @aspleenic

2022-03-08 17:22 UTC, mylonsuren commented
Hey @mhblatch, just checking in to see if you're still working on this or need any help?

2023-03-02 21:02 UTC, lieut-data commented
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

2023-03-02 21:02 UTC, closed without merging