Use case onboarding wizard
mattermost/mattermost-webapp pull request #9722
Opened 2022-01-28 22:32 UTC by neallred

#### Summary

#### Ticket Link

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

#### Release Note

```release-note

```

2022-02-07 21:48 UTC, neallred commented
/e2e-test

2022-02-07 21:49 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-02-07 21:49 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/147908

2022-02-08 15:34 UTC, hanzei commented
cc @DHaussermann

2022-02-11 19:51 UTC, JulienTant requested changes
Impressive work, good job @neallred! I did mark this PR as "Request changes" mostly to make sure I get back to it after you react to my questions and remarks.

2022-02-11 19:51 UTC, JulienTant commented on utils/channel_utils.tsx
> +        name: displayName.split(' ').join('-').toLowerCase(),
Do we have a tool/function that does some normalization? Just wondering if there's a way that some non-desired characters end up here (eg cyrilic or greek letters)

2022-02-11 19:51 UTC, JulienTant commented on components/root/root.jsx
>              if (this.props.location.pathname === '/' && response[2] && response[2].data) {
could you explicit `response[2]`?

2022-02-11 19:51 UTC, JulienTant commented on components/preparing_workspace/use_case.tsx
> +                            <button
I'm wondering if there's a way to extract the buttons to make it a reusable component over the pages, but not sure it's worth it

2022-02-13 18:48 UTC, AshishDhama commented on utils/constants.jsx
> +    USE_CASE: 'use_case',
nit: Had discussion with @hmhealey would be better if we define constants near component 
https://community.mattermost.com/core/pl/qzjd3wuzf7yw9kygzjbcgz4yrr

2022-02-13 19:19 UTC, AshishDhama commented
@neallred You have added a couple of SVG is it not possible to use them from https://mattermost.github.io/compass-icons/. Please ignore if those are logos. I think GitHub one we can use anyway.
@matthewbirtch Does it make sense to replace them with Icons
<img width="791" alt="Screenshot 2022-02-14 at 12 45 10 AM" src="https://user-images.githubusercontent.com/16203333/153770984-58fc634b-dcae-4761-aa2d-269d445f2feb.png">
s

2022-02-15 17:06 UTC, neallred commented on components/common/svg_images_components/boards_svg.tsx
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
For a lot of them, its convention in the project more than anything. Some of them need different widths and heights, and we've chosen to style that as a prop on the component versus a classname. For a few of them (the channels preview svg is an example in this PR) there is dynamic content (the team and channel names).

2022-02-16 00:13 UTC, JulienTant commented on components/common/svg_images_components/boards_svg.tsx
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
Thanks!

2022-02-16 00:33 UTC, JulienTant approved these changes
🧠💥 Good job! Thank you for your answers to my questions and the changes applied, LGTM.

2022-02-16 06:54 UTC, spirosoik commented
/update-branch

2022-02-16 21:22 UTC, esethna approved these changes
Pair reviewed with Matt, nothing majorly blocking from my perspective aside from the UI polish items. Nice work @neallred!

2022-02-17 15:56 UTC, esethna commented
@AshishDhama can you help re-review this to unblock merging?

2022-02-17 16:11 UTC, esethna commented
@neallred are we okay to go ahead and merge this now? I think anything else we need can come in separate PRs unless there's a major blocking issue

2022-02-17 16:44 UTC, neallred commented
Yep, we can merge now. Removed some last debugging code.

2022-02-17 16:46 UTC, merged