MM-T1228 CTRL/CMD+K - Open DM with user not on the current team
mattermost/mattermost-webapp pull request #9770
Opened 2022-02-08 08:05 UTC by poflankov

#### Summary
CTRL/CMD+K - Open DM with user: not on the current team

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/18523

#### Release Note
```
NONE
```

2022-02-08 08:05 UTC, mattermod commented
Hello @poflankov,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-02-10 01:27 UTC, josephbaylon requested changes
Thanks @poflankov !! Just title changes below

2022-02-10 01:27 UTC, josephbaylon commented on e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_user_from_other_team_spec.js
> +    it('MM-T1228 CTRL/CMD+K_1 - Open DM with user not on the current team / with ANY', function() {
```suggestion
    it('MM-T1228_1 CTRL/CMD+K - Open DM with user not on the current team / with ANY', function() {
```

2022-02-10 01:27 UTC, josephbaylon commented on e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_user_from_other_team_spec.js
> +    it('MM-T1228 CTRL/CMD+K_2 - Open DM with user not on the current team / with TEAM', function() {
```suggestion
    it('MM-T1228_2 CTRL/CMD+K - Open DM with user not on the current team / with TEAM', function() {
```

2022-02-10 01:27 UTC, josephbaylon commented on e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_user_from_other_team_spec.js
> +    it('MM-T1228 CTRL/CMD+K_3 - Open DM with user belonging to both teams / with ANY', function() {
```suggestion
    it('MM-T1228_3 CTRL/CMD+K - Open DM with user belonging to both teams / with ANY', function() {
```

2022-02-10 01:27 UTC, josephbaylon commented on e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_user_from_other_team_spec.js
> +    it('MM-T1228 CTRL/CMD+K_4 - Open DM with user belonging to both teams / with TEAM', function() {
```suggestion
    it('MM-T1228_4 CTRL/CMD+K - Open DM with user belonging to both teams / with TEAM', function() {
```

2022-02-10 18:52 UTC, poflankov commented
@josephbaylon, fixed!

2022-02-11 19:32 UTC, furqanmlk commented
/e2e-test

2022-02-11 19:32 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-02-11 19:32 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/149752

2022-02-14 19:23 UTC, furqanmlk approved these changes
Thanks @poflankov 👍

2022-02-14 19:23 UTC, merged