Adjust some more ux styles
mattermost/mattermost-webapp pull request #9793
Opened 2022-02-10 22:51 UTC by pablovelezvidal

#### Summary
More UX enhancements after zoom call with @michaelgamble.
Summary of changes:
- Open accordion when clicking on chips
- Adjust spacing in accordion cards content to be 24px from left, and from top-botton should be 32px.
- Remove top margin from card content h5.
- Chevron icon to be vertically aligned centered and has a size of 24px.
- Change variable name
- Accordion card item icon when is a warning should use the sys-away-indicator color.

Also as part of this PR, I added the logic to show the success texts description to the accordion card header.
<img width="1379" alt="Captura de pantalla 2022-02-11 a las 1 11 40" src="https://user-images.githubusercontent.com/10082627/153518760-bbb299b3-dd8f-48c2-a909-905db98d06fc.png">

#### Ticket Link
n/a

#### Related Pull Requests
n/a

#### Release Note
```release-note
NONE
```

2022-02-11 14:05 UTC, mkraft approved these changes

2022-02-11 14:06 UTC, mkraft commented
@cwarnermm There are some new translations going in with this PR, just pinging you in case you optionally want to review them.

2022-02-11 14:08 UTC, cwarnermm commented
Thanks, @mkraft! I'll review these new strings.

2022-02-11 14:09 UTC, michaelgamble approved these changes
Looks great based on everything we reviewed yesterday! Great work!

2022-02-11 17:45 UTC, cwarnermm reviewed
I've provided text feedback for the latest strings; however, I didn't flag every instance of a given string proposal. It will be necessary to ensure that a given string is updated throughout the product code where applicable. Thanks!

2022-02-11 17:45 UTC, cwarnermm commented on components/admin_console/workspace-optimization/dashboard.data.tsx
> +            defaultMessage: 'You seem to have good configuration for SSL and Session Lengths!',
```suggestion
            defaultMessage: 'You've successfully configured SSL and Session Lengths!',
```

2022-02-11 17:45 UTC, cwarnermm commented on components/admin_console/workspace-optimization/dashboard.data.tsx
> +            defaultMessage: 'Access to your workspace seems available!',
```suggestion
            defaultMessage: 'Your web server configuration is passing a live URL test!',
```

2022-02-11 17:45 UTC, cwarnermm commented on components/admin_console/workspace-optimization/dashboard.data.tsx
> +            defaultMessage: 'You seem to be using data retention and compliance features!',
```suggestion
            defaultMessage: 'You've enabled data retention and compliance features!',
```

2022-02-11 17:45 UTC, cwarnermm commented on components/admin_console/workspace-optimization/dashboard.data.tsx
> +            defaultMessage: 'For your current usage scale, manually managing users and guests seems apropriate!',
```suggestion
            defaultMessage: 'Based on current usage, manually managing users and guests manually is a good choice!',
```

2022-02-11 17:45 UTC, cwarnermm commented on components/admin_console/workspace-optimization/dashboard.data.tsx
> +            defaultMessage: 'Your workspace is completely up to date!',
```suggestion
            defaultMessage: 'Your workspace is using the latest version of Mattermost!',
```

2022-02-11 17:45 UTC, cwarnermm commented on components/admin_console/workspace-optimization/dashboard.data.tsx
> +            defaultMessage: 'Server Updates',
Let's change "Updates" to "updates" if all other sections of this page are also sentence case.

2022-02-11 18:41 UTC, mkraft commented on components/admin_console/workspace-optimization/dashboard.data.tsx
> +            defaultMessage: 'Server Updates',
```suggestion
            defaultMessage: 'Server updates',
```

2022-02-11 18:41 UTC, mkraft commented on components/admin_console/workspace-optimization/dashboard.data.tsx
> +            defaultMessage: 'Server Updates',
```suggestion
            defaultMessage: 'Server updates',
```

2022-02-11 18:46 UTC, mkraft commented
Thanks @cwarnermm that's really great.

2022-02-14 11:03 UTC, michelengelen requested changes
it seems as if the translations in `en.json` differ from the defaultMessage properties in code. yould you re-check those (although I suppose that @cwarnermm might have things to contribute here as well).

2022-02-14 11:03 UTC, michelengelen commented on i18n/en.json
> +  "admin.reporting.workspace_optimization.ease_of_management.descriptionOk": "For your current usage scale, manually managing users and guests seems apropriate!",
this differs from the defaultMessage in code. is that intentional?

```suggestion
  "admin.reporting.workspace_optimization.ease_of_management.descriptionOk": "For your current usage scale, manually managing users and guests seems appropriate!",
```

2022-02-14 17:58 UTC, pablovelezvidal commented
@michelengelen as discussed during today's meeting, we need these changes in the main branch so QA and UX can test everything in a single branch. If you have anything else, I can address it in a different/new PR.
@mkraft @michaelgamble @furqanmlk ^^

2022-02-14 17:58 UTC, merged