[MM-40853]Press Ctrl+/ (or Cmd+/ if you're on Mac) to close the Keyboard shortcuts modal if modal is open
mattermost/mattermost-webapp pull request #9802
Opened 2022-02-11 18:52 UTC by VishakhaPoonia

#### Summary
Pressing Ctrl+/ (or Cmd+/ if you're on Mac) to open the Keyboard shortcuts modal open's modal but hitting it back doesn’t close it this pr will fix that.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/19520#issue-1127428916
  Fixes https://mattermost.atlassian.net/browse/MM-40853

#### Related Pull Requests
``NONE``

#### Screenshots

#### Release Note
```release-note
UI: Keyboard shortcut modal toggle issue via keyboard shortcut keys
```

2022-02-11 18:52 UTC, mattermod commented
Hello @VishakhaPoonia,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-02-15 18:24 UTC, VishakhaPoonia commented
@hmhealey Could you please let me know the further process.

2022-02-16 07:33 UTC, M-ZubairAhmed commented
@VishakhaPoonia thank you for sending in the PR, we will start the review soon. Apologies for the delay from our side

2022-02-16 07:34 UTC, AshishDhama approved these changes

2022-02-16 07:34 UTC, AshishDhama commented
LGTM!

2022-02-16 07:36 UTC, AshishDhama commented
Checked working as expected, will defer QA as changes are less than 50 lines

2022-02-16 07:56 UTC, M-ZubairAhmed requested changes
It looks good just a minor suggestion.
Also would you be open to writing e2e test for this one? if you need help with that please drop by [Developers channel on community](https://community-daily.mattermost.com/core/channels/developers)

2022-02-16 07:56 UTC, M-ZubairAhmed commented on components/sidebar/index.ts
> +import {ModalIdentifiers} from '../../utils/constants';
Absolute path are preferred over relative path import.

2022-02-16 11:18 UTC, VishakhaPoonia commented
@M-ZubairAhmed Have added your suggestion, I am not very familiar with E2E but yeah would love to write, should that be part of this pr. As I mostly work on weekends so it might take some time.

2022-02-16 11:24 UTC, M-ZubairAhmed commented
@VishakhaPoonia actually that can be a separate ticket. @jgilliam17 could you please check if we have a zephyr test for that. If not can you please create one. I will open up a ticket later. And @VishakhaPoonia, if you have time around weekends feel free to work on it. no pressure  :)

2022-02-16 11:24 UTC, VishakhaPoonia commented
@M-ZubairAhmed If you create new ticket for E2E could you please assign that to me.

2022-02-16 11:25 UTC, M-ZubairAhmed commented
/e2e-test

2022-02-16 11:25 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-02-16 11:25 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/151680

2022-02-16 11:25 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed If you create new ticket for E2E could you please assign that to me.

Sure will do that. I will wait for confirmation from @jgilliam17 :)

2022-02-19 09:39 UTC, M-ZubairAhmed commented
@VishakhaPoonia can you please try to update the pr to resolve the conflicts.
@jgilliam17 gentle ping to review :)

2022-02-23 19:40 UTC, jgilliam17 commented
Thanks @VishakhaPoonia 
Tested, looks good. Will update and re-run the e2es before merging.
- Verified cmd+/ opens and closes the keyboard shortcuts modal
@M-ZubairAhmed We have an automated test for this keyboard shortcut, currently unstable. I will follow up with Saturn to see if the change I suggested is enough to promote the test to production.

2022-02-23 19:40 UTC, jgilliam17 commented
/update-branch

2022-02-23 19:40 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2022-02-23 19:43 UTC, jgilliam17 commented
@VishakhaPoonia can you please update manually. Thanks

2022-03-02 04:06 UTC, VishakhaPoonia commented
@jgilliam17 yeah, had to give my laptop for repairs got it now will update it today

2022-03-03 06:21 UTC, VishakhaPoonia commented
@M-ZubairAhmed @jgilliam17 I have updated the branch, please take a look and let me know.

2022-03-03 06:40 UTC, M-ZubairAhmed commented
/e2e-test

2022-03-03 06:41 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-03-03 06:41 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/158234

2022-03-04 18:06 UTC, AshishDhama commented
/update-branch

2022-03-04 18:36 UTC, M-ZubairAhmed commented
/e2e-test

2022-03-04 18:36 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-03-04 18:37 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/165803

2022-03-04 20:55 UTC, jgilliam17 commented
Thanks @VishakhaPoonia 
Tested, looks good to merge.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/158234-944389e-onprem-ent-webapp-pr-9802-mattermost/mm-ee-test944389e/mochawesome.html) looks good, no PR related failures. This is the run from March 3rd, the one from today failed to start, probably a cypress issue.

2022-03-04 20:56 UTC, jgilliam17 approved these changes

2022-03-04 21:14 UTC, jgilliam17 commented
@M-ZubairAhmed I didn't merge yet. Here is the link to [test case ](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/4064362) if you wanted to take a look. We can add here and I can re-test if any changes are made. Let me know.

2022-03-07 07:26 UTC, M-ZubairAhmed commented
@jgilliam17 That test case is included in our e2e https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js#L41
so i dont think @VishakhaPoonia we need to add e2e for this pr. Once again thank you so much for working on it.

2022-03-07 07:28 UTC, merged