MM-41741: fixes leaving an unread channel
mattermost/mattermost-webapp pull request #9847
Opened 2022-02-18 17:55 UTC by koox00

#### Summary

Currently when you leave a currently viewing channel, and that channel
is unread, and you have the setting "Group unread channels separately"
to ON the app crashes.

Since we remove the channel both from myMembers and channels,
but we keep an unread channel when while we are viewing it in the
unreads group, we need to guard against myMembers to ensure that the
channels in the unread list are always joined channels.

This commit does exactly that.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-41741

#### Release Note

```release-note
* Fixes app crash when leaving a currently viewing unread channel with channel unread grouping set to ON
```

2022-02-21 08:03 UTC, michelengelen approved these changes
LGTM

2022-02-21 11:39 UTC, koox00 commented
/e2e-test

2022-02-21 11:39 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-02-21 11:39 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/153833

2022-02-22 16:10 UTC, amyblais commented
@hmhealey @jgilliam17 This is a candidate to fix before Cloud March 2nd release.

2022-02-22 20:38 UTC, jgilliam17 reviewed
Thanks @koox00 
Tested, looks good no crash, seeing one issue 
When rejoining the same channel, channel is added to Unreads on the sidebar. I expected it in Channels category.
- Added test case to Zephyr and suggested ID below.

2022-02-22 20:38 UTC, jgilliam17 commented on e2e/cypress/integration/channel_sidebar/group_unreads_separately_spec.js
> +    it('Leaving an unread channel when unread category is ON', () => {
```suggestion
    it('MM-T4655 Leaving an unread channel when unread category is ON', () => {
```

2022-02-24 07:40 UTC, koox00 commented
/e2e-test

2022-02-24 07:41 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-02-24 07:41 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/155112

2022-02-24 09:28 UTC, Willyfrog requested changes
Looks good, but I'm missing having a unittest for the case at least (nice that you added the e2e test btw!)

2022-02-24 12:01 UTC, koox00 commented
> When rejoining the same channel, channel is added to Unreads on the sidebar. I expected it in Channels category.

Can we add another task for that, since that's true for current master as well?
I'd prefer to keep this one just to fix the crash.

2022-02-24 15:16 UTC, hmhealey reviewed
Could we also clear the state returned by [the `lastUnreadChannel` reducer ](https://github.com/mattermost/mattermost-webapp/blob/master/reducers/views/channel.ts#L112) as well when leaving the channel? We might end up with other code that depends on it, causing us to run into this same issue later.

That might also fix the thing Jelena was reporting above where the channel returns to the Unreads category after rejoining it.

2022-02-24 17:19 UTC, Willyfrog approved these changes

2022-02-24 20:12 UTC, hmhealey approved these changes

2022-02-25 03:48 UTC, jgilliam17 commented
/update-branch

2022-02-25 20:45 UTC, jgilliam17 commented
/e2e-test

2022-02-25 20:46 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-02-25 20:46 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/155988

2022-02-28 20:39 UTC, jgilliam17 commented
Thanks @koox00 
Tested, looks good to merge.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/155988-3be03a8-onprem-ent-webapp-pr-9847-mattermost/mm-ee-test3be03a8/mochawesome.html) also looks good, no PR related failures. 
Filed re-joining the same channel issue separately.
https://mattermost.atlassian.net/browse/MM-42140

2022-02-28 20:40 UTC, jgilliam17 approved these changes

2022-02-28 20:41 UTC, merged

2022-03-04 15:31 UTC, amyblais commented
/cherry-pick release-6.5