MM-41185,MM-41065: fixes mark thread as unread
mattermost/mattermost-webapp pull request #9865
Opened 2022-02-23 11:41 UTC by koox00

#### Summary

When marking a post as unread the timestamp should be the post's create
at minus 1.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-41185
https://mattermost.atlassian.net/browse/MM-41065

#### Release Note

```release-note
* Fixes issue where marking last post in a thread as unread didn't mark the thread as unread.
```

2022-02-24 03:36 UTC, ashishbhate approved these changes

2022-02-24 08:44 UTC, koox00 commented
@ashishbhate, @lieut-data I just wonder if instead fixing this in the webapp, we have to make the fix on the server.
To explain myself:
Scenario a thread containing a mention in the last reply. 
currently, without this fix, when marking a thread as last viewed at the last post's `create_at` the server would return `unread_mentions` to 1 BUT `unread_replies` to 0.

2022-02-25 09:31 UTC, ashishbhate commented
I took a quick look at the thread store.

For various unreads and counts check, we use: 
`sq.Expr("ThreadMemberships.LastViewed < Threads.LastReplyAt")`,
`sq.Expr("Posts.CreateAt > ThreadMemberships.LastViewed")`, or 
`sq.Gt{"Posts.CreateAt": threadMembership.LastViewed}` 


While for the mention count checking we fetch posts with the condition:
```
Select("*").
From("Posts").
Where(sq.Eq{"RootId": threadId}).
Where(sq.Eq{"DeleteAt": 0}).
Where(sq.GtOrEq{"UpdateAt": since}).ToSql()
```

Notice the `GtOrEq` check here, vs the `Gt` checks for the unreads case. I think this might be causing the issue you're seeing.

2022-03-01 20:28 UTC, lieut-data commented
> @ashishbhate, @lieut-data I just wonder if instead fixing this in the webapp, we have to make the fix on the server.

@koox00, I do like the idea of handling this on the server vs. knowing to pass in `create_at - 1`. I wonder if we might instead expose and use an API that amounts to `markThreadAsUnreadByPostId` and have the server take care of "all" the magic?

2022-03-01 20:28 UTC, lieut-data requested changes
Blocking review while we discuss the approach. (Feel free to re-request as needed!)

2022-03-05 10:05 UTC, ashishbhate commented
I'm in favour of a fix on the server side as well. Having to pass `post.create_at - 1` is an implementation detail that the webapp shouldn't need to know. The webapp should just be able to say, "mark thread as unread from this post"

2022-04-08 10:37 UTC, koox00 commented
> @koox00, I do like the idea of handling this on the server vs. knowing to pass in create_at - 1. I wonder if we might instead expose and use an API that amounts to `markThreadAsUnreadByPostId` and have the server take care of "all" the magic?

@lieut-data, @ashishbhate sorry for taking so long to reply, I got absorbed in mobile stuff.
I'm all in favor of using an API like `markThreadAsUnreadByPostId`, which is similar to what we do in channels btw.
I'll create a new PR to address that in the server.

2022-04-08 10:38 UTC, koox00 commented
I'll keep this one to make the necessary changes to conform to the new API when ready

2022-04-11 11:05 UTC, lieut-data approved these changes
:tada:

2022-04-12 10:43 UTC, koox00 commented on actions/post_actions.jsx
>              dispatch(manuallyMarkThreadAsUnread(threadId, post.create_at));
yep, thx! changed it :)

2022-04-12 12:58 UTC, lieut-data approved these changes

2022-04-12 12:58 UTC, lieut-data commented on actions/post_actions.jsx
> +            dispatch(manuallyMarkThreadAsUnread(threadId, post.create_at - 1));
Should we... add an explicit API for this? ;P

2022-04-15 07:56 UTC, merged