adding more hooks and optimizing functional components
mattermost/mattermost-webapp pull request #9871
Opened 2022-02-23 19:19 UTC by BenCookie95

#### Summary
Fixing most of the comments from here https://github.com/mattermost/mattermost-webapp/pull/9434

- Made more use of useCallback and React.memo
- Made another small component for the view group modal header

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41905

#### Release Note

```release-note
NONE
```

2022-02-28 15:10 UTC, jespino commented on components/add_users_to_group_modal/add_users_to_group_modal.tsx
> +    }, []);
I miss here the `goBack` dependency

2022-02-28 15:11 UTC, jespino commented on components/add_users_to_group_modal/add_users_to_group_modal.tsx
> +    }, []);
and maybe, but I don't think is going to change, the `props.actions.addUsersToGroup`

2022-02-28 15:13 UTC, jespino commented on components/update_user_group_modal/update_user_group_modal.tsx
> +    }, []);
I miss the `mention` dependency here.

2022-02-28 15:15 UTC, jespino commented on components/update_user_group_modal/update_user_group_modal.tsx
> +    }, []);
I miss here  `name`, `mention`, `goBack`, `props.groupId` and maybe `props.actions.patchGroup`

2022-02-28 15:19 UTC, jespino commented on components/view_user_group_modal/view_user_group_header_sub_menu/view_user_group_header_sub_menu.tsx
> +    }, [actions.openModal, group.id, backButtonAction]);
missing here the `onExited` dependency.

2022-02-28 15:20 UTC, jespino commented on components/view_user_group_modal/view_user_group_header_sub_menu/view_user_group_header_sub_menu.tsx
> +    }, [group.id, actions.removeUsersFromGroup, decrementMemberCount]);
missing here the `currentUserId` dependency.

2022-02-28 15:20 UTC, jespino commented on components/view_user_group_modal/view_user_group_header_sub_menu/view_user_group_header_sub_menu.tsx
> +    }, [group.id, actions.addUsersToGroup, incrementMemberCount]);
Missing the currentUserId dependency here.

2022-02-28 15:22 UTC, jespino requested changes
Detected some dependencies missing in the hooks, but other than that looks good to me.

2022-02-28 17:54 UTC, jespino approved these changes
LGTM. Thanks for the effort :)

2022-03-04 18:06 UTC, mkraft approved these changes

2022-03-07 20:39 UTC, BenCookie95 commented
@furqanmlk For testing we just need to make sure nothing is broken, there should be no functional changes

2022-03-17 18:32 UTC, furqanmlk commented
/update-branch

2022-03-21 14:05 UTC, furqanmlk commented
/e2e-test

2022-03-23 19:09 UTC, furqanmlk commented
/e2e-test

2022-03-23 19:09 UTC, mattermod commented
The command /e2e-test requires the build docker check to pass.

2022-03-23 19:14 UTC, furqanmlk commented
/update-branch

2022-03-24 14:35 UTC, furqanmlk commented
/e2e-test

2022-03-24 14:54 UTC, furqanmlk commented
/e2e-test

2022-03-24 14:55 UTC, mattermod commented
The command /e2e-test requires the build docker check to pass.

2022-03-24 15:03 UTC, furqanmlk commented
/e2e-test

2022-03-24 15:05 UTC, mattermod commented
The command /e2e-test requires the build docker check to pass.

2022-03-30 16:36 UTC, furqanmlk commented
/update-branch

2022-03-30 16:36 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2022-03-30 17:14 UTC, furqanmlk approved these changes
Thanks @BenCookie95 
sorry for the delay e2e build was broken. 
E2E is passed ✅ 

https://automation-dashboard.vercel.app/cycles/353321ea-4a6c-4c00-b82d-1ffe426ab081

2022-04-11 15:34 UTC, merged