[MM-40486] CRT beta warning modal
mattermost/mattermost-webapp pull request #9910
Opened 2022-03-01 06:44 UTC by AshishDhama

#### Summary
Adding CRT beta modal which was removed as part of https://github.com/mattermost/mattermost-webapp/pull/9289 (needs to be removed as soon CRT is ready for GA).
Fixes : CRT modal not showing the "Got It" Button in the Modal Footer.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-40486

#### Related Pull Requests
NONE

#### Screenshots
<img width="1333" alt="Screenshot 2022-03-01 at 12 12 39 PM" src="https://user-images.githubusercontent.com/16203333/156118532-5017e96b-0106-4674-8b51-afe7d6a6712f.png">

#### Release Note
```release-note
UI: CRT Beta warning modal 
```

2022-03-01 08:58 UTC, Willyfrog approved these changes

2022-03-01 10:30 UTC, koox00 approved these changes

2022-03-01 22:52 UTC, esethna approved these changes

2022-03-01 22:52 UTC, esethna requested changes
Can we change the modal title here to "Collapsed Reply Threads (Beta)"

2022-03-03 16:01 UTC, AshishDhama commented
@esethna earlier message was ``You're accessing an early beta of Collapsed Reply Threads`` I think I missed that earlier so I have reverted to that.

2022-03-03 16:25 UTC, jgilliam17 commented
>Can we change the modal title here to "Collapsed Reply Threads (Beta)"

@AshishDhama I am not seeing this suggested title
<img width="696" alt="Screen Shot 2022-03-03 at 11 22 32 AM" src="https://user-images.githubusercontent.com/52937121/156607159-b348c537-9fb0-4c61-a5dd-ece98913293b.png">

2022-03-03 16:43 UTC, jgilliam17 approved these changes
Thanks @AshishDhama 
Tested, looks good to merge.
- Verified Collapsed Reply beta modal text and dismiss buttons - as expected.
<img width="716" alt="Screen Shot 2022-03-03 at 11 40 24 AM" src="https://user-images.githubusercontent.com/52937121/156610464-0da742b7-6338-433f-9ce5-d097dc481e11.png">

2022-03-04 20:11 UTC, esethna approved these changes

2022-03-04 20:11 UTC, esethna commented
Ready to merge I believe @AshishDhama

2022-03-07 05:39 UTC, AshishDhama commented
@esethna yeah

2022-03-07 05:39 UTC, merged

2022-03-07 23:22 UTC, amyblais commented
/cherry-pick release-6.5

2022-03-07 23:22 UTC, mattermod commented
Cherry pick is scheduled.