[FIX] admin_console/licence_settings: fix of referencing to a button
mattermost/mattermost-webapp pull request #9952
Opened 2022-03-07 11:25 UTC by tsabi

#### Summary
The button's text is "Upgrade Server And Start trial", and not "Upgrade
And Start trial"

#### Ticket Link
I just found this error, there are no ticket exists.

#### Screenshots
Here it shows, that the button text is not matching with the help text.
![image](https://user-images.githubusercontent.com/210099/157022316-5c64477e-90e9-4b92-b358-517aeb50b8c4.png)

#### Release Note
NONE

2022-03-07 11:25 UTC, mattermod commented
Hello @tsabi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-03-07 15:17 UTC, cwarnermm approved these changes
Thanks!

2022-03-07 19:11 UTC, hmhealey commented
Thanks for the PR! This looks good to me, but I'm just double checking to see if we can merge changes to the non-English translation files as part of this PR. We usually only make changes to `en.json` and then our translation service picks up the changes. I think that might mean that we can't change the files for other language's directly on GitHub, but my info might be out of date on that.

2022-03-07 19:34 UTC, hmhealey requested changes
Okay, it does work how I thought it did. Could you revert the changes to en_AU.json and sv.json then so that we don't run into conflicts next time the translation files are updated?

2022-03-08 04:19 UTC, M-ZubairAhmed requested changes

2022-03-08 04:19 UTC, M-ZubairAhmed commented on i18n/en_AU.json
> -  "admin.license.upgrade-and-trial-request.accept-terms-initial-part": "By selecting **Upgrade and Start Trial**, I agree to the [Mattermost Software Evaluation Agreement](!https://mattermost.com/sof
As per comments from @hmhealey could you please revert these changes

2022-03-08 04:19 UTC, M-ZubairAhmed commented on i18n/sv.json
> -  "admin.license.upgrade-and-trial-request.accept-terms-initial-part": "Genom att klicka på **Upgrade And Start trial** godkänner jag [Mattermost Software Evaluation Agreement](!https://mattermost.co
As per comments from @hmhealey could you please revert these changes

2022-03-08 04:20 UTC, M-ZubairAhmed commented
/release-note-none

2022-03-08 13:22 UTC, tsabi commented
> Thanks for the PR! This looks good to me, but I'm just double checking to see if we can merge changes to the non-English translation files as part of this PR. We usually only make changes to `en.json` and then our translation service picks up the changes. I think that might mean that we can't change the files for other language's directly on GitHub, but my info might be out of date on that.

Hi!
Just did what you asked.

As a heavy weblate user (for my personal projects) and administrator (i run weblate on my own servers), i can tell you that technically it is valid to modify the translation files (json or po it doesn't matter), weblate can read them and it will update the corresponding texts. The only problem is if the translation policy doesn't allows that behavior.

2022-03-10 01:50 UTC, jgilliam17 commented
/e2e-test

2022-03-10 01:50 UTC, mattermod commented
Triggering e2e testing with options:
```<nil>```

2022-03-10 01:50 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/168710

2022-03-10 14:11 UTC, jgilliam17 commented
Thanks @tsabi 
Looks good to merge.
[E2E report](https://automation-dashboard.vercel.app/cycles/8c77e7ea-2ba2-45b0-8f21-12b90aa8aac6) looks good, no PR related failures.

2022-03-10 14:11 UTC, jgilliam17 approved these changes

2022-03-10 21:28 UTC, hmhealey approved these changes

2022-03-10 21:36 UTC, merged

2022-03-10 21:36 UTC, hmhealey commented
> As a heavy weblate user (for my personal projects) and administrator (i run weblate on my own servers), i can tell you that technically it is valid to modify the translation files (json or po it doesn't matter), weblate can read them and it will update the corresponding texts. The only problem is if the translation policy doesn't allows that behavior.

That's good to know. I assume we probably have that set up for English since that's where our translations all come from, but I haven't used the system enough to be sure