[MM-42322] add thread auto follow setting in system console
mattermost/mattermost-webapp pull request #9969
Opened 2022-03-08 10:30 UTC by AshishDhama

#### Summary
Add thread auto follow setting above collapsed reply threads setting in system console, ``ThreadAutoFollow`` needs to be true enable Collapsed reply threads, exposing that to UI. 

#### Ticket Link
  Fixes [add thread auto follow setting in admin console](https://mattermost.atlassian.net/browse/MM-42322)

#### Related Pull Requests
``NONE``

#### Screenshots
<img width="1792" alt="Screenshot 2022-03-08 at 4 00 17 PM" src="https://user-images.githubusercontent.com/16203333/157218609-0faa0303-1581-44c0-a7c4-c105dadf5cc4.png">

#### Release Note
```release-note
UI: exposing threadAutoFollow config setting to UI
```

2022-03-08 12:55 UTC, michelengelen approved these changes
LGTM

2022-03-09 03:16 UTC, jfrerich requested changes
There are two pieces of text that need to be code blocked in order to exactly match the text in the Jira ticket description.

2022-03-09 03:16 UTC, jfrerich commented on components/admin_console/admin_definition.jsx
> +                        help_text_default: 'This setting must be enabled to support [Collapsed Reply Threads](https://docs.mattermost.com/messaging/organizing-conversations.html) and may impact your
```suggestion
                        help_text_default: 'This setting must be enabled to support [Collapsed Reply Threads](https://docs.mattermost.com/messaging/organizing-conversations.html) and may impact your database server performance. If you cannot easily scale up and tune your database, or if you are running the Mattermost application server and database server on the same machine, we recommended disabling `ThreadAutoFollow` until Collapsed Reply Threads is promoted to general availability in Q2 2022. Learn more about these [performance considerations here](https://support.mattermost.com/hc/en-us/articles/4413183568276). When enabled, threads a user starts, participates in, or is mentioned in are automatically followed. Entries are added to the `ThreadMembership` table to track followed threads for each user and the read or unread state of each followed thread. Enabling this configuration setting doesn’t retroactively follow threads for actions taken prior to the setting being enabled.',
```

2022-03-09 03:16 UTC, jfrerich commented on components/admin_console/admin_definition.jsx
> +                        help_text_default: 'This setting must be enabled to support [Collapsed Reply Threads](https://docs.mattermost.com/messaging/organizing-conversations.html) and may impact your
I didn't test this, but I think you can `codeblock` the `ThreadAutoFollow` and `ThreadMembership` so they appear as shown in the Jira ticket.

2022-03-09 04:11 UTC, jfrerich commented
There is an extra `for` that snuck in on that last commit 😃 

![image](https://user-images.githubusercontent.com/7575921/157371293-dffba4ab-3b53-4d1a-83c5-240d8732b92a.png)

2022-03-09 04:18 UTC, AshishDhama commented
@jfrerich thanks

2022-03-09 04:23 UTC, jfrerich approved these changes
Looks nice!

2022-03-09 04:24 UTC, jfrerich commented
I would update the image at the top of the PR too.  Thanks for the fixes!

2022-03-09 18:48 UTC, esethna requested changes
@AshishDhama please add a line break between the two paragraphs

Also on the test server it seems the setting is in a disabled state since it says it's controlled via env variable? Is that just a problem on the test server? We want any admins to be able to easily toggle the setting from the console

![image](https://user-images.githubusercontent.com/14333569/157510412-0ed27b21-38ca-4729-b65b-bdeb496e8328.png)

2022-03-09 18:50 UTC, esethna commented
Also @AshishDhama can we remove the ` in Q2 2022` part of the sentence. I'm thinking it might be best not to "hard code" any dates into the text

2022-03-10 04:27 UTC, AshishDhama commented
> Also on the test server it seems the setting is in a disabled state since it says it's controlled via env variable? Is that just a problem on the test server? We want any admins to be able to easily toggle the setting from the console

@esethna Yeah this is a warning as we cannot override setting if it’s set via ENV variable, which we requested https://mattermost.atlassian.net/browse/MM-42108 (link to conversation with SRE team)
cc// @angeloskyratzakos Please correct me if I have wrong understanding.

2022-03-10 15:47 UTC, esethna commented
@AshishDhama just to understand, what's expected in production cloud deployments and production on-prem deployments? 

For production cloud deployments I would actually expect that this setting is not shown at all (since it only affects backend resources which we ourselves manage). Sorry if that wasn't clear in the ticket, my fault

For production on-prem, this setting should be togglable via the system console UI

2022-03-11 09:50 UTC, AshishDhama commented
> I'm not familiar with how the spinwick test servers are deployed, what matters most to me is understanding what will be expected in production. Just to understand, can you clarify what's expected in **production cloud deployments** and **production on-prem deployments**?
> 
> For production cloud deployments I would actually expect that this setting is not shown at all (since it only affects backend resources which we manage ourselves for all cloud instances). Sorry if that wasn't described in the ticket, my fault
> 
> For production on-prem, this setting should be togglable via the system console UI

@marianunez @neallred Could you guys please guide me here.
@esethna Does it make sense to hide Collapsed reply threads option as well. I mean user cannot enable it with ``ThreadsAutoFollow``.

2022-03-11 14:39 UTC, neallred commented
For on prem, this value will be controllable by admins. For both test and production cloud, it is overridden and admins won't be able to control it, so agree that  I think we can hide it for cloud environments. Looks like [the code that generates the UI](https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/admin_console.tsx#L143-L148) supports hiding items by defining an `isHidden` function property that gets called with the license. Typically we check for whether something is cloud by seeing if `license.Cloud === 'true'`.

2022-03-11 14:44 UTC, michelengelen commented
good call @neallred ... it is located in `components/admin_console/admin_definition.jsx` ... thats probably the best way to handle that

2022-03-11 16:47 UTC, esethna approved these changes
Makes sense @neallred, thanks for the clarification. In that case I'll approve to unblocking merging.

2022-03-11 16:48 UTC, AshishDhama commented
@esethna Have tested on suggested server it's working.

2022-03-11 16:57 UTC, merged

2022-04-05 21:01 UTC, cwarnermm commented
Documented via https://github.com/mattermost/docs/pull/5520